ops/terraform/env/prod-sbx/stateful/main.tf, ops/terraform/env/prod/stateful/main.tf, ops/terraform/env/test/stateful/main.tf, ops/terraform/modules/resources/rds/main.tf, ops/terraform/modules/resources/rds/variables.tf, ops/terraform/modules/stateful/main.tf, ops/terraform/modules/stateful/variables.tf
This PR does 3 things:  
* Removes RDS storage autoscaling completely by removing the `max_allocated_storage` parameter in favor of directly setting `allocated_storage`.  We have a large existing dataset and to import it properly storage needs to be allocated up front.  
* Implements an RDS import mode on master nodes.  This is a feature that when enabled allows for immediate application of RDS parameters, and sets several RDS parameters tuned for import per this guide: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/PostgreSQL.Procedural.Importing.html#PostgreSQL.Procedural.Importing.Copy  
* I have also tweaked RDS instance size, storage size, and IOPS parameters based feedback, though I think these are still subject to change (definitely post-import).  
Let me know if you think …
=> Remove RDS storage autoscaling, implement RDS import mode, tweak test/prod RDS params for import

ops/terraform/env/prod-sbx/migration/backend.tf, ops/terraform/env/prod-sbx/migration/main.tf, ops/terraform/env/prod/migration/backend.tf, ops/terraform/env/prod/migration/main.tf, ops/terraform/env/test/migration/backend.tf, ops/terraform/env/test/migration/main.tf, ops/terraform/modules/migration/main.tf, ops/terraform/modules/migration/variables.tf, ops/terraform/modules/resources/dns/main.tf, ops/terraform/modules/resources/dns/outputs.tf, ops/terraform/modules/resources/dns/variables.tf, ops/terraform/modules/resources/dns_pairs/main.tf, ops/terraform/modules/resources/dns_pairs/variables.tf, ops/terraform/modules/stateful/main.tf
**Why**
To gradually migrate partners between the HealthApt and CCS environments. The plan is contained in https://confluence.cms.gov/display/BB/Traffic+routing+between+HealthApt+and+CCS.
- A new env/migration folder deploys the migration DNS zone per environment. The main.tf contains the weights.  
- A new migration module drives the weight policy
- The DNS resource has a bunch more features. 
- See https://gist.github.com/RickHawesUSDS/9669dc8683b23ff40861badd44ce80f3 for the Terraform plan
**Decisions Made**
- One zone per environment with the apex record resolving to the CCS environment
- One record per partner to allow complete flexibility per partner
- Use the Route53 alias feature to allow for health checks 
- Registered bfdcloud.net domain to allow us to start. …
=> BLUEBUTTON-1218 Migration DNS Zone

ops/terraform/modules/stateful/main.tf
Quick fix for two things observed:  
* Two parameters required `pending-reboot` rather than `immediate` apply method  
* It makes more sense if the read replicas are in lock-step with master during import mode so changes like IOPS and storage size can be propagated immediately  
I have already applied this in PROD-SBX to get going.
=> Fix RDS import mode issues

ops/ansible/roles/bfd-server/files/bluebutton-appserver-config.sh
Currently breaking all of our deploys:
```
WFLYCTL0212: Duplicate resource [(\"system-property\" => \"bfdServer.db.url\")]
```
Didn't catch this in the PR that created it, because it only goes boom the _second_ time you run the script as-is.
https://jira.cms.gov/browse/BLUEBUTTON-1086
=> BLUEBUTTON-1086: Fix dumb typo in deploy config script

ops/terraform/modules/resources/asg/main.tf, ops/terraform/modules/resources/asg/variables.tf, ops/terraform/modules/resources/ec2/main.tf, ops/terraform/modules/resources/ec2/variables.tf, ops/terraform/modules/stateless/main.tf
**Why**
Add more space on the root volumes for logs and other things. 
Variable passed in as part of launch_config in resources. 100GB set in stateless/main.tf. 
**Choices Made**
The volume is encrypted with the default iops. 
**Terraform State**
This change will cause replacement of all instances. Example TF Plan is here: https://gist.github.com/RickHawesUSDS/b4e26c172889af24676da8f1a765f24b. The plan has not been applied to any environment.
=> Change the root volume size to 100GB

ops/terraform/modules/resources/asg/main.tf, ops/terraform/modules/resources/asg/variables.tf, ops/terraform/modules/stateless/main.tf
Fix for the following build error:
```
Error: Invalid function argument
on ../../../modules/resources/asg/main.tf line 110, in resource "aws_launch_configuration" "main":
110:   user_data                   = templatefile("${path.module}/../templates/${var.launch_config.user_data_tpl}", {
111: 
112: 
113: 
|----------------
| var.env_config.env is "test"
| var.lb_config.port is 7743
Invalid value for "vars" parameter: vars map does not contain key "accountId",
referenced at
../../../modules/resources/asg/../templates/fhir_server.tpl:9,33-42.
```
=> User data needs account id, fix to pass it down to proper scope

ops/terraform/modules/resources/templates/fhir_server.tpl
With logging enabled it became apparent that the `data_server_version` var was missing.
```
TASK [bfd-server : Deploy WAR (with Authentication)] *******************************************************
Friday 13 September 2019  17:03:29 -0400 (0:00:00.049)       0:00:02.049 ******
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'data_server_version' is undefined\n\nThe error appears to be in '/beneficiary-fhir-data/ops/ansible/roles/bfd-server/tasks/war_deploy.yml': line 21, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Deploy WAR (with Authentication)\n  ^ here\n"}
```
This is currently hardcoded for pipeline, hardcoding for the time being …
=> Fix missing data_server_version that causes war deploy to fail

ops/terraform/modules/stateless/main.tf
We have a mismatch in our configuration. Instances are deployed and being bound to port 7443 but our LB and SG's are configured for 7743.  
This resolves BLUEBUTTON-1278
=> BLUEBUTTON-1278: Update LB and SG's to use app port 7443 instead of 7743

Jenkinsfile
Was forcing folks to always build the platinum AMI unnecessarily.
https://jira.cms.gov/browse/BLUEBUTTON-1112
=> BLUEBUTTON-1112: Fixed a silly Jenkins error due to undefined platinumAmiId

Jenkinsfile
The ultimate end goal is that auto-builds in the CCS environment "just work" as expected. As opposed to right now, where you have to manually kick off a hand-configured job to really test things.
Was hoping this'd be more of a one-line change, but it turns out that Jenkins' `params` object is read-only, so have to (kinda' sorta') shadow the variable, instead of updating it.
Note: There was another default-Jenkins-builds-don't-work-in-the-CCS issue, which was resolved in #45 (and has been merged in here now that that's accepted).
=> BLUEBUTTON-1112: Fix Jenkinsfile default for deploy_env in CCS

apps/bfd-pipeline/bfd-pipeline-app/src/test/java/gov/cms/bfd/pipeline/app/S3ToDatabaseLoadAppIT.java, apps/bfd-pipeline/bfd-pipeline-rif-extract/src/main/java/gov/cms/bfd/pipeline/rif/extract/s3/DataSetTestUtilities.java, apps/bfd-pipeline/bfd-pipeline-rif-extract/src/test/java/gov/cms/bfd/pipeline/rif/extract/s3/DataSetMonitorIT.java, apps/bfd-pipeline/bfd-pipeline-rif-extract/src/test/java/gov/cms/bfd/pipeline/rif/extract/s3/task/ManifestEntryDownloadTaskIT.java
It's _almost_ the same as before, except now the "get a random bucket name" code is centralized, and improved:
1. Added a couple decimal places to the random number.
2. Added usernames to the generated strings, so that one person failing to clean up their mess shouldn't impact someone else.
There are still several other things that can cause intermittent test failures, but this was definitely the biggest offender.
https://jira.cms.gov/browse/BLUEBUTTON-850
=> BLUEBUTTON-850: Resolve non-unique bucket name test errors

ops/terraform/env/global/dlm/backend.tf, ops/terraform/env/global/dlm/main.tf, ops/terraform/modules/resources/asg/main.tf, ops/terraform/modules/resources/dlm/main.tf, ops/terraform/modules/resources/dlm/variables.tf, ops/terraform/modules/resources/ec2/main.tf
**Why**
For security audits and other security purposes, retain daily snapshots of BFD's instance volumes. 
- A new global data lifecycle manager policy that takes snapshots of volumes and retains them for 21 days.
- Since DLM policy runs on tag matching, tag all ec2 instance volumes. 
- In order to tag volumes, switched from Launch Configurations to Launch Templates to specify the instances created by Autoscale Groups
The terraform plan is here:
https://gist.github.com/RickHawesUSDS/dad91f312d9ec5ae1b755c00466a6df1
**Choices Made**
- The use of DLM to do manage the snapshots. Could of done this with a Lambda function.
- Use Launch Templates to tag snapshots. Found articles that recommended using Lambdas to do this task.
**Whats Left**
This finishes BLUEBOTTON-1163.
=> BLUEBUTTON-1163 Instance Snapshots

ops/ansible/playbooks-ccs/vars/prod-sbx/group_vars/all/env_specific.yml, ops/ansible/playbooks-ccs/vars/prod/group_vars/all/env_specific.yml
We need the correct client certs installed for each environment. I goofed and a copy/paste issue is causing us to deploy certs configured for the TEST environment to all our environments. 
Updated variable data_server_ssl_client_certificates for both prod-sbx and prod to reflect the correct client certs.
=> BLUEBUTTON-1157: Correcting prod and prod-sbx to load the correct client certs.

ops/ansible/roles/bfd-server/files/bluebutton-appserver-config.sh
The Jboss server fails to start due to the default access log already being registered. 
2019-09-13 15:42:53,172 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 1) JBAS014612: Operation ("add") failed - address: ([
("subsystem" => "undertow"),
("server" => "default-server"),
("host" => "default-host"),
("setting" => "access-log")
]): org.jboss.msc.service.DuplicateServiceException: Service jboss.undertow.server.default-server.default-host.access-log is already registered
Moved the removal of the access-log to before the reload.
=> BLUEBUTTON-1284: Resetting jboss application access log before reload

ops/terraform/env/prod-sbx/stateful/main.tf, ops/terraform/env/test/stateful/main.tf, ops/terraform/modules/stateful/main.tf
When the RDS instances were built there was no parameter group specified, so a default group was assigned.  After RDS instances were assigned the import parameter group, setting them back to null did not trigger a change, we need to be explicit to set them back to defaults.  We could also create our own parameter group to pave the way for setting custom values as we need them.
=> Remove import mode from TEST and PROD-SBX

ops/ansible/playbooks-ccs/build_bfd-server.yml
**Why**
My last PR had a bug that wasn't caught. This PR fixes our build-server.yml ansible playbook. 
The copy keystore task had to order to after the /jboss directory was created. 
**Verification Done**
Built the AMI and deployed to test env. Smoke test run.
=> BLUEBUTTON-1257: Fix Ansible

Jenkinsfile, ops/deploy-ccs.groovy, ops/terraform/env/test/stateless/main.tf, ops/terraform/env/test/stateless/variables.tf, ops/terraform/modules/resources/asg/main.tf, ops/terraform/modules/resources/asg/variables.tf, ops/terraform/modules/resources/ec2/main.tf, ops/terraform/modules/resources/ec2/variables.tf, ops/terraform/modules/resources/templates/fhir_server.tpl, ops/terraform/modules/resources/templates/pipeline_server.tpl, ops/terraform/modules/stateless/main.tf, ops/terraform/modules/stateless/variables.tf
This PR supplies the specific git branch and git commit used during the build pipeline and makes it available to terraform to pass along to user_data 
... so that during post bake of the AMI this commit is checked out to finalize the deployment thus keeping all stages of the pipeline in sync with a specific branch / commit. 
Built and Deployed this PR to TEST with successful results. Jumped on instance to confirm the branch was cloned and commit was checked out and used to complete the user_data script. 
BLUEBUTTON-1157
=> BLUEBUTTON-1157: Make deployed commit available to user_data script

Jenkinsfile, ops/deploy-ccs.groovy, ops/packer/build_bfd-pipeline.json, ops/packer/build_bfd-server.json
This PR address one main feature, a bug fix and a deployment modifications so that we can tag our AMIs to give insights into its contents, provide the git commit to our user_data script so that we post-ami config with the same code as we built with, and to disable prod AMI building until we're cleared for prod launch, respectively. 
BLUEBUTTON-1312 - Feature - Tag AMI's
BLUEBUTTON-1157 - Bug - Build and Deploy (user_data script)
BLUEBUTTON-1314 - Feature - Disable PROD AMI Builds.
=> Tag AMI's, user_data commit checkout and disable prod builds. 

Jenkinsfile
When building PR's we need the BRANCH NAME passed to the user_data script, and not the JOB NAME. Added a step to check if the build is a PR, if so switching to the env.CHANGE_BRANCH var and if not, using env.BRANCH_NAME. 
I tested this PR and this branch to confirm both methods work as expected.
=> Refactor how Jenkinsfile populates branch name and commit id vars. 

ops/deploy-ccs.groovy
I think this bug occurred because there was an assumption that packer would overwrite the old manifest on every run.  However packer is "intelligent" in that it actually appends to an existing manifest if detected.  This ensures that if the manifest has multiple entires, we always pull the last addition.
Tested in Jenkins script console.
=> Fix to always pull last AMI ID from packer manifest

ops/ansible/roles/bfd-server/handlers/enable_appserver.yml, ops/ansible/roles/bfd-server/tasks/appserver_config.yml, ops/deploy-ccs.groovy, ops/deploy-healthapt.groovy
For the `Jenkinsfile` errors: params were added to `deploy(...)` environment, but not the other. Led to weird errors.
For the JBoss service errors: the service definition was getting swapped for Jetty's when that branch was deployed, but not swapped back when other branches were deployed. (The fixes here are hacky and non-idempotent, but temporary, so I don't care.)
https://jira.cms.gov/browse/BLUEBUTTON-1298
=> BLUEBUTTON-1298: Fixed errors from Jenkinsfile syntax and JBoss service

ops/terraform/modules/migration/main.tf, ops/terraform/modules/resources/asg/main.tf, ops/terraform/modules/resources/asg/variables.tf, ops/terraform/modules/resources/lb/main.tf, ops/terraform/modules/resources/lb/outputs.tf, ops/terraform/modules/resources/lb/variables.tf, ops/terraform/modules/stateful/main.tf, ops/terraform/modules/stateless/main.tf
**Why**
To make the CCS environment better match the HealthApt environment, move to the classic ELB. 
- Replaced the FHIR LB with a classic v1 ELB
- Created a Security Group for the new ELB
- Created a S3 Bucket for the new ELB's access logs
- The Launch Template references the new ELB instead of the old target group
**Terraform Plan**
Ignore the ETL change which was picked up accidentally. 
```
14:20:50 <bfd> ~/p/b/o/t/e/t/stateless> tf plan -var fhir_ami=ami-074f924de93c81314 -var etl_ami=ami-00a5226c314e71769 -var ssh_key_name=bfd-test -var git_branch_name=master -var git_commit_id=18846ecb9a81e9919d396d48931adefb62cb29ea
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be …
```
=> BLUEBUTTON-1329: Move to classic ELB

ops/terraform/env/prod/stateful/main.tf
Now that bulk data import is complete this needs to be reverted so daily operation tasks like autovacuuming can happen.  Also implements a custom default parameter group so we can more easily apply settings like forcing encrypted connections down the road.
NOTE: This has already been applied in test and prod-sbx.
=> BLUEBUTTON-1327: Disable import mode for prod RDS

ops/terraform/modules/stateful/main.tf
This leaves access key management outside of terraform since we currently don't manage any keys there.
=> BLUEBUTTON-1308: Create user, policy, and attachment for external ETL access

ops/packer/build_bfd-platinum.json, ops/terraform/modules/resources/asg/main.tf
This does two things:
- Encrypts the platinum AMI with the mgmt KMS key
- Ensures that at launch time, the root volume of an instance in an ASG is then encrypted with the per environment KMS key, rather than inheriting encryption from the mgmt key
Alternately we could apply the per environment KMS key at application AMI build, but this solution makes more sense (and is simpler) if we are planning to move to environment agnostic AMIs after implementing SSM.
=> BLUEBUTTON-1315: Encrypt AMIs

ops/terraform/modules/resources/asg/main.tf, ops/terraform/modules/resources/asg/variables.tf, ops/terraform/modules/resources/ec2/main.tf, ops/terraform/modules/resources/lb/outputs.tf, ops/terraform/modules/stateless/main.tf
Fixed the security group for the BFD Pipeline EC2 instance, as it was not configured in a way that allowed SSH access.
Also:
* Cleaned up the security groups for the ASG and BFD Pipeline systems in general, as they were a bit borked.
* Fixed a couple comments. 
Security implications:
1. Now attaching the `*-vpn-private` security groups to the BFD Server and BFD Pipeline EC2 instances.
* These SGs are created as part of GDIT's CCS Cloud Formation templates and allow systems on the CCS VPN access to all ports of the EC2 systems.
* That does seem a bit broad to me, but it's the supported mechanism, so I've raised the issue in general to our ISSO -- we should use these rather than maintaining our own CIDR lists, but they should also be a bit narrower (e.g. just port 22).
BLUEBUTTON-1288
=> BLUEBUTTON-1288: Allow SSH access from VPN to BFD Pipeline EC2 instances

ops/terraform/env/prod-sbx/migration/main.tf, ops/terraform/env/test/migration/main.tf
**Why**
As the first step of the migration to the CCS environment, move prod-sbx traffic from health-apt to the CCS environment.
**What**
Altered the weighting records for the prod-sbx.bfdcloud.net and test.bfdcloud.net domains to point to the CCS environment. Already applied to test and prod-sbx.
=> BLUEBUTTON-1257: Migrate BB and BCDA prod-sbx traffic 

ops/packer/build_bfd-pipeline.json
Discovered this as I was starting to look into AMI cleanup.
=> Fix inconsistency in AMI naming scheme for ETL AMI

ops/terraform/modules/resources/asg/main.tf, ops/terraform/modules/resources/bfd_pipeline/main.tf, ops/terraform/modules/resources/bfd_pipeline/variables.tf, ops/terraform/modules/resources/ec2/main.tf, ops/terraform/modules/resources/ec2/variables.tf, ops/terraform/modules/stateless/main.tf
Needs access to the primary/write DB, which wasn't accounted for in the security groups.
Restructured things a bit to group the resources for the BFD Pipeline app all together, since there's now more than just what the `ec2` resource provides.
```
$ cd ops/terraform/env/test/stateless
$ terraform plan -no-color -var 'etl_ami=foo' -var 'fhir_ami=foo' -var 'git_branch_name=foo' -var Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
module.stateless.module.fhir_asg.aws_autoscaling_group.main: Refreshing state...
module.stateless.module.etl_instance.aws_security_group.base: Refreshing state... [id=sg-08a5db0c457334064] …
```
=> BLUEBUTTON-1288: Fix BFD Pipeline app's DB access

Jenkinsfile
Prevent one deploy from stomping on another. This should fix the "`Error: Error locking state: Error acquiring the state lock: ConditionalCheckFailedException: The conditional request failed`" errors that we've been getting from Terraform.
=> BLUEBUTTON-1288: Lock deploys to the test environment

ops/terraform/modules/resources/bfd_pipeline/main.tf, ops/terraform/modules/resources/ec2/main.tf, ops/terraform/modules/resources/ec2/variables.tf
When I rolled out my previous PR to the `test` environment, the BFD Pipeline app failed to launch the first time, because the RDS security group it depended on wasn't in place.
This is a rather gross hack, but should fix it. It's be much simpler if Terraform just supported `depends_on` for modules, but it apparently doesn't yet.
Note: I don't think this workaround will trigger if the SG is changed; it only ensures it's _created_ first.  🤷‍♂ 
=> BLUEBUTTON-1288: Create BFD Pipeline EC2 instance after SGs

ops/terraform/modules/resources/lb/main.tf, ops/terraform/modules/resources/s3/main.tf, ops/terraform/modules/resources/s3/variables.tf, ops/terraform/modules/stateful/main.tf, ops/terraform/modules/stateless/main.tf
**Why**
To ensure the ability to audit, record S3 and ELB access
**Problem Fixed**
The previous logging bucket, the ELB bucket, was setup by TF was created with CMK encryption. This type of encryption was incompatible with ELB logging. 
- Created a per environment bfd-<env>-logs bucket. Setup this bucket with AES256 encryption and Log Delivery ACLs.
- Point S3 and ELBs to write access logs to this bucket
- Added block public access lock to all S3 buckets for safety
**Notes**
- Tested in test environment
- TF Plan in comments
=> BLUEBUTTON 1340: Fix logging bucket

apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V11__Create_medicare_beneficiary_id_history_table.sql, apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V13__Create_beneficiary_history_temp_table.sql, apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V1__Create_beneficiary_and_claim_tables.sql, apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V9__Create_beneficiary_history_table.sql
Back during the monorepo migration, I accidentally made some changes to these scripts.
These migration scripts **can't** be modified at all, for any reason, once deployed, as Flyway tracks their checksums and reports errors if it detects a mismatch.
Reverting the changes should resolve the checksum mismatches for the CCS and hhsdevcloud environments.
=> BLUEBUTTON-1288: Revert accidental changes to DB migrations

ops/ansible/playbooks-ccs/templates/cwagent-data-pipeline.json.j2, ops/ansible/playbooks-ccs/templates/cwagent-data-server.json.j2, ops/terraform/modules/stateful/main.tf
Create all of the CloudWatch log groups as part of the stateful Terraform setup.
Why? Won't the CloudWatch agent just create all of these when it pushes records into them? Yes, it will, but this fixes two things:
1. It ensures that all of the data written to the log groups is encrypted.
2. It ensures that creating the CloudWatch metrics against these groups don't fail.
=> BLUEBUTTON-1288: CloudWatch log groups

ops/terraform/modules/resources/iam/main.tf
This is apparently working for the BFD Server? No idea why; I'm not seeing the permissions that enable that anywhere in our Terraform.
Nevertheless, it definitely wasn't working for the BFD Pipeline, so I'm adding this fix, which will cover both of them.
=> BLUEBUTTON-1288: Allow EC2 instances to push to CloudWatch logs

ops/ansible/playbooks-ccs/templates/cwagent-data-pipeline.json.j2
Had a silly typo there that needed to be fixed.
=> BLUEBUTTON-1288: Fixed the bfd-pipeline/messages.txt log group name

ops/terraform/modules/resources/iam/main.tf
This reverts the custom policy from #99 and #101 and instead opts to use the AWS managed cloudwatch agent policy.
=> Use AWS managed cloudwatch agent policy instead of custom policy

ops/ansible/playbooks-ccs/vars/prod/group_vars/all/env_specific.yml
Was causing New Relic data for the _CCS_ `prod` env to be stored under the "BFD Server (prod, _HealthAPT_)" app. Whoops.
I have no clue how this ended up here (other than -- obviously -- I goofed it at some point). The variable isn't redefined in the same file for the other CCS envs, nor should it be: the default in the playbooks is fine.
https://jira.cms.gov/browse/BLUEBUTTON-1359
=> BLUEBUTTON-1359: Fix New Relic app name in CCS prod

ops/terraform/modules/resources/bfd_pipeline/main.tf, ops/terraform/modules/stateless/main.tf
**Why**
To save costs, use reserve instances when possible. Also, add a bump in volume size of the ETL servers to get them to run with real data. 
- FHIR servers are m5.xlarge in size
- ETL servers are m5.4xLarge in `prod`, m5.xlarge elsewhere
- ETL servers have a 200GB volume size
**Notes**
- Not deployed to test or prod-sbx yet
- Terraform plan is attached in comments
=> BLUEBUTTON-1360: Use Reserve Instances

ops/terraform/modules/resources/bfd_pipeline/main.tf
That's really all the BFD Pipeline app does with disk space: download RIF files ahead of time, so it doesn't have to wait later on in processing.
=> BLUEBUTTON-1288: Bump space for RIF downloads to 1TB

ops/terraform/modules/resources/bfd_pipeline/main.tf, ops/terraform/modules/resources/templates/fhir_server.tpl, ops/terraform/modules/resources/templates/pipeline_server.tpl, ops/terraform/modules/stateless/main.tf
@karlmdavis discovered that despite us setting the EBS volume size on deploy, the instance was not properly utilizing the space.  This fixes that.  Only issue I see is if for some reason we had to revert to older instance classes that do not support [NVMe volumes](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html#ec2-nitro-instances), this would break deploys without more logic.
=> Extend gold image defined root partition with all available free space

ops/terraform/env/prod-sbx/stateful/main.tf, ops/terraform/env/prod/stateful/main.tf, ops/terraform/env/test/stateful/main.tf, ops/terraform/modules/stateful/main.tf, ops/terraform/modules/stateful/variables.tf
This allows us to more easily tune RDS parameters per environment.  This also tunes 4 parameters in prod CCS RDS that were much lower than their HealthApt equivalents.
Side note: Do we need import mode any longer?  Would be great to rip it out if unneeded.  It's unclear to me whether it even helped with the bulk imports at all.
=> Implement dynamic param passing for RDS per env, tune prod params

ops/terraform/modules/stateless/main.tf
**Why**
Fix the connection from BB2 to CCS prod
Add the BB2 VPC peering CIDR to the LB's security group. Only affects prod.
=> BLUEBUTTON-1362: Fix BB2 connection to prod

ops/terraform/modules/resources/lb/main.tf
This allows us to more safely remove an ASG instance from service.  According to Rick MCT does not let go of connections so this will not make instance removal entirely safe, but will hopefully provide a buffer so that reduces errors for new incoming requests.
=> Enable connection draining on ELBs

ops/terraform/modules/resources/cw_metric_alarms/main.tf
This bug was causing terraform to constantly try to replace a single alarm with either the 4s one or the 6s one (depending which apply "won" on a last apply).
=> Fix duplicate EOB latency alarm name

ops/terraform/modules/resources/asg/main.tf
**Why**
To narrow the VPN ingress on our FHIR servers. This problem was caught in the audit that @cthulhuplus did. Fixing this is part of good defense in depth practice. 
**Details**
Our current `bfd-<env>-fhir-base` security groups have a wide 10.0.0.0/8 ingress rule. There appears to be a bug in TF where this ingress rule isn't being cleared in deploys. Hence, if we rebuilt our environments they wouldn't have VPN access. 
@karlmdavis ran into this problem during the pipeline bring-up and found the solution. We need to add the private-vpn security group to each instance.
=> BLUEBUTTON 1363:  Narrow VPN ingress

ops/terraform/modules/resources/asg/main.tf
Our deploy times have crept up in length, possibly due to adding more work at launch time to handle disk partitioning: https://github.com/CMSgov/beneficiary-fhir-data/pull/110
AWS operations are also generally unreliable.  In the last 2 days I have seen numerous instances were we did not get to full capacity before terraform hit its ASG timeout:
```
Error: "bfd-test-fhir-120": Waiting up to 10m0s: Need at least 3 healthy instances in ELB, have 2.
```
This causes issues where the old ASG is not properly cleaned up and more concerning, scaling policies are not properly applied to the new ASG. A better long term solution is to investigate ways to speed up our deploys, but I think this will help in the interim.
=> Increase ASG capacity wait timeout to 20m

ops/terraform/modules/resources/asg/main.tf
Discussion here: https://cmsgov.slack.com/archives/CJQRH9RLG/p1570746279101600
Please sanity check me on the behavior by reading this doc: https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html#waiting-for-capacity
=> Prefer the behavior of min_elb_capacity to wait_for_elb_capacity

ops/terraform/modules/resources/asg/main.tf
Starting discussion here: https://cmsgov.slack.com/archives/CJQRH9RLG/p1570800638110600
AWS definition of the health check grace period:
> Frequently, an Auto Scaling instance that has just come into service needs to warm up before it can pass the health check. Amazon EC2 Auto Scaling waits until the health check grace period ends before checking the health status of the instance. Amazon EC2 status checks and Elastic Load Balancing health checks can complete before the health check grace period expires. However, Amazon EC2 Auto Scaling does not act on them until the health check grace period expires. To provide ample warm-up time for your instances, ensure that the health check grace period covers the expected startup time for your application. If you add a lifecycle hook, the grace …
=> Adjust healthcheck grace period to account for increased provisioning time

ops/terraform/modules/stateful/main.tf
**Why**
During testing disk queue depth went up higher than expected, but that event didn't correlate with overall RDS health. Since we don't want to be waken up for false events, remove the alarm on this metric.  
**What**
Simple change in the stateless module.
=> BLUEBUTTON 1370: Remove RDS disk queue depth alarms

ops/terraform/env/prod-sbx/migration/main.tf, ops/terraform/env/prod/migration/main.tf, ops/terraform/env/test/migration/main.tf
The latest 50/50 settings for the migration scripts. These changes have already been applied to `prod` and `prod-sbx`
=> BLUEBUTTON 1372: Smooth traffic migration between HealthApt to CCS

ops/terraform/env/prod-sbx/stateful/main.tf, ops/terraform/env/prod/stateful/main.tf, ops/terraform/env/test/stateful/main.tf
This reverts prod back to its previous value of 16k IOPS, and greatly reduces prod-sbx and test.  Data imports are the only time a high amount of write IOPS are used, and the only time we even approached 16k write IOPS in prod was during the initial data catch up.  RDS metrics show that we have stayed under 10k write IOPS during the last two data loads.  Our read IOPS on the replicas stays in the hundreds even during (thus far) peak loads.
This is definitely up for debate.  I think we could safely move prod IOPS to 10k unless we needed to process an abnormally large data load again.  Since no regular data loading is happening in test or prod-sbx I believe these are more than safe to move to 1k IOPS, at least for the time being.
=> BLUEBUTTON-1513: Revert high IOPS configurations of databases post migration

ops/terraform/env/test/stateful/main.tf
=> Minimum permitted IOPS ratio by AWS is 0.5

ops/terraform/env/prod/stateful/main.tf, ops/terraform/env/test/stateful/main.tf
**DO NOT MERGE UNTIL 10/21**
This allows us to obtain better debugging info for slow queries when they happen.  The auto_explain module can also run an analyze, but at a performance cost:
Ref: https://www.postgresql.org/docs/9.6/auto-explain.html
> Note: When this parameter is on, per-plan-node timing occurs for all statements executed, whether or not they run long enough to actually get logged. This can have an extremely negative impact on performance. Turning off auto_explain.log_timing ameliorates the performance cost, at the price of obtaining less information.
=> BLUEBUTTON-1500: Log plan on queries slower than 6s

ops/ansible/playbooks-ccs/build_bfd-server.yml, ops/ansible/playbooks-ccs/templates/cwagent-data-server.json.j2, ops/ansible/playbooks-ccs/vars/test/group_vars/all/env_specific.yml, ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2
This conditionally injects a backgrounded function into the startup routine that will make a number of attempts (with various configurable timeouts) to validate that one metadata endpoint and one database backed endpoint return expected values.  If not, it will attempt to safely stop the process as to prevent a successful deploy.
Need some feedback on a few things before it's readier to merge:
* Are the default timeouts sane?
* We probably want to check for a larger/more complete value, however I'm not sure what will be consistent between all environments.
* Should we attempt a more drastic process kill if safe kill fails?
* Any other error handling I'm missing?
=> BLUEBUTTON-1271: Startup smoke testing; Jetty edition

apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/S3ToDatabaseLoadApp.java, apps/bfd-pipeline/bfd-pipeline-rif-extract/src/main/java/gov/cms/bfd/pipeline/rif/extract/s3/DataSetMonitor.java, apps/bfd-pipeline/bfd-pipeline-rif-extract/src/main/java/gov/cms/bfd/pipeline/rif/extract/s3/DataSetMonitorWorker.java, apps/bfd-pipeline/bfd-pipeline-rif-extract/src/main/java/gov/cms/bfd/pipeline/rif/extract/s3/DataSetTestUtilities.java, apps/bfd-pipeline/bfd-pipeline-rif-extract/src/main/java/gov/cms/bfd/pipeline/rif/extract/s3/S3RifFile.java, apps/bfd-pipeline/bfd-pipeline-rif-extract/src/main/java/gov/cms/bfd/pipeline/rif/extract/s3/TaskExecutor.java, apps/bfd-pipeline/bfd-pipeline-rif-extract/src/main/java/gov/cms/bfd/pipeline/rif/extract/s3/task/DataSetMoveTask.java, apps/bfd-pipeline/bfd-pipeline-rif-extract/src/main/java/gov/cms/bfd/pipeline/rif/extract/s3/task/S3TaskManager.java, apps/bfd-pipeline/bfd-pipeline-rif-extract/src/test/java/gov/cms/bfd/pipeline/rif/extract/s3/DataSetMonitorWorkerIT.java
Ensure that exceptions in executors are bubbled up to threads, so that the threads' uncaught exception handlers can do their thing.
Also: update the uncaught exception handlers to use the graceful shutdown routines that were already being used elsewhere.
https://jira.cms.gov/browse/BLUEBUTTON-1361
=> BLUEBUTTON-1361: Improve BFD Pipeline's async error handling

ops/terraform/modules/stateless/main.tf
**Why**
DPC has new environment dpc-dev. This environment is peering with prod-sbx. 
**What**
Added the dpc-dev peering to the list of peerings for the prod-sbx. This change only affects the prod-sbx.
=> Add DPC dev VPC peering

ops/terraform/modules/resources/bfd_pipeline/main.tf
I enabled debug logging on the pipeline this weekend, and noticed that the DataSetMoveTask was getting kicked off properly, but appeared to fail after the first copy operation, as no further debug logs in that task appeared.  Through some testing of the AWS CLI I noticed the following error when copying objects:
```
An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied
```
This was strange because there is no CopyObject IAM permission itself.  Research dug up this very helpful article: https://aws.amazon.com/premiumsupport/knowledge-center/s3-troubleshoot-copy-between-buckets/
This helped establish that our bucket permissions were ok, but we were not granting enough KMS access to the pipeline role.  I've tested this by manually editing the policy …
=> BLUEBUTTON-1361: Fix pipeline data set move

ops/terraform/modules/resources/bfd_pipeline/main.tf, ops/terraform/modules/resources/bfd_pipeline/variables.tf, ops/terraform/modules/stateless/main.tf
By design, the pipeline treats any unhandled exception as an error log and shutdown event.  We want to make sure we are tracking these errors, but only page in prod as that is currently the only environment where the pipeline is doing anything.
=> BLUEBUTTON-1531: Add metrics and alarms for pipeline errors

apps/bfd-model/bfd-model-rif/pom.xml, apps/bfd-model/bfd-model-rif/src/main/java/gov/cms/bfd/model/rif/schema/DatabaseTestHelper.java, apps/bfd-model/bfd-model-rif/src/test/java/gov/cms/bfd/model/rif/schema/DatabaseSchemaManagerTest.java, apps/bfd-pipeline/bfd-pipeline-app/src/test/java/gov/cms/bfd/pipeline/app/AppConfigurationTestIT.java, apps/bfd-pipeline/bfd-pipeline-app/src/test/java/gov/cms/bfd/pipeline/app/S3ToDatabaseLoadAppIT.java, apps/bfd-pipeline/bfd-pipeline-rif-load/src/main/java/gov/cms/bfd/pipeline/rif/load/LoadAppOptions.java, apps/bfd-pipeline/bfd-pipeline-rif-load/src/main/java/gov/cms/bfd/pipeline/rif/load/RifLoader.java, apps/bfd-pipeline/bfd-pipeline-rif-load/src/main/java/gov/cms/bfd/pipeline/rif/load/RifLoaderTestUtils.java, apps/bfd-pipeline/bfd-pipeline-rif-load/src/test/java/gov/cms/bfd/pipeline/rif/load/RifLoaderIT.java, apps/bfd-pipeline/bfd-pipeline-rif-load/src/test/java/gov/cms/bfd/pipeline/rif/load/RifLoaderTest.java, apps/bfd-server/bfd-server-war/pom.xml, apps/bfd-server/bfd-server-war/src/main/config/server-start.sh, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/SpringConfiguration.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/ServerTestUtils.java, apps/dev/docker-compose.yml, apps/pom.xml, dev/devenv-readme.md
Added support for running ITs against PostgreSQL.
As part of this, had to do a bunch of stuff:
* Refactor a lot of tests to use the new `DatabaseTestHelper`.
* Make `RifLoader` `AutoCloseable`, to avoid connection leaks that were causing test failures (when run against PostgreSQL).
* Add properties to the root POM that specify which DB to run ITs against.
* Add a configuration option to the BFD Server that causes it to run DB schema migrations (disabled by default).
* Add a `docker-compose.yml` descriptor that can be used to standup a temporary PostgreSQL DB, for use in local development and testing.
* Updated the `devenv-readme.md` file a bit, and added instructions on testing against PostgreSQL.
* Set the PostgreSQL connection's `application_name` option for the BFD Server.
* Needed …
=> BLUEBUTTON-1379: Added support for running ITs against PostgreSQL

ops/deploy-ccs.groovy
We need to update our deployments to use the latest gold image ASAP to comply with the audit.  I've tested this filter expression locally to ensure it finds the latest gold image available using RedHat 7.
=> BLUEBUTTON-1615: Use latest gold image

ops/terraform/modules/resources/bfd_server_metrics/main.tf
Unfortunately while rolling out #149 in test I ran into the realization that CloudWatch limits you to 100 metrics per log group.  Since we were near 200 metrics with my PR I needed to greatly reduce this by removing:
- Direct resource read metrics (didn't have these yet anyway)
- Latency > 6s count metrics (we track latency, don't think its necessary to count specific instances of it)
=> BLUEBUTTON-1376: Work around CloudWatch limitation

ops/terraform/env/prod-sbx/stateful/main.tf, ops/terraform/env/prod-sbx/stateful/variables.tf, ops/terraform/env/prod/stateful/main.tf, ops/terraform/env/prod/stateful/variables.tf, ops/terraform/env/test/stateful/main.tf, ops/terraform/env/test/stateful/variables.tf, ops/terraform/modules/stateful/main.tf, ops/terraform/modules/stateful/variables.tf
This requires the VictorOps URL to be passed as a local variable (ideally pulled from a secret store in the future) rather than hardcoded.  After this PR is deployed I will roll the new VictorOps URL out in all environments.
=> BLUEBUTTON-1616: Remove VictorOps URL from hardcoded location

ops/terraform/modules/mgmt_stateless/variables.tf, ops/terraform/modules/stateless/main.tf
This PR bumps the jenkins instance size to the c5 class to test performance gains during app builds.
=> BLUEBUTTON-1579: Increase instance size to c5.xlarge

ops/terraform/modules/mgmt_stateless/variables.tf
We saw no significant improvements with the change in instance size when building apps.
=> BLUEBUTTON-1579: Jenkins, revert back to m5 instance

ops/terraform/modules/resources/bfd_server_metrics/main.tf, ops/terraform/modules/stateless/main.tf
This adds request metrics tracking for DPC requests.  It also removes metrics tracking for specific types of searches due to CloudWatch limitations.  Ultimately this shouldn't be a huge issue due to the fact that 1) most partners only send one type of parameterized request per endpoint 2) CloudWatch lacks the charting ability to make good use of endpoint parameter breakdown metrics
=> BLUEBUTTON-1625: Add DPC metrics

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/BeneficiaryTransformer.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/BeneficiaryTransformerTest.java, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/patientByIdentifier.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/patientByIdentifierWithIncludeIdentifiers.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/patientRead.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/patientReadWithIncludeIdentifiers.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/patientSearchById.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/patientSearchByIdWithIncludeIdentifiers.json, apps/bfd-server/dev/api-changelog.md
Summary:
This is to remove the hashed HICN identifier from the patient resource response.
The following tasks were performed:
- Removed the TransformerConstants.CODING_BBAPI_BENE_HICN_HASH identifier from the BeneficiaryTransformer .  The BeneficiaryTransformer is used by the PatientResourceProvider for the FHIR response. 
- Testing of the Patient resource using CURL is working as expected in the local docker setup. 
- Reviewed the code base for other areas that this change might affect. Not seeing BeneficiaryTransformer utilized anywhere besides PatientResourceProvider and in related tests.
- Updated the unit tests in the BeneficiaryTransformerTest class. This included transformSampleARecord() and transformSampleARecordWithIdentifiers() methods. In addition to validating the count/size …
=> BLUEBUTTON-1679 Remove hicn-hash identifier from Patient Resource

apps/bfd-server/bfd-server-launcher/src/test/java/gov/cms/bfd/server/launcher/DataServerLauncherAppIT.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/BeneficiaryTransformer.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/TransformerUtils.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/BeneficiaryTransformerTest.java, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/patientByIdentifier.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/patientByIdentifierWithIncludeIdentifiers.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/patientRead.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/patientReadWithIncludeIdentifiers.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/patientSearchById.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/patientSearchByIdWithIncludeIdentifiers.json, apps/bfd-server/dev/api-changelog.md
**Why**
Improve the reliability of local builds.
When I switched to a faster laptop, my local `mvn clean install` builds of the master branch began to fail more frequently. Often, these failures would be in the `bfd-server-launcher` project. Other times they would be associated with `NPI_Coded_Display_Values_Tab.txt`. If I restarted the builds, they would succeed, so the problems were transitory. 
The test for the presence of the `access_log` was failing. Added a pause in the `DataServerLauncherAppIT` to allow the `access_log` to be written out. 
The `TransformUtils` function would read in the local resources like `NPI_Coded_Display_Values_Tab.txt`. The streams for these files were not in try-resource blocks. This is poor practice, although I don't think it was the cause …
=> Improve Build Reliability

apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V21__Add_MBI_hash.sql, apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V22__Add_MBI_hash_index.sql
**Why**
For the search by MBI hash feature, we need to add a mbiHash column to our database. This change only contains a DB migration. 
**What**
Two DB migrations: 21 and 22. Two DB migrations are needed because FlyWheel wants alters and index changes in separate migrations. 
The mbiHash columns are nullable and indexed. No default is set for the column so that the column will not be updated during the alter. 
**Testing**
Deployed to locally to both HSQL and Postgres. Tests passed. 
**Future**
Other code changes will populate the hash column.
**Security Implication**
=> BLUEBUTTON-1516: DB Migration for the mbiHash columns

apps/bfd-model/bfd-model-rif/src/main/resources/db/scripts/Flyway_revert_v21_Add_lastUpdated.sql, apps/bfd-model/bfd-model-rif/src/main/resources/db/scripts/Flyway_revert_v22_Add_bene_views.sql
**Why**
To fix the TEST environment.
The current TEST database has a couple of migrations from developer experimental branches applied to it that conflict with the current migration set in the master branch. 
**What**
These SQL scripts will remove the developer migrations which were non-destructive types of migrations. 
**Deployment**
Note: These scripts will only work in TEST. 
1. These scripts will be applied by hand to the TEST database.
2. Redeploy master branch to TEST
**Security**
NA
=> BLUEBUTTON-1727-Revert-Dev-Migration

apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/AppConfiguration.java, apps/bfd-pipeline/bfd-pipeline-rif-load/src/main/java/gov/cms/bfd/pipeline/rif/load/LoadAppOptions.java, apps/bfd-pipeline/bfd-pipeline-rif-load/src/main/java/gov/cms/bfd/pipeline/rif/load/RifLoaderIdleTasks.java, apps/bfd-pipeline/bfd-pipeline-rif-load/src/main/java/gov/cms/bfd/pipeline/rif/load/RifLoaderTestUtils.java, apps/bfd-pipeline/bfd-pipeline-rif-load/src/test/java/gov/cms/bfd/pipeline/rif/load/RifLoaderIT.java, apps/bfd-pipeline/bfd-pipeline-rif-load/src/test/java/gov/cms/bfd/pipeline/rif/load/RifLoaderTest.java, apps/bfd-pipeline/bfd-pipeline-rif-load/src/test/resources/logback-test.xml, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/ServerTestUtils.java
**Why**
The current mbiHash fixup feature is not working in PROD (works elsewhere) and is causing errors in the PROD logs. This feature flag disables the fixup feature so the logs are clear. It also increases the debugging level to assist in debugging the problem. 
Added a feature flag `FIXUPS_ENABLED` to the configuration of the pipeline application. Defaults to false. MBI hash fixups are only run if the FIXUPS_ENABLED=true. 
**Security Implications**
N/A
=> BLUEBUTTON-1516: Add feature flag for MBI fixups

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProvider.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProviderIT.java
**Why** 
The current code was returning the wrong beneficiary information for a bene search when
a HICN was mapped to multiple beneficiaries. 
**What**
Just error on this case.
=> BLUEBUTTON-1737: Revert to throw an exception when multiple Benes match a search

apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/AppConfiguration.java, apps/bfd-pipeline/bfd-pipeline-app/src/main/resources/logback.xml, apps/bfd-pipeline/bfd-pipeline-rif-load/src/main/java/gov/cms/bfd/pipeline/rif/load/LoadAppOptions.java, apps/bfd-pipeline/bfd-pipeline-rif-load/src/main/java/gov/cms/bfd/pipeline/rif/load/RifLoaderIdleTasks.java, apps/bfd-pipeline/bfd-pipeline-rif-load/src/main/java/gov/cms/bfd/pipeline/rif/load/RifLoaderTestUtils.java, apps/bfd-pipeline/bfd-pipeline-rif-load/src/test/java/gov/cms/bfd/pipeline/rif/load/RifLoaderIT.java, apps/bfd-pipeline/bfd-pipeline-rif-load/src/test/java/gov/cms/bfd/pipeline/rif/load/RifLoaderTest.java, apps/bfd-pipeline/bfd-pipeline-rif-load/src/test/resources/logback-test.xml
**Why**
This PR aims to speed up the fix-ups of the `mbiHash` field. In production, there are about 1 billion  fix-ups, which was about 10x as many fix-ups needed as expected. Using the current code, this would take about 14 days to complete. 
About a 10x speed up was achieved by: 
- Bypassing Hibernate and batching updates by using native SQL. Note: This code only works for Postgres. 
- Partitioning the tables and using multiple threads
- Bigger hardware running the pipeline code.
A new configuration parameter was added. `fixup_threads`. 
The idle task code was refactored to have a clear hierarchy of names and concepts. 
Ran a bunch of tests in PROD to benchmark the code. The number of threads were varied:
```
Threads   Fix-ups Per Second
------- …
```
=> BLUEBUTTON-1516: Faster fixups

ops/terraform/modules/stateless/main.tf
This adjusts the required number of 500s from > 0 to > 20 before triggering a page.  The upper bound I've seen so far is 15, but it's possible a bulk partner could trigger more than this.
I welcome any additional ideas, but ideally I'd like to get this or an equivalent solution merged in soon per: https://cmsgov.slack.com/archives/CJQRH9RLG/p1579282785023700
=> BLUEBUTTON-1737: Adjust 500s alarm threshold

ops/terraform/modules/stateful/main.tf
This adjusts our replica lag alert threshold from: > 10 minutes of lag for 3 minutes to > 30 minutes of lag for 3 hours.  I think this is acceptable at our current weekly update rate.  Long term we need to merge in #122 and restart each database.
=> BLUEBUTTON-1374: Adjust replica lag threshold and period given our data update model

ops/terraform/env/prod-sbx/stateless/main.tf, ops/terraform/modules/resources/lb/main.tf, ops/terraform/modules/resources/lb/variables.tf, ops/terraform/modules/stateless/main.tf, ops/terraform/modules/stateless/variables.tf
**Why**
To allow developers to continue to test against the latest releases of BFD in their integration tests. See [SIA to open prod-sbx](https://confluence.cms.gov/pages/viewpage.action?spaceKey=BB&title=Update+to+SIA+to+include+request+to+open+prod-sbx+to+general+internet+access+for+developer+usage).
**Changes**
- prod-sbx ELB is replaced and made public.
- The LB security group ingress rule is changed to `0.0.0.0/0`.
- {dpc, mct, bcda, bb}.prod-sbx.bfdcloud.net points to the new ELB.
- ELBs are marked with `prevent_destroy` for safety. 
- No change in other environments
**Deployment Plan**
The change to the prod-sbx ELB cannot be made in-place; It must be destroyed and replaced. This plan deploys without down-time by using a temporary ELB to hold traffic while the main ELB is replaced. …
=> BLUEBUTTON-1781: Open prod-sbx to Internet traffic

apps/bfd-model/bfd-model-rif-samples/src/main/java/gov/cms/bfd/model/rif/samples/TestDataSetLocation.java
**Why**
A new set of RIF files were created with MBIs and negative ids. These files were loaded into a new s3 bucket that is under the BFD AWS account. This change points our integration tests to use these new RIF files. 
1. A new S3 bucket was created by hand. bfd-public-test-data
2. The full synthetic data set was uploaded to this bucket. 
3. The loadSyntheticData test was updated to load from this bucket  
Other sample RIF files did not change. 
**Testing**
Loaded the data set locally on a local Postgres instance. The data set doesn't load on HSQL. 
**Future Work**
SAMPLE_A and other sample RIF files are still in the old bucket. Eventually, they should be made to have negative bene-ids and good synthetic MBIs.
=> BLUEBUTTON-1524: Update integration tests to load new synthetic data

ops/terraform/env/prod-sbx/stateful/main.tf, ops/terraform/env/prod/stateful/main.tf, ops/terraform/env/test/stateful/main.tf
**DO NOT MERGE UNTIL 10/21**
Initially we were planning to just bump up the replica lag alert threshold, however I took a deeper dive into replica lag across all 3 read nodes and found only replica 3 had ever hit our current threshold.  I came across a solid article from AWS on working with read replicas: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PostgreSQL.Replication.ReadReplicas.html
Based on this article its appeared that `max_wal_senders` being too low had the highest probability of causing an issue with the number of replicas we had.  I've increased this to 15 (default is 10) on the assumption that 5 per read replica is a good number (since replica 1 and 2 have not had issues), open to debate.
=> BLUEBUTTON-1374: Bump max_wal_senders to more gracefully handle replication between 3 read nodes during data load

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/BeneficiaryTransformer.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/CoverageResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProvider.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/BeneficiaryTransformerTest.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/ExtraParamsInterceptor.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProviderIT.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/utils/EndpointJsonResponseComparatorIT.java, apps/bfd-server/dev/api-changelog.md
Summary:
This PR extends the `IncludeIdentifiers` request header values for returning just "mbi" or "hicn" behaviors in the Patient Resource, and retains the default "true" behavior to return mbi and hicn.
NOTE: The code was refactored to replace the `PatientResourceProvider.IncludeIdentifiersMode` ENUM that had two states:  `INCLUDE_HICNS_AND_MBIS` and `OMIT_HICNS_AND_MBIS`. This was change to utilize a List `includeIdentifiersValues` instead that has valid values:  [ "true", "hicn", "mbi' ]. This was done to make the code more readable and simplify the logic.
The following tasks were performed:
* Created a `PatientResourceProvider.returnIncludeIdentifiersValues()` method to return a `List<String>` of validated request header values from   [ "true", "hicn", "mbi' ].
* Added  `hasMBI()` …
=> BLUEBUTTON-1536  Extend IncludeIdentifiers header options for Patient Resource response

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProvider.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProviderIT.java
Summary:
This PR updates the `PatientResourceProvider.queryDatabaseByHash()` method used for HICN and MBI searches to throw a `ResourceNotFoundException` exception when multiple bene id's are found. An entry in the access.json logs (via MDC) is also made for auditing.
The ignored (using @ignore) IT tests in the `PatientResourceProviderIT` class were updated for the new behavior.
These tests are:  `searchForExistingPatientByHicnHashWithBeneDups()` and `searchForExistingPatientByMbiHashWithBeneDups()`
A new assert method `assertPatientByHashTypeMatch()` was created to be used by these tests. It combines the overlapping code from the two separate `assertPatientByHicnHashWithBeneDupsMatch()` and `assertPatientByMbiHashWithBeneDupsMatch()` methods.
That HICN or MBI search requests that map to …
=> BLUEBUTTON-1737 Throw ResourceNotFoundException (404) for ID multiple matches 

ops/terraform/env/test/stateful/main.tf, ops/terraform/modules/stateful/main.tf
Why
To enable the logging of successful and unsuccessful logins to our RDS instances
What Changed
Added the log_connections parameter to the parameter group
Testing
None currently
Security Impact
Positive, will provide additional RDS database access data
=> Added the log_connections parameter to parameter group

ops/terraform/modules/stateless/main.tf
This adds cloudwatch metrics for AB2D, since we still use CloudWatch as 1st line reporting/monitoring.
=> BLUEBUTTON-1792: Add metrics for AB2D

ops/terraform/env/prod-sbx/stateful/main.tf, ops/terraform/env/prod/stateful/main.tf, ops/terraform/env/test/stateful/main.tf, ops/terraform/modules/resources/s3_pii/main.tf, ops/terraform/modules/resources/s3_pii/templates/bucket-policy.json, ops/terraform/modules/resources/s3_pii/templates/kms-policy.json, ops/terraform/modules/resources/s3_pii/variables.tf, ops/terraform/modules/stateful/main.tf, ops/terraform/modules/stateful/variables.tf
Adapted from the great work by @rnagle, this creates a PII S3 bucket module with fined grained access for readers, writers, and admins: https://github.com/CMSgov/dpc-ops/tree/master/terraform/modules/resources/s3-pii
One subject for debate is the lifecycle rule.  Should this be configurable, and should it operate on more than just object versions?
Also **do not merge** until this PR has been updated with the appropriate roles from BCDA and DPC, and test roles have been removed.
=> BLUEBUTTON-1595: 1-800 medicare opt out data bucket

ops/terraform/modules/resources/s3_pii/main.tf, ops/terraform/modules/stateful/main.tf
Unfortunately I ran into a few issues applying #168 :
- The root ARN was not properly formatted
- Group ARNs cannot be used as a principal in a KMS key policy (😞) so I reverted to the previous behavior of directly passing the admin users list: https://docs.aws.amazon.com/kms/latest/developerguide/control-access-overview.html
I have already rolled this out, just need to get it merged in.
=> BLUEBUTTON-1595: Fix issues with medicare opt out rollout

.github/workflows/ci-java.yml, .github/workflows/ci-terraform.yml, .gitignore, ops/terraform/modules/mgmt_stateful/main.tf
This PR adds the following two GitHub Actions workflows:
- On a PR that has changes inside the apps directory, run a `mvn verify` against the parent pom of the apps directory.  This will ensure all unit and integration tests pass prior to being merged.
- On a PR that has changes inside the terraform directory, run a `terraform validate` against each independent piece of terraform state.  This will ensure terraform is syntactically valid and internally consistent prior to being merged.  
The following changes were made to the mgmt stateful module:
- Adds a user, policy, and attachment that allows the GitHub Actions runner to run S3 integration tests.
Discussion:
- What else could be added/linted without increasing the security impact?  Some of the other terraform linting tools require …
=> BLUEBUTTON-1787: GitHub Actions CI for Java and Terraform development

apps/bfd-server/dev/api-changelog.md
Summary:
This updates the API Change Log information for:
BLUEBUTTON-1536 Extend IncludeIdentifiers header options for Patient Resource response #177
Information related to using an invalid value throwing an InvalidRequest exception (400 HTTP status code) was missing.
**NOTE: This is a documentation change only!**
The API Change Log documentation is corrected.
* [BLUEBUTTON-1536](https://jira.cms.gov/browse/BLUEBUTTON-1536)
* `IncludeIdentifiers` header values table:  https://confluence.cms.gov/display/BB/Blue+Button+Identifier+Options
=> BLUEBUTTON-1536 Update api-changelog with exception (400) information

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/LoadedFilterManager.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/LoadedFilterManagerIT.java
**Why**
Our deployment code expects that startup time will be consistent. It will timeout if startup takes too long. The current _since does a full filter refresh during startup. The duration of this operation varies by the number of RIF files recently loaded. This algorithm increases the possibility of a timeout during startup.  
**Changes**
The current design sets up `transactionTime` during init time, so the server can return Bundles with a transactionTime. Instead of calling `refreshFilters` during init time, the LoadedFilterManger just fetches transactionTime directly during init time. RefreshFilters will happen periodically in the background as before. 
**Security Implications**
None
=> Faster startup time

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/LoadedFilterManager.java
**Why**
During a load of RIF files in production, Coverage calls were discovered to be slowing down.
Replace a lock for the entire `refreshFilters` method with one just at the end when the state is set.
- Local IT
- Ad-hoc load testing of making a request while loading
=> Fix latency issue when RIF files are being loaded. 

apps/bfd-server-test-functions/pom.xml, apps/bfd-server/bfd-server-war/pom.xml, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/SpringConfiguration.java, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/metadata.json, apps/bfd-server/dev/api-changelog.md, apps/bfd-server/pom.xml
**Why**
This PR replaces the DependaBot https://github.com/CMSgov/beneficiary-fhir-data/pull/146 PR. It changes the FHIR library for the whole project. 
- API changelog updated
- Remove the ResponseHighlighter as it is deprecated in 4.1.0
- Common HAPI version for all bfd-server
- Updated Metadata fhir version from 3.0.1 to 3.0.2
- Confirmed that the except for the metadata response, the FHIR endpoint's response does not change. 
**Security Implications**
According to GitHub this pull request will fix a security vulnerability of moderate severity.
=> BLUEBUTTON-1843: Upgrade to HAPI 4.1.0

ops/ansible/playbooks-ccs/build_bfd-pipeline.yml, ops/ansible/playbooks-ccs/build_bfd-server.yml, ops/ansible/playbooks-ccs/launch_bfd-pipeline.yml, ops/ansible/playbooks-ccs/launch_bfd-server.yml
It seems in rolling out #226 I neglected the env dependent parts of the cloudwatch agent config.  This was fixed by moving those sections to the launch playbook, and tagging them as post-ami.
=> BLUEBUTTON-1810: Fix cloudwatch agent

apps/bfd-model/bfd-model-rif-samples/dev/design-sample-data-sets.md, apps/bfd-model/bfd-model-rif-samples/src/main/java/gov/cms/bfd/model/rif/samples/StaticRifResource.java, apps/bfd-model/bfd-model-rif-samples/src/main/java/gov/cms/bfd/model/rif/samples/StaticRifResourceGroup.java, apps/bfd-model/bfd-model-rif-samples/src/main/java/gov/cms/bfd/model/rif/samples/TestDataSetLocation.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/TransformerUtils.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/OutpatientClaimTransformerTest.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/TransformerTestUtils.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/TransformerUtilsTest.java
**Why**
Add new Outpatient claims to the synthetic data set.
- A new synthetic data set was created and loaded into the s3.
- In creating the new RIF files many fix-ups had to be done. The keybase://team/oeda_bfs/team/synthetic-data/outpatient-claims folder has the scripts and source data. @dtisza1 did most of this work. Some of the fix-ups include:
- Setting bene_ids to negative
- Fixing column names 
- Date formats
- White space 
- Decimal formats
- Generating REV_CNTR_STUS_IND_CD values from the distribution found in PROD
- Removed 2 files with conflicting CLM_IDs 
- New synthetic RIF file enumerations for the new outpatient RIF files
- New tests for the data
- Fixed a bug in addAddCareTeamPractitioner where the existing
- Updated the …
=> BLUEBUTTON-1788: Add Outpatient Data and Tests

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/TransformerUtils.java
The LGTM Static Analysis Tool has [uncovered a section of dead code](https://lgtm.com/projects/g/CMSgov/beneficiary-fhir-data/snapshot/df4e011a2b10444d7e58c539ee9e775d242963be/files/apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/TransformerUtils.java?sort=name&dir=ASC&mode=heatmap#x6617737a5dce7940:1) in the BFD code base.  This code is considered "dead code" because it is not being used/referenced by any other code.  It is likely that this code was introduced into the codebase with [this commit](https://github.com/CMSgov/beneficiary-fhir-data/commit/d440cbcba64dea6dd41ecc6e23730e5e1baf6237).
- Removed the code that is not being utilized
No PHI/PII is at-risk or affected as a result of this change.  The code in question was not being used and is being …
=> Remove Dead Code Uncovered by Static Analysis Tools

apps/bfd-pipeline/bfd-pipeline-app/src/main/resources/logback.xml
**Why**
As part of OUTPATIENT load work, it was discovered that the pipeline load was taking a very long time in TEST (and production). 
The RifLoader log level was set to debug. At the debug level, the pipeline would count every row in every table after every RIF load. Even in PROD, this query would take hours.  
To get this fix done quickly, this PR just lowers the log level to info. 
Local testing to confirm that changing the log level stops the counting step. 
**Future Action**
Filed ticket to fix the debug level problem at the root. 
https://jira.cms.gov/browse/BLUEBUTTON-1921
=> BLUEBUTTON-1788: Change RifLoader log level

ops/deploy-ccs.groovy, ops/packer/build_bfd-all.json
Inspired by this week's OEDA engineering meeting, I set out to see if we could build our AMIs in parallel.  As it turns out this is pretty easy to do, and packer supports running builders in parallel by default.  I combined the two packer definitions we had for the FHIR server and pipeline into one, ensured the builders were uniquely named, and that provisioners/post-processors only run for their corresponding named builder.  This shaves about 4-5 minutes off of our deploy times in total.
The only caveat is that since the builds happen in parallel, the ansible playbook output becomes wonky and harder to follow:
```
bfd-server: TASK [cloudwatch-agent-instrumented : cwagent | Copy agent configuration file] ***
bfd-pipeline: TASK [cloudwatch-agent-instrumented : cwagent | Copy agent …
```
=> BLUEBUTTON-1903: Use single packer definition to build AMIs in parallel

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/ExplanationOfBenefitResourceProvider.java
The list of claim types was not presented in stable order, so it ended up with a lot of duplicates.
https://jira.cms.gov/browse/BLUEBUTTON-1912
=> Fix EOB transaction/op names in New Relic and logs.

apps/bfd-model/bfd-model-rif-samples/dev/design-sample-data-sets.md, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/OutpatientClaimTransformer.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/OutpatientClaimTransformerTest.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/TransformerTestUtils.java, ops/ccs-ops-misc/synthetic-data/scripts/outpatient/convert_files.sh, ops/ccs-ops-misc/synthetic-data/scripts/outpatient/convert_outpatient_claims_csv_file_to_rif.py, ops/ccs-ops-misc/synthetic-data/scripts/test_eob_requests.sh
**Why**
The last attempt at loading this Outpatient data failed. This PR documents the changes made to fix this bug and more importantly the test added to fully test every record so that we confidence in the data load. 
- The root cause bug was identified as a missing PTNT_DSCHRG_STUS_CD field in some records. Fortunately, a good default value exists for this field. 0-Unknown Value was used in these cases.
- Discovered a corner case typo bug in the Outpatient transformer. This was fixed.
- A new test that loads and requests all 174k synthetic outpatient records was added. Previously, only a sample of these records was tested. 
- Work was done to optimize the execution speed of the outpatient tests. Without these optimizations, the 174k record test didn't complete in a …
=> BLUEBUTTON 1788: Outpatient Data Fixes and Tests

ops/terraform/env/prod-sbx/stateful/main.tf, ops/terraform/env/prod/stateful/main.tf, ops/terraform/env/test/stateful/main.tf, ops/terraform/modules/resources/s3_pii/templates/bucket-policy.json, ops/terraform/modules/resources/s3_pii/templates/kms-policy.json
This PR contains some minor changes:
- Fixes the KMS policy
- Fixes the bucket policy by removing a non-functional deny statement
- Removes offboarded admin
- Adds AB2D roles as readers to test (not currently used) and prod-sbx
- AB2D can make S3 requests to prod-sbx bucket
- [BLUEBUTTON-1864](https://jira.cms.gov/browse/BLUEBUTTON-1864)
This is worth discussing, as it was implemented that we'd have an explicit whitelist through denying actions via `NotPrincipal`, however I haven't been able to make this work in practice.  I'm unsure how much this changes to our security posture since we already have PII buckets (data from CCW) without this in place.
=> BLUEBUTTON-1864: Medicare Opt Out bucket fixes, AB2D onboarding

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProvider.java
**Motivation**
https://jira.cms.gov/browse/BLUEBUTTON-2001 reports a bug where a coverage searches together with paging and include-identifiers timed-out. 
**Cause**
When include-identifiers is set, the search uses a `join` clause to fetch the bene-id history. When paging is enabled, the search uses a `limit` clause to limit the number of returned results. 
There is subtle behavior with Hibernate where joins and limits cannot be used together; In this case, Hibernate drops the limit. 
This post explains the problem as well.
https://stackoverflow.com/questions/53569908/jpa-eager-fetching-and-pagination-best-practices
Note: The current code returns correct or nearly correct results. Test cases passed and the current code works small history datasets like those in SBX. 
**Changes Made**
When …
=> BLUEBUTTON 2001: Slow Coverage search with paging and identifiers

ops/terraform/modules/stateless/main.tf
This addition to our stateless module within our terraform scripts adds the AB2D CIDR's to our inbound security group for the BFD PROD load balancer. 
The correct peering name is used and in the correct environment.
Note: Notice that the VPC peer name is different, the naming scheme diverges from our original scheme. 
Does this look right?
- [BLUEBUTTON-1975](https://jira.cms.gov/browse/BLUEBUTTON-1975)
- [ X ] altered security controls
This PR adds the AB2D prod vpc CIDR's as a source(s) allowed inbound to the BFD PROD load balancer.
=> Add ab2d CIDR's to BFD prod LB firewall

apps/bfd-pipeline/bfd-pipeline-rif-load/src/main/java/gov/cms/bfd/pipeline/rif/load/RifLoaderIdleTasks.java
**Why**
When fixupEnabled=false, the fixup code was still counting the number of bene and bene-history records that needed to be fixed up. This count was causing an timeout with the Aurora DB.
**What**
A test for fixupEnabled=true was added to the initial idle task. 
**Testing**
I tried a canary on PROD to see if this fix worked. Confirmed that it does remove the count query and the ETL process starts up. 
```
2020-04-27 21:59:53,241 [main] INFO  org.hibernate.Version - HHH000412: Hibernate Core {5.2.10.Final}
2020-04-27 21:59:53,242 [main] INFO  org.hibernate.cfg.Environment - HHH000206: hibernate.properties not found
2020-04-27 21:59:53,264 [main] INFO  o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
2020-04-27 21:59:53,407 [main] INFO …
```
=> Disable Fixup Count

ops/terraform/env/prod-sbx/stateful/main.tf, ops/terraform/env/prod/stateful/main.tf, ops/terraform/env/test/stateful/main.tf, ops/terraform/modules/stateful/main.tf, ops/terraform/modules/stateful/variables.tf, ops/terraform/modules/stateless/main.tf
This comments out all RDS resources and variable definitions/values from upstream modules in order to effectively destroy all unused RDS resources without removing them from code (yet).  Resources destroyed include:
- RDS parameter groups
- RDS subnet groups
- RDS security groups
- RDS instances
- RDS route 53 records
- RDS cloudwatch alarms
- Unused RDS resources are destroyed per environment via terraform, and this change does not impact anything running in that environment
NOTE: This has already been run successfully in test and prod-sbx
- [BLUEBUTTON-1992](https://jira.cms.gov/browse/BLUEBUTTON-1992)
=> BLUEBUTTON-1992: Clean up RDS resources post Aurora migration

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/CoverageResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/ExplanationOfBenefitResourceProvider.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/CoverageResourceProviderIT.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/ExplanationOfBenefitResourceProviderIT.java
NOTE: This is a continuation of a previous PR with the target branch moved local.  Please reference  that PR for previous review comments at:  https://github.com/CMSgov/beneficiary-fhir-data/pull/175
A regex for parsing the format of EoB and Coverage resource read requests did not successfully parse synthetic Resource read requests due to their negative IDs. The result was that no synthetic EoB or Coverage resources were found on Read requests.
This updates those regex to allow for the IDs of these Resources to be negative.
* Moved the target branch to local and created a new PR so that this works with our deployment process.
* For the Coverage and EOB `read()` ID parameter, changed the exception from `ResourceNotFoundException` to `IllegalArgumentException` when an `IdText` does not …
=> BLUEBUTTON-2002 Return synthetic resources with negative IDs

ops/terraform/env/prod-sbx/stateful/main.tf, ops/terraform/env/prod/stateful/main.tf, ops/terraform/env/test/stateful/main.tf, ops/terraform/modules/resources/s3_pii/main.tf, ops/terraform/modules/resources/s3_pii/templates/bucket-policy.json, ops/terraform/modules/resources/s3_pii/templates/iam-write-assume-policy.json, ops/terraform/modules/resources/s3_pii/templates/iam-writer-assume-policy.json, ops/terraform/modules/resources/s3_pii/templates/iam-writer-policy.json, ops/terraform/modules/resources/s3_pii/templates/kms-policy.json, ops/terraform/modules/resources/s3_pii/variables.tf, ops/terraform/modules/stateful/main.tf, ops/terraform/modules/stateful/variables.tf
[BLUEBUTTON-1864](https://jira.cms.gov/browse/BLUEBUTTON-1864)
Refactor medicare opt out module to support assumed writer role
- Refactors the `s3_pii` module so that we no longer pass in a list of external writer roles, but instead pass in a list of writer AWS accounts that will assume a writer role we create.  This solves the issue of a bucket owner not being able to apply policies to objects owned by another account.
- While refactoring this module I ran into multiple issues with JSON formatting due to terraform template string interpolation, so I have wrapped the JSON templates in `jsonencode` and moved to native terraform expressions as per recommendations: https://www.terraform.io/docs/configuration/functions/templatefile.html#generatin …
=> BLUEBUTTON-1864: Refactor medicare opt out module to support assumed writer role

ops/terraform/env/prod-sbx/stateless/main.tf, ops/terraform/env/prod/stateless/main.tf, ops/terraform/env/test/stateless/main.tf
Hotfix for: https://github.com/terraform-providers/terraform-provider-aws/issues/13236
This should be reverted one we validate that the most recent AWS provider version works again.
=> BFD-211: Fix for broken AWS terraform provider >= 2.61.0

ops/terraform/env/prod/stateful/main.tf
Slack reference: https://cmsgov.slack.com/archives/CMT1YS2KY/p1590523487339100
Add AB2D role to prod medicare opt out bucket
Adds AB2D's instance role to the S3 policy for the prod medicare opt out bucket
That this successfully grants AB2D access to the intended bucket
* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment: N/A.
* Does this PR add any new software dependencies? **No**.
* Does this PR modify or invalidate any of our security controls? **No**.
* Does this PR store or transmit data that was not stored or transmitted before? **Yes**.
* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR should not …
=> Add prod role for AB2D

ops/terraform/modules/resources/bfd_pipeline/main.tf, ops/terraform/modules/resources/bfd_server_alarm/main.tf, ops/terraform/modules/resources/bfd_server_alarm/variables.tf, ops/terraform/modules/stateless/main.tf
[BFD-168](https://jira.cms.gov/browse/BFD-168)
Adjust CloudWatch alarms to alert when there is a systemic issue rather than an outlier, bring alerts slightly closer to reality with our SLOs
FHIR server:
- Refactor to pass in a configurable number of datapoints for alarms rather than hardcoding "1"
- Attempt to set sane configuration parameters for evaluating unacceptable P95 latencies for MCT and other partners over time
- Attempt to set sane configuration parameters for evaluating persistent HTTP 500 errors over time
Pipeline:
- Refactor to pass in a configurable number of datapoints for alarms rather than hardcoding "1"
- Add metric for data set failure event
- Add alarm for data set failure event
- Attempt to set sane configuration …
=> BFD-168: Refactor CloudWatch metric alarms

ops/ccs-ops-misc/DEPLOY-INFO.md
[BFD-63](https://jira.cms.gov/browse/BFD-63)
Provide deployment general and troubleshooting information as documentation
This documentation outlines general information regarding how our Jenkins multibranch pipeline is architected, along with some edge cases.  It also provides deployment troubleshooting guidance based on past issues seen, and some theoretical scenarios that have never come to pass (rollbacks) but could be needed in the future.
If you're reviewing this PR, please check these things, in particular:
- Anything else you feel you don't know about our deployment scenario that I could provide here?
* If the answer to any of the questions below is **Yes**, then here's a link to …
=> BFD-63: Deployment information and troubleshooting documentation

ops/terraform/modules/stateless/main.tf
In support of increasing performance for AB2D, we are increasing the minimum number of running instances from 3 to 6 for prod and prod-sbx environments (test should remain at 3 to save on costs).
This is a temporary measure until a better AutoScaling metric can be created.
- Min and Desired counts should be twice the count of availability zones (we have 3) if prod or prod-sbx
- Test should remain at the default number of 1 per AZ (3 total)
Notes:
A `terraform plan` was run manually to verify that test would remain at 3 instances and prod would be increased to 6. This is a snippet from prod (test remained at 3):
```
~ min_elb_capacity.   = 3 -> 6
~ min_size.   = 3 -> 6
```
- [BFD-256](https://jira.cms.gov/browse/BFD-256)
None
=> BFD-256 - Increase min ASG size for prod and prod-sbx

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/TransformerUtils.java
LGTM identified a type mismatch when checking for a care team entry in an ExplanationOfBenefit item, where `PositiveIntType` objects are being compared to an `int`. This changes the check to use the `PositiveIntType`'s value, an `Integer`.
- https://lgtm.com/projects/g/CMSgov/beneficiary-fhir-data/snapshot/fe72eb2cf5aa84e17bf1be7738398f59f645d081/files/apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/TransformerUtils.java#x1661a4d14162ef46:1
No security implications.
=> Correct type mismatch in TransformerUtils

.github/workflows/ci-java.yml, ops/ansible/playbooks-ccs/vars/prod-sbx/group_vars/all/env_specific.yml, ops/ansible/playbooks-ccs/vars/prod/group_vars/all/env_specific.yml, ops/ansible/playbooks-ccs/vars/test/group_vars/all/env_specific.yml, ops/ansible/roles/bfd-server/defaults/main.yml, ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2
Does this variable definition look complete?
Is the variable set to FALSE in all environments?
N/A
- [BLUEBUTTON-347](https://jira.cms.gov/browse/BLUEBUTTON-347)
=> Add V2_ENABLED environment variable for all environments

contributing/patches/load_local_synthetic_data.patch
Previous changes made to StaticRifResourceGroup.java and RifLoaderIT.java caused `make loadable` to fail.
Command output:
```
cd ../; git apply --ignore-space-change --ignore-whitespace contributing/patches/load_local_synthetic_data.patch
error: patch failed: apps/bfd-model/bfd-model-rif-samples/src/main/java/gov/cms/bfd/model/rif/samples/StaticRifResourceGroup.java:44
error: apps/bfd-model/bfd-model-rif-samples/src/main/java/gov/cms/bfd/model/rif/samples/StaticRifResourceGroup.java: patch does not apply
error: patch failed: apps/bfd-pipeline/bfd-pipeline-rif-load/src/test/java/gov/cms/bfd/pipeline/rif/load/RifLoaderIT.java:287
error: apps/bfd-pipeline/bfd-pipeline-rif-load/src/test/java/gov/cms/bfd/pipeline/rif/load/RifLoaderIT.java: patch does not apply
make: *** [loadable] Error 1
``` …
=> BCDA-3622 - Update patch file to reflect latest base changes

contributing/patches/load_local_synthetic_data.patch
Fixing missing curly brace in load_local_synthetic_data.patch file. This caused compilation errors in RifLoaderIT.java.
Resolves regression introduced by https://github.com/CMSgov/beneficiary-fhir-data/pull/346
1. After running `make loadable`, verified that we can run `make load` successfully.
=> Fix error in load_local_synthetic_data.patch file

ops/ansible/playbooks-ccs/build_jenkins.yml, ops/ansible/playbooks-ccs/update_jenkins.yml
This change removes (or does not install) the unused docker installation from our build servers. Since we do not use docker in any shape or form on our build servers, this service simply eats up system resources for no reason.
Note: I deployed this change to mgmt-test and verified that docker was not present and we were able to build.
The 'install_docker' ansible role is not included when building or updating jenkins.
None. It actually improves security by decreasing our build server's attack surface.
=> Remove docker from our build servers.

insights/terraform/projects/bcda/backend.tf, insights/terraform/projects/bcda/main.tf
This branch adds glue catalog tables per environment for the postgres queries that we are currently making in BCDA using the insights data samplers.
These tables allow us to query any information that is being pushed through our firehoses.
Additionally, this fixes version of terraform to `0.13.4`.
All feedback is welcome.
- [BCDA-3815](https://jira.cms.gov/browse/BCDA-3815)
- [BCDA-3873](https://jira.cms.gov/browse/BCDA-3873)
All feedback is welcome.
=> BCDA-3815: BFD Insights: Adding tables for BCDA insights queries

ops/ansible/playbooks-ccs/build_bfd-platinum.yml, ops/ansible/playbooks-ccs/roles/platinum_post/tasks/main.yml
There is a cron entry baked into the gold image that runs `aide` and attempts to send the results over email. This is problematic because:
1. Email is not a secure method of sending sensitive data.
2. The results of the aide check is too large so the email fails.
3. The aide database needs to be updated after installing/updating packages.
This patch removes the failing cron job and updates the aide database so our ops can run it on live instances as needed.
For more information on `aide` see:
- https://aide.github.io
- https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sec-using-aide
- Removes the cron job in root's crontab.
- Runs `aide --update` after all other platinum roles have run.
- [BFD-602](https://jira.cms.gov/browse/BFD-602)
=> Aide fixup

Jenkinsfile
Fix to send Slack notifications when builds are started (doh).
Somehow this was missing from my previous [Jenkins/Slack PR](https://github.com/CMSgov/beneficiary-fhir-data/pull/447)
- Sends slack notifications during the 'Prepare' stage. 
Nothin obvious stands out.
=> [FIX] Notify that a build was started.

ops/terraform/modules/resources/aurora/main.tf
Background:
Recently, in order to backfill many millions of MBI hashes, we cloned our production database cluster, did the work, and then switched over our production environment to use this clone. As a result, our terraform state is now out of sync because of this out-of-band work.
Unfortunately, during this cloning process, the cloned (and now live) cluster db instance identifiers were named slightly different than before. For example, we went from `bfd-prod-aurora-node-0` to `bfd-prod-aurorar-cluster-node-0`. This naming difference only occurs in prod, not prod-sbx or test and the same issue occurs for nodes 1 and 2.
Now terraform does not know about these "new" nodes and wants to create them. Normally, a simple `terraform import` would fix this issue, but because of the naming issues, …
=> [BFD-665] Dynamically select node identifier name to help resolve tf state

ops/terraform/env/prod-sbx/stateful/main.tf, ops/terraform/env/prod/stateful/main.tf, ops/terraform/env/test/stateful/main.tf, ops/terraform/modules/resources/kms/main.tf
The HWRI IAM user does not exist which is causing errors applying policy related terraform.
This removes Rick's HWRI IAM entries from the repo (minus insights as we do not manage that portion.)
No glaring issues.
- [BFD-673](https://jira.cms.gov/browse/BFD-673)
Removes non-existent user from our IAM policies.
=> [BFD-673] Removes Rick's (non-existant) HWRI EUA ID

ops/ansible/roles/bfd-pipeline/tasks/main.yml
Amazon's EFS Utils package allows us to mount EFS file systems using IAM
permissions and is generally recommended over the standard NFS utils
when working with EFS shares.
This is required for the EFT<>BFD<>EFS<>BCDA work.
- Deployed to test and verified no impact to ETL pipeline
- [BFD-679](https://jira.cms.gov/browse/BFD-679)
- [BFD-615](https://jira.cms.gov/browse/BFD-615)
- https://docs.aws.amazon.com/efs/latest/ug/using-amazon-efs-utils.html
None. This package is available in our standard yum repos.
=> [BFD-679] Install AWS EFS Utils on ETL/Pipeline

ops/ansible/playbooks-ccs/build_bfd-pipeline.yml, ops/ansible/playbooks-ccs/roles/amazon-efs-utils/defaults/main.yml, ops/ansible/playbooks-ccs/roles/amazon-efs-utils/tasks/main.yml, ops/ansible/roles/bfd-pipeline/tasks/main.yml
The default amazon-efs-utils on rhel 7 is not capable of creating secure tunnels to amazon's efs service for several reasons:
1. The version of stunnel in rhel 7 (version 4 something) is wildly  outdated
2. The default amazon-efs-utils is not running in fips mode
3. The default stunnel is not configured for fips mode
This commit adds an ansible role that replaces the outdated stunnel with a manually compiled (with fips) version, installs a fips compatible version of amazon-efs-utils, and configures the server accordingly.
This role is imported into our ETL pipeline build so that our ETL instances can securely mount EFS file systems using IAM.
- No glaring issues
- A successful deployment to test has been performed and efs mount verified
- [BFD-692](https://jira.cms.gov/browse/BFD-692)
- …
=> [BFD-692] Install and configure amazon-efs-utils on ETL

CONTRIBUTING.md, README.md, contributing/patches/load_local_synthetic_data.patch
- Update top-level README to include native development environment setup instructions
- Update `loadLocalSynthethicData` patch to account for the reorganization of the `bfd-pipeline` app.
You should be able to follow these instructions and have them work for with a totally new setup (pending things like AWS access that are assumed). 
Do these instructions work for you? Anything else you'd like to see?
- [BFD-702](https://jira.cms.gov/browse/BFD-702)
This change updates documentation and updates a previously existing patch's filepaths. It would surprise me if this triggered security concerns.
=> BFD-702: Add native development environment setup instructions

apps/bfd-server/bfd-server-launcher/src/main/resources/logback.xml, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/LoadedFilterManager.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/LoadedFilterManagerTest.java
* Changed the way that the last and current update times are compared in `LoadedFilterManager`
* Added unit tests that show the issue and protects against possible behavioral changes in future versions of Java.
A detailed explanation of the issue along with testing notes is available in JIRA: [BFD-713](https://jira.cms.gov/browse/BFD-713)
From a high level, the issue is that the `Date` objects being compared in `LoadedFilterManager` are actually `java.sql.Timestamp` instances.  `java.sql.Timestamp` splits the time into Seconds and Nanos, instead of keeping a complete millisecond timestamp.  This causes  `Date.before` to return `false` when the times are different because only the seconds were compared and not the milliseconds.  This meant that if the last update in the database happened …
=> [BFD-713] Fix for `lastUpdated` time being inconsistent across BFD instances

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4PatientResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProvider.java
Because the DISTINCT JPQL keyword has two meanings based on the underlying query type, it’s important
to pass it through to the SQL statement only for scalar queries where the result set requires duplicates
to be removed by the database engine.
For parent-child entity queries where the child collection is using JOIN FETCH, the DISTINCT keyword should
only be applied after the ResultSet is got from JDBC, therefore avoiding passing DISTINCT to the SQL statement
that gets executed.
Added boolean logic to optimize distinct processing.
.setHint("hibernate.query.passDistinctThrough", passDistinctThrough); 
This PR does not address changes to V2 patientResource handling of HICN or MBI headers; those will be addressed in another ticket.
Minimum acceptable processing is to marginally improve JPA …
=> BFD-659: Remediate-Performance-Regression_Patient_Endpoint

apps/bfd-server/bfd-server-war/pom.xml, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/SpringConfiguration.java, apps/pom.xml
This PR addresses [BFD-717](https://jira.cms.gov/browse/BFD-717). It adds a `NewRelicReporter` that takes existing measurements from Dropwizard, transforms them into a format that New Relic will understand, and then ships them off. It also upgrades the Dropwizard Metrics major version to 4.1.2. There is an enum introduced in v4 that the New Relic integration package relies on. This also required adding a separate `metrics-jmx` artifact, which was split out in the migration from v3 to v4.
The reporter will only be configured as part of the `MetricRegistry` Spring Bean if the `NEW_RELIC_METRIC_KEY` environment variable is set. This is a new key that differs from the existing license key. 
A writeup on how to query and analyze the new Dropwizard metrics in New Relic is forthcoming.
_Special …
=> BFD-717: Send Dropwizard Metrics to New Relic

apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/OutpatientClaimTransformerV2Test.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/TransformerTestUtilsV2.java
This PR addresses [BFD-745](https://jira.cms.gov/browse/BFD-745). It adds unit tests for the `OutpatientClaimTransformerV2` in the style created in #521.
- Tests all pass
- The test coverage of serialized Sample A Outpatient Claims is complete enough for our purposes
- [BFD-745](https://jira.cms.gov/browse/BFD-745)
=> BFD-745: Add unit tests for OutpatientClaimTransformerV2

apps/bfd-model/bfd-model-rif/pom.xml, apps/bfd-model/bfd-model-rif/src/main/java/gov/cms/bfd/model/rif/schema/DatabaseSchemaManager.java, apps/bfd-model/bfd-model-rif/src/main/java/gov/cms/bfd/model/rif/schema/DatabaseTestHelper.java, apps/bfd-model/pom.xml, apps/pom.xml
This PR finishes [BFD-778](https://jira.cms.gov/browse/BFD-778). It upgrades Flyway and HSQL versions. This PR is another attempt following work that was done in #541 and the reversion of that work in #546. After the first attempt we received the following error:
```
org.flywaydb.core.api.FlywayException: Found non-empty schema(s) "public" but no schema history table. Use baseline() or
set baselineOnMigrate to true to initialize the schema history table.
```
This exception occurred because in Flyway v5 the default name of the schema table was changed from `schema_history` to `flyway_schema_history`. This is the  table where Flyway records which migrations it previously applied. Because we are upgrading from Flyway v4 to v7, we need to specify the old table name for backwards …
=> [BFD-778] Upgrade Flyway and HSQL

apps/bfd-model/bfd-model-rif/src/main/resources/db/scripts/BFD-854-Fix-PartD-Enrollment-Smaller-Transactions/05_process_ccw_table.sql
BFD-766 created the main setup and processing engine for fixing BeneficiaryMonthly Part D contract data with custom load files (one for 2019, one for 2020) provided by CCW. The last step in that process, 05_process_ccw_table.sql, failed when the OS killed the database server due to extraneous memory consumption. This was probably due to a significantly high amount of memory being reserved for the rollback/commit buffers.
This PR modifies the 05_process_ccw_table.sql procedure to perform a db COMMIT every 10,000 records.
In addition, there was (very) minor logic to attempt to minimize unnecessary date calculations which might save some (minimal) processing compute cycles...but times 130M rcds might add up.
Look for the COMMIT statement every 10,000 rcds.
Look at the date calc cache logic …
=> [BFD-854] Fix-PartD-Enrollment-Smaller-Transactions

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/TransformerUtilsV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/TransformerUtils.java
The file fda_products_cp1252.tsv holds codes that the app expects in a certain format. One of the codes did not have a hyphen, which caused unit test failures. This commit ignores malformed ids.
- [BFD-883](https://jira.cms.gov/browse/BFD-883)
=> [BFD-883] Ignore malformed drug codes

apps/bfd-pipeline/bfd-pipeline-app/src/test/java/gov/cms/bfd/pipeline/app/PipelineManagerIT.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/pom.xml, apps/bfd-server/bfd-server-war/pom.xml
This PR addresses two issues that cause intermittent IT test failures:
- ~~`PipelineManagerIT` sometimes fails due to a `RejectedExecutionException`.  This was caused by the extremely short (1ms) execution interval leading to a race condition as the test shuts down the `ScheduledExcecutor`.  Increasing that to 100ms makes the race condition far less likely to happen.~~
- Various tests in `bfd-server-war` and `bfd-pipeline-ccw-rif` fail with `lastUpdated` related error messages.  These are due to the logic in the tests assuming that the timezone is set to UTC.  Adding a `TZ` environment variable to the execution environment in the pom.xml assures the timezone is set as expected by the test.
Unit tests should pass more reliably than before.
Nothing specific.
None.
no
no
no
no
no
=> MISC - fixes intermittent IT test failures due to timezone and race conditions

ops/ansible/playbooks-ccs/vars/prod/group_vars/all/env_specific.yml, ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2
This change sets the `data_server_v2_enabled `to `true` for the BFD PROD API servers thus enabling all BFD V2 FHIR Resources and Endpoints (i.e. /v2/fhir/Patient, etc.) 
This change also adds V2 endpoints (and an additional EOB check) to the bfd-server.sh startup script. Is this a good idea?
Did I set the correct environment variable?
Are we ready for this? :)
Do you all agree having a EOB API check during bfs-server startup is helpful? It would have prevented last weeks PG12 migration incident, because patient and coverage resources performed well, EOB was hosed. 
- [BFD-907](https://jira.cms.gov/browse/BFD-907)
=> [BFD-907] Enable BFD API V2 in PROD

.github/workflows/ci-java.yml, apps/bfd-model/bfd-model-codebook-extractor/pom.xml, apps/bfd-model/pom.xml, apps/bfd-pipeline/bfd-pipeline-app/pom.xml, apps/bfd-pipeline/bfd-pipeline-benchmarks/pom.xml, apps/bfd-pipeline/bfd-pipeline-ccw-rif/pom.xml, apps/bfd-pipeline/bfd-pipeline-rda-grpc/pom.xml, apps/bfd-pipeline/bfd-pipeline-shared-utils/pom.xml, apps/bfd-pipeline/pom.xml, apps/bfd-server-test-perf/pom.xml, apps/bfd-server/bfd-server-launcher/pom.xml, apps/bfd-server/bfd-server-war/pom.xml, apps/pom.xml
This was already _mostly_ happening for ITs, but I moved that into the parent POM to apply it everywhere and also turned it on for unit tests. (Surefire runs our unit tests and failsafe runs our ITs.)
Should help make our build logs a bit more manageable, particularly on GH Actions and Jenkins.
In addition:
* Cleaned up the failsafe POM entries a bit, to improve consistency.
* Set GH Actions to save our test data files, e.g. `failsafe-reports`, as build artifacts.
1. Do you agree this is a good idea?
2. Does it work as expected?
(see above)
This PR has no security implications.
=> BFD-897: Redirect all test output to separate files

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProvider.java
_May_ workaround an intermittent DB query timeout that we're seeing in production.
1. Does the logic here look sound?
2. Does it pass our build?
3. Are you comfortable with the performance tradeoff?
* We'll be adding a third DB query to the first page of every search result for this operation. It _should_ only be a hundred milliseconds or so, but that's not nothing.
(see above)
- [BFD-1057](https://jira.cms.gov/browse/BFD-1057)
This PR should not have any security implications.
=> BFD-1057: Add pre-flight check to Patient search by Part D

Jenkinsfile
N/A
The default STS assume role timeout is 1hr, and due to our large one-shot deployments, there is a good chance we'll hit that limit by the time we deploy upper environments.  This sets the timeout to the maximum to ensure that won't happen.
Sets STS assume role timeout to 12hr.
N/A …
=> BFD-1095: Set maximum session duration for STS assume role

apps/bfd-pipeline/bfd-pipeline-rda-grpc-server/src/main/java/gov/cms/bfd/pipeline/rda/grpc/sink/ConfigLoader.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc-server/src/test/java/gov/cms/bfd/pipeline/rda/grpc/sink/ConfigLoaderTest.java
[DCGEO-198](https://jira.cms.gov/browse/DCGEO-198)
As a BFD developer I need to be able to run unit tests in environments that limit access to temp files.
---
Removes temp file access from ConfigLoader unit tests.
Cloudbees did not allow the unit test to create temp files.  This PR includes a change to isolate the file validation code into testable methods that can be passed a mock File object so that no actual files need to be created.
* Do the tests look correct and cover all of the intended cases. …
=> DCGEO-198: Remove temp file access from ConfigLoader unit tests

apps/bfd-model/bfd-model-rda/pom.xml, apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/PreAdjFissClaim.java, apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/PreAdjMcsClaim.java
[PACA-471](https://jira.cms.gov/browse/PACA-471)
Adding the `@BatchSize(size=100)` annotation to the one-to-many fields on the `PreAdjFissClaim` and `PreAdjMcsClaim` entities improves the performance of our Claim and ClaimResponse FHIR APIs as it instructs Hibernate to gather the child resources using an `IN` clause rather than 1 by 1.  Locally, we've observed speed increases up to 3x faster.  We don't anticipate that large of a bump in AWS, but do think it will add a significant percentage increase, especially to claims with many line items.
---
Simply adds `@BatchSize` annotations in the claim entities so that hibernate combines lookups for detail tables of multiple claims into a single query.
If you're reviewing this PR, please check for …
=> PACA-471: Add BatchSize annotations to pre-adj claim entities.

apps/bfd-server/bfd-server-launcher/src/main/java/gov/cms/bfd/server/launcher/DataServerLauncherApp.java, ops/terraform/modules/stateless/main.tf
[BFD-1613](https://jira.cms.gov/browse/BFD-1613)
Clarify Log-Derived Metric Units
---
This corrects the log format to begin producing milliseconds instead of microseconds in the bfd-server application. Additionally, this effectively reverts recent changes to the alarm threshold to expected milliseconds once again.
**Old Log Format**
Values are represented in microseconds (µs). Three test requests timed at `2196000`, `263000`, and `161000` yields a simple average of `873333` microseconds:
```
127.0.0.1 - "CN=client-local-dev" [23/Mar/2022:22:01:34 +0000] "GET /v2/fhir/ExplanationOfBenefit/?patient=567834&_format=json HTTP/1.1" "?patient=567834&_format=json" 200 129797 2196000 - - [-] - "-" - "-" - "-" -
127.0.0.1 - "CN=client-local-dev" …
```
=> BFD-1613 Clarify Log-Derived Metric Units

apps/build.groovy
[BFD-1658](https://jira.cms.gov/browse/BFD-1658)
Increase threading in Build Apps Stage of Jenkins Pipeline
---
This PR uses 1 thread per core in the Jenkins Build Apps stage, which at last makes it more like the process we use in GitHub Actions. We have seen between 30% and 40% decrease in time spent in the Build Apps stage in the Jenkins pipeline with the addition of just these 13 characters, `--threads 1C`.
* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security …
=> BFD-1658 Increase threading in Build Apps Stage

apps/bfd-server/bfd-server-launcher/pom.xml, apps/pom.xml, ops/ansible/roles/bfd-server/defaults/main.yml, ops/ansible/roles/bfd-server/tasks/install.yml, ops/ansible/roles/bfd-server/test/post-test.sh, ops/ansible/roles/bfd-server/test/run-tests.sh
[BFD-1631](https://jira.cms.gov/browse/BFD-1631)
Prefer maven over ansible for newrelic agent jar inclusion
---
* Treats the newrelic agent more like other dependencies by packaging along with other bfd-server dependencies
* Removes newrelic java agent fetch, unarchive, and copy operations from ansible role, replacing them with a find+copy operation from the newly available, pre-installed newrelic java agent
* Updates jdk package installation logic to tamp down on deprecation warnings and prepare for newer ansible versions
* Extends the bfd-server ansible role test harness with `getopts` for more flexibility in local ansible development …
=> BFD-1631 Package newrelic-agent with bfd-server

apps/bfd-model/bfd-model-codegen/src/main/java/gov/cms/bfd/model/codegen/RifLayoutsProcessor.java, apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V65__Add_PreUpdate_Trigger_Beneficiaries.sql, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoaderIT.java
[BFD-1699](https://jira.cms.gov/browse/BFD-1699)
Fix RIF loader bug in which an UPDATE to the _beneficiaries_ table would contain a zero value in the Beneficiary object that is used to persist a record. The issue is that _bene_id_numeric_ is a native long, which will be 0 (zero) when the Beneficiary object is instantiated. This creates a situation in which the first record will be stored with a zero value in a unique index constraint; when the 2nd records is attempted to be persisted, it throws a db constraint violation since we are again trying to write a zero value on a column defined as unique.
This PR fixes the issue where the RIF loader attempts to update a _beneficiaries_ record during an UPDATE operation; a pre-update trigger is …
=> BFD-1699 fix bene id numeric update bug

ops/ansible/roles/bfd-server/tasks/install.yml, ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2, rfcs/0013-bfd-server-startup-check.md
[BFD-1685](https://jira.cms.gov/browse/BFD-1685)
Implement a startup check for bfd-server.
---
This is the implementation side of the RFC 0013 and extends the `stop_service_if_failing` function to fully satisfy the requirements of a startup check with the following:
1. Augment the bfd-server service account with sudoers access, restricted to `/sbin/iptables` via ansible definition
2. Adjust the templated `bfd-server.sh.j2` file with the following changes:
- At the beginning of the `stop_service_if_failing` function, disallow external traffic on port 7443:
```bash
sudo iptables -A INPUT -p tcp -i eth0 --dport 7443 -j REJECT
```
- Where the script currently produces the log message "Server started properly", allow external traffic on port …
=> BFD-1685: Implement bfd-server startup check

ops/ansible/playbooks-ccs/build_bfd-db-migrator.yml, ops/ansible/playbooks-ccs/launch_bfd-db-migrator.yml, ops/ansible/playbooks-ccs/templates/cwagent-db-migrator.json.j2, ops/ansible/roles/bfd-db-migrator/README.md, ops/ansible/roles/bfd-db-migrator/defaults/main.yml, ops/ansible/roles/bfd-db-migrator/handlers/main.yml, ops/ansible/roles/bfd-db-migrator/tasks/migrator.yml
[BFD-1600](https://jira.cms.gov/browse/BFD-1600)
Introduce the ansible portions of the bfd-db-migrator infrastructure configuration.
---
This _largely_ adds the "launch" playbook (and dependency), but there are some minor adjustments to the "build" playbook and migrator role that seemed appropriate to introduce at this time.
Ultimately, this is still begging to be tidied up further, but the `bfd-db-migrator` infrastructure has been implicitly re-prioritized over the past six weeks several times and it's badly needed. I've tried to keep the ansible for the migrator and its respective playbooks similar in shape to the existing services, `bfd-pipeline` and `bfd-server`, however there are some innovations that should probably be applied …
=> BFD-1600: Add bfd-db-migrator launch playbook

ops/ccs-ops-misc/load_test/README.md, ops/ccs-ops-misc/load_test/common/bfd_user_base.py, ops/ccs-ops-misc/load_test/common/config.py, ops/ccs-ops-misc/load_test/common/stats.py, ops/ccs-ops-misc/load_test/common/test_setup.py, ops/ccs-ops-misc/load_test/requirements.txt, ops/ccs-ops-misc/load_test/runtests.py
[BFD-1691](https://jira.cms.gov/browse/BFD-1691)
As a BFD engineer, I want to capture and store performance performance metrics on configured runs, so that I can store performance metrics which will be reviewed to assess the performance of the BFD as new functionality gets added.
---
This PR:
* Adds a new file, `stats.py`, that includes several new classes and enums:
* A new class, `AggregatedStats`, which exposes a computed property `all_stats` that returns a dictionary of the aggregated stats of all endpoints along with some extra metadata (timestamp, runtime, etc)
* Two writer classes, `StatsJsonFileWriter` and `StatsJsonS3Writer`. These classes each expose a `write()` method that writes the stats from `AggregatedStats.all_stats` to …
=> BFD-1691: Store performance statistics in JSON format to S3 or file if specified

Jenkinsfile, ops/ansible/roles/bfd-db-migrator/test/test_basic.yml, ops/deploy-ccs.groovy, ops/terraform/services/migrator/Jenkinsfile, ops/terraform/services/migrator/sqs.groovy
[BFD-1550](https://jira.cms.gov/browse/BFD-1550)
This introduces the test, prod-sbx, and prod database migration stages to the Jenkins pipeline.
---
While this changeset focuses mainly on extending the existing multibranch/multistage pipeline in defining a new Jenkinsfile for the `bfd-db-migrator` service, it also fixes a few overlooked issues:
- adjusts the `bfd-db-migrator` ansible role test harness to accurately define the `env` variable
- introduces a new pipeline parameter that allows operators to use the latest image available (useful for faster iterative development in the `test` environment)
- introduces a single, globally accessible `awsAssumeRole` method to standardize role assumption and sessions
- removes the unused …
=> BFD-1550: Introduce migrator deployment stages

apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/FissClaimTransformer.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/McsClaimTransformer.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/FissClaimTransformerTest.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/McsClaimTransformerTest.java
[PACA-630](https://jira.cms.gov/browse/PACA-630)
Due to the raw nature of the partially adjudicated claims we receive, it's expected that sometimes the code and name values will come through as empty strings. We should remove our transformer data validation checks around the following and allow for 0 length strings (aka the empty string) to be persisted.
- mcs_details.idr_proc_code
- fiss_payers.bene_last_name
- fiss_payers.bene_first_name
---
The API is supposed to not send empty strings as values of empty fields but some bad test data in their IMPL environment caused it to do so for these fields.
This change treats empty strings in these fields as though the fields were not sent in the message rather than applying validation checks that …
=> PACA-630: Allow empty strings to work around bad test data from RDA API.

apps/bfd-server/bfd-server-launcher/src/main/java/gov/cms/bfd/server/launcher/DataServerLauncherApp.java, apps/bfd-server/bfd-server-launcher/src/test/java/gov/cms/bfd/server/launcher/DataServerLauncherAppIT.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/Operation.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/RequestResponsePopulateMdcFilter.java, apps/bfd-server/bfd-server-war/src/main/webapp/WEB-INF/web.xml
[BFD-1294](https://jira.cms.gov/browse/BFD-1294)
Adds the http response payload size (in bytes) to the access.json, making it possible to deprecate and eventually remove the access.log file entirely once other dependencies are adjusted to no longer rely on access.log.
---
BFD currently writes to two access logs -- access.log and access.json (which are respectively unstructured and structured) although the preference is to only have one log (the structured one). In order to remove the unstructured log, all data available in that log must be made available in the structured log file. Currently only the response payload size in bytes is missing from the structured log file. Making that available in the structured log file is the subject of this …
=> BFD-1294 Add payload size to the structured access log (access.json)

apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/FissClaimTransformer.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/FissClaimTransformerTest.java
[PACA-684](https://jira.cms.gov/browse/PACA-684)
Occasionally, we receive FISS diagnosis codes records with no data in them. This was previously unexpected behavior, but have confirmed with the RDA API team that this is what they receive from the IDR extracts. We should record this record as is, with just primary key values and the rest of the rows empty.
---
Removes the at-least-one-has-value requirement for RdaFissDiagnosisCode `diagCd2`/`bitFlags`.
* If the answer to any of the questions below is **Yes**, then **you must** …
=> PACA-684: Allow blank diag code and bitFlags

apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/McsClaimTransformer.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/McsClaimTransformerTest.java
[PACA-685](https://jira.cms.gov/browse/PACA-685)
Some MCS claims include diagnosis code records with an empty string value for the idrDiagCode field. Currently validation rejects those records as invalid. Remove this validity check and allow empty strings in this field so that processing of MCS claims can continue.
---
Changes `McsClaimTransformer` to allow empty string value for the `McsDiagnosisCode.idrDiagCode` field. …
=> PACA-685: Allow empty string value for idrDiagCode

apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/RdaSink.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/AbstractClaimRdaSink.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/FissClaimRdaSink.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/McsClaimRdaSink.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/AbstractClaimRdaSinkTest.java
[PACA-689](https://jira.cms.gov/browse/PACA-689)
Due to a difference in which write methods the two classes are using, only the single threaded mode is marking the metrics up. 
---
Previously transformation metrics were only updated when `transformMessages()` was called.  This caused `ConcurrentRdaSink` to not update these metrics because it called `transformMessage()` directly.  Now the `transformMessage()` method does all of the metric updates and delegates only the transformation logic to the derived classes.
Also fills in some missing javadocs and refactors the unit test to make it easier to add new tests.
* Verify all PR security questions and checklists have been …
=> PACA-689: Fixes transformMessage not updating metrics properly.

apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/DataSetManifestFactory.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/extract/s3/DataSetManifest.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/extract/s3/DataSetQueue.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/resources/bfd-manifest.xsd, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/resources/manifest-sample-a.xml, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/resources/manifest-sample-b.xml, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/resources/manifest-sample-c.xml
[BFD-2063](https://jira.cms.gov/browse/BFD-2063)
XML manifests from CCW contain an attribute exportType which fails XML validation; this ticket handles that by treating the exportType as a XmlTransient.
Modify _DatasetManifestEntry_ to contain XML attribute _exportType_; this field will be defined as transient and effectively ignored.
Updates test data manifests to include _exportType_ attribute.
The field in question, exportType, has been provided by CCW for some time now. However, at no time has this field every been used in the BFD pipeline loading process. However, since CCW provides that field, we need to at least account for it in our XML Schema (XSD) definition else it will fail schema validation.
Verify that the test data manifests …
=> BFD-2063 - handle exportType in DatasetManifestEntry

apps/build.groovy
[BFD-2067](https://jira.cms.gov/browse/BFD-2067)
Remove redundant tests, test artifacts, javadocs, fingerprinting, and archiving from the Build Apps Stage.
---
By removing these additional, largely redundant steps from the Build Apps stage, it now takes between 1m 30s and 1m 45s on average compared to the existing range between ~6m across the previous 10 builds. In short:
- **without** tests and javadoc, builds take 3-5m to execute (a 2m to 3m savings)
- The fingerprinting and archiving steps take ~1m 30s so eliminating this further reduces by the same amount
Again, these pieces are largely redundant, because deployments to our path-to-production environments (`test`, `prod-sbx`, `prod`) are executed from the trunk/master branch, where …
=> BFD-2067: Reduce Time in Jenkins Build Apps Stage

apps/bfd-pipeline/bfd-pipeline-app/src/test/java/gov/cms/bfd/pipeline/app/PipelineApplicationIT.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/CcwRifLoadJob.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/extract/s3/DataSetManifest.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/extract/s3/DataSetQueue.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/extract/s3/DataSetTestUtilities.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/extract/s3/task/DataSetMoveTask.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/extract/s3/task/ManifestEntryDownloadTask.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/java/gov/cms/bfd/pipeline/ccw/rif/CcwRifLoadJobIT.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/java/gov/cms/bfd/pipeline/ccw/rif/extract/s3/DataSetManifestTest.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/java/gov/cms/bfd/pipeline/ccw/rif/extract/s3/task/ManifestEntryDownloadTaskIT.java
[BFD-2126](https://jira.cms.gov/browse/BFD-2126)
As a BFD engineer, I would like to have a second location that the ETL loads from, so that I can leave the Incoming folder uncluttered when I have hundreds of weeks future data folders created during synthetic data generation.
---
Updates a number of places needed to read loads from a new location, Synthetic/Incoming, and write the finished files from this location into Synthetic/Done. This will allow us to keep synthetic "future" loads in a storage location that does not clutter up the standard pipeline Incoming/Done folders.
- Add two new S3 prefix locations that the pipeline uses, Synthetic/Incoming and Synthetic/Done
- Synthetic/Incoming is treated the same as Incoming for all intents and …
=> BFD-2126: Add ability for pipeline to read and write to a new location for synthetic data

apps/utils/locust_tests/services/server-load/Jenkinsfile, apps/utils/locust_tests/services/server-load/controller/controller.py, apps/utils/locust_tests/services/server-load/node/node.py, ops/terraform/services/server/server-load/variables.tf
[BFD-2178](https://jira.cms.gov/browse/BFD-2178)
As a BFD Engineer, I want the Load Tests to be safe to run and to immediately stop when I choose to
stop them. Additionally, I want the documentation (including Job parameter descriptions) associated
to the Load Tests to be as clear and accurate as possible so that there is no question what the Load
Tests behavior is.
---
This PR:
- Changes the descriptions of several parameters to be more accurate and more precise about their
behaviors
- Changes the way the Jenkins job timeout is calculated if `STOP_ON_SCALING` is `true` such that
`COASTING_TIME` is also accounted for in the timeout
- Removes all `async` code from `node.py`, replacing it with non-`async` equivalents from the
`subprocess` …
=> BFD-2178: Make Load Tests safer and improve associated documentation

ops/terraform/env/global/s3/legacy.tf, ops/terraform/env/global/s3/main.tf, ops/terraform/env/global/s3/synthea.tf, ops/terraform/env/global/s3/temporary.tf
[BFD-2164](https://jira.cms.gov/browse/BFD-2164)
This successfully remediates Security Hub Findings associated with AWS Foundational Security Best Practices v1.0.0 S3.4: _S3 buckets should have server-side encryption enabled_.
---
- import additional, unmanaged S3 buckets into the global module (glue-assets, cf-bfd-vpc-template, bfd-synthea)
- apply appropriate default encryption settings for each bucket in the global module where necessary
* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or …
=> BFD-2164: Enable default S3 server-side encryption

ops/terraform/env/global/kms/.terraform-docs.yml, ops/terraform/env/global/kms/README.md, ops/terraform/env/global/kms/main.tf, ops/terraform/modules/resources/iam/main.tf, ops/terraform/modules/stateful/main.tf, ops/terraform/services/server/server-load/README.md, ops/terraform/services/server/server-load/signaling.tf
[BFD-2166](https://jira.cms.gov/browse/BFD-2166)
_In part_, this successfully remediates Security Hub Findings associated with AWS Foundational Security Best Practices v1.0.0 SNS.1: _SNS topics should be encrypted at-rest using AWS KMS_.
---
- Revive, repurpose, and extend env/global/kms module as a home (if temporarily) for path-to-production KMS CMKs
- Generally tidy existing CMK policies, removing errant statements
- Extend AWSServiceRoleForAutoScaling permissions to allow the environment-specific CMK to support encrypted ASG-to-SNS topic signaling
- Modify CMK policies, introduce non-default SNS topic policies to allow for encrypted cloudwatch alarm-to-SNS topic signaling
- Encrypt bfd-server-load and bfd-server cloudwatch SNS topics (3 …
=> BFD-2166: Encrypt SNS topics

ops/terraform/services/pipeline/README.md, ops/terraform/services/pipeline/cloudwatch.tf, ops/terraform/services/pipeline/iam.tf, ops/terraform/services/pipeline/main.tf
[PACA-850](https://jira.cms.gov/browse/PACA-850)
As a PACA/BFD engineer I need to be alerted when the RDA ETL pipeline jobs are falling behind.
---
Creates alerts in CloudWatch to trigger when the appropriate micrometer latency metric exceeds our published SLO value.  The alerting threshold is 8 hours (encoded in milliseconds, 8 * 60 * 60 * 1000).  The metric names used for the alerts are:
- FissClaimRdaSink.change.latency.millis.avg
- McsClaimRdaSink.change.latency.millis.avg …
=> PACA-850: Add alerts for RDA API claim latency

apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/AppConfiguration.java, apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/PipelineApplication.java
[PACA-856](https://jira.cms.gov/browse/PACA-856)
As a BFD engineer I want to be able to send only the necessary metrics to Cloudwatch from the ETL pipeline.
Optimize costs by reducing number of metrics sent to Cloudwatch
Allow definition of a single alarm per environment that works regardless of the EC2 instance the pipeline is running on.
---
Install a `MetricFilter` to ensure that only a list of approved metrics are transmitted to cloudwatch.  For simplicity sake the list is currently hard coded but an environment variable could be added at a later date to make the list configurable.
**Note:** This filter will also prevent Micrometer JVM metrics from being transmitted to Cloudwatch.  They will still be published to NewRelic and/or JMX (if …
=> PACA-856: Refine cloudwatch micrometer metrics

.github/workflows/ci-java.yml
[BFD-868](https://jira.cms.gov/browse/BFD-868)
(re)Enable GHA Workflow Filtering
This work originally appeared in the change set addressing BFD-2334; while helpful to the testing effort, it has little to do with the subject of that Jira issue.
---
This is a modest change and fix to the extended regexp pattern(s) employed by the _Checking workflow_ job to avoid lengthy builds/re-builds with `mvn` (and other consequences like the ansible role tests) when there aren't any relevant changes to evaluate.
As before, unrelated changes like RFCs or runbooks (encoded as markdown files), will no longer trigger the long-tail tasks included in the _CI - Java_ workflow (`ci-java.yml`), resulting in more focused, speedier review for these change sets.
The …
=> BFD-868: Fix Filtering in GHA Workflows

apps/bfd-pipeline/bfd-pipeline-app/pom.xml, apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/PipelineApplication.java, ops/ansible/roles/bfd-pipeline/templates/bfd-pipeline-service.sh.j2, ops/terraform/services/pipeline/README.md, ops/terraform/services/pipeline/main.tf, ops/terraform/services/pipeline/variables.tf
[BFD-2330](https://jira.cms.gov/browse/BFD-2330)
ETL pipeline can leak PII/PHI data if it encounters a SQL exception during insert or update operation.
This PR leverages a recent bugfix to the Postgres JDBC driver that enables control over whether the driver will output detailed SQL that encountered an Exception.
It accomplishes this by leveraging the _logServerErrorDetail_ flag that can be set during the setup of the Postgres DataSource:
- true (the default) will output detailed SQL, which may include PII data.
- false will disable the detailed output (but still provide call stack info)
The bulk of the changes are tied to pipeline ops changes that disable detailed SQL output in the Postgres JDBC driver.
In addition to the ops changes, there …
=> BFD-2330 : Prevent Postgres JDBC driver from leaking PII/PHI data during BatchUpdateException

ops/terraform/modules/resources/bfd_cw_dashboards/templates/bfd-dashboard-slos.tftpl, ops/terraform/modules/resources/bfd_cw_dashboards/templates/bfd-dashboard.tftpl, ops/terraform/modules/resources/bfd_server_slo_alarms/main.tf
[BFD-2351](https://jira.cms.gov/browse/BFD-2351)
As a BFD Engineer, I want to know when the BFD is out of SLO for availability, so that I know when
there is an issue that requires prompt action by the BFD team.
---
This PR implements CloudWatch Alarms covering our Availability SLOs for uptime percentage ~~over 30 days (a month)~~ 24 hours as well as an additional alarm that covers more immediate uptime failures. Additionally, visuals showing metrics for availability have been added to both BFD Server CloudWatch dashboards. In more detail:
- Two distinct CloudWatch SLO Alarms have been added:
- A CloudWatch Alarm covering ~~both warning and alert thresholds for our monthly percent uptime
availability SLOs~~ a 24 hour period of uptime …
=> BFD-2351: Implement Availability SLO CloudWatch Alarms and add visuals for Availability SLIs to CloudWatch Dashboards

apps/bfd-model/bfd-model-rif/src/main/resources/db/scripts/BFD-1240-cleanup-beneficiary-history/invoke-psql.sh
[BFD-1240](https://jira.cms.gov/browse/BFD-1240)
This ticket addresses an issue in which CCW provided alternating null/non-null EFCTV_BGN_DT in the Beneficiary RIF data file. This null/non-null comparison between a current BENEFICIARIES record and the new RIF record would trigger a new record being added to the BENEFICIARIES_HISTORY table; over time this caused significant bloat to the BENEFICIARIES_HISTORY table resulting in poor database performance and increased AWS RDS costs.
This PR represents work to cleanup (remove) spurious records from the BENEFICIARIES_HISTORY; it does this in basically two major steps:
1. Due to the extreme bloat (approx 1.9B records), normal SQL cleanup had to be refactored into smaller batches due to memory …
=> BFD-1240: bash script to cleanup spurious records in BENEFICIARIES_HISTORY table

apps/utils/locust_tests/.vscode/settings.json, apps/utils/locust_tests/common/bfd_user_base.py, apps/utils/locust_tests/common/stats/aggregated_stats.py, apps/utils/locust_tests/common/stats/stats_compare.py, apps/utils/locust_tests/common/stats/stats_config.py, apps/utils/locust_tests/lambda/server-regression/.dockerignore, apps/utils/locust_tests/lambda/server-regression/Dockerfile, apps/utils/locust_tests/lambda/server-regression/Dockerfile.dockerignore, apps/utils/locust_tests/lambda/server-regression/README.md, apps/utils/locust_tests/lambda/server-regression/app.py, apps/utils/locust_tests/lambda/server-regression/build-push.sh, apps/utils/locust_tests/pyproject.toml
[BFD-2746](https://jira.cms.gov/browse/BFD-2746)
As a BFD Engineer I want the Regression Suite to exercise the BFD Server as fully as possible in order to test for regressions in both performance and behavior
---
This PR adds the PACA smoke tests to the existing Regression Suite Lambda such that they will run immediately after the existing Regression Suite during deployment and so the outcome of the smoketest will influence the result of the corresponding deployment stage.
These smoke tests differ from the existing Regression Suite in that they use random, non-synthetic data and thus do not have consistent performance characteristics from environment-to-environment or run-to-run; thus, statistics from these smoke tests are _not_ collected as …
=> BFD-2476: Execute Partially Adjudicated Smoketest During Deployments

apps/utils/locust_tests/common/db.py, apps/utils/locust_tests/v2/partially_adjudicated_smoketest.py
[BFD-2505](https://jira.cms.gov/browse/BFD-2505)
The PACA smoketests were added to the Regression Suite Lambda in BFD-2476, configured to run after the existing Regression Suite during deployments. These smoketests execute a fairly complex query against the database to collect the necessary data to run the test suite, and this query had acceptable performance in both test and prod-sbx. However, in prod, this query's performance was dramatically slower than the lower environments and was consistently causing the Regression Suite Lambda to exceed its overall timeout of 10 minutes.
This is causing the deployment pipeline to hang when deploying to prod, and is causing false negatives with respect to the Regression Suite's success.
---
This PR …
=> BFD-2505: Fix PACA smoketests in Regression Suite Lambda

apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/MessageError.java, apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/AppConfiguration.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/RdaLoadOptions.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/FissClaimRdaSink.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/McsClaimRdaSink.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/DLQDao.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/DLQGrpcRdaSource.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/RdaSourceConfig.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/DLQDaoIT.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/DLQGrpcRdaSourceTest.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/TransformerTestUtils.java
[PACA-1000](https://jira.cms.gov/browse/PACA-1000)
Manage the growth of the rda.message_errors table by deleting records once they are no longer required.  Allow the parameters used to determine what records should be deleted to be configurable.
---
- Moves `DLQDao` class to the top level for cleaner testing.
- Adds integration tests for `DLQDao`
- Adds cleanup method to `DLQDao`
- Adds `RDA_JOB_ERROR_EXPIRE_DAYS` environment variable to configure cleanup.  Defaults to no cleanup being done if env var is not present in environment.
- Adds cleanup logic to `DLQGrpcRdaSource`.  Cleanup takes place before the regular DLQ resolution code is started.
Note: Any exceptions thrown during cleanup are logged but do not halt regular DLQ processing …
=> PACA-1000: message errors cleanup feature

ops/ansible/roles/bfd-pipeline/defaults/main.yml, ops/ansible/roles/bfd-pipeline/templates/bfd-pipeline-service.sh.j2, ops/terraform/services/base/values/ephemeral.yaml, ops/terraform/services/base/values/prod-sbx.yaml, ops/terraform/services/base/values/prod.yaml, ops/terraform/services/base/values/test.yaml, ops/terraform/services/pipeline/user-data.sh.tftpl
[BFD-2508](https://jira.cms.gov/browse/BFD-2508)
Provide updated configuration supporting changes proposed in BFD-2509 _or_ #1664.
---
This PR introduces three new bfd-pipeline ansible role configuration fields to support the changes in #1664:
1. `rif_thread_multiple` replaces the `data_pipeline_loader_threads` and multiplies by the number of cpus available
2. `rif_job_batch_size` represents the size of the batch the rif loader will process
3. `rif_job_queue_size_multiple` represents the multiplier for the queue size
Values for these configuration settings were determined through trial and error. Using the smaller, 1.2GB data set in `2023-03-03T12:00:00Z/bene_upd20230310141228.txt`, we arrived to a batch size/queue size/thread count of …
=> BFD-2508: Improved Pipeline performance config

ops/terraform/services/pipeline/modules/bfd_pipeline_slis/lambda_src/update_pipeline_slis.py
[BFD-2530](https://jira.cms.gov/browse/BFD-2530)
The Pipeline SLIs Lambda submits "time deltas", in seconds, to the following metrics per-environment (with corresponding dimensions):
- `time-delta/data-full-load-time`
- `time-delta/data-load-time`
Unfortunately, due to a misunderstanding when computing time deltas using Python's `timedelta` it was assumed that the `seconds` property was the total seconds of the duration that the `timedelta` represents. However, this is not the case, as the `timedelta`'s `seconds` property instead represents the seconds component of the internal representation of the `timedelta`'s duration. Until now, this seconds component has been submitted to each of the aforementioned metrics whenever a time delta was …
=> BFD-2530: Fix "Pipeline SLIs Lambda submits incorrect time delta samples to CloudWatch Metrics"

apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/server/AbstractRandomClaimGenerator.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/RdaServerJobIT.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/server/RandomFissClaimGeneratorTest.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/server/RandomFissClaimSourceTest.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/server/RandomMcsClaimGeneratorTest.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/server/RandomMcsClaimSourceTest.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/FissClaimStreamCallerIT.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/McsClaimStreamCallerIT.java
[PACA-1032](https://jira.cms.gov/browse/PACA-1032)
Improve realism of random claim generators compared to real RDA API.
Currently the random claim generators start with sequence number zero but the real RDA API starts with 1.  Change the random claim generators to start at sequence 1 and change any associated tests and/or logic to work properly with this change.
---
Changes the starting sequence number and adjusts tests to reflect the change.
* If the answer to any of the questions below is **Yes**, then **you must** supply a link …
=> PACA-1032: random claims start at seq 1

Jenkinsfile, ops/jenkins/bfd-deploy-apps/Jenkinsfile, ops/terraform/services/server/modules/bfd_server_asg/data-sources.tf, ops/terraform/services/server/modules/bfd_server_asg/main.tf, ops/terraform/services/server/modules/bfd_server_asg/scripts/rds-cluster-config.sh
[BFD-2586](https://jira.cms.gov/browse/BFD-2586)
As a release engineer, I want the path-to-production deployment process to use the server terraservice so that I can avoid any drift-related issues between ephemeral and established environment deployments.
AC
path-to-production environments test, prod-sbx, and prod resources are imported into environment specific workspaces in the server terraservice remote state
Jenkins file is updated to make use of the server terraservice in typical path-to-production deployments
---
Add server to deployment specific environments. Additionally, migration from stateless to the terraservice pattern was accommodated through the following statements for each of the established path-to-production SDLC …
=> BFD-2586: Add server terraservice to standard deployments

Jenkinsfile, apps/bfd-shared-test-utils/src/main/java/gov/cms/bfd/DatabaseTestUtils.java, apps/pom.xml, ops/terraform/services/base/values/prod-sbx.yaml, ops/terraform/services/base/values/prod.yaml, ops/terraform/services/base/values/test.yaml, ops/terraform/services/common/.terraform-docs.yml, ops/terraform/services/common/README.md, ops/terraform/services/common/app-autoscaling.tf, ops/terraform/services/common/aurora-cluster.tf, ops/terraform/services/common/main.tf
[BFD-2674](https://jira.cms.gov/browse/BFD-2674)
This change set supports the upgrade to the 6th generation database instances and minor upgrade to Aurora PostgreSQL 14.7.
---
- encode the logic for db.r6i instances for the Aurora PostgreSQL 14.7 Aurora Clusters for path-to-production environments.
- point `prod-sbx` and `prod` environments to their respective, primary data stores
- introduce a new override variable to allow for specifying alternative rds_cluster_identifier values for exceptional use cases in the `common` terraservice, useful in case of upgrades like this
- include minor fixes for formatting and documentation updates in the `common` terraservice
- re-enable `common` terraservice deployments
- update test references from 14.6 …
=> BFD-2674: Upgrade RDS Clusters

apps/bfd-pipeline/bfd-pipeline-rda-grpc/pom.xml, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4ExplanationOfBenefitResourceProvider.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/ServerExecutor.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/ServerRequiredTest.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/commons/QueryUtilsTest.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/CarrierClaimTransformerV2Test.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/R4ExplanationOfBenefitResourceProviderE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/R4ExplanationOfBenefitResourceProviderTest.java
[BFD-2614](https://jira.cms.gov/browse/BFD-2614)
As a BFD engineer I would like the Explanation of Benefit resource provider end-to-end tests to be converted to unit/integration tests if possible so that I can more easily test the resource provider functionality in isolation.
---
Major:
- Renamed R4ExplanationOfBenefitResourceProviderIT to R4ExplanationOfBenefitResourceProviderE2E
- Moved some tests in the E2E to unit tests (arrows indicate being replaced by the noted unit test in the unit test class):
_readEobForMissingCarrierClaim_
_readEobForMissingDMEClaim_
_readEobForMissingHHAClaim_
_readEobForMissingHospiceClaim_
_readEobForMissingInpatientClaim_
_readEobForMissingOutpatientClaim_
_readEobForMissingPartDEvent_ …
=> BFD-2614: Convert subset of V2 EOB Provider E2E tests into unit tests

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/pac/AbstractR4ResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/pac/R4ClaimSamhsaMatcher.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/pac/R4ClaimResponseResourceProviderE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/pac/R4ClaimSamhsaMatcherTest.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/pac/R4ClaimSamhsaMatcherTransformerTest.java
[BFD-2720](https://jira.cms.gov/browse/BFD-2720)
After a recent adjustment to the RDA code to use dependency injection, one of the side effects was a mis-cast on some logic that changed as a result of the transformer injection. This fixes that.
---
Root cause of this issue was injecting a single transformer based on the resource type into the resource provider. The samhsa matcher REQUIRES the resource to be transformed into a claim, so when resources were passed into the samhsa matcher of a claimResponse resource provider, it used the claimResponse transformer, attempted to cast it to a claim after, and blew up.
This fixes that by moving the samhsa determination logic into the samhsa matcher, and injects the appropriate transformers into …
=> BFD-2720: Fix bug with samhsa matcher class cast in RDA logic

apps/utils/locust_tests/common/bfd_user_base.py, apps/utils/locust_tests/common/stats/aggregated_stats.py, apps/utils/locust_tests/common/stats/stats_loaders.py
[BFD-2731](https://jira.cms.gov/browse/BFD-2731)
Locust tests that collect and compare against statistics stored in Athena, such as the Regression Suite, fail to complete stat comparison due to a recent Athena v3 engine upgrade. This new engine now properly supports returning JSON objects, in full, whereas before it would only return a list of values per object. Unfortunately, the logic for loading and deserializing stats from Athena expects the result of stats queried from Athena to be returned as JSON lists rather than as proper JSON objects. This format mismatch is causing the Regression Suite to fail.
---
This PR removes the special logic (`TaskStats.from_list()`) for deserializing `TaskStats` objects returned as JSON lists of values, …
=> BFD-2731: Fix Locust test stat loading from Athena fails when trying to deserialize statistics

ops/terraform/services/base/values/prod-sbx.yaml, ops/terraform/services/base/values/prod.yaml, ops/terraform/services/base/values/test.yaml, ops/terraform/services/server/modules/bfd_server_asg/main.tf
[BFD-2804](https://jira.cms.gov/browse/BFD-2804)
Current scaling policies exist to scale-out when CPU utilization increases. We found that a potentially more reliable or more realistic metric to analyze is network or traffic based.
---
This PR updates:
- BFD Server's scaling policies to scale based upon "filtered" `NetworkIn` (`NetworkIn` with corresponding `NetworkOut`). Essentially, BFD Server will now scale-out and scale-in depending on the amount of _incoming_ traffic to the Server ELB. These new scaling policies are tuned to be faster and more aggressive than the previous policies, opting to scale-out within a minute of heavy traffic and scale-in only after traffic has subsided for 5 minutes. 
- Capacity is now added to the ASG in …
=> BFD-2804: Fix BFD Server scaling policies

ops/terraform/services/server/modules/bfd_server_asg/main.tf, ops/terraform/services/server/modules/bfd_server_lb/main.tf
[BFD-2584](https://jira.cms.gov/browse/BFD-2584)
The "health check grace period" for the Server AutoScaling Group is too low and the Elastic Load Balancer healthchecks are configured with less-than-ideal thresholds, so perfectly healthy instances are being created, quickly and erroneously being marked as `Unhealthy` before they are even _ready_ to be healthchecked, and then promptly removed from the AutoScaling Group shortly after being added even though they are truly healthy. This is causing poor behavior during scaling events.
---
This PR updates:
- The healthcheck grace period for the Server ASG to 600 seconds
- This _should_ outright stop ELB healthchecks causing the erroneous removal of instances falsely identified as `Unhealthy` from …
=> BFD-2854: Server ASG health check grace period is too low and ELB healthcheck configuration is not ideal

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/CarrierClaimTransformerV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/DMEClaimTransformerV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/InpatientClaimTransformerV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/TransformerUtilsV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/CarrierClaimTransformer.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/DMEClaimTransformer.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/InpatientClaimTransformer.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/TransformerUtils.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/CarrierClaimTransformerV2Test.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/DMEClaimTransformerV2Test.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/TransformerUtilsV2Test.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/CarrierClaimTransformerTest.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/DMEClaimTransformerTest.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/TransformerUtilsTest.java
[BFD-2815](https://jira.cms.gov/browse/BFD-2815)
Fixes a couple issues where Optional was misused, causing potential issues in the event that the optional fields were not present.
---
Major:
- Simplifies some code in v1 and v2 DME+Carrier transformers where careTeam extensions were added, using Optionals
- Adds the optional check code to a util method, which is reused. Takes no action if the optional is empty instead of causing an exception
- Fixes a bug in InpatientClaimTransformer (v1) where an optional was checked against null instead of using isPresent
- Fixes a similar bug in InpatientClaimTransformerV2, where the optional was not even being checked at all before calling get() for the same field
- Add unit tests for the transformers …
=> BFD-2815: Fix Inappropriate Usage of Optional

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/RequestHeaders.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/StringUtils.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4PatientResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProvider.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/commons/StringUtilsTest.java
[BFD-2813](https://jira.cms.gov/browse/BFD-2813)
As a BFD engineer I would like to reduce the attack vector for denial of service attacks on BFD so that the application is more secure.
This change brings in the following:
- A `RegexUtils` class with a customSplit utility function that is used across the 3 classes where the regex was used.
-  A RegexUtilsTest class that test the veracity of the customSplit function.
- Updates the requestHeaders, R4PatientResourceProvider and PatientResourceProvider classes to import and use the customSplit class. …
=> BFD-2813: Clean up DOS Attack vector regexes in BFD Server code

ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2, ops/terraform/services/server/modules/bfd_server_asg/main.tf, ops/terraform/services/server/modules/bfd_server_asg/templates/fhir_server.tpl, ops/terraform/services/server/modules/bfd_server_iam/data-sources.tf, ops/terraform/services/server/modules/bfd_server_iam/main.tf
[BFD-2863](https://jira.cms.gov/browse/BFD-2863)
As a BFD Engineer, I want BFD Server instances to be able to signal when they have warmed-up so that they are not added prematurely to the Load Balancer and made reachable before they should be
---
This PR adds a [Launch Lifecycle Hook](https://docs.aws.amazon.com/autoscaling/ec2/userguide/lifecycle-hooks.html) to the BFD Server AutoScaling Group that is automatically completed when an instance has fully warmed-up. Now, BFD Server EC2 Instances will enter the `Pending:Wait` lifecycle state on scale-out _until_ the instances signals, through completing the Lifecycle Action corresponding to the Launch Lifecycle Hook, that the BFD Server application is ready to receive traffic. Only then will …
=> BFD-2863: Introduce Launch Lifecycle Hooks to BFD Server Instances

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/OffsetLinkBuilder.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4ExplanationOfBenefitResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/TransformerUtilsV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/pac/AbstractR4ResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/ExplanationOfBenefitResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/TransformerUtils.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/ServerRequiredTest.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/ServerTestUtils.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/commons/OffsetLinkBuilderTest.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/CoverageE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/ExplanationOfBenefitE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/PatientE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/TransformerUtilsV2Test.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/pac/ClaimE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/pac/ClaimResponseE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/CoverageE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/ExplanationOfBenefitE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/PatientE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/TransformerUtilsTest.java
[BFD-2849](https://jira.cms.gov/browse/BFD-2849)
Calling the EOB (and probably other) endpoints with a startIndex greater than the number of entries in the response returns a 500; the response should be a 400, since this is a user input error and can be corrected by adjusting the request.
---
For every endpoint (via adjusting the bundling logic when pagination is request in the TransformerUtils) we will throw an InvalidRequestException with a useful error message when the `startIndex >= totalResources.size()` which will cause a 400 at the response layer in HAPI-FHIR.
While many restAssured tests were added to cover this case for each endpoint (including PAC endpoints), 99% of the tests are just copy/pasted from the newly added EOB tests with …
=> BFD-2849: Adjust case where startIndex >= maxResults to throw 400 instead of 500

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/CarrierClaimTransformerV2.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/CarrierClaimTransformerV2Test.java
[BFD-2852](https://jira.cms.gov/browse/BFD-2852)
As a BFD customer, I want EOB.provider to populate some default value so that I can pass FHIR validation.
---
- Add a default for v2 carrier claim EOB data so that when CARR_CLM_BLG_NPI_NUM does not exist in the database data, we default to a value. 
- This allows Provider to always be supplied, since that absence of provider was breaking FHIR validation for customers.
- Add tests for both the regular provider being mapped, as well as the default being mapped if the provider field isnt supplied …
=> BFD-2852: Add default 'UNKNOWN' value for EOB carrier provider if no data (V2)

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/TransformerUtils.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/ExplanationOfBenefitE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/ExplanationOfBenefitE2E.java
[BFD-2850](https://jira.cms.gov/browse/BFD-2850)
---
When using an EOB request with lastUpdated AND pagination (using _count) the _count parameter seems to be ignored.  This change was fixed in #1922. This change is specific to adding the test for version 1 (Stu3) providers. 
Note: This change updates the E2E for both R4 to remove  `log().body()` which was used for debugging as well as 
updating the E2E for both Stu3 to enabled the test and fix certain aspects of the test for version 1. 
These changes update the `searchEobByPatientIdWithLastUpdatedAndPagination()` for both the R4 and Stu3 providers which were disabled in stu3. The r4 update removes .log().body() which was used for debugging. 
- Updates `TransformerUtils.java` to reference …
=> BFD-2850: Bug fix to count being ignored when using lastUpdated ranges: V1

apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/ServerRequiredTest.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/ExplanationOfBenefitE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/ExplanationOfBenefitE2E.java
[BFD-2883](https://jira.cms.gov/browse/BFD-2883)
Fixes an issue where a restAssured test was failing when calling a pagination url.
---
Originally this was a bugfix due to a pagination link failing when calling it via RestAssured, leading to the incorrect assumption the server could not read the url-encoded pagination link (as opposed to the non-encoded first response link) when lastUpdated was present and the timestamp was part of the request. 
After much fiddling with HAPI interceptors and various debugging, it turns out this is an issue with RestAssured; it automatically url-encodes requests, leading to issues when the url is _already_ encoded, as is the case with our pagination "next" links. For other tests this wasnt an issue because …
=> BFD-2883: Fix pagination url encoding issue in RestAssured test

ops/terraform/services/server/modules/bfd_server_asg/main.tf
[BFD-2862](https://jira.cms.gov/browse/BFD-2862)
The BFD Server scale-in policy will immediately scale-in instances when NetworkIn drops beneath a particular scale-in threshold range, unless prior to scale-in the BFD Server ASG scaled-out to 12 instances. The expected behavior is that scale-in does not occur until 10 minutes after scale-out, but the current scale-in policy allows for near immediate scale-in after scale-out.
---
This PR updates the scaling "configuration" such that:
- scale-in should no longer be able to immediately, erroneously activate and scale-in the Server after a scale-out.
- the period of time that must pass before scale-in can occur has been increased to 15 minutes from 10 minutes to ensure the Server remains …
=> BFD-2862: BFD Server ASG scale-in policy is evaluating too soon after scale-out causing premature scale-in

ops/terraform/modules/resources/bfd_server_slo_alarms/main.tf, ops/terraform/services/server/modules/bfd_server_slo_alarms/main.tf
[BFD-2706](https://jira.cms.gov/browse/BFD-2706)
Purpose:
- The BFD team will need to update PACA-related SLOs (Claim / ClaimResponse) 6-8 weeks after Full Launch
Notes:
- After observing normal traffic patterns we need to define the SLOs further in Cloudwatch
- We also need to move from Splunk to Cloudwatch alerts for those SLOs
AC:
- update Claim / ClaimResponse SLOs
- move to CloudWatch alerts from Splunk
Resources:
- https://confluence.cms.gov/pages/viewpage.action?spaceKey=BFD&title=BFD+SLOs
Addendum:
- after discussing this topic w/ mitch and burling it was decided that these SLOs need to be researched the "BFD way"
- BFD captures a lot of query information via its "data lake service" called AWS Athena
- we need to break this tix up in …
=> BFD-2706 Update performance SLO alarms for claim and claimresponse resources

apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/R4ExplanationOfBenefitResourceProviderE2E.java
[BFD-2691](https://jira.cms.gov/browse/BFD-2691)
Fixes a typo with the tax num test which was causing a check to fail.
---
The test `searchForEobsIncludeTaxNumbersHandling` (v2) had, in the recent past, been missing some tests relating to ensuring the tax number values were present and correct. I added additional assertions for this, but noticed one of them was not working and marked it for later review.
In v1, taxNumber on DME and carrier claims was checked via the careteam component and not the current location, in the line items. The extra checks ensured that the old v1 careteam mapping was not filled for v2, however I accidentally used `assertNotNull` for DME, leading to thinking there was a functionality issue. Thankfully it was just a …
=> BFD-2691: Fix minor test issue with tax num test

apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/R4PatientResourceProviderE2E.java
[BFD-2565](https://jira.cms.gov/browse/BFD-2565)
searchForPatientByPartDContractNumWithAnInvalidYear tests the case where BFD Patient (v2) should throw an InvalidRequestException when a bad contract year is passed; however this test was passing only because we had been previously been throwing this exception when no MBI header was set. With the removal of the MBI header check, this test now fails, indicating this functionality is broken and was only passing due to improper test setup. This should be properly fixed in v2 such that the test passes.
Adds a test for bad contract year with Patient (v2) requests.
- The specific test failure that's listed in the bug description no longer applies as the test case was removed in an earlier commit. …
=> BFD-2565: Add test with invalid contract year

ops/terraform/services/common/aurora-cluster.tf, ops/terraform/services/server/modules/bfd_server_asg/main.tf, ops/terraform/services/server/modules/bfd_server_asg/scripts/rds-cluster-config.sh
[BFD-2935](https://jira.cms.gov/browse/BFD-2935)
As a BFD Engineer I want the BFD Server to be able to query all of the available reader endpoint nodes such that no one reader node is overwhelmed with traffic resulting in poor BFD Server performance
---
This PR updates the `server` Terraservice such that BFD Server instances will be created with their database URLs pointing to the default reader endpoint, thus allowing the BFD Server to take advantage of all available reader nodes
This PR has been validated by:
- `terraform apply`ing it to `prod` (in response to the most recent incident), verifying that it `apply`s as expected and that all reader nodes were being used by the BFD Server
The changes remain in `prod` in order to manage further …
=> BFD-2935: Update BFD Server to use default RDS reader endpoint

ops/terraform/services/server/modules/bfd_server_metrics/main.tf
[BFD-2969](https://jira.cms.gov/browse/BFD-2969)
Recent usage of BFD Server CloudWatch Dashboards uncovered a discrepancy between the number of total requests reported by metrics and per-endpoint metric counts. It was discovered that `Claim` and `ClaimResponse` `access.json` Metric Filter pattern definitions are incorrectly assuming that their corresponding log entries cannot have a trailing slash (`/`). This is resulting in a fraction of the total metrics being collected for `Claim` and `ClaimResponse` endpoints.
---
This PR:
- Updates filter generation for URI filtering such that mutliple patterns can be specified for a given endpoint
- Updates `Claim` and `ClaimResponse` endpoint definitions such that all variations of corresponding URIs …
=> BFD-2969: PAC endpoint metric filters still do not filter URI correctly due to inconsistent trailing slash

ops/terraform/services/base/values/prod-sbx.yaml, ops/terraform/services/base/values/prod.yaml, ops/terraform/services/base/values/test.yaml, ops/terraform/services/pipeline/modules/bfd_pipeline_slo_alarms/main.tf
[BFD-2971](https://jira.cms.gov/browse/BFD-2971)
The CloudWatch Alarms for the following Pipeline SLOs:
- `Data Availability - CCW RIF Pipeline Job - Time to ingest a weekly batch load once available in S3`
- `Data Availability - CCW RIF Pipeline Job - Weekend data load availability`
are evaluating and alerting incorrectly.
Specifically, the CloudWatch Alarm for the first SLO is evaluating data sparsely such that the Alarm oscillates from `OK` to `ALARM` and then back to `OK` every 15 minutes. This is causing a flood of alerts to be sent to the on-call engineer, where only a single alert should have been sent at the moment the SLO was broken.
The Alarm for the second SLO is _evaluating_ incorrectly such that the Alarm enters `ALARM` at 00:00 …
=> BFD-2971: CloudWatch Alarms for Pipeline SLOs are alerting incorrectly

apps/bfd-server/bfd-server-shared-utils/src/main/java/gov/cms/bfd/server/sharedutils/BfdMDC.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/AccessJsonE2E.java
[BFD-2933](https://jira.cms.gov/browse/BFD-2933)
As a BFD Engineer I would like existing IT tests to use restAssured so that we are testing our REST endpoints as customers use them.
---
- Coverts the AccessJsonIT to AccessJsonE2E and converts the test to use RestAssured
- Fixes the test to wipe access.json before running, since before it was not and the test results were based on what (if anything) had run before it. The test previously did not pass when run solo.
- Removes two headers which don't get set as part of the test as written: Content-Location (which I don't know if/how we use this today, but we dont explicitly set or use it) and Accept-Charset (which has been deprecated and advised to not be used since 2012, and we dont explicitly …
=> BFD-2933: Convert AccessJsonE2E to restAssured

apps/bfd-server/bfd-server-war/pom.xml, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/OpenApiDocs.java, apps/bfd-server/dev/bfd-data-dictionary/app/dd-transformer/dd_to_csv.py, apps/bfd-server/dev/bfd-data-dictionary/generate_dd.sh, apps/pom.xml
[BFD-2987](https://jira.cms.gov/browse/BFD-2987)
As a BFD engineer I want the maven builds to contain all of the release artifacts necessary to deploy the application, including data dictionary files and OpenAPI specifications.
---
Adds generation of the data dictionary csv and json files, and OpenAPI spec yaml files to build output.
* Adds a `generate_dd.sh`  script to generate the data dictionary csv and json files for V1 and V2.  Adapted from the runbook instructions [How-to-do-a-Deployment](https://github.com/CMSgov/beneficiary-fhir-data/wiki/How-to-do-a-Deployment).
* Modifies the `apps/pom.xml` to use the `maven-exec-plugin` to execute the script including the project version as a parameter.
* Adds a OpenAPIDocs class to the …
=> BFD-2987: Build data dictionary and OpenAPI artifacts

ops/terraform/services/pipeline/user-data.sh.tftpl
[BFD-3051](https://jira.cms.gov/browse/BFD-3051)
As a BFD engineer I want to use GC settings for the ETL pipelines that improve performance and/or help to reduce costs.
---
* Modifies the shell script file template for `bfd-pipeline-server.sh`  so that it includes an additional JVM parameter to use string deduplication during garbage collection cycles.  [JEP 192: String Deduplication in G1](https://openjdk.org/jeps/192) 
Summary from BFD-3051:
Used the prod-based ephemeral environment `bfd-3051-prod` to repeatedly run through files copied from the "Done/2023-11-24T12:00:00Z" folder.  The JVM parameters were updated and measurements were captured until 1M beneficiaries were processed, which seemed sufficient to see differences in GC settings …
=> BFD-3051: Add UseStringDeduplication to JVM params for RIF pipeline

.github/workflows/ci-ansible.yml, .github/workflows/ci-java.yml, apps/.dockerignore, apps/build.groovy, ops/ansible/roles/bfd-db-migrator/README.md, ops/ansible/roles/bfd-db-migrator/defaults/main.yml, ops/ansible/roles/bfd-db-migrator/templates/bfd-db-migrator-service.sh.j2, ops/ansible/roles/bfd-db-migrator/test/run-tests.sh, ops/ansible/roles/bfd-db-migrator/test/test.sh, ops/ansible/roles/bfd-db-migrator/test/test_basic.yml, ops/ansible/roles/bfd-pipeline/README.md, ops/ansible/roles/bfd-pipeline/defaults/main.yml, ops/ansible/roles/bfd-pipeline/templates/bfd-pipeline-service.sh.j2, ops/ansible/roles/bfd-pipeline/test/run-tests.sh, ops/ansible/roles/bfd-pipeline/test/test.sh, ops/ansible/roles/bfd-pipeline/test/test_basic.yml, ops/ansible/roles/bfd-server/defaults/main.yml, ops/ansible/roles/bfd-server/tasks/install.yml, ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2, ops/ansible/roles/bfd-server/test/run-tests.sh, ops/ansible/roles/bfd-server/test/test.sh, ops/ansible/roles/bfd-server/test/test_basic.yml, ops/deploy-ccs.groovy, ops/terraform/services/server/modules/bfd_server_asg/templates/fhir_server.tpl
[BFD-3091](https://jira.cms.gov/browse/BFD-3091)
Replace static, 1.0.0-SNAPSHOT references with a dynamic version in workflows centered around ansible.
---
This introduces 2 larger changes across BFD's delivery and deployment mechanisms:
* standardize the ansible test _harness_ and scripting entrypoints to accept an optional image flag and mandatory `bfd_version` positional argument for ansible roles supporting bfd-db-migrator, bfd-pipeline, and bfd-server.
* generally defer to the version encoded in `apps/pom.xml` as a stored, ansible variable `bfd_version` _or_ accurately divine script/artifact locations through other, automatic means where possible
* Inputs for `bfd_version` and the ansible default value is 1.0.0-SNAPSHOT. It might be …
=> BFD-3091: Use dynamic versions in ansible

apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/RdaPipelineTestUtils.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/DLQDaoIT.java, apps/bfd-shared-test-utils/src/main/java/gov/cms/bfd/DatabaseTestUtils.java
[BFD-3154](https://jira.cms.gov/browse/BFD-3154)
Post removal of HSQLDB, a race condition appears to be present when evaluating certain code paths that were more tightly coupled to HSQLDB setup routines, etc. This is causing intermittent failures in GHA.
---
Modifies `runTestWithTemporaryDb()` to use the same postgres container as all other tests.  The name of the method was retained since the test is still using a temporary pooled data source and transaction manager.  Changing all 16 tests that call this method seemed unnecessary.
Adds code to wait for the postgres database within the docker container to begin processing queries successfully before allowing tests to run.
Eliminates the use of current time of day and all of the …
=> BFD-3154: fix test race conditions

.github/workflows/build-docker-images.yml
[BFD-3209](https://jira.cms.gov/browse/BFD-3209)
AWS Lambda does not support images built by Buildx (see [this GitHub issue](https://github.com/docker/buildx/issues/1533)), specifically multi-platform images. This is the default type of image built by the [suite of Docker image build GitHub Actions](https://github.com/docker/build-push-action), and must be explicitly opted-out of in order to build traditional images. The `Build Docker Images` Workflow must be updated to build platform-specific images so that the BFD EFT Outbound Lambda (and other Docker image based Lambdas, in the future) can properly take advantage of the Docker images built by this Workflow.
This _will_ cause Deployment Failures if not resolved before Peering Partners …
=> BFD-3209: AWS Lambda does not support BFD EFT Outbound Lambda Buildx Docker image format

.github/workflows/ci-ansible.yml, .github/workflows/ci-base-container-image.yml, .github/workflows/ci-java.yml, .github/workflows/ci-rust.yml
[BFD-3244](https://jira.cms.gov/browse/BFD-3244)
Improve GitHub Actions Workflow Executions
---
* Parallelizes system testing and unit/integration/e2e testing yielding 15-20% decrease in execution time 🚀 
* Adds the maven cache under the setup-java action with very limited potential for execution time improvements 🤷 
* Updates common github actions, largely tamping down on Node 16 runtime deprecation notices in favor of Node 20 ✅ 
* Replaces commented-out conformance testing code with a TODO and JIRA issues BFD-3245, scheduled for sometime in February 🤞
Submitters should complete the …
=> BFD-3244: Improve Common GitHub Actions Workflows

ops/terraform/services/server/modules/bfd_server_asg/main.tf, ops/terraform/services/server/modules/bfd_server_asg/variables.tf
[BFD-3313](https://jira.cms.gov/browse/BFD-3313)
As a US taxpayer, I want BFD to be as efficient as possible so that I can be confident that my tax dollars are not going to waste.
---
This PR updates the BFD Server's ASG scaling policies to scale based upon average CPU utilization across the ASG. These new scaling policies are designed keeping in mind that:
- BFD Server typically sees large bulk loads, rather than consistent, sustained traffic
- Average CPU utilization is _inversely_ proportional to the number of instances in the ASG
- As in, the average utilization goes _down_ as the number of instances _increase_
- Step Scaling policies are based upon CloudWatch Alarms that can remain in `ALARM` (and thus cause scaling) _after_ scale-out …
=> BFD-3313: Adjust autoscaling policies

ops/ansible/playbooks-ccs/roles/base_patch/tasks/main.yml, ops/ansible/playbooks-ccs/roles/platinum/tasks/install-dependencies.yml, ops/ansible/playbooks-ccs/roles/platinum/tasks/main.yml
[BFD-3332](https://jira.cms.gov/browse/BFD-3332)
Improve reliability of existing packer image creation process with explicit calls to `yum-complete-transaction`.
---
It's unclear exactly what is responsible for the current issues, but something appears to be interrupting the yum package manager. The misbehaving process yields intermittent errors, which has made the root cause identification difficult. It's also unclear if this has been resolved by the application of `yum-complete-transaction` _or_ if any ansible task that introduces a few extra seconds at the tail end of the ansible provisioner in packer would be enough to avoid the interruptions. Regardless, this is a fairly light-weight change which has made for more reliable image …
=> BFD-3332: Complete yum transactions explicitly

ops/terraform/services/eft/modules/bfd_eft_outbound_o11y/README.md, ops/terraform/services/eft/modules/bfd_eft_outbound_o11y/data-sources.tf, ops/terraform/services/eft/modules/bfd_eft_outbound_o11y/timeouts.tf
[BFD-3348](https://jira.cms.gov/browse/BFD-3348)
Alert on SFTP Outbound Timeouts in Lambda-based EFT
---
This implements a cloudwatch alarm using the existing slack notifier that is triggered if a lambda's duration exceeds its configured timeout.
`AWS/Lambda/${FunctionName}/Duration` is calculated at the end of a function's execution but recorded/timestamped at execution time, i.e. if a function is executed at 01:00 and times out at 01:15, a duration of >900s will be recorded at 01:00.  Because of this **and** our configuring the timeout to match the maximum allotted 15m, the alarm must _look back_ to the previous 15m period to report on these timeout failures.
* …
=> BFD-3348: Alarm on SFTP Outbound Timeouts

Jenkinsfile, ops/terraform/services/eft/README.md, ops/terraform/services/eft/data-sources.tf, ops/terraform/services/eft/main.tf, ops/terraform/services/eft/variables.tf
[BFD-3408](https://jira.cms.gov/browse/BFD-3408)
BFD EFT terraservice fails to deploy when attempting to resolve the latest github release version.
---
While this does not address the issues with Jenkins pipeline and resolving the latest release version itself, it should resolve the immediate deployment pipeline issues where this is most problematic. With this, the EFT terraservice now uses the GitHub-derived latest release version as a default when no such override is provided, similar to how the other terraservices function.
* …
=> BFD-3408: Introduce EFT version override

apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/EndpointJsonResponseComparatorV2E2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/EndpointJsonResponseComparatorE2E.java
[BFD-3423](https://jira.cms.gov/browse/BFD-3423)
When developers regenerate the endpoint responses by running -DgenerateTestData, new endpoint responses are created in which the port isn't fully replaced by IGNORE_FIELD. A number is appended at the end since the regex doesn't fully capture the port.
---
Changes regex pattern for port to just grab all digits before "/" but after "https://localhost:"
* Run mvn clean install -Dmaven.build.cache.enabled=false -DgenerateTestData and verify that port gets marked as IGNORE_FIELD with no extra digits exposed.
* If the answer to any of the questions below is **Yes**, then …
=> BFD-3423: Correct testing port-matching regex

.github/actions/await-cw-logging/action.yml, .github/actions/deploy-terraservice/action.yml, .github/scripts/stdout-to-cwlogs.sh, .github/workflows/ci-static-site.yml, ops/terraform/services/common/cloudwatch-logs.tf, static-site/_plugins/copy_data_dictionary.rb
BFD-3465
:warning: NOTE: The `CI - Deploy Static Site` Workflow (and helper Composite Actions) work as expected, but there are a few caveats:
- The IAM Role assumed by GitHub Actions will not have the required permissions to apply the `static-site` Terraservice upon merging this PR. We intend to grant these permissions _correctly_ in BFD-3583
- The `static-site` Terraservice creates a Cloudfront distribution that is not configured properly for use with `SSE-KMS` (customer-managed KMS keys) with the backing S3 Bucket. So, while the `CI - Deploy Static Site` Workflow _does_ correctly deploy the built Jekyll static site it is not able to be viewed unless the uploaded objects are re-encrypted with AWS-managed keys. This, and other deficiencies, will be resolved in BFD-3582
- …
=> BFD-3465: Implement CI Workflow for Static Site

apps/utils/locust_tests/common/db.py
BFD-3563
This PR replaces the now-defunct PAC hashed MBIs query with a new query courtesy of @aschey-forpeople and @mjburling that returns usable data for our `Claim` and `ClaimResponse` Regression Suite tests.
Note that the query is limited to 300 results as the Regression Suites cycle through the returned data, so the MBIs will never be exhausted. This is fine for this type of test as we're strictly looking for regressions in performance due to _code_ changes.
Have you fully …
=> BFD-3563: Regression Suite PAC hashed MBIs query is returning no data resulting in failing tests

ops/ccs-ops-misc/synthetic-data/scripts/synthea-manual/load-dataset.sh
BFD-3505
This scripts the manual steps for generating (and loading) a dataset as described under item seven of the [How to Run Synthea Automation runbook](https://github.com/CMSgov/beneficiary-fhir-data/wiki/How-to-Run-Synthea-Automation).
This syncs a given dataset's critical files (ignoring metadata and synthea-specific files) from `bfd-mgmt-synthea` to the targeted ETL bucket, by placing the data in a _folder_ so-named after the dataset's manifested timestamp (from the `manifest.xml` file). Finally, it renames the `manifest.xml` to the expected `0_manifest.xml` for the environment's ETL pipeline to begin loading this data.
- Upon acceptance, the aforementioned [How to Run Synthea Automation runbook](https://github.com/CMSgov/beneficiary-fhir-data/wiki/How-to-Run-Synthea …
=> BFD-3505: Script load dataset functionality

ops/terraform/services/server/README.md, ops/terraform/services/server/main.tf, ops/terraform/services/server/modules/bfd_server_disk_alarms/data-sources.tf, ops/terraform/services/server/modules/bfd_server_disk_alarms/lambda_src/manage_disk_usage_alarms.py, ops/terraform/services/server/modules/bfd_server_disk_alarms/main.tf, ops/terraform/services/server/modules/bfd_server_disk_alarms/variables.tf
BFD-3573
This PR fixes the `manage-disk-alarms` Lambdas and supporting infrastructure by:
- Refactoring the `bfd_server_disk_alarms` module in the `server` Terraservice to use the `asg_id` output of the `bfd_server_asg` module instead of looking up the ASG name using a `data` resource. As the ASG name changes each time we apply `server`, the `data` resources were returning the name of the _outgoing_ ASG instead of the incoming ASG which was causing the `aws_autoscaling_notifications` resource to be attached to the wrong ASG. Using variables and outputs resolves this by forcing Terraform to wait to apply the `bfd_server_disk_alarms` module until the `bfd_server_asg` module is fully applied and the value of `asg_id` is known
- Fixing the usage of `None` when there is no …
=> BFD-3573: manage-disk-alarms Lambda(s) are failing due to incorrect Terraform apply ordering

.github/workflows/build-release.yml
BFD-3625
This effectively installs `gitleaks` from the latest [gitleaks/gitleaks](https://github.com/gitleaks/gitleaks/releases/latest) release archive inside the build-release workflow.
While `gitleaks` itself is MIT licensed, the _official_ gitleaks action appears to require a _free_ license when executing as part of a GitHub organization. I don't believe this flouts any specific licenses at issues as I've simply implemented a step to download/install the MIT-licensed gitleaks archive–I'd just rather not go through any additional steps to allow gitleaks executions to proceed as part of the build-release workflow.
* Adds any new software …
=> BFD-3625: Add gitleaks to build-release

ops/terraform/services/base/values/prod.yaml
BFD-3679
This PR _correctly_ disables the PAC endpoints by setting the `pac_resources_enabled` SSM parameter to `false` rather than the `pac/enabled` SSM parameter.
Until BFD-3045 is merged the former parameter controls whether or not the PAC endpoints are enabled.
For context, the Java source looks for a configuration value named `pac/enabled` but the BFD Server does not yet self-configure from SSM. So, this value needs to be provided to the BFD Server in the form of an environment variable named `BFD_PAC_ENABLED` (`BFD_`-prefixed environment variables are converted to configuration paths by removing the `BFD_` prefix, lowercasing, and then replacing underscores with slashes). Unfortunately, the value of `BFD_PAC_ENABLED` is provided by `pac_resources_enabled` in …
=> BFD-3679: Temporarily, correctly disable PAC endpoints during SAMHSA Incident

apps/utils/locust_tests/lambda/server-regression/app.py, apps/utils/locust_tests/services/server-load/controller/controller.py, apps/utils/locust_tests/services/server-load/node/node.py, ops/ccs-ops-misc/synthetic-data/scripts/synthea-manual/ssmutil.py
BFD-3684
This PR updates old references to two BFD Server DB-related SSM parameters in various Python scripts used by Lambdas and other processes; most importantly, this fixes the Regression Suite.
- Searching the repository for `data_server_db_username` and `data_server_db_password`, _verifying that_ …
=> BFD-3684: Some processes are failing to run as they reference old BFD Server database parameters

apps/bfd-server/bfd-server-shared-utils/src/main/java/gov/cms/bfd/server/sharedutils/BfdMDC.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/TransformerUtilsV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/pac/AbstractR4ResourceProvider.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/CoverageE2EBase.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/ExplanationOfBenefitE2EBase.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/PatientE2EBase.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/ServerTestUtils.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/PatientE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/pac/ClaimE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/pac/ClaimResponseE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/PatientE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/utils/RDATestUtils.java, ops/terraform/services/server/insights/api-requests/glue.tf
BFD-3688
This PR introduces additional logging to the `Claim` and `ClaimResponse` endpoints that logs the `mbi_id` and `mbi_hash` of the MBI associated with the FISS or MCS claim to the MDC. Since the MDC log informs BFD Insights, these fields are now available to query within Athena as `mdc_mbi_hash` and `mdc_mbi_id`. Correspondingly, the Glue Table and Parquet schemas have been updated to include these new columns.
Additionally, E2E tests were added verifying that these identifiers are logged to the `access.json` MDC log for any valid request against `Claim` or `ClaimResponse`.
**Note that the Glue Crawlers in `prod-sbx` and `prod` must be run after this is merged before `mdc_mbi_hash` and `mdc_mbi_id` can be queried upon. I will do this upon merge, out-of-band.**
If …
=> BFD-3688: Log nonsensitive MBI identifiers to MDC for Claim and ClaimResponse requests

ops/terraform/services/server/modules/bfd_server_asg/scripts/launch-template-data.sh
BFD-3737
This adds a missing helper script that was erroneously absent in the BFD-2558.
n/a
This was used to run successful out-of-band on deployments to `test`, `prod-sbx`, and `prod`.
=> BFD-3737: Add missing launch-template-data.sh

ops/jenkins/bfd-cbc-build/Dockerfile
BFD-3740
Updates awscli to version 2 to match what engineers are using in their local development environments.
- builds locally without issue
- remote build was successful, resulting cbc build image used as part of the 2.164.0 deployment today, 2024-11-06
=> BFD-3740: Update awscli to v2 in CBC Container

ops/terraform/services/server/modules/bfd_server_slo_alarms/data-sources.tf, ops/terraform/services/server/modules/bfd_server_slo_alarms/main.tf
BFD-3788
Enable evaluation for module "bfd_server_slo_alarms" despite zero count for ephemerals
Are any unintended consequences introduced?
Employing these changes locally for BFD-3766 allowed bad-server deployment to succeed.
=> BFD-3788: Fix ephemeral bfd-server-slo-alarm apply

ops/terraform/services/eft/main.tf, ops/terraform/services/eft/modules/bfd_eft_outbound_o11y/main.tf
BFD-3848
This PR updates the maximum Lambda retries to 3 instead of disabling retries outright. Initially, the fear was that this Lambda was not idempotent, but after some investigation we determined that it is actually idempotent and the Lambda as a whole can be retried. Accordingly, the CloudWatch Alarms alerting on failures for this Lambda has been updated to alert after 3 failures in a 10 minute period so that the on-call is not alerted if the Lambda is able to recover automatically.
* ~~Any other changes that could …
=> BFD-3848: Transient SFTP connection errors are affecting BFD EFT Outbound in test

ops/ansible/playbooks-ccs/templates/cwagent-data-pipeline.json.j2, ops/terraform/services/pipeline/cloudwatch.tf, ops/terraform/services/pipeline/main.tf
BFD-3685
This PR separates the CloudWatch log groups for the CCW and RDA pipelines. The relevant alarms and other affected resources have been updated accordingly. The changes have been applied to an ephemeral environment, and it has been tested to confirm that the logs are now separated as intended …
=> BFD-3685: Separate CCW and RDA Pipeline Log Groups

ops/terraform/services/base/main.tf, ops/terraform/services/common/main.tf, ops/terraform/services/eft/main.tf, ops/terraform/services/migrator/main.tf, ops/terraform/services/pipeline/main.tf, ops/terraform/services/server/main.tf, ops/terraform/services/server/server-load/main.tf, ops/terraform/services/server/server-regression/main.tf, ops/terraform/services/static-site/main.tf
BFD-3923
This pins the `bfd-terraservice` module to a known, good version at tagged release 2.181.0 so that we can innovate on the child module for forthcoming fargate and greenfield migrations, without any concerns toward introducing errors.
* Reviewers should be familiar with various modules in terraform, especially the so-called[ Root Modules and Child Modules](https://developer.hashicorp.com/terraform/language/v1.5.x/modules); for our purposes, the terraservices themselves, i.e. `base`, `common`, `eft` and so on are _root modules_, while the `bfd-terraservice` module is a _child module_. This PR seeks to reference that `bfd-terraservice` by a tag reference. 
* Reviewers may note that while this …
=> BFD-3923: Use versions in child module references

apps/pom.xml
BFD-3922
This PR updates the base Image definition (`jib.from`) for Jib-built BFD application Images to base them off the new `bfd-mgmt-base-jdk` Image introduced in BFD-3919. This PR also changes the default `jib.from` to build from _local_ `bfd-mgmt-base-jdk` Images as developers will typically be building local images based upon `-SNAPSHOT` versions.
NOTES:
- There is [a known compatibility issue between Jib and Podman](https://github.com/GoogleContainerTools/jib/issues/4134) that currently causes local `dockerBuild`s to fail when the `jib.from` is pulling from the Podman daemon.
- It seems that Maven does not expand environment variables during the `dockerBuild` goal (i.e. specifying a `jib.from` in the `pom.xml` like `${env.ECR_REPO}/...` does not work), so at this …
=> BFD-3922: bfd-parent jib definition uses standardized base container images

ops/terraform/services/server/modules/bfd_server_log_alarms/main.tf
BFD-4023
Addresses a bug where the metric_name for CloudWatch Metric Alarm samhsa-mismatch-error was incorrect
Correct metric_name is set properly to "samhsa-mismatch/count/error"
None
Test alarm is triggered when encountering error message like "Samhsa: Claim ID mismatch between old SAMHSA filter":
1. Insert a log event into CloudWatch test log stream:
aws logs put-log-events --log-group-name "/bfd/test/bfd-server/messages.json" --log-stream-name "i-0f00beeed624e1f90" --log-events timestamp=$(date +%s%3N), message="{\"message\": \"Samhsa: Claim ID …
=> BFD-4023: Fix metric_name on the CloudWatch Metric Alarm, samhsa-mismatch-error

ops/terraform/services/server/modules/bfd_server_metrics/main.tf
BFD-4024
Addresses an incorrect message filter pattern on bfd samhsa-mismatch CloudWatch Log filter.
log message filter %Samhsa: Claim ID mismatch between old SAMHSA filter% is set
None
Execute in Test the following command and verified alarm samhsa-mismatch-error is triggered:
aws logs put-log-events --log-group-name "/bfd/test/bfd-server/messages.json"  --log-events timestamp=$(date +%s%3N), message="{\"message\": \"Samhsa: Claim ID mismatch between old SAMHSA filter (hasSamhsaData) and new SAMHSA 2.0 (hasSamhsaDataV2) - Claim ID: 12345678 (Class: …
=> BFD-4024: Change log metric filter pattern

ops/terraform/services/eft/modules/bfd_eft_outbound_o11y/lambda_src/outbound_slack_notifier/outbound_slack_notifier.py
BFD-4012
Skip sending file transfer successful messages by BFD EFT Outbound Lambda, to slack.
No file transfer successful messages by BFD EFT Outbound Lambda on the slack channel bfd-internal-alerts.
None
Publish a message of type TRANSFER_SUCCESS in the Outbound Notifications SNS topic.  This should not send slack TRANSFER_SUCCESS notification to slack channel bfd-internal-alerts.
=> BFD-4012: Do not send slack messages when file transfer is successful

ops/platform/01-config/main.tf, ops/platform/01-config/values/.gitignore, ops/platform/01-config/values/platform.legacy.sopsw.yaml, ops/services/01-config/values/prod-sbx.sopsw.yaml, ops/services/01-config/values/prod.sopsw.yaml, ops/services/01-config/values/test.sopsw.yaml, ops/services/02-database/main.tf, ops/services/04-server/deploy.tf, ops/services/04-server/regression-wrapper.tf, ops/services/04-server/service.tf, ops/services/04-server/templates/server-appspec.yaml.tftpl, ops/terraform-modules/general/trigger-glue-crawler/lambda_src/trigger_glue_crawler.py
BFD-4115
This PR is an assortment of changes that were necessary in order to `apply` our Greenfield Terraform to the Legacy account.
In no particular order, this PR:
- Enables placement of `server` Service Tasks into both of the `FARGATE` (on-demand, not subject to Spot Termination) and `FARGATE_SPOT` (spot, subject to Spot Termination) Capacity Providers based on SSM Parameter values. Both `base` and `weight` values can be configured via SSM. Only `prod` is configured with any Tasks placed in the `FARGATE` Capacity Provider: 1 Task will _always_ run in `FARGATE` in `prod` to ensure we are never running without _some_ capacity in `prod`
- Ensures that `tofu apply`s of `server` report "no changes" when there really are no changes. Before this fix, the private IP address …
=> BFD-4115: Deploy all Greenfield Terraform to Legacy in all environments

apps/bfd-pipeline/bfd-pipeline-idr/load_synthetic.py
BFD-4245
Ignores extra columns when loading CSVs by comparing the input to the schema in the database.
Ran the script directly, data was loaded with extra fields ignored.
=> BFD-4245: Ignore extra columns when loading CSVs

.github/workflows/ci-java.yml, apps/bfd-db-migrator/src/test/java/gov/cms/bfd/migrator/app/MigratorAppIT.java, apps/bfd-server-ng/src/test/java/gov/cms/bfd/server/ng/IntegrationTestConfiguration.java, apps/bfd-shared-test-utils/src/main/java/gov/cms/bfd/AbstractLocalStackTest.java, apps/bfd-shared-test-utils/src/main/java/gov/cms/bfd/DatabaseTestUtils.java, apps/pom.xml, ops/platform/000-bootstrap/README.md, ops/platform/000-bootstrap/codebuild.tf, ops/platform/01-config/values/platform.non-prod.sopsw.yaml
BFD-3764
* adds a test/prod vpc-connected `platform-large` self-hosted runner for `ci-java` workloads
* runs `ci-java` on these newly introduced runners, with added logic for producing jacoco reports and submits them to sonarqube
* schedule `ci-java` workflow to run against trunk/`master` Monday through Friday mornings
* update testcontainer container images to use the Amazon Public ECR Gallery instead of DockerHub to avoid rate limit exceptions
* ~Determine the appropriate log volume–do we want to revert to sparser logs from the maven build step (<300 lines) or is current implementation of more verbose logs (\~6,000 lines) preferred?~ More verbosity is appreciated. Thanks, @aschey-forpeople!
* 0813 …
=> BFD-3764: Enable SonarQube Analysis in GHA
