CMSgov/beneficiary-fhir-data

Jenkinsfile, apps/build.groovy, ops/ansible/playbooks-healthapt/backend.yml, ops/ansible/playbooks-healthapt/load_balancers.yml, ops/ansible/roles/bfd-server/tasks/appserver_install.yml, ops/ansible/roles/bfd-server/tasks/base_install.yml, ops/deploy-healthapt.groovy
Get deploys working for HealthAPT environments.
https://jira.cms.gov/browse/BLUEBUTTON-1086
=> BLUEBUTTON-1086: Debug Jenkinsfile deploys for HealthAPT environments

ops/deploy-ccs.groovy
This switches the packer build to use AZ2 instead of AZ1.
=> CCS - Switching packer AZ

ops/terraform/modules/resources/templates/fhir_server.tpl, ops/terraform/modules/resources/templates/pipeline_server.tpl
Tested that this works successfully on a detached ASG instance.
=> Fix extra vars creation

ops/terraform/modules/resources/lb/main.tf
Title sums it up. Hotfix. I am deploying this PR to TEST to confirm.
=> BLUEBUTTON-1278: Using name_prefix for target group name to avoid resource conflict.

Jenkinsfile
Thought of this (unfortunately) after I merged the previous PR. Just cleans up the code a bit.
https://jira.cms.gov/browse/BLUEBUTTON-1112
=> BLUEBUTTON-1112: Remove unnecessary parameter

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/FDADrugDataUtilityApp.java
Honestly not sure why the previous shutdown hook wasn't working: it
should have? Regardless, this will hopefully be more reliable.
https://jira.cms.gov/browse/BLUEBUTTON-888
https://jira.cms.gov/browse/BLUEBUTTON-889
=> BLUEBUTTON-888: Fix cleanup of fda-data temp files.

apps/bfd-pipeline/bfd-pipeline-rif-extract/src/test/java/gov/cms/bfd/pipeline/rif/extract/s3/DataSetMonitorWorkerIT.java
Oops: I somehow missed this in my previous PR.
https://jira.cms.gov/browse/BLUEBUTTON-850
=> BLUEBUTTON-850: Resolve another non-unique bucket name error

Jenkinsfile
Not safe until we have completed all related security & compliance items.
https://jira.cms.gov/browse/BLUEBUTTON-1212
=> BLUEBUTTON-1212: Disable all CCS deploys to prod

ops/deploy-ccs.groovy, ops/packer/build_bfd-pipeline.json, ops/packer/build_bfd-server.json
I think this may give us more insight into the AMI issue being seen.
=> Include environment name in manifest path

ops/ansible/playbooks-healthapt/dev/stress-test.sh
Also updated it to run multiple queries for each beneficiary, and improved its logging.
Makes it somewhat more useful, though it's still pretty terrible.
https://jira.cms.gov/browse/BLUEBUTTON-1309
=> BLUEBUTTON-1309: Update stress test script to use random bene IDs

ops/terraform/modules/resources/asg/main.tf, ops/terraform/modules/resources/ec2/main.tf
**Why**
Nathan noticed that volumes where accumulating a very fast rate. 
Change the delete on termination flag on ETL and FHIR servers.
=> Fix-delete-on-termination

ops/terraform/env/prod-sbx/stateless/main.tf, ops/terraform/env/prod-sbx/stateless/variables.tf, ops/terraform/env/prod/stateless/main.tf, ops/terraform/env/prod/stateless/variables.tf
Because I forgot to add these vars that are passed through TF from Jenkins to the prod-sbx and prod TF variables.
=> Adding git vars for user_data to prod-snx and prod

ops/deploy-ccs.groovy
Not easy right now to tell when locks are being taken and released as part of our deploys. Logging these timestamps should help diagnose that.
=> BLUEBUTTON-1288: Adding debug logging for Terraform locks

apps/bfd-server/bfd-server-launcher/src/main/resources/logback.xml, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/SpringConfiguration.java
Enabling additional logging to help with debugging Hikari
=> BLUEBUTTON-1233: Enabling Hikari Logging

apps/bfd-server-test-perf/src/main/java/gov/cms/bfd/server/test/perf/utils/FhirClient.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/SpringConfiguration.java
There were some changes that make our formatter sad, which block further commits (via the pre-commit hook).
=> BLUEBUTTON-1288: Fixing Java formatting

ops/terraform/modules/resources/bfd_pipeline/main.tf, ops/terraform/modules/resources/bfd_pipeline/variables.tf, ops/terraform/modules/stateless/main.tf
Main functional difference is that it now has access to the KMS key and permissions to list the RIF bucket.
Also restructured things a bit.
=> BLUEBUTTON-1288: BFD Pipeline S3 access

ops/terraform/env/prod/stateful/main.tf
Just being extra cautious for the start of Open Enrollment.
=> BLUEBUTTON-1288: "Turbo Mode": Bump up RDS IOPS in PROD

Jenkinsfile, ops/deploy-ccs.groovy, ops/deploy-healthapt.groovy
Also cleaning up a couple of minor things in our `Jenkinsfile`, while I'm poking at it.
https://jira.cms.gov/browse/BLUEBUTTON-1359
=> BLUEBUTTON-1359: Enable deploys to the CCS prod environment

ops/terraform/env/prod-sbx/migration/main.tf, ops/terraform/env/prod/migration/main.tf
This work has already been applied per yesterday's migration.
=> BLUEBUTTON-1372: CCS 100 percent traffic

ops/ansible/playbooks-ccs/vars/000_cross_env_vars.yml
Adds an ssh user for Dave Tisza.
=> Add dtisza ssh user

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/BeneficiaryTransformer.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/BeneficiaryTransformerTest.java, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/patientByIdentifier.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/patientByIdentifierWithIncludeIdentifiers.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/patientRead.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/patientReadWithIncludeIdentifiers.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/patientSearchById.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/patientSearchByIdWithIncludeIdentifiers.json, apps/bfd-server/dev/api-changelog.md
Reverts #170
Needing to remove this PR that got merged to master, since this is now planned for a later date.
=> Revert "BLUEBUTTON-1679 Remove hicn-hash identifier from Patient Resource"

apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProviderIT.java
**Why**
Missed a test to disable on the PR#192. 
**Testing**
Local build.
=> BLUEBUTTON-1737: One more dup test to disable

apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/ServerTestUtils.java
**Why**
The master branch is broken because of a merge problem from my last PR. 
**What**
Fix build by adding a parameter to a test function. 
**Testing**
Build works locally.
=> BLUEBUTTON-1516: Fix master branch

rfcs/0005-mbi-search.md
**Why**
The MBI changes taken in total is a significant change to the BFD contract with its partners. 
**What**
An RFC is an agreed-upon process to document significant changes to the BFD.
=> BLUEBUTTON 1516: Add the RFC

ops/ansible/playbooks-ccs/vars/000_cross_env_vars.yml
Adds my SSH key for server access to environments.
=> Add Ron Heft's SSH key

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/TransformerUtils.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProviderIT.java, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/metadata.json, apps/bfd-server/dev/api-changelog.md
This creates a search operation that find patients based on their part D contract status for a given month of this year.
- https://github.com/CMSgov/beneficiary-fhir-data/pull/156 for spec and RFC
- [BLUEBUTTON-1784](https://jira.cms.gov/browse/BLUEBUTTON-1784)
=> BLUEBUTTON-1784 Search for patients by ptdcntrct

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/CoverageResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/ExplanationOfBenefitResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PageLinkBuilder.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProvider.java
Summary:
This refactors the paging code related to the work done for BLUEBUTTON-1593 (Support paging for TYPE parameter) and BLUEBUTTON-1506 (Bulk Export Since support). This builds on the work commited via the PR: https://github.com/CMSgov/beneficiary-fhir-data/pull/155
The following was done:
* Refactored the `createPageLink()` method in the `PageLinkBuilder` class with the following:
* Retains the original URL parameters utilizing the `RequestDetails`.  This includes `type`, `excludeSAMHSA`, `lastUpdated`, or any other parameters.
* Only update URL parameters related to paging, including `startIndex` and `_count`.
* Removes `PageLinkBuilder` Java parameters not directly concerned with paging, including `lastUpdated`, `claimTypes`, and `excludeSamhsaq`
```
curl -v -k -E ${KEYSTORE_FILE} …
```
=> BLUEBUTTON-1593 Refactor to simplify paging parameters

ops/ansible/playbooks-ccs/build_bfd-platinum.yml
Per CCS this was a networking issue that has since been fixed: https://jiraent.cms.gov/browse/CLDSUPSD-1005
=> Revert "BLUEBUTTON-1844: TrendMicro activation workaround (#221)"

ops/terraform/env/mgmt/stateful/main.tf, ops/terraform/env/mgmt/stateless/main.tf, ops/terraform/env/mgmt/stateless/variables.tf
This PR brings the mgmt TF in line with how we will structure the TF for this environment (to reflect work being done in my mgmt-test branch / env) and allows our CI to pass. 
This work is not complete, as I work to finish up in mgmt-test testing, etc., but it does fix our CI and passes `terraform validate` 
- [BLUEBUTTON-1281](https://jira.cms.gov/browse/BLUEBUTTON-1281)
=> BLUEBUTTON-1281: Bring MGMT into parity and pass CI

apps/bfd-pipeline/bfd-pipeline-rif-load/src/main/java/gov/cms/bfd/pipeline/rif/load/RifLoader.java
**Why**
https://confluence.cms.gov/pages/viewpage.action?pageId=287673729 Incident is caused by a failure in the BFD-Pipeline. 
**Cause Analysis**
The relevant events in the pipeline logs are: 
```
java.lang.IllegalArgumentException: Removing a detached instance gov.cms.bfd.model.rif.LoadedFile#2
at org.hibernate.jpa.event.internal.core.JpaDeleteEventListener.performDetachedEntityDeletionCheck(JpaDeleteEventListener.java:52) ~[hibernate-core-5.2.10.Final.jar:5.2.10.Final]
at org.hibernate.event.internal.DefaultDeleteEventListener.onDelete(DefaultDeleteEventListener.java:89) ~[hibernate-core-5.2.10.Final.jar:5.2.10.Final]
at org.hibernate.event.internal.DefaultDeleteEventListener.onDelete(DefaultDeleteEventListener.java:56) ~[hibernate-core-5.2.10.Final.jar:5.2.10.Final]
at …
```
=> Fix 2020-03-30 Incident

apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/TransformerTestUtils.java
**Why**
Occasionally, BFDs integration tests will fail because of a small difference in lastUpdated values. Running the tests again and they will most likely pass. 
@dtisza1 Reported this example. 
>I ran into something interesting and maybe a possible intermittent issue.  I received this error when running the IT tests related to the lastUpdated time comparison in PatientResourceProvider.   In this case, the time is just off by a short amount.
However, I've run the IT test several more times and I can't reproduce the error again :thinking_face:
Just wondering if we might get intermittent cases were this test fails, when the time is slightly off?
Untitled 
Results :
Failed tests: 
PatientResourceProviderIT.readExistingPatientIncludeIdentifiersHicnMbi:82->assertExistingPatientIncludeIdentif …
=> BLUEBUTTON-1900: Fix an intermittent failing test

apps/bfd-model/bfd-model-rif-samples/dev/design-sample-data-sets.md, ops/ccs-ops-misc/synthetic-data/scripts/beneficiary/update_beneficiary_rif_files_for_bb1896.py
This PR updates realistic coverage contracts to the 30,000 synthetic beneficiary part D enrollment data fields.
The following was performed:
* Created a python mapping script for processing the synthetic-beneficiary RIF files. This updates the coverage contract part D fields and generates output files with a ".new" extension.
* Updated the `design-sample-data-sets.md` document with details about the changes.
* Uploaded the resulting file set to the `bfd-public-test-data` S3 bucket.
* That the resulting RIF output files are valid related to the requested changes.
* That the resulting RIF output files are suitable to be used for updating the database via the ETL process and are ready for the related Jira BB-1901 tasks.
- [BLUEBUTTON-1896](https://jira.cms.gov/browse/BLUEBUTTON-1896)
- …
=> BLUEBUTTON-1896 Generate synth part D enrollment data

ops/terraform/env/prod-sbx/stateful/main.tf, ops/terraform/env/prod/stateful/main.tf, ops/terraform/env/test/stateful/main.tf, ops/terraform/modules/resources/aurora/main.tf, ops/terraform/modules/resources/aurora/variables.tf, ops/terraform/modules/stateful/main.tf, ops/terraform/modules/stateful/variables.tf, ops/terraform/modules/stateless/main.tf
This implements an Aurora cluster into every environment with the following configurable parameters:
- Instance class
- Nodes per cluster
- Engine/parameter group version
- Custom parameter group parameters
Maintenance and backup parameters were ported from the RDS module, however these could be made configurable as well.  I have also ported over the Route 53 CNAME address from the RDS module to create entries for Aurora writer and reader endpoints, although we don't currently use this address.
I am looking for two areas of validation before considering this complete:
- Instance sizes per environment
- Omission of cloudwatch alarms from RDS module in favor of increased obervability in the form of performance insights and additional debugging parameters.
**Instance sizes per environment** …
=> BLUEBUTTON-1988: Aurora implementation

apps/bfd-model/bfd-model-rif-samples/src/main/java/gov/cms/bfd/model/rif/samples/TestDataSetLocation.java
This updates the ENUM `TestDataSetLocation.SYNTHETIC_DATA` with the latest S3 bucket location of the synthetic data files.
The related integration test is successful. NOTE: The @skip should be commented out when running the test at:  https://github.com/CMSgov/beneficiary-fhir-data/blob/ee7900b1c2df7fa81aa9d591eb9794b1937ca1ec/apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/OutpatientClaimTransformerTest.java#L65
=> Update S3 synthetic data location for tests

insights/terraform/modules/bucket/main.tf, insights/terraform/modules/bucket/outputs.tf, insights/terraform/modules/bucket/policies.tf, insights/terraform/modules/jobs/main.tf, insights/terraform/modules/jobs/policies.tf, insights/terraform/modules/jobs/variables.tf, insights/terraform/projects/ab2d/main.tf, insights/terraform/projects/ab2d/tables.tf
BFD-164
Setup the BFD-Insights project for AB2D
**What Does This PR Do?**
This PR adds an AWS role for Glue jobs to access the S3 buckets of the project. 
**What Should Reviewers Watch For?**
Mistakes or missing pieces. 
**Submitters should complete the following questionnaire:**
N/A
=> BFD-164: AB2D glue role

ops/ansible/playbooks-ccs/roles/rhel_prep/tasks/main.yml, ops/ansible/playbooks-ccs/roles/rhel_prep/tasks/ntp.yml, ops/terraform/modules/resources/templates/fhir_server.tpl, ops/terraform/modules/resources/templates/pipeline_server.tpl
[BFD-151](https://jira.cms.gov/browse/BFD-151)
As a BFD engineer, I need to be able to diagnose deployment timeouts or other things that might go wrong during an instance launch. Adding timestamps to operations during instance launch will greatly help in this process. Additionally, I need the ETL to be set to UTC in order to avoid miscommunication and other confusion around what time events are happening in our logs – especially given the distributed nature of our team. And to avoid common mistakes in analytics and data processing.
1. Adds a timestamp to user_data script output to assist in debugging.
2. Sets the platinum build to use UTC timezone. Which, will in-turn, configure the local timezone to UTC for images/instances built on-top of …
=> BFD-151 timezone timestamp

ops/ansible/roles/bfd-server/tasks/install.yml
[BFD-210](https://jira.cms.gov/browse/BFD-210)
Fix broken log rotation caused by selinux file context violation.  This occurs due to the fact that cron jobs run in a limited context (issue does not persist when running logrotate manually which is an uninhibited context).
This adds and applies the proper file context for logrotate to be able to run on the bfd-server directory during a cron job.
Primarily that this doesn't break anything else.  I have tested successfully on a detached instance but will test with a full deployment.
* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment: N/A.
* Does this PR add any new software dependencies? **No**. …
=> BFD-210: Fix broken log rotation due to selinux

apps/bfd-model/bfd-model-rif-samples/src/main/resources/rif-static-samples/sample-mct-update-4-manifest.xml
This adds a manifest .xml file for the MCT update-4 rif-static-samples resources.  The related `sample-mct-update-4-beneficiaries.txt` file is already in the master branch.
The related files have already been loaded in to prod-sbx and prod environments.
https://jira.cms.gov/browse/BLUEBUTTON-1829
=> BLUEBUTTON-1829 Add manifest for mct update-4

.github/CODEOWNERS
​
N/A
​
​We need to update our git hub code owners with the new teammates so that the correct people are tagged and suggested for reviews.
​
​
This PR updates the CODEOWNERS file that is picked up by GitHub during PR Reviews. 
​
​
If you're reviewing this PR, please check these things, in particular:
​
- Confirm if you see the correct people as Code Owners for the various section of our code. 
​- Are any additional documentation updates needed?
​
​
​
* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment: N/A.
* Does this PR add any new software dependencies?  **No**. …
=> Update GitHub Code Owners

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/OutpatientClaimTransformer.java
JIRA Ticket:
BFD-252
​
User Story or Bug Summary:
The BCDA team reported the below.
Goal of this ticket is to investigate and resolve the reported issue.
We're getting a few 500 errors when we attempt to retrieve ExplanationOfBenefit for a select few beneficiaries. This happens repeatedly on a few beneficiaries. Coverage and Patient requests work perfectly fine for the same beneficiary.
​
What Does This PR Do?
​Handling for optional status code claim line: BFD-252​
​
Code handling for optional Status claim line field in OutpatientClaimTransformer.
​
What Should Reviewers Watch For?
​
If you're reviewing this PR, please check these things, in particular:
Code handling for optional Status claim line field in OutpatientClaimTransformer.
​
​
​
What Security Implications Does This PR Have? …
=> BFD-252​: ​Handling for optional status code claim line

contributing/docker/Dockerfile
This one line change sets the CentOS FHIR App container LANG (locale) so that IT's can pass when invoked.
IT's now pass when run within the docker container. I've added output in the comments. 
Is there a better way to have this set?
- [BLUEBUTTON-249](https://jira.cms.gov/browse/BLUEBUTTON-249)
=> BFD-249: Onboard DPC, set LANG=UTF8 in docker container for local dev.

insights/docs/onboarding.md, insights/terraform/groups/main.tf
[BFD-208](https://jira.cms.gov/browse/BFD-208)
Add Andy Daykin and Oren Fromberg to the BFD insights analysts group
Add Andy Daykin and Oren Fromberg to the BFD Insights analysts groups so they can do work on the BFD Insights projects. 
Their character should be reviewed. 
* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment: N/A.
* Does this PR add any new software dependencies? **No**
* Does this PR modify or invalidate any of our security controls? **No**
* Does this PR store or transmit data that was not stored or transmitted before? **No**.
* If the answer to any of the questions below is **Yes**, then please add …
=> BFD. Add Andy Daykin and Oren Fromberg to Analysts group

apps/bfd-model/bfd-model-rif-samples/dev/design-sample-data-sets.md, apps/bfd-server/pom.xml
**Change Details**
Updated the documentation for synthetic data. As a BFD peering partner, I need updated synthetic users and their MBI's in all environments so that they match the values loaded within the various SLS environments and so end to end testing can be completed.
Added steps in the sample set info to how to download updated synthetic data documentation.
The following is a summary of the changes related to update #7 2020-05-21-synthetic-bene-updated-mbi: To denote that an MBI is synthetic in the BFD database, we are using the 2nd position character = "S". We are breaking the MBI standard format for just the 2nd character position for this purpose: https://www.cms.gov/Medicare/New-Medicare-Card/Understanding-the-MBI-with-Format.pdf However, we ran in to validation issues with 999 …
=> Cbrune/bfd 21- updated synthetic bene

.github/workflows/ci-java.yml
Our GitHub Actions that power our CI (integration tests in this case) are failing. Looking back at the most recent successful checks and seeing JDK version 1.8.0.252 in github actions workflow scripts was successful, while the latest (1.8.0.262) was breaking the AuthenticationIT's intermittently (mostly all the time, for some unknown reason)
This PR also removes the java_version from the matrix logic, as we dont use different nor test on different versions of java. 
Please check that the GitHub Actions / checks pass with this change and that there are no security concerns with sticking on 1.8.0.252.
Will this break future dependency updates?
- [BFD-332](https://jira.cms.gov/browse/BFD-332)
I see no major security updates between 252 and 262.
=> BFD-332: Pin JDK 1.8.0.252 for GitHub CI, last known working version.

ops/ansible/playbooks-ccs/vars/prod/group_vars/all/env_specific.yml
This PR sets 'idempotency required' to FALSE in only the PROD environment. This will modify our RIF LoadStrategy so that it will NOT check to see if the record already exists. This is set so that for records which we might have already loaded do not cause the ETL service to fail once we attempt to reload the bene records from the newest CCW extract that was provided in response to the bug with duplicate INSERT records over the previous weekend. 
ATTN: We will need to revert this setting as soon as the data load is completed and redeploy with 'idempotency required' to TRUE. This has been specified in the Jira Ticket as part of the AC.
Is this the correct location to set this? 
- [BFD-334](https://jira.cms.gov/browse/BFD-334)
=> BFD-334: Set ETL idempotency to FALSE to accommodate CCW Data Bug

ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2
[BFD-409](https://jira.cms.gov/browse/BFD-409)
Update New Relic agent configuration for BFD FHIR app to use FedRAMP approved endpoints
This PR simply changes the default host domain for which New Relic agents report to so that we use FedRamp approved endpoints.  I did not make this a configuration variable because this is unlikely to ever change again.
N/A
* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence: N/A.
* Does this PR add any new software dependencies?  **No**.
* Does this PR modify or invalidate any of our security controls? **No**.
* Does …
=> BFD-409: Point New Relic Agent to report to FedRamp endpoint. 

insights/terraform/projects/bcda/backend.tf, insights/terraform/projects/bcda/main.tf
This branch adds folder `terraform/projects/bcda` with some infrastructure that will be used to collect data for BFD insights.
The infrastructure consists of a terraform backend and an instance of the bucket module which creates a number of resources.
This module is copied almost exactly from the AB2D folder and allows for 1 cross account role to access the bucket.
Here is the terraform plan to be applied:
```
------------------------------------------------------------------------
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
+ resource "aws_iam_group_policy_attachment" "athena_attach" {
+ group      = "bfd-insights-readers"
+ id         = (known after apply)
+ …
```
=> BFD Insights: Adding BCDA project

rfcs/0007-service-date-filter.md
Adding RFC that describes approach for the service date filter.
Review RFC and sign off on the approach
- [BCDA-3781](https://jira.cms.gov/browse/BCDA-3781)
=> BCDA-3781 - RFC for service date filter

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/Operation.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/SpringConfiguration.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/CoverageTransformerV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4CoverageResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/TransformerUtilsV2.java
[BFD-344](https://jira.cms.gov/browse/BFD-344)
BFD V2: Implement POC for Coverage V2 FHIR R4 resource.
Makes Coverage v2 (FHIR R4) available to peer partners in Production Sandbox.
All functional and integration tests pass for lower environments and a test deploy is done before deploying to prod
N/A
* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence: N/A.
* Does this PR add any new software dependencies?  **No**.
* Does this PR modify or invalidate any of our security controls? **No**.
* Does this PR store or transmit data that was not stored or …
=> Coverage v2 poc

apps/bfd-model/bfd-model-rif/src/main/resources/db/scripts/Beneficiary_and_claim_statistics.sql
Add a DB query for bene counts.
Please confirm:
1. This DB query does not contain any logic errors; that it correctly models the info that it purports to.
2. This DB query is reasonably readable and understandable.
3. This DB query is worth keeping around in this file.
See above.
- [BFD-524](https://jira.cms.gov/browse/BFD-524)
No security implications found:
=> BFD-524: Add a DB query for bene counts

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4CoverageResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4PatientResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/CoverageResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/ExplanationOfBenefitResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProvider.java
Resolve operation name bugs, including with `_lastUpdated` requests:
1. Fix operation name bug for Coverage search. The call to `publishOperationName()` has to be last or the options set won't actually take effect.
2. Fix operation name bugs in Patient?_id= searches. The operation name wasn't being set **at all** when `_lastUpdated` filtering triggered such that no results would be returned. This likely led to some of the generic (i.e. not useful) operation name entries seen in our logs.
3. Add `_lastUpdated=[true|false]` to operation names. This was not previously being included in operation names, which really reduces the usefulness of our logs for performance measurement purposes.
1. Are these fixes correct?
2. Are these fixes complete: are there any other operation name issues that …
=> BFD-523: Fix operation name issues, particularly with _lastUpdated requests

apps/bfd-model/bfd-model-codegen/pom.xml, apps/bfd-server-test-functions/pom.xml, apps/bfd-server-test-perf/pom.xml, apps/bfd-server/bfd-server-launcher/pom.xml, apps/bfd-server/bfd-server-war/pom.xml, apps/bfd-server/bfd-server-war/src/main/config/server-start.sh, apps/pom.xml
Bumped up the following java deps to resolve security vulnerabilities:
jackson-databind
guava
spring-framework-bom
spark-sketch_2.12
Do CI Checks Pass?
Do these updates resolve the vulnerabilities? 
I intend to deploy this to test and run a bunch of smoke tests to check for edge cases our unit or iT tests MIGHT not catch. 
Should we update any other packages?
- [BFD-465](https://jira.cms.gov/browse/BFD-465)
=> BFD-465: Updating Java dependencies to resolve security vulnerabilities 

contributing/fetch.sh
Changed the fetch script to get the new synthetic data with newly added ccw fields
Make sure the right files are being sent over
Everything looks correct since the last time it was changed.
- [BLUEBUTTON-xxx](https://jira.cms.gov/browse/BLUEBUTTON-xxx)
=> Changed fetch script to point to the new data

apps/bfd-model/pom.xml, apps/bfd-pipeline/pom.xml, apps/bfd-server/pom.xml, apps/bfd-shared-utils/pom.xml, apps/bfd-shared-utils/src/main/java/gov/cms/bfd/sharedutils/package-info.java, apps/pom.xml
Adds a (currently empty) module, creatively named `bfd-shared-utils`, as a central place to start adding code and dependencies that should be shared with the entire BFD suite of projects and applications (more or less).
Nothing here yet, as I plan to use it in several separate PRs; it'll start getting actual content in those.
Please confirm:
* You don't hate this.
Please consider, is this a...
- [BLUEBUTTON-531](https://jira.cms.gov/browse/BLUEBUTTON-531)
No security implications noted here:
=> BFD-531: Add bfd-shared-utils module

apps/bfd-pipeline/bfd-pipeline-rif-load/src/main/java/gov/cms/bfd/pipeline/rif/load/RifLoader.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/SpringConfiguration.java
Have to disable the setting .HBM2DDL_AUTO to none in a separate PR before the schema change, If you don't, and the app hits any auto-scaling events will cause the app to do bad things.
- [BFD-549](https://jira.cms.gov/browse/BFD-549)
Sets the jpa entity property to NONE
n/a
=> BFD-549 - Set jpa property to none

.github/CODEOWNERS, .github/pull_request_template.md
This change updates and expands on the code owners assigned to this repo as well as updates our PR template to reflect the correct JIRA project space. Major changes include:
- Removes @karlmdavis as code owner from all sections _except_ rfc's. - The man can only be in one place at one time. :)
- Assigns @cbrunefearless as code owner to the 'catch-all' group. - Woohoo!
- Assigns @keithdadkins as a code owner to the 'catch-all' group. - Joy!
- Assigns @mackec1 as code owner to /app and to the 'catch-all' group. - Welcome!
- Re-Assigns! @njdister as a code owner of /ops. - Hope to see you soon!
- Assigns @lailasharshar @nflearl @wnyffenegger as code owners to /insights/terraform/projects/ab2d - Hi Fam!
- Assigns @msnook @orenfromberg as code owners to /insights/terraform/projects/bcda - …
=> BFD-608: Update GitHub Code Owners and PR Template

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/TransformerUtils.java, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/eobByPatientIdAll.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/eobByPatientIdPaged.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/eobReadCarrier.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/eobReadDme.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/eobReadInpatient.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/eobReadOutpatient.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/eobReadSnf.json
Carrier Number Line Error reported through google group.  The Carrier Number was getting a second value that was mapped to the carrier claim control number.
As a reviewer make sure the bug fix looks accurate
Make sure we are not canceling or deleting other fields that might break other systems.
- [BFD-628](https://jira.cms.gov/browse/BFD-628)
N/A
N/A
N/A
N/A
N/A
=> Fixed bug with control number

Jenkinsfile
Adds Slack notifications to builds (via Jenkinsfile).
_** Note: working with scripted style pipelines is very different from declarative pipelines. They use different syntax which required the use of try catch blocks instead of post blocks for triggering notifications. Just a heads up if you are only used to declarative._
Review slack notifications in the #bfd-build-status channel (after a few test deployments) to ensure messages include the following:
- Build number
- Branch 
- Stage of failure 
- Build URL
- Job name 
- Who launched the build
Test deployments should cover successful builds, successful but unstable builds, aborted builds, and failed builds.
Any glaring issues. Cases that I may have missed.
Please see #bfd-build-status slack for example builds.
Please feel free to offer …
=> Adds slack notifications to Jenkinsfile

ops/ansible/playbooks-ccs/roles/ops_tools/tasks/main.yml
Pip is outdated and is failing to install ansible. In addition, when pip was working, it was taking 30+ minutes to install ansible. We cannot build platinum images until this is resolved.
This installs anisble using yum instead.
=> Installs ansible using yum instead of pip

ops/ccs-ops-misc/synthetic-data/scripts/synthetic_endpoint_response.sh
Script to grab synthetic benes and run it against EOB, Patient, and Coverage Endpoints
Script to grab synthetic benes and run it against EOB, Patient, and Coverage Endpoints.  Make sure no security data is stored and the right synthetic benes are being pulled
Script to grab synthetic benes and run it against EOB, Patient, and Coverage Endpoints.  Make sure no security data is stored and the right synthetic benes are being pulled
- [BFD-605](https://jira.cms.gov/browse/BFD-605)
N/A
N/A
N/A
N/A
=> Synthetic script

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/TransformerConstants.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/PartDEventTransformerV2.java
(1) Fix V2 C4BB EOB PDE profile definition url: 
from:       "https://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-ExplanationOfBenefit-Pharmacy"
to:       "http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-ExplanationOfBenefit-Pharmacy"
(2) Added following C4BB EOB profiles definition urls as constants in TransformerConstants to promote use of 
constants vs. string literals across code base:
(3) Following constants added for CARIN, add more as needed:
public static final String C4BB_EOB_INPATIENT_PROFILE_URL =
"http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-ExplanationOfBenefit-Inpatient-Institutional";
public static final String C4BB_EOB_OUTPATIENT_PROFILE_URL =
"http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-ExplanationOfBenefit-Outpatient-Institutional"; …
=> BFD-640-fix-V2-EOB-PDE-profile-url

apps/bfd-server-test-functions/pom.xml, apps/bfd-server-test-perf/pom.xml, apps/bfd-server/bfd-server-launcher/pom.xml
Upgraded org.apache.httpcomponents.httpclient to 4.5.13.  
Upgraded org.apache.httpcomponents.httpcore to 4.4.14.  Upgraded com.fasterxml.jackson.core to 2.12.2.  Also had to upgrade the maven-shade-plugin to 3.2.4.
Look at the security vulnerabilities and make sure they look correct
- [BFD-601](https://jira.cms.gov/browse/BFD-601)
n/a
n/a
n/a
n/a
n/a
n/a
=> BFD- 601 - Upgrade jackson, shade plugin, httpclient, httpcore

ops/ansible/playbooks-ccs/templates/cwagent-data-server.json.j2
In order to debug an issue we are having with one of our partners, we need to (*temporarily*) send the log file generated in BFD-671 (loadedFilterManagerLog.json) to CloudWatch.
This change needs to be removed once debugging has been completed.
No glaring issues.
- [BFD-671](https://jira.cms.gov/browse/BFD-671)
=> [BFD-671] Adds loadedFilterManagerLog.json file to cloud watch

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/LoadedFilterManager.java
Changed loaded filter manager in json
Changed loaded filter manager in json
- [BFD-671]](https://jira.cms.gov/browse/BFD-671])
=> Added log details

ops/ansible/playbooks-ccs/launch_bfd-server.yml, ops/terraform/modules/stateless/main.tf
Increases the amount of CPU cores in prod-sbx for AB2D performance testing.
- m5.xlarge (4 cores) -> m5.4xlarge(16 cores)
- adjusts number of db connections to match
Notes: 
- sticking with the same instance class so we can see if/how AB2D scales linearly with num cores
- this will also increase the amount of ram from 16GB to 64GB, however, we have not experienced issues with memory pressure that I am aware of
- [BFD-695](https://jira.cms.gov/browse/BFD-695)
=> [BFD-695] Upsize prod-sbx to 16 cores (from 4) for performance testing

ops/ansible/playbooks-ccs/requirements.txt, ops/ansible/roles/bfd-server/requirements.freeze.txt, ops/ansible/roles/bfd-server/requirements.txt
In an effort to clear up some snyk PR's, we should update ansible to a non-vulnerable version that is available in RHEL7 yum packages. This is currently 2.9.18.
This also updates lxml to a non-vulnerable version.
Better to do this in one PR over trying to merge/update multiple snyk pr's.
Note: these are low risk updates.
This should allow us to close out:
https://github.com/CMSgov/beneficiary-fhir-data/pull/504
https://github.com/CMSgov/beneficiary-fhir-data/pull/498
https://github.com/CMSgov/beneficiary-fhir-data/pull/497
https://github.com/CMSgov/beneficiary-fhir-data/pull/496
https://github.com/CMSgov/beneficiary-fhir-data/pull/495
https://github.com/CMSgov/beneficiary-fhir-data/pull/461
https://github.com/CMSgov/beneficiary-fhir-data/pull/460 …
=> [BFD-703] Update ansible/lxml to non-vulnerable versions

ops/terraform/modules/resources/bfd_pipeline/main.tf
Before our ETL instance can mount our EFT EFS file systems, we need to query for mount points, Availability Zones, etc. This allows the ETL instance read only access to EFS file systems and allows the instance to query the AWS API for availability zones via the cli.
Note: While attaching the AWS managed AmazonElasticFileSystemReadOnlyAccess policy does allow the instance to query and mount any EFS file system in our account, actual access to file systems is managed in the individual file system policies.
- [BFD-477](https://jira.cms.gov/browse/BFD-477)
=> [BFD-477] Allow pipeline instance to query EFS and AZ's

ops/terraform/modules/resources/efs_alarms/main.tf, ops/terraform/modules/resources/efs_alarms/variables.tf
As part of the EFT EFS work, we need to configure Cloud Watch alarms for EFS file systems.
This PR adds a terraform module (heavily copied from BCDA) to do so.
- [BFD-477](https://jira.cms.gov/browse/BFD-477)
=> [BFD-477] TF module for EFS alarms

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/TransformerUtilsV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/TransformerUtils.java
Added instant to set lastupdated timestamps to after compare points of setlastupdated
Make sure it is in the correct timestamp format
Looks correct as the before checking.
- [BFD-727](https://jira.cms.gov/browse/BFD-727)
n/a
n/a
n/a
n/a
=> Added instant to set lastupdated timestamps to after compare points of setlastupdated

ops/ansible/playbooks-ccs/build_bfd-server.yml, ops/ansible/playbooks-ccs/launch_bfd-server.yml, ops/ansible/playbooks-ccs/vars/prod-sbx/group_vars/all/env_specific.yml, ops/ansible/playbooks-ccs/vars/prod/group_vars/all/env_specific.yml, ops/ansible/playbooks-ccs/vars/test/group_vars/all/env_specific.yml, ops/terraform/modules/stateless/main.tf
This PR is an attempt to "right-size" our application server ec2 instance sizes to better handle our current and future workloads. 
This involves migrating our application servers from memory optimized instance classes to compute optimized instance classes, and ups the number of virtual CPU's from 4 to 16 (for upper environments). Which gives prod and prod-sbx 16 cores and 32 GiB of memory (up from 4 cores and 16GiB of memory).
Specifically, this PR:
- Moves prod and prod-sbx to c5.4xlarge instance class from m5.xlarge.
- Moves test to c5.xlarge from m5.xlarge (keeping test at 4 cores to save $)
- Dynamically sets the max db connections to the Oracle recommended 10 per core.
- [BFD-735](https://jira.cms.gov/browse/BFD-735)
=> [BFD-735] Right-size app server instance sizes.

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/CoverageTransformerV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/CoverageTransformer.java
BFD-697 - errors related to Evidation/Heartline.. Checking for null in the beneficiary monthly table.  After looking into the incident, it looks like CCW is sending over nulls for partdcontract numbers.  This eliminates the bug that was found by BB2.
NOTE - When this ticket is pulled in, time-box the ticket and assign a date that the investigation should be completed by 
Background: 
BB2 has experienced a high number of errors stemming from Evidation on two occasions:   
Tuesday March 16 around 7:40PM EDT. 
Wednesday, March 17 around 11:45AM EDT
The team has also correlated these errors back to issues reported by Heartline in February.  Findings were:
Primarily all errors from 1 bene (FHIR ID can be provided in Keybase), but there are others within Evidation (total 77)
2 with coverage …
=> Cbrune/BFD-697 - errors related to Evidation/Heartline

apps/bfd-model/bfd-model-rif/pom.xml, apps/bfd-model/bfd-model-rif/src/main/java/gov/cms/bfd/model/rif/schema/DatabaseSchemaManager.java, apps/bfd-model/bfd-model-rif/src/main/java/gov/cms/bfd/model/rif/schema/DatabaseTestHelper.java, apps/bfd-model/pom.xml, apps/pom.xml
This PR reverts changes made in #541. The deployed pipeline application is encountering an error with Flyway that will need to be troubleshot separately.
=> Revert "Upgraded HSQL and Flyway. (#541)"

ops/terraform/env/prod-sbx/stateful/main.tf, ops/terraform/env/prod-sbx/stateful/variables.tf, ops/terraform/env/prod/stateful/main.tf, ops/terraform/env/prod/stateful/variables.tf, ops/terraform/env/test/stateful/main.tf, ops/terraform/env/test/stateful/variables.tf
Updates infra to use terraform variables for opt out config (instead of hard coded values).
- [BFD-821](https://jira.cms.gov/browse/BFD-821)
=> [BFD-821] Use terraform vars for opt out config

ops/terraform/modules/stateless/main.tf
Simple fix to grab our account number dynamically instead of using hard coded value.
=> [BFD-821] Use dynamic account number in terraform

ops/terraform/modules/resources/kms/main.tf
Refactored module resource to use IAM groups and policies.
As I am not seeing this module used anywhere, I went ahead and manually created the kms-key-admins group with the kms-key-admin policy attached.
- [BFD-821](https://jira.cms.gov/browse/BFD-821)
=> [BFD-821] Manage kms key using iam groups

ops/terraform/env/global/s3/main.tf, ops/terraform/env/global/s3/variables.tf
Moves account numbers to variables. 
=> [BFD-821] move acct numbers to vars

ops/terraform/modules/mgmt_stateless/main.tf, ops/terraform/modules/mgmt_stateless/variables.tf
Removes an unneeded variable by getting the subnet dynamically.
=> [BFD-821] Remove unnecessary variable

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4ExplanationOfBenefitResourceProvider.java
Changed .Equals from == comparsion
Verify its the correct way to see if a string is equal
Change makes sense and fixes checking by string equals
- [BFD-892](https://jira.cms.gov/browse/BFD-892)
N/A
N/A
N/A
N/A
N/A
=> BFD-892 - String comparsion of .equals instead of ==

README.md, contributing/create-db.sh, contributing/fetch.sh
Create a new script to dockerize a postgres 12 database and load the latest synthetic data changes. Updates the README and RIF file fetch script.
Confirm being able to locally create a docker container, loaded with synthetic data in postgres 12 with the updated instructions in the README.
Do the changes to the fetch.sh and create-db.sh scripts reflect best practices and fit our needs for automating database creation and data loading?
- [BFD-710](https://jira.cms.gov/browse/BFD-710)
=> [BFD-710] Build and Publish a Postgres Container with Synthetic Data Loaded

apps/pom.xml
Update logback-classic to >= 1.2.0 due to security finding by dependabot. More details here: https://github.com/advisories/GHSA-vmfg-rjjm-rjrj
Do things still work? 
Did I miss any instances of logback-classic?
None
- [BFD-926](https://jira.cms.gov/browse/BFD-926)
=> BFD-926] Update logback-classic in response to security

ops/terraform/modules/resources/bfd_pipeline/variables.tf, ops/terraform/modules/stateless/main.tf
This PR reconciles some VPC peering changes in our terraform.
- [BFD-931](https://jira.cms.gov/browse/BFD-931)
=> [BFD-931] Reconcile vpc peerings in terraform

apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/AppConfiguration.java, apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/PipelineApplication.java, apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/PipelineManager.java, apps/bfd-pipeline/bfd-pipeline-app/src/test/java/gov/cms/bfd/pipeline/app/AppConfigurationTestIT.java, apps/bfd-pipeline/bfd-pipeline-app/src/test/java/gov/cms/bfd/pipeline/app/PipelineApplicationIT.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/load/LoadAppOptions.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoader.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoaderTestUtils.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoaderIT.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoaderTest.java, apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/DatabaseOptions.java, apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/databaseschema/DatabaseSchemaUpdateJob.java, apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/jobs/store/PipelineJobRecordStore.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/ServerTestUtils.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/R4ExplanationOfBenefitResourceProviderIT.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/ExplanationOfBenefitResourceProviderIT.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/LoadedFilterManagerIT.java
Fixes the exit-on-error issue that caused us to revert the changes initially. Also ensures that job failures are logged appropriately.
1. Does this fix the intended issues?
1. Does this code look okay?
(see above)
This PR has no known security implications.
=> BFD-897: Fix BFD Pipeline's init errors and job failure handling

apps/pom.xml
In many cases, we were not getting **any** stack traces, line numbers,
etc.
If it doesn't break the GH Actions build, let's ship it ASAP.
(see above)
This PR has no security implications.
=> BFD-897: Get Full Stack Traces from Surefire and Failsafe

apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/PipelineManager.java, apps/bfd-pipeline/bfd-pipeline-app/src/test/java/gov/cms/bfd/pipeline/app/PipelineApplicationIT.java, apps/bfd-pipeline/bfd-pipeline-app/src/test/java/gov/cms/bfd/pipeline/app/PipelineManagerIT.java, apps/bfd-pipeline/bfd-pipeline-app/src/test/resources/logback-test.xml, apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/jobs/store/PipelineJobRecordStore.java
This PR fixes PipelineApplicationIT.noRifData test case.
It also adds more logging for the PipelineManagerIT test case that's failing.
If the build passes in GH Actions, let's push it.
N/A
There are no security implications for this PR.
=> BFD-897: Fix and diagnose unstable Jenkins builds

ops/ansible/playbooks-ccs/host_vars/builds.bfd-mgmt.cmscloud.local/000_cross_env_vars.yml
BFD-897
This symlink just pointed directly at itself, and so contained no actual content. I have no clue why it was created in the first place, but... it couldn't have been doing anything useful, right?
I've seen all sorts of things get upset about this and fail. The latest is the `actions/upload-artifact` task for GH Actions.
1. Does anyone have a good reason as to why this was there and whether or not it's needed? If not, let's yank it and see what happens.
(see above)
This PR has no known security implications.
=> BFD-897: Remove 000_cross_env_vars.yml symlink loop

apps/bfd-model/bfd-model-codegen/src/main/java/gov/cms/bfd/model/codegen/RifLayoutsProcessor.java, apps/bfd-pipeline/bfd-pipeline-app/src/main/resources/logback.xml, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoader.java, apps/bfd-server/bfd-server-launcher/src/main/resources/logback.xml, apps/bfd-server/bfd-server-war/src/main/config/server-start.sh, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4CoverageResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/CoverageResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProvider.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProviderIT.java
=> BFD-826: Fix Patient Search by Part D Contract ID

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProvider.java
Just does what it says on the tin. Should help determine where Java app time is being spent.
1. Anything else worth adding tracing to?
(see above)
- [BFD-826](https://jira.cms.gov/browse/BFD-826)
No security implications.
=> BFD-826: Add tracing to Patient search by Part D contract

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProvider.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProviderIT.java
At least for a couple of spot checks, this greatly improves the DB query plan, which makes sense as it's one of two large-row-count joins that the query had.
We may be able to remove other joins as well, but I want to make changes like this one step at a time, so we can keep track of what's actually impacting perforance, if anything.
1. Does this pass our tests? If so, I think we should merge and deploy it for testing in prod.
(see above)
- [BFD-826](https://jira.cms.gov/browse/BFD-826)
This PR should not have any security implications.
=> BFD-826: Remove unneeded join for HICN history

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProvider.java
I'm honestly not even sure how this join landed in there, anyways, because I thought we'd tested it without it in the earlier big refactor. Apparently not, though, because everything works just fine without it.
1. Do the tests still pass? If so, I'd suggest merging it.
2. What do you want to be when you grow up?
(see above)
- [BFD-826](https://jira.cms.gov/browse/BFD-826)
This PR does not have any security implications.
=> BFD-826: Remove unneeded join to bene monthly table

ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2
Fixes startup script bug
- [BFD-907](https://jira.cms.gov/browse/BFD-907)
=> [BFD-907] fix starttup bug

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProvider.java
On larger contract-year-months, this was spending a minute or three on the aggregate computation -- generally when there were millions of results. From some spot testing, a simpler `count(*)` query is much faster.
1. Does this still pass our tests?
2. Is this just running a `count(*)`?
* Verified this on a Zoom with folks.
What superpower would you want: flying or invisibility?
- [BFD-1065](https://jira.cms.gov/browse/BFD-1065)
This PR has no security implications.
=> BFD-1065: Simplify Part D contract-year-month count DB query

.github/CODEOWNERS
This PR adds @christrotteradhoc to CODEOWNERS.
=> Add Chris Trotter to codeowners

ops/ansible/roles/bfd-pipeline/tasks/eft_efs.yml
This PR stops the pipeline instances from automatically trying to mount the EFT EFS file systems on boot, but leaves the ability for us to manually mount the file system to help with testing. This is for a few reasons:
1. Originally, we had planned to do all of the EFT EFS workflow on the ETL pipeline server (ConnectDirect, EFS, etc), and that may no longer be the case. In fact, we will likely end up runing this on a dedicated EFT EFS instance.
2. I have since renamed BCDA's EFS module not thinking about the auto mounting. This is causing the boot to hang a bit, which is triggering an alert and page.
3. We will be refactoring much of the work that was done to get EFS working on FIPS enabled RHEL 7 once we migrate to Amazon Linux 2.
=> [BFD-477] Do not automatically mount partner EFS on ETL

apps/bfd-model/bfd-model-rif-samples/src/main/java/gov/cms/bfd/model/rif/samples/StaticRifResource.java, apps/bfd-model/bfd-model-rif-samples/src/main/java/gov/cms/bfd/model/rif/samples/StaticRifResourceGroup.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoaderIT.java
Added IT test for synthea loading rif files locally
Look at the IT test and it accomplishes loading rif files locally.
Make sure the code looks correct
- [BFD-908](https://jira.cms.gov/browse/BFD-908)
Load synthea data locally
n/a
n/a
n/a
n/a
=> BFD-908 - SYnthea local IT tests for loading data locally

.github/CODEOWNERS
This PR removes Ryan as a code owner as he is no longer on the project.
- [BFD-1177](https://jira.cms.gov/browse/BFD-1177)
None (other than the obvious)
=> [BFD-1177] Update CODEOWNERS

ops/ansible/playbooks-ccs/roles/stunnel/defaults/main.yml
The stunnel library is a manually compiled dependency of the current EFT EFS architecture due to FIPS/rhel 7. During builds, we download the source from stunnel.org (ie https://www.stunnel.org/downloads/stunnel-5.59.tar.gz) and compile. Problem is, when stunnel releases a new version, they delete the previous so it breaks our builds.
Ideally, we would download, verify, and cache the stunnel source, but having this is a temporary problem that will go away once we migrate to Amazon Linux. Until that happens, having new versions of stunnel break builds, while a pain, ensures we have the latest secure version.
- [BFD-1187](https://jira.cms.gov/browse/BFD-1187)
=> [BFD-1187] Update stunnel version to 5.60

ops/ansible/playbooks-ccs/roles/stunnel/defaults/main.yml, ops/ansible/playbooks-ccs/roles/stunnel/tasks/main.yml
Forgot to update the checksum in https://github.com/CMSgov/beneficiary-fhir-data/pull/738 
This PR updates the checksum and makes it a variable so it will not be missed next time.
=> [BFD-1187] Update stunnel version and checksum to 5.60

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/PartDEventTransformerV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/TransformerUtilsV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PartDEventTransformer.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/TransformerUtils.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/PartDEventTransformerV2Test.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/PartDEventTransformerTest.java, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v1/eobByPatientIdAll.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v1/eobByPatientIdPaged.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v1/eobReadPde.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobByPatientIdAll.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobByPatientIdPaged.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobReadPde.json
Create mapping between billablePeriod and service date for Part D Events in v1 and v2 
Do the Part D Events with a billablePeriod map and test properly?
Make sure code and documentation is sound
- [BFD-1170](https://jira.cms.gov/browse/BFD-1170)
=> [BFD-1170] Map EOB.billablePeriod for Part D Events in both V1 and V2

.github/workflows/ci-java.yml, .github/workflows/ci-terraform.yml
[BFD-1161](https://jira.cms.gov/browse/BFD-1161)
As a BFD engineer, I want application CI to only run against app code, in order to decrease the time it takes for CI to run. Same for ops code.
---
Currently, any workflow check required in a branch protection rule **must** run in order to merge a PR. But, this means, for example, we always have to run java checks even though no changes to java code were made. This also means we cannot use the simple workflow filter syntax like this:
```
on:
pull_request:
paths:
- apps/
```
As the above would only run the workflow IF files in `apps/` were changed. Thus, the required branch protection check would not run and we could not merge.
**This PR** always run the workflows; But, will skip (_skipping_ …
=> BFD-1161: always run java and terraform workflows but skip as needed

apps/bfd-server/bfd-server-war/src/main/resources/samhsa-related-codes/codes-cpt.csv, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/SamhsaMatcherR4FromClaimTransformerV2Test.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/SamhsaMatcherFromClaimTransformerTest.java, apps/bfd-server/dev/api-changelog.md
[BFD-1338](https://jira.cms.gov/browse/BFD-1338)
As a peering partner, I want the list of SAMHSA codes that are filtered out to be updated for 2021, in order to remain compliant with policy that prevents substance abuse data to be shared.
---
Added three CPT codes for SAMHSA filtering.
* Ensure any locations where SAMHSA codes need to be updated have been changed …
=> BFD-1338: Update CPT Codes for SAMHSA filtering

.github/pull_request_template.md
[BFD-1200](https://jira.cms.gov/browse/BFD-123456)
FIXES: Update github pull request template.
---
Escapes Jason's github username in our PR template so they are not automatically added as a mentioned/participant in all PR's.
Note: You cannot simply escape @ usernames with a slash as they are processed post rendering. Use the following instead:
```markdown
**@StewGoin is a secret squirrel**
``` 
This displays properly without linking:
**@StewGoin is a secret squirrel**
* If the answer to any of the questions below is **Yes**, then …
=> BFD-1200: escape StewGoin in markdown so they are not automatically tagged in PRs

apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/PipelineApplicationState.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/SpringConfiguration.java
[BFD-1391](https://jira.cms.gov/browse/BFD-1391)
---
Disables hibernate schema validation temporarily so that a deployment to production may proceed. This will be reverted in a PR in the near future.
* …
=> BFD-1391 Disable hibernate schema validation

apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/PipelineApplicationState.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/SpringConfiguration.java
This reverts commit 38b70b4a87338079c469742e7703c2a864096faf.
[BFD-1391](https://jira.cms.gov/browse/BFD-1391)
---
Re-enables hibernate schema validation now that the deployments are complete for the migration that prompted schema validation to be turned off.
* Does …
=> BFD-1391 Re-enable hibernate schema validation"

ops/ccs-ops-misc/scripts/bfd-monthly-inventory
As an engineer, running monthly inventories should be automated as much as possible.
---
Simple bugfix to set the default inventory directory.
* Does …
=> BFD-1349: Fix default inventory directory

apps/bfd-server-test-perf/pom.xml
[BFD-1419](https://jira.cms.gov/browse/BFD-1419)
Remove log4j from BFD dependencies
---
Removes the single log4j dependency from the BFD maven build. This dependency is in the bfd-server-test-perf module which is an unused performance test that is set to be removed from BFD. Out of an abundance of caution this is being removed since there is a new CVE for log4j: CVE-2021-44228. This necessitated bringing in the slf4j adapter for log4j since the perf test uses log4j logging classes. No attempt was made to bring in a logger implementation for slf4 in this module since this test is slated to be replaced so if this is ever reinstated that will need to be done.
* Verify all …
=> BFD-1419 Remove log4j from BFD dependencies

ops/ansible/roles/bfd-server/defaults/main.yml, ops/ansible/roles/bfd-server/tasks/install.yml
As an engineer, I need to ensure we are using the latest New Relic agent that is not vulnerable to log4j jindi exploits.
---
Bump New Relic agent to version 7.4.1 to mitigate log4j vulnerability.
* Does this PR …
=> BFD-1420: bump-new-relic-agent-to-7.4.1

apps/bfd-pipeline/bfd-pipeline-rda-grpc/pom.xml, apps/bfd-server/pom.xml, apps/pom.xml, ops/ansible/roles/bfd-server/defaults/main.yml
[BFD-1431](https://jira.cms.gov/browse/BFD-1431)
Update New Relic Java agent to 7.4.3.
Update Logback to 1.2.8.
---
Resolve security vulnerabilities:
Update New Relic Java agent to 7.4.3.
Update Logback to 1.2.8.
* Does this PR modify or invalidate any of our security …
=> BFD-1431 - Upgrade: Logback to 1.2.8 ; New Relic Java Agent to 7.4.3

apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V37__preadj_rda_0_5_table_updates.sql
[PACA-265](https://jira.cms.gov/browse/PACA-265)
paca-265 upgrades the RDA pipeline job to consume RDA API 0.5 messages,
this PR applies the necessary DB schema changes to be compliant with the
changes coming in #858
---
- Adds a new database migration script V37__preadj_rda_0_5_table_updates.sql.
* Does this PR add …
=> PACA-265: adding pre-migrations needed for RDA API 0.5 changes

insights/terraform/projects/bb2/modules/glue_crawler/main.tf
[BB2-1017](https://jira.cms.gov/browse/BB2-1017)
Update the BB2 Glue Crawler configuration to match manual changes made on AWS console.
---
Update Glue Crawler config for crawler_output and schema_change_policy. Applied on all environments. …
=> [ BB2-1017 ] Update glue crawler TF config for BB2 insights

apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/PipelineApplicationState.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/SpringConfiguration.java
[PACA-265](https://jira.cms.gov/browse/PACA-265)
After the schema changes for PACA-265 have been applied, we can safely
re-enable hibernate validation
---
* enables hibernate validation
* Does this PR store or transmit data that was …
=> PACA-265: enabling hibernate schema validation for PACA-265

ops/terraform/modules/resources/lb/main.tf, ops/terraform/modules/resources/lb/variables.tf, ops/terraform/modules/stateless/main.tf
[BFD-1474](https://jira.cms.gov/browse/BFD-1474)
---
This PR updates our prod and test load balancer security groups to allow HTTPS (443) for our VPN users. It obtains the VPN subnets by querying a CMS managed prefix list, so the rules will automatically be updated during deploys if the cidr blocks were to change.
* …
=> BFD-1474: allow https from vpn to prod and test load balancers

ops/terraform/modules/resources/lb/main.tf, ops/terraform/modules/stateless/main.tf
[BFD-1474](https://jira.cms.gov/browse/BFD-1474)
BUGFIX for https://github.com/CMSgov/beneficiary-fhir-data/pull/890
---
This is a bugfix for https://github.com/CMSgov/beneficiary-fhir-data/pull/890 which has already been merged.
That PR failed when deploying to prod-sbx as it could not parse an empty prefix list id in prod-sbx's static ingress block. This PR uses a dynamic ingress block instead.
* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment …
=> BFD-1474: Dynamic ingress blocks for prefix list

ops/ansible/roles/bfd-server/defaults/main.yml
[BFD-1431](https://jira.cms.gov/browse/BFD-1431)
Update new relic java agent to 7.5.0
---
Updates new relic java agent to 7.5.0 …
=> BFD-1431 - Update new relic java agent to 7.5.0

apps/bfd-server/bfd-server-war/pom.xml, apps/pom.xml
[BFD-1475](https://jira.cms.gov/browse/BFD-1475)
Remediate SNYK finding of vulnerable jackson-databind transitive dependency.
---
There are two problems – first the zjsonpatch dependency is not scoped as 'test' and it should be since it is only used in the unit and integration tests and secondly even once it is marked as a test dependency it still manages to bring in the vulnerable jackson-databind dependency because other compile dependencies also transitively depend on jackson-databind but have a deeper hierarchy (so the version used by zjsonpatch is the one that ultimately makes it into the war file). Adding an exclusion to the zjsonpatch dependency for jackson libraries allows jackson-databind to be resolved from the metrics-servlets …
=> BFD-1475: Resolve SNYK jackson-databind transitive dependency issues

apps/bfd-pipeline/bfd-pipeline-rda-grpc-server/pom.xml, apps/bfd-pipeline/bfd-pipeline-rda-grpc/pom.xml, apps/bfd-server/bfd-server-war/pom.xml, apps/bfd-shared-utils/pom.xml, apps/pom.xml
[BFD-1437](https://jira.cms.gov/browse/BFD-1437)
As a BFD engineer, I want Mockito upgraded, so the BFD's software dependencies are up to date.
---
Updates the mockito dependency to 4.2.0.
* Does this PR …
=> BFD-1437: Upgrade Mockito to 4.2.0

apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/test/java/gov/cms/bfd/pipeline/bridge/RDABridgeIT.java
[BFD-1436](https://jira.cms.gov/browse/BFD-1436)
Small followup/cleanup related to https://github.com/CMSgov/beneficiary-fhir-data/pull/895
---
Adjusts the RDABridgeIT test to check for no exceptions thrown instead of asserting the result of the transform.
* Does this …
=> BFD-1436: Add does not throw for RDA IT test

apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/server/S3BucketMessageSourceFactory.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/server/S3JsonMessageSource.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/server/S3BucketMessageSourceFactoryTest.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/server/S3JsonMessageSourceTest.java
[PACA-420](https://jira.cms.gov/browse/PACA-420)
The mock server can currently load NDJSON files as input, it would be convenient if the server could also load gzipped NDJSON files, as it would be quicker for us to transfer compressed files.
---
When scanning NDJSON files from an S3 bucket the mock server now recognizes file names ending in a `.gz` suffix and automatically inserts a `GzipInputStream` to decompress the file data on the fly.
* If the answer to any of the questions below is **Yes**, then **you must** supply a link to …
=> PACA-420: add S3 gzipped file support to mock server

apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/R4PatientResourceProviderIT.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProviderIT.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/utils/EndpointJsonResponseComparatorV2IT.java, apps/pom.xml
[BFD-1436](https://jira.cms.gov/browse/BFD-1436)
Fixes an issue where some IT tests were being skipped due to an old version of failsafe plugin.
---
Small update to upgrade the failsafe plugin, as some IT tests were being skipped with the previous version after the Junit5 upgrade.
Also fixes a couple tests that had some errors that were obscured by the IT tests not running during the Junit5 Upgrade. …
=> BFD-1436: Upgrade failsafe plugin to allow all IT tests to run

apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/PipelineApplicationState.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/SpringConfiguration.java
[PACA-265](https://jira.cms.gov/browse/PACA-265)
---
Disabled hibernate validation in preparation for the deployment of PACA-265 changes which requires a flyway migration.
* Does this PR store or …
=> PACA-265: Disable hibernate validation for PACA-265

apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/PipelineApplicationState.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/SpringConfiguration.java
This reverts commit 54f1e114df9871e1dd79c4c561b6ea04a7779f88.
[PACA-265](https://jira.cms.gov/browse/PACA-265)
---
Re-enables hibernate validation now that PACA-265 DB migration and application changes have been deployed. …
=> PACA-265 : Re-enable hibernate validation for PACA-265 (#909)

.github/CODEOWNERS
[BFD-1511](https://jira.cms.gov/browse/BFD-1511)
Offboard JZ
---
Removes JZ from CODEOWNERS as part of offboarding.
* If …
=> BFD-1511: Remove JZ from codeowners

apps/bfd-model/bfd-model-codebook-extractor/src/main/java/gov/cms/bfd/model/codebook/model/Value.java, apps/bfd-model/bfd-model-codebook-extractor/src/main/java/gov/cms/bfd/model/codebook/model/ValueGroup.java, apps/bfd-model/bfd-model-codebook-extractor/src/main/java/gov/cms/bfd/model/codebook/model/Variable.java, apps/bfd-model/bfd-model-codegen/src/main/java/gov/cms/bfd/model/codegen/MappingSpec.java, apps/bfd-model/bfd-model-codegen/src/main/java/gov/cms/bfd/model/codegen/RifLayout.java, apps/bfd-model/bfd-model-codegen/src/main/java/gov/cms/bfd/model/codegen/RifLayoutProcessingException.java, apps/bfd-model/bfd-model-rif/src/main/java/gov/cms/bfd/model/rif/RifRecordEvent.java, apps/bfd-model/bfd-model-rif/src/main/java/gov/cms/bfd/model/rif/schema/DatabaseSchemaManager.java, apps/bfd-model/bfd-model-rif/src/main/java/gov/cms/bfd/model/rif/schema/DatabaseTestUtils.java, apps/pom.xml
[BFD-1514](https://jira.cms.gov/browse/BFD-1514)
As a BFD engineer I want there to be no javadoc errors in the build log for the Model module so that the build log is easier to read and real errors can be more easily noticed.
---
- Fixes missing/incorrect javadocs in the Model module (for any that were being picked up as warnings in the build)
- Add a configuration for the javadoc plugin to not detectJavaApiLink (this setting causes errors due to a bug in openJdk java 11 + maven)
- Update the javadoc plugin to the most recent version
* Ensure javadocs added do not need any …
=> BFD-1514: Clean up javadoc errors in Model module

apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/AppConfiguration.java, apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/PipelineManager.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/extract/s3/TaskExecutor.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/extract/s3/task/ManifestEntryDownloadTask.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/load/CcwRifLoadTestUtils.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc-server/src/main/java/gov/cms/bfd/pipeline/rda/grpc/server/RdaServerApp.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/ProcessingException.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/RdaLoadOptions.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/server/EmptyMessageSource.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/server/JsonMessageSource.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/server/MessageSource.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/server/RandomMcsClaimGenerator.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/server/RdaServer.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/server/S3JsonMessageSource.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/server/S3JsonMessageSources.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/server/WrappedClaimSource.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/sink/concurrent/WriterThreadPool.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/sink/direct/AbstractClaimRdaSink.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/DataTransformer.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/GrpcRdaSource.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/GrpcStreamCaller.java, apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/IdHasher.java, apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/PipelineApplicationState.java, apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/PipelineTestUtils.java, apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/jobs/store/PipelineJobRecordStore.java, apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/s3/S3MinioConfig.java, apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/s3/SharedS3Utilities.java, apps/pom.xml
[BFD-1521](https://jira.cms.gov/browse/BFD-1521)
As a BFD engineer I want there to be no javadoc errors in the build log for the Pipeline module so that the build log is easier to read and real errors can be more easily noticed.
---
- Adds a package exclusion in the javadoc plugin configuration for most of the generated files so they don't get flagged for javadoc issues
- Fixes javadoc errors and warnings for the pipeline submodules
* Ensure javadoc corrections make sense
* If the answer to any of the questions below is **Yes**, …
=> BFD-1521: Fixing javadoc issues in Pipeline module

apps/bfd-shared-utils/src/main/java/gov/cms/bfd/sharedutils/config/ConfigLoader.java, apps/bfd-shared-utils/src/main/java/gov/cms/bfd/sharedutils/database/DatabaseUtils.java, apps/bfd-shared-utils/src/main/java/gov/cms/bfd/sharedutils/exceptions/BadCodeMonkeyException.java
[BFD-1523](https://jira.cms.gov/browse/BFD-1523)
As a BFD engineer I want there to be no javadoc errors in the build log for the bfd-utils module so that the build log is easier to read and real errors can be more easily noticed.
---
- Fixes javadoc warnings in bfd-utils module
* Does this PR add any new software …
=> BFD-1523: Fixing javadoc warnings in shared utils module

apps/bfd-model/bfd-model-rif/src/main/resources/db/scripts/Beneficiaries_with_duplicate_hicns.sql, apps/bfd-model/bfd-model-rif/src/main/resources/db/scripts/Beneficiary_and_claim_statistics.sql, apps/bfd-model/bfd-model-rif/src/main/resources/db/scripts/Create_all_constraints.sql, apps/bfd-model/bfd-model-rif/src/main/resources/db/scripts/DateThrough_dateFrom_greater_than_lastupdated.sql, apps/bfd-model/bfd-model-rif/src/main/resources/db/scripts/Delete_Synthetic_Negative_Beneficiaries_With_PositiveClaimIds.sql, apps/bfd-model/bfd-model-rif/src/main/resources/db/scripts/Drop_all_constraints.sql, apps/bfd-model/bfd-model-rif/src/main/resources/db/scripts/Select_id_ranges.sql
[BFD-1515](https://jira.cms.gov/browse/BFD-1515)
The BFD db schema has changed table and table column names; we have several SQL scripts that get used periodically to discover duplicate records, to count bene(s) that fall under some criteria, etc; These scripts are located in the
`bfd-model/bfd-model-rif/src/main/resources/db/scripts`
This ticket identifies the following scripts that should be modified to make them useable under the modified schema:
- Beneficiaries_with_duplicate_hicns.sql
- Beneficiary_and_claim_statistics.sql
- Create_all_constraints.sql
- DateThrough_dateFrom_greater_than_lastupdated.sql
- Delete_Synthetic_Negative_Beneficiaries_With_PositiveClaimIds.sql
- Drop_all_constraints.sql
- Select_id_ranges.sql
---
Modifies SQL …
=> BFD-1515: update db scripts to use new table and column names

ops/ansible/playbooks-ccs/vars/prod-sbx/group_vars/all/env_specific.yml
[PACA-452](https://jira.cms.gov/browse/PACA-452)
Given that end-users will need to access partially adjudicated claims data in the SBX environment, the RDA mock will need to be enabled to read claims data from the S3 bucket.
---
Adds the necessary flag to enable the RDA API ETL job to run in sandbox environment.
* Does …
=> PACA-452: Enables RDA API ETL pipeline in sandbox.

ops/jenkins/bfd-cert-checker/Jenkinsfile
[BFD-1506](https://jira.cms.gov/browse/BFD-1506)
As a BFD engineer, I want to configure alerts for certificate renewal in Jenkins so I am alerted when certificates need to be renewed.
---
Bugfix and refactor for recently merged https://github.com/CMSgov/beneficiary-fhir-data/pull/957 that fails to run
- Adds missing '}' and switches to 4 space tabs
- Configures pipeline to test each environment's cert in stages (test, prod-sbx, and prod).
* If the answer to any of the questions below is **Yes**, then **you must** supply a link to …
=> BFD-1506: cert-checker pipeline bugfix and refactor

apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V57__rda_message_metadata.sql
[PACA-238](https://jira.cms.gov/browse/PACA-238)
As an engineer, I want to be able to analyze RDA message frequency.
**THIS PR MUST BE MERGED BEFORE [PR 908](https://github.com/CMSgov/beneficiary-fhir-data/pull/908).**
This PR contains a Flyway migration script to create the new table and sequence required by the PACA-238 PR.  Hibernate validation is unaffected by this PR since Hibernate ignores tables it doesn't have entities for when performing validation.
---
- Adds a new table named `RdaApiClaimMessageMetaData` to the `pre_adj` schema to hold certain meta data about each message received from the RDA API.
* Verify all PR security questions and checklists have been …
=> PACA-238: Migration only PR for PACA-238.  Merge before PR 908.

apps/bfd-server/bfd-server-launcher/src/main/java/gov/cms/bfd/server/launcher/DataServerLauncherApp.java
[BFD-1564](https://jira.cms.gov/browse/BFD-1564)
The access.log format changed slightly during the Jetty 10 upgrade and that change has invalidated some of the cloudwatch alerting. The current access.log is showing this:
127.0.0.1 - "CN=client-local-dev" [[25/Feb/2022:22:56:42 +0000]] "GET / HTTP/1.1" "?null" 200 26 32000 - - [-] - "-" - "-" - "-" -
but the double brackets are causing pattern matching for alerts to behave incorrectly. It should look like this:
127.0.0.1 - "CN=client-local-dev" [25/Feb/2022:22:56:42 +0000] "GET / HTTP/1.1" "?null" 200 26 32000 - - [-] - "-" - "-" - "-" -
---
Fixes the access.log
* Verify all PR security questions and checklists have …
=> BFD-1564 - fix access.log pattern

apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V58__Add_rif_records_skipped_Table.sql
[BFD-1566](https://jira.cms.gov/browse/BFD-1566)
In some of the CCW data some benes were coming in with late 2021 enrollment data, which was overwriting newer 2022 entries. This adds the migration for the table which will hold the skipped records, to be implemented in #980 .
---
Adds the migration script for a new table that will hold skipped records. …
=> BFD-1566: Add migration script for new table

.github/workflows/ci-java.yml, .github/workflows/ci-terraform.yml
[BFD-1581](https://jira.cms.gov/browse/BFD-1581)
As an engineer, it's vital that the appropriate github actions get triggered when files are added, deleted, modified, moved, or had file mode changes (made executable, etc).
Currently, actions are not triggered on file deletions because the `git diff-filter` is set to `ACMRT` instead of `ACMRTD`. 
---
Replace me. …
=> BFD-1581: Trigger github workflows on file deletions

apps/bfd-db-migrator/README.md, apps/bfd-db-migrator/pom.xml, apps/bfd-db-migrator/src/main/assembly/bin/bfd-db-migrator.sh, apps/bfd-db-migrator/src/main/assembly/zip.xml, apps/bfd-db-migrator/src/main/java/gov/cms/bfd/migrator/app/MigratorApp.java, apps/bfd-db-migrator/src/main/java/gov/cms/bfd/migrator/app/package-info.java, apps/bfd-db-migrator/src/main/resources/logback.xml, apps/pom.xml
[BFD-1554](https://jira.cms.gov/browse/BFD-1554)
Define a placeholder or _application shell_ for the proposed `bfd-db-migrator` service described in RFC 0011 (pending review of #956).
---
This PR introduces a new `bfd-db-migrator` Java application that will serve as a placeholder for the functionality proposed in RFC 0011 (pending review in #956). This minimally defines the `gov.cms.bfd.migrator.app` package with a functional main that produces notional NDJSON-formatted logs available for targeting by centralized log aggregation mechanisms (addressed in a related line of effort under [BFD-1543](https://jira.cms.gov/browse/BFD-1543)). 
* This satisfies my needs for getting the ansible and packer definitions together, but _should_ it already …
=> BFD-1554 Introduce bfd-db-migrator app Shell

.github/workflows/ci-base-container-image.yml, ops/Dockerfile
[BFD-1568](https://jira.cms.gov/browse/BFD-1568)
Introduce bfd-ansible container image
---
This PR introduces a Dockerfile and CI workflow that builds a base container image, `bfd-ansible`, similar to the images that are currently built on-demand as part of the `ci-ansible.yml` workflow, and stores it in the CMSgov artifact repository/container registry–[see the non-trunk builds here](https://github.com/CMSgov/beneficiary-fhir-data/pkgs/container/bfd-ansible).
There are no updates to existing functionality as part of this request and newly-introduced artifacts are not yet in use. The CI here only operates on the protected `master` branch when there are changes to one or both of `.github/workflows/ci-base-container-image.yml` or …
=> BFD-1568 Introduce bfd-ansible container image

apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoader.java
[BFD-1586](https://jira.cms.gov/browse/BFD-1586)
The load Ran into a bunch of these errors on Sunday:
```2022-03-06T18:13:52.649Z prod [pool-5-thread-400] WARN  g.c.b.p.ccw.rif.load.RifLoader - Failed to load 'SNF' record.
java.lang.IllegalArgumentException: Cannot INSERT beneficiary with non-2022 enrollment year; investigate this data load.
at gov.cms.bfd.pipeline.ccw.rif.load.RifLoader.process(RifLoader.java:450)
at gov.cms.bfd.pipeline.ccw.rif.load.RifLoader.lambda$processAsync$2(RifLoader.java:353)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:11 …
```
=> BFD-1586: Fix Filtering Logic for Non-Bene Records

apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/load/CcwRifLoadTestUtils.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoader.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoaderIT.java
[BFD-1587](https://jira.cms.gov/browse/BFD-1587)
See [BFD-1586](https://jira.cms.gov/browse/BFD-1586) for the problem and fix. This ticket represents the work to add test coverage for that fix since it was deployed with only a code review in the interest of allowing the load to continue.
Note this was developed in the following fashion to ensure the code refactor did not break anything:
- Tests written to validate initial fix worked
- Fix removed, ensured new tests broke (3 tests break when the bene type check added in the 1586 fix is removed)
- Refactored filter code
- Reran tests and ensured everything passed as before
---
- Adds test coverage for CCW non-2022 filtering to cover a missed case for non-bene inserts.
- Cleans up the filtering …
=> BFD-1587: Add more tests for bene filtering and clean up confusing logic

apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/CcwRifLoadOptions.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/load/LoadAppOptions.java
BFD-1590
[BFD-1590](https://jira.cms.gov/browse/BFD-1590)
The missing `toString()`s made it very hard to figure out what the app config is/was at runtime, which makes debugging issues in prod very hard.
---
Just what it says on the tin. …
=> BFD-1590: Fix Logging of Configuration at Pipeline Launch

ops/terraform/modules/stateless/main.tf
[BFD-1584](https://jira.cms.gov/browse/BFD-1584)
Address CloudWatch SLO Paging
---
The threshold was developed with miliseconds in mind, but it's actually emitting microseconds. As a result, the latency threshold is broken each time request duration is greater than 0.006 seconds, which is effectively every request.
* …
=> BFD-1548 Expect microseconds in latency threshold

ops/Dockerfile
[BFD-1571](https://jira.cms.gov/browse/BFD-1571)
Use amazonlinux base image
---
Toward making the tests more faithful and more production-like, it would make sense to run them inside an amazonlinux2 container, instead of an aging centos7 container image. I've also invoked the campsite rule to tidy up the Dockerfile a bit, notably dropping the sshd and at removing the user with passwordless sudo. Other suggestions towards a simpler Dockerfile are welcome. 
* If the answer to any of the questions below is **Yes**, then **you must** …
=> BFD-1571 Use amazonlinux base image

ops/ansible/roles/bfd-db-migrator/tasks/migrator.yml, ops/ansible/roles/bfd-db-migrator/templates/bfd-db-migrator-service.sh.j2, ops/ansible/roles/bfd-db-migrator/test/inventory.docker.yaml, ops/ansible/roles/bfd-db-migrator/test/post-test.sh, ops/ansible/roles/bfd-db-migrator/test/run-tests.sh, ops/ansible/roles/bfd-db-migrator/test/test_basic.yml
[BFD-1624](https://jira.cms.gov/browse/BFD-1624)
Enhance bfd-db-migrator ansible role
---
- accommodates the bfd-db-migrator's new requirements for defined and non-empty `DATABASE_USERNAME` ,`DATABASE_PASSWORD` in our GitHub Actions-based ansible Tests
- Provides templated variables for newrelic environment variables
- extends the `run-tests.sh` script to allow users to keep containers running for local debugging purposes
- tamps down on ansible warnings using the more modern/efficient `pkg` array syntax rather than the deprecated looping `with_items` array syntax. …
=> BFD-1624 Enhance bfd-db-migrator ansible role

ops/ansible/roles/bfd-db-migrator/templates/bfd-db-migrator-service.sh.j2, ops/ansible/roles/bfd-db-migrator/test/run-tests.sh, ops/ansible/roles/bfd-db-migrator/test/test.sh
[BFD-1629](https://jira.cms.gov/browse/BFD-1629)
bfd-db-migrator role requires explicit db max pool size
---
I made the mistake of selecting the automatic merge after required checks passed, while non-required checks ended up failing. There will be a separate line of effort to adjust the testing here, but for now, this solves the immediate need: fix broken bfd-db-migrator role testing. Here's the summary of changes:
* prefers the default max pool size set in the bfd-db-migrator java application
* uses `db_migrator_db_max_pool_size` as an override when defined as a non-empty string
* tidies the templated service script's white space controls for newrelic variables
* extends bfd-db-migrator role test harness to include the `-e` flag, akin to …
=> BFD-1629 Fix bfd-db-migrator role max pool size

.github/CODEOWNERS
Updates to the codeowners file to expand upon the directories that the PACA team is responsible for, this includes
- `apps/bfd-pipeline/bfd-pipeline-rda-grpc`
- `apps/bfd-pipeline/bfd-pipeline-rda-grpc-server`
- `apps/bfd-pipeline/bfd-pipeline-rda-bridge`
- `apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/preadj`
- `apps/bfd-model/bfd-model-rda`
Also adding @KyRobbins to the cohort that is responsible for these directories
---
Updates the CODEWONERS with new rules for the PACA team
Double-checking the CODEOWNERS syntax rules …
=> expanding the codeowners dirs owned by the PACA team

apps/bfd-server/dev/api-changelog.md
[BFD-1446](https://jira.cms.gov/browse/BFD-1446)
Changing the change log for adding the focal field for v2 to match the change that was made.
---
Making changes to our api change log to show what has been done to add the focal field to v2
Verify the change log accurately maps the change made,
* Does this PR add any new …
=> [BFD-1446] - Change Log Api change for Focal field for v2

apps/bfd-server/dev/api-changelog.md
[BFD-1446](https://jira.cms.gov/browse/BFD-1446)
Fixes a couple of issues in the api-changelog.md:
- Formatting was broken due to a code block not being closed in BFD-1582
- Wording correction for BFD-1446
---
Makes corrections to the api-changelog.md.
* Does this PR …
=> BFD-1446 - Correct the wording for BFD-1446 changelog and fix formatting issue

apps/bfd-db-migrator/pom.xml, apps/bfd-model/bfd-model-codebook-extractor/src/main/java/gov/cms/bfd/model/codebook/model/CcwCodebookInterface.java, apps/bfd-model/bfd-model-codegen/src/main/java/gov/cms/bfd/model/codegen/RifLayoutsProcessor.java, apps/bfd-model/pom.xml, apps/bfd-pipeline/pom.xml, apps/bfd-server/pom.xml, apps/bfd-shared-utils/src/main/java/gov/cms/bfd/sharedutils/config/ConfigException.java, apps/bfd-shared-utils/src/main/java/gov/cms/bfd/sharedutils/config/ConfigLoader.java, apps/bfd-shared-utils/src/main/java/gov/cms/bfd/sharedutils/database/DatabaseUtils.java, apps/bfd-shared-utils/src/main/java/gov/cms/bfd/sharedutils/interfaces/ThrowingFunction.java, apps/checkstyle.xml, apps/pom.xml, docs/style/style-guide.md
[BFD-1671](https://jira.cms.gov/browse/BFD-1671)
As a BFD user I want the documentation of the java code to be consistent and clear so that I can more easily make changes and maintain the codebase.
---
- Added checkstyle to the build by adding a maven plugin, which will check enabled projects within BFD for proper javadoc styling (and that docs exist where they should)
- Fixed bfd-shared-utils to be in compliance with the new javadoc rules
- Added checkstyle.xml to the root of the apps folder which will be used to check all checkstyle-enabled projects
- Disabled checkstyle for projects other than shared-utils so checkstyle is not run on them until compliance is achieved (tech debt)
- Added a style guide to the BFD documentation which reviews …
=> BFD-1671: Add checkstyle and javadoc style guide

apps/bfd-pipeline/bfd-pipeline-rda-grpc/pom.xml
[PACA-555](https://jira.cms.gov/browse/PACA-555)
---
Resolves the "illegal reflection" warning logged by JDK9+ in the `bfd-pipeline-rda-grpc` module by adding the `mockito-inline` dependency along side the existing `mockito-core` dependency.
`mockito-inline` simply adds in a single line configuration file that configures Mockito to use the "inline" mock maker implementation, which unlike the default implementation, is able to mock final classes, protected fields, etc., without causing an illegal reflection warning.
* If the answer …
=> PACA-555: Resolve illegal reflection warning from gRPC module

apps/bfd-db-migrator/src/test/java/gov/cms/bfd/migrator/app/MigratorAppIT.java
[BFD-1680](https://jira.cms.gov/browse/BFD-1680)
This is a small PR to address a potential issue with sql in the flyway migration folder which is not versioned or being held until later.
---
Fixes an issue where if unversioned SQL exists in the flyway migration folder, the IT test will count it as an expected file to have been run and the test will fail to match the version correctly in the assertion. This was causing an issue in a couple branches in progress including 1680. …
=> BFD-1680: Fix test potentially reading unversioned sql

0014-dsl-driven-rda-code-generation.md
udpating the RFC number for using a DSL to drive RDA code generation 0014
---
* filename change to an approved RFC
* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
* Do you think this PR requires …
=> udpating the rfc number for DSL RFC

apps/bfd-pipeline/bfd-pipeline-app/src/main/resources/logback.xml
[PACA-554](https://jira.cms.gov/browse/PACA-554)
---
In an effort to be able to track package specific messages in monitoring tools (i.e. splunk), the logger for the pipeline application needs to be updated to no longer truncate class path names in the logs.
* Does …
=> PACA-554: Update pipeline logger to not truncate class path

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/carin/C4BBAdjudicationStatus.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/PartDEventTransformerV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/TransformerUtilsV2.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/PartDEventTransformerV2Test.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/TransformerUtilsV2Test.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/utils/EndpointJsonResponseComparatorV2IT.java, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobByPatientIdAll.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobByPatientIdPaged.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobReadHospice.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobReadOutpatient.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobReadPde.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobReadSnf.json
[BFD-1620](https://jira.cms.gov/browse/BFD-1620)
As a peering partner customer, I want EOB total to be populated, so that I am receiving CARIN compliant data.
---
- Adds two total slices to comply with CARIN compliance for PDE claims
- Adds a new adjudication status CARIN enum to cover the adjudication status values
- Adds new util methods to add slices that do not have CCW codes added as well, since this was breaking CARIN compliance in this case
- Adds unit tests for new code
- Regenerates golden files with new slices (which in turn updates the IT tests related to the response)
Note: Output has been reviewed by @bfausett77 and run through the CARIN validator to ensure this fixes the CARIN compliance issues on PDE
If you're reviewing this …
=> BFD-1620: Add total slices for CARIN compliance

apps/bfd-db-migrator/src/main/java/gov/cms/bfd/migrator/app/MigratorApp.java
[BFD-1550](https://jira.cms.gov/browse/BFD-1550)
In part, this helps satisfy the Jenkins db migrator deployment stage's ability to receive signals from the migrator.
---
The changes here has the `bfd-db-migrator` create an empty pid file that is ultimately populated with the application's exit code. This file is intended for use with a forthcoming monitoring service on the same host that will facilitate communication with Jenkins stage responsible for the deployment of **this** application instance. …
=> BFD-1550: Record migrator exit codes

apps/pom.xml
[BFD-1732](https://jira.cms.gov/browse/BFD-1732)
As a BFD Engineer I want third party libraries to be updated to the latest versions so that BFD is kept up to date with security and maintenance patches on these dependencies.
---
Updates jackson, guava, postgres driver, and logback to the latest versions.
* Does this PR …
=> BFD-1732: Update jackson, guava, postgres driver, and logback to latest versions

ops/terraform/modules/stateless/main.tf
=> HOTFIX: increase disk space in prod

apps/bfd-server/dev/api-changelog.md
[BFD-1620](https://jira.cms.gov/browse/BFD-1620)
Adds the changelog for BFD-1620 (Add slices for CARIN compliance)
---
Adds the changelog for BFD-1620 that was missed in the original PR.
* Does this PR …
=> BFD-1620: Add changelog for BFD-1620

apps/bfd-server/bfd-server-launcher/src/main/java/gov/cms/bfd/server/launcher/DataServerLauncherApp.java, apps/bfd-server/bfd-server-launcher/src/test/java/gov/cms/bfd/server/launcher/DataServerLauncherAppIT.java, ops/terraform/modules/resources/bfd_server_metrics/main.tf
[BFD-1822](https://jira.cms.gov/browse/BFD-1822)
Adds the 'X-Request-ID' response header to the access.log so that entries from access.log can be correlated with the corresponding entry from access.json.
---
* Adds the response header 'X-Request-ID' as a new field to the end of the access.log format.
* Updates the IT tests accordingly.
* Updates the terraform metrics patterns that rely on access.log. …
=> BFD-1822: Add X-Request-ID response header to access.log

ops/terraform/modules/resources/bfd_pipeline/main.tf, ops/terraform/modules/resources/bfd_pipeline/templates/bfd-dashboards.tpl
[BFD-1809](https://jira.cms.gov/browse/BFD-1809)
Import AWS Cloudwatch dashboard into terraform for test, prod-sbx, and prod environments
---
Introduces  a new terraform resource for bfd-pipeline aws cloudwatch dashboards for test, prod-sbx, and prod environments
* Verify if this PR addresses the goals expressed in the user story
* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence …
=> BFD-1809: Importing bfd-pipeline dashboard to terraform

ops/terraform/modules/resources/bfd_pipeline/templates/bfd-dashboards.tpl
[BFD-1809](https://jira.cms.gov/browse/BFD-1809)
This is a fix to the yet to be deployed bfd-pipeline dashboard.
---
This PR corrects a pipeline dashboard widget's stat function.
* Does this PR store or …
=> BFD-1809: Fix pipeline dashboard stat

ops/terraform/env/test/stateless/synthea.tf
[BFD-1652](https://jira.cms.gov/browse/BFD-1652)
This supports  a temporary test bucket for synthea loading, as well as the required policies to allow the bfd pipeline/etl role the appropriate r/w access to it.
---
As stated in the summary and description, we're adding a new test environment bucket and iam resources to allow the pipeline instance profile to access this bucket. This is a temporary set of resources that will be cleaned up after the synthetic data load has completed. …
=> BFD-1652: Temporary synthea Bucket and IAM resources

ops/terraform/modules/resources/ec2/main.tf
[BFD-1832](https://jira.cms.gov/browse/BFD-1832)
Make bfd-pipeline terraform idempotent
---
This PR adjusts the ec2 child module to address a static value, rather than a _lookup_ value for the kms/cmk key, i.e. the key's arn. Currently, this forces a replacement of the `bfd-pipeline` ec2 instance, even when the configuration wouldn't otherwise result in a diff, e.g.
```hcl
~ root_block_device {
delete_on_termination = true
~ device_name           = "/dev/xvda" -> (known after apply)
encrypted             = true
~ iops                  = 3000 -> (known after apply)
~ kms_key_id            = "arn:aws:kms:us-east-1:000000000000:key/00000000-0000-0000-0000-000000000000" -> "alias/bfd-test-cmk" # forces replacement
- tags                  = {} -> …
```
=> BFD-1832: Make bfd-pipeline IaC idempotent

ops/terraform/modules/resources/bfd_cw_dashboards/templates/bfd-dashboards.tpl
[BFD-1747](https://jira.cms.gov/browse/BFD-1747)
---
Improves the dashboard readability by changing the period and the title of the 'non-2xxs' and '5xxs' widgets.
* Does this PR store or transmit data …
=> BFD-1747: Fix the error rates in the CW dashboards

ops/ccs-ops-misc/synthetic-data/scripts/test_synthetic_bene_file.py, ops/ccs-ops-misc/synthetic-data/scripts/test_synthetic_file.py
[BFD-1739](https://jira.cms.gov/browse/BFD-1739)
As a BFD engineer, I want to load a significant synthetic beneficiaries, so that they can be used to trigger scaling during load tests.
---
Adds a simple script for validating rif csvs generated by Synthea. 
This is useful to catch small errors with synthea data generation, and for the short term, to catch any issues resulting from splitting the beneficiary_interim file without having to get to the lengthy loading process first. …
=> BFD-1739: Add Synthea validation file for generated rif files

apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V75__new_schema_remove_old_claims_tables.sql
[BFD-1859](https://jira.cms.gov/browse/BFD-1859)
Flyway migration script to remove old claims tables.
- Drop the following tables:
- public.partd_events
- public.carrier_claim_lines
- public.carrier_claims
- public.dme_claim_lines
- public.dme_claims
- public.hha_claim_lines
- public.hha_claims
- public.hospice_claim_lines
- public.hospice_claims
- public.inpatient_claim_lines;
- public.inpatient_claims
- public.outpatient_claim_lines
- public.outpatient_claims
- public.snf_claim_lines
- public.snf_claims
- dropping a table is , by definition, a _destructive_ act; this script only targets unused tables.
- flyway scripts works for both HSQL and PSQL
- scripts are …
=> BFD-1859: flyway script to remove unused claims tables

apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/RdaFissAuditTrail.java, apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/RdaFissDiagnosisCode.java, apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/RdaFissPayer.java, apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/RdaFissProcCode.java, apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/RdaMcsAdjustment.java, apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/RdaMcsAudit.java, apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/RdaMcsDiagnosisCode.java, apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/RdaMcsLocation.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/DataTransformer.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/ClaimTransformerFieldTester.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/utils/RDATestUtils.java
[PACA-621](https://jira.cms.gov/browse/PACA-621)
Fixes hibernate validation issue caused by postgresql using `int2` when column is created as `smallint` which causes hibernate validation to fail on fields that have `int` type.
---
Changes `rdaPosition` fields to use type `short` so Hibernate won't object to them being stored as `smallint`/`int2` in database. …
=> PACA-621: Converts rdaPosition to short to fix hibernate issues.

ops/ansible/playbooks-ccs/vars/prod/group_vars/all/env_specific.yml
[PACA-683](https://jira.cms.gov/browse/PACA-683)
Increasing our RDA ETL threads to 5 in production to boost our claims ingestion rate.
---
- update our RDA ETL thread count to 5 in production
* Does this …
=> PACA-683: increasing our RDA ETL threads to 5 in production

ops/terraform/modules/resources/bfd_pipeline/main.tf, ops/terraform/modules/resources/bfd_pipeline/rds-cluster-config.sh
[BFD-1943](https://jira.cms.gov/browse/BFD-1943)
Ensure bfd-pipeline is homed in same az as RDS writer node.
---
This PR introduces nearly identical logic found in the module supporting the bfd-db-migrator.  While it's not critical for the migrator to be homed in the same AZ as the writer node, I used that module as a test case to model this solution for the bfd-pipeline.
A perfect solution probably doesn't exist for this, but this change set is a **very** light touch producing the expected results. This is only good for the time of instantiation, however. If the writer node changes for any reason from one AZ to another, bfd-pipeline would need to be re-instantiated or manually moved.
If you're reviewing this PR, please check for these …
=> BFD-1943: Derive bfd-pipeline's availability zone

ops/terraform/modules/resources/iam/main.tf, ops/terraform/services/migrator/iam.tf
~DRAFT status to be removed after adequate testing~ Works just fine in test. Plans are successful in `prod-sbx` and `prod`.
[BFD-1484](https://jira.cms.gov/browse/BFD-1484)
This provisions expected parameter store access for migrator, pipeline, and server roles.
---
Toward adopting AWS SSM Parameter Store, we need to ensure that the services configured with these parameters have the ability to read from them. This change set introduces read access to the appropriate IAM Roles in terraform for those services that are backed by infrastructure-as-code.
- The remaining access controls really ought to be controlled by terraform, too. It might make sense to re-imagine the `mgmt` module to handle resources like this.
- The existing _stateless_ …
=> BFD-1484: Configure AWS SSM Parameter Store Access

ops/ansible/playbooks-ccs/vars/prod/group_vars/all/env_specific.yml
[PACA-694](https://jira.cms.gov/browse/PACA-694)
Increasing the number of RDA ETL threads in production to 20.  Both the EC2 and RDS servers are staying below 10% CPU utilization with 10 threads in place, we're going to try increasing to 20 threads to see if we can increase our MCS throughput.  We're targeting a rate of ~250 claims per second, but are still averaging only ~100 claims per second.
---
- fixes a typo in the prod env variables file
- increases the RDA ETL worker threads from 10 to 20 in production
* If the answer to …
=> PACA-694: increasing RDA ETL threads in PROD from 10 to 20

ops/ansible/playbooks-ccs/vars/prod/group_vars/all/env_specific.yml
[PACA-697](https://jira.cms.gov/browse/PACA-697)
Enabling the RDA ETL in production
---
- turning the RDA ETL on in production …
=> PACA-697: enabling the RDA ETL in production for the week

ops/ansible/playbooks-ccs/vars/prod/group_vars/all/env_specific.yml
[PACA-697](https://jira.cms.gov/browse/PACA-697)
Disabling the RDA ETL for the weekend.
---
- turning off the RDA ETL
* If …
=> PACA-697: disable rda etl for weekend

apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V93__remove_clm_grp_index.sql
[BFD-1939](https://jira.cms.gov/browse/BFD-1939)
As a BFD Engineer I would like the same data fixes applied to test to be applied to prod-sbx and prod, so that future synthea data generation is not hampered in those environments.
---
Removes indexes that were added for clm_grp_id on the four tables that needed to be cleaned up now that the cleanup is complete. …
=> BFD-1939: Flyway script to remove temporary indexes

apps/bfd-data-fda/src/main/java/gov/cms/bfd/data/fda/utility/DataUtilityCommons.java, apps/bfd-data-fda/src/test/java/gov/cms/bfd/data/fda/lookup/FDADrugUtilsTest.java, apps/bfd-data-fda/src/test/java/gov/cms/bfd/data/fda/utility/AppTest.java, apps/bfd-data-fda/src/test/java/gov/cms/bfd/data/fda/utility/DataUtilityCommonsTest.java, apps/bfd-db-migrator/src/test/java/gov/cms/bfd/migrator/app/HibernateValidatorTest.java, apps/bfd-db-migrator/src/test/java/gov/cms/bfd/migrator/app/MigratorAppIT.java, apps/bfd-db-migrator/src/test/java/gov/cms/bfd/migrator/app/RdaSchemaMigrationIT.java, apps/bfd-model/bfd-model-codebook-extractor/src/test/java/gov/cms/bfd/model/codebook/extractor/PdfParserTest.java, apps/bfd-model/bfd-model-codebook-extractor/src/test/java/gov/cms/bfd/model/codebook/unmarshall/CodebookVariableReaderIT.java, apps/bfd-model/bfd-model-dsl-codegen/bfd-model-dsl-codegen-library/src/test/java/gov/cms/model/dsl/codegen/library/DataTransformerTest.java, apps/bfd-model/bfd-model-dsl-codegen/bfd-model-dsl-codegen-plugin/src/test/java/gov/cms/model/dsl/codegen/plugin/GenerateEntitiesFromDslMojoTest.java, apps/bfd-model/bfd-model-dsl-codegen/bfd-model-dsl-codegen-plugin/src/test/java/gov/cms/model/dsl/codegen/plugin/GenerateSqlFromDslMojoIT.java, apps/bfd-model/bfd-model-dsl-codegen/bfd-model-dsl-codegen-plugin/src/test/java/gov/cms/model/dsl/codegen/plugin/GenerateTransformersFromDslMojoIT.java, apps/bfd-model/bfd-model-dsl-codegen/bfd-model-dsl-codegen-plugin/src/test/java/gov/cms/model/dsl/codegen/plugin/accessor/OptionalSetterTest.java, apps/bfd-model/bfd-model-dsl-codegen/bfd-model-dsl-codegen-plugin/src/test/java/gov/cms/model/dsl/codegen/plugin/accessor/StandardSetterTest.java, apps/bfd-model/bfd-model-dsl-codegen/bfd-model-dsl-codegen-plugin/src/test/java/gov/cms/model/dsl/codegen/plugin/model/ColumnBeanTest.java, apps/bfd-model/bfd-model-dsl-codegen/bfd-model-dsl-codegen-plugin/src/test/java/gov/cms/model/dsl/codegen/plugin/model/EnumTypeBeanTest.java, apps/bfd-model/bfd-model-dsl-codegen/bfd-model-dsl-codegen-plugin/src/test/java/gov/cms/model/dsl/codegen/plugin/model/MappingBeanTest.java, apps/bfd-model/bfd-model-dsl-codegen/bfd-model-dsl-codegen-plugin/src/test/java/gov/cms/model/dsl/codegen/plugin/model/ModelUtilTest.java, apps/bfd-model/bfd-model-dsl-codegen/bfd-model-dsl-codegen-plugin/src/test/java/gov/cms/model/dsl/codegen/plugin/model/TableBeanTest.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/DataTransformerTest.java, apps/bfd-shared-utils/src/test/java/gov/cms/bfd/sharedutils/config/ConfigLoaderTest.java, apps/pom.xml
[BFD-1703](https://jira.cms.gov/browse/BFD-1703)
Small fix for a previous checkstyle config change, which accidentally turned off test checkstyle validation.
---
- Re-enables checkstyle validation for test classes (for projects with checkstyle currently enabled)
- Fixes test classes that were out of compliance in those projects
* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence …
=> BFD-1703: Re-enable checkstyle for test classes, bring test classes into compliance

ops/ccs-ops-misc/synthetic-data/scripts/generate-characteristics-file.py
[BFD-1909](https://jira.cms.gov/browse/BFD-1909)
As a BFD Engineer, I want to know the makeup and information about an automated synthea generation, so that I can better use the data created.
---
Adds a script which runs queries and exports a csv describing any number of benes between two bene_ids and the number of contracts and claim types associated with those benes.
* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or …
=> BFD-1909: Create script for generating synthea characteristics file

ops/terraform/env/mgmt/README.md, ops/terraform/env/mgmt/iam.tf, ops/terraform/env/mgmt/main.tf
[BFD-1484](https://jira.cms.gov/browse/BFD-1484)
These changes include importing existing resources for necessary extension, subject to BFD-1484. This _largely_ encodes the desired SSM access for bfd developers and Jenkins. Non-goals include further organization of the resources, deduplication of policy documents, and assessing appropriate levels of access for IAM resources. See the future work section for more details.
---
Summary of changes here:
- import existing cloudbees jenkins role and policies (_OOB_ changes to jenkins already accommodate ssm access)
- import bfd-app-engineer group and associated policies
- introduce, attach policy to allow associated bfd-app-engineer users read-only access to `/bfd` ssm hierarchies
Overall there is …
=> BFD-1484: Import, extend jenkins, dev policies

apps/bfd-model/bfd-model-rif/src/main/resources/db/scripts/delete_duplicate__synthetic_bene_mbis.sql, ops/ccs-ops-misc/synthetic-data/scripts/prepare-for-new-synthea-load.py
[BFD-2041](https://jira.cms.gov/browse/BFD-2041)
As a BFD Engineer I would like to understand why there were duplicate mbi_hashes added to beneficiary_history during the 10 million synthea data load so that I can catch and avoid having this issue occur in the future.
---
Adds a script to correct the issue in bene history in Test which was caused by the 10M synthea load, where a specific load being reloaded 3 times caused the same mbi to point to multiple bene_ids, causing an error in bfd-server when using that data.
Also adds validation which checks for this issue during the Synthea automation, so we can catch it if it happens.
* Verify all PR security questions and …
=> BFD-2041: Add cleanup script and validation for removing synthea load duplicate bene history entries

apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/resources/bfd-manifest.xsd, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/java/gov/cms/bfd/pipeline/ccw/rif/extract/s3/DataSetManifestTest.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/resources/manifest-sample-c.xml
[BFD-2062](https://jira.cms.gov/browse/BFD-2062)
Fix XML schema definition (XSD) to treat sequenceId as an integer.
Fixes a bug in the BFD pipeline manifest XSD to treat sequenceId as an integer. Added test support to verify correct parsing and data equality.
* XSD correctly defined.
* Test support to assert sequenceId has a value > 255. …
=> BFD-2062 - fix support for sequenceId in manifest

ops/jenkins/global-pipeline-libraries/README.md, ops/jenkins/global-pipeline-libraries/vars/awsAuth.groovy, ops/jenkins/global-pipeline-libraries/vars/awsSqs.groovy
[BFD-2064](https://jira.cms.gov/browse/BFD-2064)
Hoist aws role assumption and sqs methods into global pipeline libraries.
---
This PR introduces aws role assumption and sqs methods that are commonly referenced throughout the Jenkinsfile-defined pipelines, making them more globally accessible to allow for further simplification of our pipelines in the near future.
* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or …
=> BFD-2064: Introduce global pipeline libraries

ops/ccs-ops-misc/pg-password-generator/README.md, ops/ccs-ops-misc/pg-password-generator/pgpass-gen.py
[BFD-1633](https://jira.cms.gov/browse/BFD-1633)
Implement database RBAC.
---
Adds a python script that will allow database users to generate and share a database password, without revealing the password to the db administrator.
This is a python3 script with no external dependencies.
Example usage:
* Does this PR add …
=> BFD-1633: Adds a postgres password generator script

ops/Dockerfile
TODO: Need BFD Jira ISSUE to accept these changes
[BFD-2077](https://jira.cms.gov/browse/BFD-2077)
Pin flyway container image in the bfd-ansible base container to (at least temporarily) avoid automatic upgrade of flyway 9 in the ansible test harness.
---
**NOTE:** I have already built, tagged, and pushed this container image pushed it to ghcr under `master` to unblock the regular GHA workflows. This change set is still necessary so that the codebase reflects the resources it _purportedly_ creates.
We mistakenly overlooked pinning flyway when introducing postgresql and flyway into the bfd-ansible and bfd-apps container image creation process for a more meaningful testing harness. As of mid July, version 9 of Flyway have been released, …
=> BFD-2077: Pin flyway container image

ops/terraform/services/server/server-regression/main.tf
[BFD-2078](https://jira.cms.gov/browse/BFD-2078)
A misconfiguration in the Terraform associated with the `bfd-*-server-regression-glue-trigger` Lambdas' S3 Event Notification triggers could allow for the public to run the Lambdas. These triggers should be locked down such that only the BFD AWS account can trigger them via S3. 
---
This PR adds a "source account" to the Terraform resource representing the S3 Event Notification trigger for each `bfd-*-server-regression-glue-trigger` Lambda.
This should remove any possiblity for users outside of the BFD organization to trigger these Lambdas.
* Are any additional security measures required? …
=> BFD-2078: Lock down S3 event notification triggers for Glue trigger Lambdas

ops/ccs-ops-misc/synthetic-data/scripts/synthea-automation/prepare-and-run-synthea.py
[BFD-2076](https://jira.cms.gov/browse/BFD-2076)
As a BFD Engineer I want the synthea generation automation to ensure that test, prod-sbx, and prod have space to load synthea data so that I can load them into those environments without worrying.
---
Mainly updates the synthea automation script to validate all environments, so we can safely load into test, prod-sbx, and prod when automating.
- Replaces the target DB string with a list of usernames and passwords for each environment as arg4
- Updates the validation to check against test, prod-sbx, and prod for the various validations
- Moves some of the logging about validation inside the logic which is only run if skip validation is False to reduce noise
- Updates the validation to take into …
=> BFD-2076: Enhance Synthea automation script to validate all environments

ops/ccs-ops-misc/splunk/pipeline-job-failure-queries
[BFD-2070](https://jira.cms.gov/browse/BFD-2070)
Troubleshoot why #bfd-notices channel does not get Pipeline job failure notices.
This PR is effectively a work placeholder in that the remediation is not germane to BFD application code but denotes work within Splunk to propagate BFD Pipeline job failure(s) for _prod, test, and prod-sbx_ environments to the _#bfd-notices_ Slack channel.
While the queries reside and operate solely within Splunk as Splunk Alerts, the search queries that drive the notifications have been added to a new ops/ccs-ops-misc/splunk folder.
Within Splunk itself, 3 new Alerts have been added:
1. BFD-CCW-JOB-FAILED-PROD
2. BFD-CCW-JOB-FAILED-PROD-SBX
3. BFD-CCW-JOB-FAILED-TEST
There is no code per se that can be tested …
=> BFD-2070 - Enable splunk alerts for pipeline job failures

runbooks/how-to-mark-snyk-findings-ignored.md, runbooks/how-to-resolve-snyk-bot-prs.md, runbooks/how-to-resolve-snyk-report-findings.md
[BFD-2085](https://jira.cms.gov/browse/BFD-2085)
Runbook is created that reflects the outcomes of the snyk process discussions from the [Engineering sync](https://confluence.cms.gov/pages/viewpage.action?spaceKey=BFD&title=BFD+Engineering+Sync).
---
Creates runbooks for three common SNYK process:
1. Resolving a SNYK-bot PR
2. Resolving a finding from the SNYK report
3. Marking a finding as Ignored
* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment …
=> BFD-2085 Runbooks for SNYK processes

Jenkinsfile, ops/terraform/services/base/deploy.groovy
[BFD-2116](https://jira.cms.gov/browse/BFD-2116)
Enable base service deployments.
---
This PR introduces environment-specific `base` service deployment stages to the existing build/deliver/deploy pipeline. Additionally, because the `base` service relies on `yq`, included in an updated `bfd-cbc-build` image. Embarassingly, the pace of configuration changes has been so sluggish that this has been done manually for each environment. Let's fix that!
* If the answer to any of the questions below is **Yes**, then **you must** supply a …
=> BFD-2116: Enable base service deployments

ops/ansible/playbooks-ccs/roles/base_patch/tasks/main.yml
[BFD-2123](https://jira.cms.gov/browse/BFD-2123)
---
Adds `pre-ami` tag to the base patch play so minimal security updates are applied during builds.
* Does this PR store or transmit data that was not …
=> BFD-2123: Fix install security updates during builds

ops/ccs-ops-misc/synthetic-data/scripts/synthea-automation/generate-characteristics-file.py, ops/ccs-ops-misc/synthetic-data/scripts/synthea-automation/prepare-and-run-synthea.py, ops/ccs-ops-misc/synthetic-data/scripts/synthea-automation/ssmutil.py, ops/ccs-ops-misc/synthetic-data/scripts/synthea-automation/validate-synthea-load.py
[BFD-2097](https://jira.cms.gov/browse/BFD-2097)
Adds SSM for the synthea automation scripts instead of passing in the passwords to the args.
---
Adds a util to get db data from SSM, and uses that util to get the database credentials and urls from SSM instead of passing credentials and using hardcoded database strings.
This uses boto3, which was already in use for the regression scripts.
* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), …
=> BFD-2097: Add SSM for DB passwords in automation scripts

ops/terraform/modules/resources/templates/fhir_server.tpl, ops/terraform/modules/resources/templates/pipeline_server.tpl, ops/terraform/modules/stateless/main.tf, ops/terraform/services/base/values/test.yaml
[BFD-2006](https://jira.cms.gov/browse/BFD-2006)
The test environment accommodates prod-like load testing by scaling out to match that of the prod environment.
---
* removed the `local.is_prod` variable from the `stateless` module definition
* updates `fhir_asg` module declaration to treat all path-to-production environments equally
* increases rds node count to 3 to include 2 readers and 1 writer (prod has 3 readers, but the _general_ reader pool has just 2 members)
* removes outdated comments on prod and non-prod environment sizing
* removes outdated, commented code from fhir_server and pipeline_server user-data scripts to facilitate testing …
=> BFD-2006: Scale out test environment

ops/terraform/modules/resources/asg/main.tf, ops/terraform/modules/resources/ec2/main.tf
[BFD-1156](https://jira.cms.gov/browse/BFD-1156)
As a product, we should configure our instances to use shared tenancy to reduce operational costs.
---
Deploys resources using the default shared tenancy.
* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **See ticket https://jira.cms.gov/browse/BFD-1156 comments**
* Does this …
=> BFD-1156: Use default tenancy

ops/terraform/modules/stateless/main.tf
[BFD-2125](https://jira.cms.gov/browse/BFD-2125)
Scale prod-sbx environment in from 6 to 3 nodes in the fhir asg.
---
This simply scales the prod-sbx in from its current 6-node count to a more reasonable 3-node count. It continues to enjoy ample nodes in warm pools, so even during the rare scaling event, the ASG should be able to scale quickly to meet an influx of traffic.
* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security …
=> BFD-2125: Scale in prod-sbx environment

.github/CODEOWNERS
[BFD-2133](https://jira.cms.gov/browse/BFD-2133)
---
Replaces Earl with Laila as Earl is no longer on the project.
* If …
=> BFD-2133: Update AB2D Insights code owners

ops/terraform/env/mgmt/s3.tf, ops/terraform/env/test/stateless/synthea.tf, ops/terraform/modules/resources/s3/main.tf, ops/terraform/modules/resources/s3_pii/main.tf, ops/terraform/modules/resources/s3_pii/templates/bucket-policy.json, ops/terraform/modules/resources/s3_pii/templates/iam-writer-policy.json
[BFD-2111](https://jira.cms.gov/browse/BFD-2111)
---
1. Hardens s3_pii bucket policy templates
2. Fixes s3 bucket logging prefixes
As an AWS Foundational Security Best Practice, there are a few Amazon S3 permissions that should not be granted to other AWS accounts. Ie.:
- s3:DeleteBucketPolicy
- s3:PutBucketAcl
- s3:PutBucketPolicy
- s3:PutEncryptionConfiguration
- s3:PutObjectAcl
However, a few of our s3_pii policy templates contains wildcards that would grant some of these to our partners.
For example, the following actions would grant PutObjectAcl, DelectObjectAcl, etc.
```json
{
...
"Effect": "Allow",
"Action": [
"s3:PutObject*",
"s3:DeleteObject*"
],
},
```
**This PR refactors these policies to address this and tighten up on some of the …
=> BFD-2111: Harden AWS S3 bucket policies

ops/terraform/services/base/README.md, ops/terraform/services/base/ephemeral.tf, ops/terraform/services/base/main.tf, ops/terraform/services/base/nonsensitive.tf, ops/terraform/services/base/sensitive.tf, ops/terraform/services/base/values/ephemeral.yaml, ops/terraform/services/base/variables.tf, ops/terraform/services/common/aurora-cluster.tf, ops/terraform/services/common/main.tf, ops/terraform/services/migrator/README.md
[BFD-2134](https://jira.cms.gov/browse/BFD-2134)
Ensure that existing terraservice modules can accommodate ephemeral environments.
---
This PR predominantly focuses on extending the `base` _terraservice_ module to allow users to define non-established environments (e.g. `test`, `prod-sbx`, and `prod`) _or_ more simply, _ephemeral environments_. We took care when introducing the `common` and `migrator` terraservice modules, and as a result, they needed little modification to support an arbitrary environment definitions.
**There is complexity in the `base` module.** However, with the understanding that the objectives for "ephemeral environment support" in the base module are few and humble, this should lend itself to a relatively quick review: …
=> BFD-2134: Add initial ephemeral env support

ops/terraform/env/mgmt/code-suite.tf, ops/terraform/env/mgmt/iam.tf
[BFD-1925](https://jira.cms.gov/browse/BFD-1925)
Introduce AWS CodeArtifact resources and permissions for Cloudbees Jenkins interaction.
---
- adds `bfd-mgmt` domain and repository
- adds permissions to Cloudbees Jenkins role for usage
**FIXME: likely requires further adjustments to GHA runner and  bfd-app-engineer permissions**
* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence …
=> BFD-1925: Add bfd-mgmt CodeArtifact Resources

.github/workflows/ci-java.yml, apps/bfd-data-fda/Jenkinsfile
[BFD-1925](https://jira.cms.gov/browse/BFD-1925)
User Story
As a developer I want the FDA library to build successfully in github actions, in jenkins, so it can be uploaded to AWS Code Artifact
AC
1. Add the Jenkinsfile to the FDA project
2. Make sure the project builds in GitHub Actions and in Jenkins. (SIA is probably needed for this)
3. The FDA LIbrary is uploaded to AWS Code Artifact 
4. The jenkinsfile is used by jenkins
5. AWS Code Artifact needs to be in terraform (SIA is probably needed for this). - this will be a separe PR by michael burling
---
This adds a jenkins file and github actions for the new awa code artifactory
* Verify all PR security questions and …
=> BFD-1925: add CI workflows for fda drug code

apps/utils/locust_tests/common/validation.py, apps/utils/locust_tests/high_volume_suite.py
[BFD-1885](https://jira.cms.gov/browse/BFD-1885)
Adjusts the load test validation to only be safeguards and not check actual SLOs.
---
Originally, we wanted to add SLO validation to the load test to ensure the application is performant or at least does not die under load. However, we discussed implementing these SLOs and decided there was little value in these checks being automated and failing a run, so this PR removes those automated validations. Instead we will check the results manually when we run the suite under varying loads. …
=> BFD-1885: Adjust load test validation to only be safeguards

ops/terraform/services/server/server-load/README.md, ops/terraform/services/server/server-load/data-sources.tf, ops/terraform/services/server/server-load/main.tf
[BFD-1783](https://jira.cms.gov/browse/BFD-1783)
Addenda to original scaling load tests story BFD-1783 and #1267 to improve the availability zone resolution, minimize diffs in terraform resolution, and extend documentation.
---
The original change set in BFD-1783 included automatic **and** pseudo-random AZ resolution, but because the random_integer was always included, terraform produced unnecessary diffs when tearing down the locust instance. These changes conditionally create the random_integer resource and accommodates its now conditional inclusion. This change also includes the additions of rand_integer and  aws_availability_zones. …
=> BFD-1783: Improve load test AZ resolution, docs

ops/ansible/roles/cloudwatch-agent-instrumented/templates/cwagent.json.j2
[BFD-2013](https://jira.cms.gov/browse/BFD-2013)
Addendum to BFD-2013 and #1340.
---
The changes introduced here align with the official [Metrics collected by the CloudWatch agent
](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/metrics-collected-by-CloudWatch-agent.html#linux-metrics-enabled-by-CloudWatch-agent) documentation, fixing some typographical errors introduced in #1340 that fail the `Build App AMIs` stage in Jenkins as in the following:
```json
{
"changed": true,
"cmd": "/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/tmp/cwagent-base.json -s",
"delta": "0:00:00.777837",
"end": "2022-09-09 10:20:51.296147",
"msg": "non-zero return code",
"rc": 1,
"start": "2022-09-09 …
```
=> BFD-2013: Fix CloudWatch Agent Metrics Collection

ops/terraform/services/base/README.md, ops/terraform/services/base/nonsensitive.tf, ops/terraform/services/base/sensitive.tf, ops/terraform/services/base/values/prod-sbx.yaml, ops/terraform/services/base/values/prod.yaml, ops/terraform/services/base/values/test.yaml
[BFD-2050](https://jira.cms.gov/browse/BFD-2050)
This fixes an issue discovered in the `bfd-pipeline` where RDA jobs are provided with variables for which no reasonable default exists.
---
Generally, this PR addresses the immediate need for the inclusion of configuration definitions that have no sensible default. While these settings should remain for discoverability and standardization, they should not yield stored values in AWS SSM Parameter Store. To achieve this, we will reserve the all-caps literal `UNDEFINED` to communicate that no value will be stored. We yield to the translation from AWS SSM Parameter Store hierarchies to tool-specific values to make appropriate decisions for their respective contexts, e.g. `is not defined` in the …
=> BFD-2050: Enable undefined values in bfd-pipeline

.github/CODEOWNERS
[BFD-2169](https://jira.cms.gov/browse/BFD-2169)
Align CODEOWNERS with composition of current BFD contributors
---
* Introduce special handling for cross-functional performance testing utilities under /apps/utils/locust_tests
* Add @malessi to various operator-focus areas of the BFD repository
* Does this PR add any …
=> BFD-2169: Update CODEOWNERS alignment

apps/utils/locust_tests/README.md, runbooks/how-to-run-load-and-regression-locust-tests.md
[BFD-2007](https://jira.cms.gov/browse/BFD-2007)
As a BFD Engineer I would like the documentation on how to run the load tests to be updated so that
I know what steps are needed to run them.
---
This PR adds a new runbook titled "How to Run the Regression and Load Test Suites" that goes into
depth on how to run the regression suite and load tests in a variety of scenarios:
- Running the regression suite locally against a local BFD Server
- Running the regression suite locally against a particular environment
- Running the regression suite on a detached instance against a particular environment
- Running a scaling load test using the `bfd-run-server-load` Jenkins job
- Running a static load test using the `bfd-run-server-load` Jenkins job
In …
=> BFD-2007: Update documentation on running load and performance regression test suites

insights/terraform/modules/bucket/policies.tf, ops/terraform/env/prod-sbx/stateful/main.tf, ops/terraform/env/prod/stateful/main.tf, ops/terraform/env/test/stateful/main.tf, ops/terraform/modules/resources/s3_pii/templates/bucket-policy.json, ops/terraform/modules/stateful/main.tf, ops/terraform/modules/stateful/variables.tf
[BFD-2163](https://jira.cms.gov/browse/BFD-2163)
_In part_, this successfully remediates Security Hub Findings associated with AWS Foundational Security Best Practices v1.0.0 S3.6: _S3 permissions granted to other AWS accounts in bucket policies should be restricted_.
---
What _should_ have been a ~10 line change swelled into what you see here.
- updating the _insights_ bucket child module was straightforward, however, the modules make use of it are in various states of disrepair and required manual intervention to address. 
- For a variety of reasons, the stateful module hasn't enjoyed automation that would ensure it remains _largely_ in-sync with the resources it purportedly manages. What's more, we neglected to remove the resources that …
=> BFD-2163: Restrict x-account S3 Bucket Policies

insights/terraform/modules/bucket/policies.tf, ops/terraform/modules/resources/s3_pii/templates/bucket-policy.json
[BFD-2165](https://jira.cms.gov/browse/BFD-2165)
_In part_, this successfully remediates Security Hub Findings associated with AWS Foundational Security Best Practices v1.0.0 S3.5: _S3 buckets should require requests to use Secure Socket Layer_.
---
Update the stateful and insights bucket modules to ensure that SSL is required on all requests. …
=> BFD-2165: Require SSL on S3 Buckets

apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/s3/SharedS3Utilities.java
[BFD-1748](https://jira.cms.gov/browse/BFD-1748)
S3 buckets created during integration tests should not attempt to enforce CMS S3 bucket security if running under minio. 
This PR is a necessary change to how S3 buckets are created during integration tests. Normally, buckets created in AWS S3 must adhere to CMS security constraints; that functionality is not available when using _minio_ as an S3 mock.
Code changes in SharedS3Utilities is concise in its functionality and commented appropriately.
While this PR does have security implications, they are extremely limited in scope and …
=> BFD-1748 : Bypass AWS S3 bucket security constraints under minio

Jenkinsfile
[BFD-2161](https://jira.cms.gov/browse/BFD-2161)
---
Fixes small typo in https://github.com/CMSgov/beneficiary-fhir-data/pull/1396 that is breaking builds.
* Does this PR store or transmit data that was …
=> BFD-2161: bugfix typo in Jenkinsfile

docs/request-audit-headers.md
[BFD-2185](https://jira.cms.gov/browse/BFD-2185)
BFD currently requests that partners making bulk requests supply a client ID (a unique key for the associated bulk client for that request, such as the contract ID, or similar). During SLO review it was noted that also having a human readable name will aid in consuming this information for debugging or tracing purposes. This PR updates the request-audit-headers.md accordingly.
---
Add BULK-CLIENTNAME to the request-audit-headers.md. …
=> BFD-2185: Add BULK-CLIENTNAME to request-audit-headers.md

ops/terraform/env/mgmt/github-actions-iam.tf, ops/terraform/env/mgmt/iam.tf, ops/terraform/env/mgmt/jenkins-iam.tf, ops/terraform/env/mgmt/main.tf, ops/terraform/services/server/server-regression/data-sources.tf
[BFD-2168](https://jira.cms.gov/browse/BFD-2168)
_In part_, this successfully remediates Security Hub Findings associated with AWS Foundational Security Best Practices v1.0.0 KMS.1: _IAM customer managed policies should not allow decryption actions on all KMS keys_.
---
- separates the jenkins/github policies from the mgmt's `iam.tf`
- removes the lax statements that allowed e.g. the Cloudbees Jenkins role access to **all** KMS actions among **all** KMS keys
- prefer key alias to key id when referring to the BFD Insights KMS Key
* …
=> BFD-2168: Tighten KMS access

apps/pom.xml
[BFD-2190](https://jira.cms.gov/browse/BFD-2190)
This resolves the following SNYK vulnerability:
✗ Denial of Service (DoS) [Medium Severity][https://security.snyk.io/vuln/SNYK-JAVA-COMGOOGLEPROTOBUF-3040284] in com.google.protobuf:protobuf-java@3.21.1
introduced by gov.cms.bfd:bfd-pipeline-rda-grpc@1.0.0-SNAPSHOT > io.grpc:grpc-protobuf@1.48.1 > com.google.protobuf:protobuf-java@3.21.1
---
Updates the version of io.grpc:grpc-protobuf to the latest -- 1.49.2.
* If the answer to any of the questions below is **Yes**, then **you …
=> BFD-2190: Update grpc-protobuf pom version to 1.49.2

ops/terraform/env/mgmt/code-suite.tf, ops/terraform/env/mgmt/github-actions-iam.tf, ops/terraform/env/mgmt/iam.tf, ops/terraform/env/mgmt/jenkins-iam.tf, ops/terraform/env/mgmt/main.tf, ops/terraform/env/mgmt/r53.tf, ops/terraform/env/mgmt/s3-account.tf, ops/terraform/env/mgmt/s3.tf, ops/terraform/env/mgmt/terraform.tf
[BFD-2188](https://jira.cms.gov/browse/BFD-2188)
Block Public Access setting should be enabled at the account level to prevent new buckets from being public.
---
As a best practice, AWS recommends disabling public access at the account level to prevent buckets from every being able to be made public ([see control here](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-s3-1)). 
However, we currently host public test data via the`bfd-public-test-data` s3 bucket so we cannot block public on existing buckets. But, we _can_ prevent new buckets and objects from being made public by flipping a few account level settings.
* …
=> BFD-2188: block public access on new buckets

ops/terraform/env/mgmt/README.md, ops/terraform/env/mgmt/github-actions-iam.tf, ops/terraform/services/pipeline/README.md, ops/terraform/services/pipeline/iam.tf, ops/terraform/services/pipeline/main.tf, ops/terraform/services/pipeline/variables.tf
[BFD-2184](https://jira.cms.gov/browse/BFD-2184)
_In part_, this successfully remediates Security Hub Findings associated with AWS Foundational Security Best Practices v1.0.0 IAM.3: _IAM users' access keys should be rotated every 90 days or less_.
---
* imports and manages the github actions user and related aws iam resources
* creates an ssm parameter store value containing a generated aws iam access key for the gha user in the mgmt hierarchy
* imports and manages the production etl user, along with related aws iam resources
* If …
=> BFD-2184: Manage BFD Service Accounts

.github/workflows/ci-java.yml
[BFD-2197](https://jira.cms.gov/browse/BFD-2197)
Fix the GHA Java Workflow.
---
- prefer testing BFD system together with all changes in the same commit instead of pre-built NDC/NPI JARs stored in CodeArtifact
- re-order the dependencies to ensure NDC/NPI dependencies are built ahead of the dependent BFD system
- incidentally, tamp down on GHA errors in CloudTrail where maven fails to resolve a number of non-existent artifacts in CodeArtifact
* If the answer to any of the questions below is **Yes**, then **you must** supply a link …
=> BFD-2197: Fix GHA Java Workflow

ops/terraform/services/pipeline/iam.tf, ops/terraform/services/pipeline/main.tf, ops/terraform/services/pipeline/s3-temporary.tf
[BFD-2147](https://jira.cms.gov/browse/BFD-2147)
Create a _temporary_ S3 Bucket for CCW testing, limited to the `prod` environment.
---
This PR introduces the S3 bucket and attendant resources to satisfy testing/verification requirements of CCW meeting and meeting CMS security standards. See the `terraform plan` below for more details.
<details><summary>Terraform Plan</summary>
**NOTE** these changes have already been applied.
```hcl
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
+ create
~ update in-place
Terraform will perform the following actions:
~ resource "aws_iam_policy" "etl-rw-s3" {
id          = …
```
=> BFD-2147: Create S3 Bucket for CCW Testing

apps/bfd-pipeline/bfd-pipeline-ccw-rif/pom.xml, apps/bfd-server/bfd-server-war/pom.xml, apps/bfd-server/pom.xml, apps/pom.xml, apps/rules.xml
[BFD-2199](https://jira.cms.gov/browse/BFD-2199)
This PR addresses several library/dependency updates. 
SNYK and Performance Test Results:
- Performance regression tests were conducted on both this branch with upgraded dependency versions, and the master branch on TEST server. The number of requests differed by 3.61%, and the average number of requests/second differed by 3.68%.
<details>
<summary>
TEST Server Master Branch
</summary>
```
Type     Name                                                                          # reqs      # fails \|    Avg     Min     Max    Med \|   req/s  failures/s
--
--------\|----------------------------------------------------------------------------\|-------\|-------------\|-------\|-------\|-------\|----- …
```
=> BFD-2199: Upgrade Out of Date Dependencies

insights/terraform/projects/bfd/api-requests/lambda_src/bfd-cw-to-flattened-json.py, runbooks/how-to-investigate-firehose-ingestion-processing-failures.md
[BFD-2205](https://jira.cms.gov/browse/BFD-2205)
As a BFD Engineer, I want to better understand the root-cause for the two BFD Insights error files
that were reported on 10/17/2022, so I can determine what next steps are required to either resolve
or mitigate the issue.
---
This PR updates the `bfd-cw-to-flattened-json.py` to the newest
`kinesis-firehose-cloudwatch-logs-processor-python` Lambda blueprint by retrofitting the changes we
had made to this new version. We made very few changes to the original blueprint, so much of the
changes are from AWS -- specifically, the Lambda no longer has a hard 6 MB limit for incoming data.
This was the only case where data could be marked as `processing-failed` in the original blueprint,
and so once …
=> BFD-2205: Update bfd-cw-to-flattened-json.py to resolve processing failures and add runbook for investigating Kinesis delivery stream failures

README.md
[BFD-1923](https://jira.cms.gov/browse/BFD-1923)
Update Read Me File
---
Update Read Me …
=> BFD-1923: Update readme file

apps/bfd-db-migrator/src/main/java/gov/cms/bfd/migrator/app/MigratorApp.java
[BFD-2243](https://jira.cms.gov/browse/BFD-2243)
As a BFD Engineer, I'd like the migrator service to no longer generate PID files so that the only files created are relevant to the service needs.
---
Removes the PID file generation from the migrator since it is no longer used, to ease local builds from having many pid files stack up. …
=> BFD-2243: Remove pid file generation from migrator

ops/terraform/env/mgmt/synthea.tf
[BFD-2135](https://jira.cms.gov/browse/BFD-2135)
As a BFD Engineer I would like to have the aws bucket relating to required synthea files to be recreatable in the event the bucket is lost so that I can quickly recover from a failure scenario.
---
Adds the bucket creation for bfd-mgmt-synthea, along with the group policy, permissions, and attachments related to accessing the bucket for the synthea devs.
Also moves the synthea TF script to the MGMT environment location.
Updated the s3 util script used for synthea automation to the new bucket.
Noted terraform has been applied and verified in AWS console, and looks good.
* Verify all PR security questions and checklists …
=> BFD-2135: Add synthea bucket and group creation to terraform

insights/terraform/modules/bucket/main.tf, insights/terraform/modules/bucket/variables.tf, insights/terraform/modules/firehose/outputs.tf, insights/terraform/projects/bb2/base_config/backend.tf, insights/terraform/projects/bb2/base_config/main.tf
[BFD-2189](https://jira.cms.gov/browse/BFD-2189)
Use Bucket Key for BFD Insights bucket
---
This PR makes the lightest touch possible for the existing bucket+kms module in the insights hierarchy, only targeting bfd-insights-bfd. I'm including @StewGoin as a reviewer for further awareness and completeness. However, we've already informally discussed this in brief.
This includes changes to the BFD and BB2 Insights buckets, hence changes to the `base_config` BB2 module. However, these changes should also be applicable to the BCDA insights bucket, too.
Submitters should complete the …
=> BFD-2189: Use Bucket Key for BFD Insights

insights/terraform/projects/bfd/common/main.tf
[BFD-2192](https://jira.cms.gov/browse/BFD-2192)
Encodes AWS S3 Bucket Inventories with Terraform.
---
Strictly speaking, the AC was met through a more manual, click-ops approach. And now that the work supporting BFD-2189 is done (as part of #1449), these inventories are no longer necessary, disabled in perpetuity. However, there are just a few dozen lines of code here that will be very helpful in producing similar results for other re-encryption efforts when enabling AWS S3 BucketKeys in the near future, e.g. the bfd-insights-bb2 bucket is a very candidate for this process to reduce ongoing development costs.
* Verify all PR security questions and checklists have been …
=> BFD-2192: Add select AWS S3 Bucket Inventories

ops/terraform/services/base/values/test.yaml
Turning off the RDA API pipeline jobs in the TEST environment
---
Replace me.
* If the answer to any of the questions below is **Yes**, …
=> BFD-2258: Disable RDA pipeline in test

Jenkinsfile, rfcs/0011-separate-flyway-from-pipeline.md, runbooks/how-to-recover-from-migrator-failures.md
[BFD-1557](https://jira.cms.gov/browse/BFD-1557)
Introduce migrator runbook
---
Here, we're introducing a runbook that operators might reference when encountering problems during migrator deployments. In doing so, we can transition [RFC#0011](https://github.com/CMSgov/beneficiary-fhir-data/blob/master/rfcs/0011-separate-flyway-from-pipeline.md) to an **Implemented** status.
* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security …
=> BFD-1557: Introduce migrator runbook

.github/CODEOWNERS
[BFD-2263](https://jira.cms.gov/browse/BFD-2263)
---
Updates CODEOWNERS to reflect team changes.
* If the answer to any of …
=> BFD-2263: Update codeowners file

ops/terraform/modules/resources/bfd_cw_dashboards/templates/bfd-dashboard-slos.tftpl, ops/terraform/modules/resources/bfd_server_slo_alarms/main.tf
[BFD-2247](https://jira.cms.gov/browse/BFD-2247)
As a BFD Engineer, I need alerts to be actionable so that I can investigate and fix those that are
relevant and warrant action
---
This PR:
- Updates the following SLO thresholds as they were incorrectly calculated to be much lower than
necessary:
- `/v*/fhir/Patient by_contract=false 15-minute 99th Percentile (BULK) Latency`
- `WARNING` threshold increased from 110 ms to 585 ms
- `/v*/fhir/Patient by_contract=false 15-minute 99th Percentile (NON-BULK) Latency`
- `WARNING` threshold increased from 110 ms to 520 ms
- `ALERT` threshold increased from 160 ms to 740 ms
- Splits the existing error rate SLO into _two_ SLOs; one with a high threshold over a 1 hour
period, and one with the existing …
=> BFD-2247: Update some Patient SLO thresholds, and improve error SLOs and implementation

.github/workflows/ci-ansible.yml, .github/workflows/ci-base-container-image.yml, .github/workflows/ci-java.yml, .github/workflows/ci-rust.yml, .github/workflows/ci-terraform.yml
=> Use ubuntu-20.04

.github/workflows/ci-ansible.yml, .github/workflows/ci-base-container-image.yml, .github/workflows/ci-java.yml, .github/workflows/ci-rust.yml, .github/workflows/ci-terraform.yml
[BFD-2296](https://jira.cms.gov/browse/BFD-2296)
Github Actions (GHA) are throwing warnings and failing due to a recent upgrade to ubuntu-22.04.
* upgrades a subset of actions to more recent versions that target Node16, e.g. actions/checkout@v2 to actions/checkout@v3
* pins to ubuntu-20.04, effectively a downgrade from the [automatic ubuntu-22.04](https://github.blog/changelog/2022-12-01-github-actions-larger-runners-using-ubuntu-latest-label-will-now-use-ubuntu-22-04/)
Verify efficacy and completeness of changes.
* Does this PR …
=> BFD-2296: Upgrade GitHub Actions

ops/terraform/modules/resources/asg/main.tf, ops/terraform/modules/resources/ec2/main.tf, ops/terraform/services/migrator/README.md, ops/terraform/services/migrator/data-sources.tf, ops/terraform/services/migrator/main.tf, ops/terraform/services/pipeline/README.md, ops/terraform/services/pipeline/data-sources.tf, ops/terraform/services/pipeline/main.tf
[CLDSPT-38315](https://jiraent.cms.gov/browse/CLDSPT-38315)
Fix nessus connectivity.
---
Attaches the CMS ent tools security group in all environments to re-enable nessus scans.
- Adds and attaches the security group to the migrator and pipeline services
- Re-attaches to stateless ec2 resources
- I also ran terraform fmt on changed files and updated terraform-docs for the migrator and pipeline services. …
=> CLDSPT-38315: Ensure enterprise tools connectivity (CMS)

ops/ansible/roles/bfd-pipeline/templates/bfd-pipeline-service.sh.j2, ops/terraform/services/base/values/ephemeral.yaml, ops/terraform/services/base/values/prod-sbx.yaml, ops/terraform/services/base/values/prod.yaml, ops/terraform/services/base/values/test.yaml
[PACA-810](https://jira.cms.gov/browse/PACA-810)
Enable micrometer metrics collection for production environments
---
* adds micrometer configuration for bfd-pipeline
* enables micrometer cloudwatch collection in `prod-sbx` and `prod`
**Note**: I've evaluated the resultant image and application of the bfd-pipeline role in the lower `test` environment and this functions as intended. This continues to be limited in scope as we evaluate micrometer-to-cloudwatch.
* If the answer to any of the questions below is **Yes**, then **you …
=> PACA-810: Add prod micrometer metrics collection

.github/workflows/ci-java.yml
[BFD-2277](https://jira.cms.gov/browse/BFD-2277)
Temporarily (or potentially indefinitely) disable the fhir-validations as part of the ci-java workflows.
---
This disables the fhir-validations that present dubious value to the product at this point. In the near future, we need to take the fhir-validation more seriously, potentially moving the validations _further left_ or earlier in the process as part of regular integration testing. Currently, this is only serving to block largely completed work. …
=> BFD-2277: Disable CI fhir validations

ops/terraform/services/pipeline/cloudwatch.tf
[BFD-2327](https://jira.cms.gov/browse/BFD-2327)
Disable/Disallow automatic resolution of bfd-pipeline alerts–the ETL process is not self-recovering or _autonomic_. If it encounters a failure, the current implementation requires an operator to clear the fault before it can be considered resolved.
---
This seeks to remove the OK actions from the two alarms associated with the pipeline service which prevents the CloudWatch Alarm from self-resolving after the 5-minute evaluation period.
This is in response to three recent, automatically self-resolving pipeline failures where the alarm wasn't lengthy enough to alert the primary, secondary on-call engineers.
Under normal circumstances, when the CCW Rif processing encounters a fault, it causes the …
=> BFD-2327: Disable automatic resolution in pipeline

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/TransformerUtilsV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/TransformerUtils.java
[BFD-2255](https://jira.cms.gov/browse/BFD-2255)
Remove log entry for NPI, causing the logs to be bloated.
---
Removed the log entry for the missing npi number in a static file
* Does this PR store or …
=> BFD-2255: Remove log entries for NPI Code Display.

apps/bfd-model/bfd-model-dsl-codegen/bfd-model-dsl-codegen-plugin/pom.xml, apps/bfd-server/bfd-server-launcher/pom.xml, apps/bfd-server/bfd-server-war/pom.xml, apps/bfd-server/pom.xml, apps/pom.xml
[BFD-2309](https://jira.cms.gov/browse/BFD-2309)
This PR addresses several library/dependency updates. 
SNYK and Performance Test Results:
- Performance regression tests were conducted on both this branch with upgraded dependency versions, and the master branch on TEST server. The number of requests differed by 1.05%, and the average number of requests/second differed by 0.29%.
<details>
<summary>
TEST Server Master Branch
</summary>
```
Type     Name                                                                          # reqs      # fails \|    Avg     Min     Max    Med \|   req/s  failures/s
--
--------\|----------------------------------------------------------------------------\|-------\|-------------\|-------\|-------\|-------\|----- …
```
=> BFD-2309: Upgrade Out of Date Dependencies

ops/terraform/services/base/values/prod.yaml
[BFD-2218](https://jira.cms.gov/browse/BFD-2218)
Disable production RIF loader until the _New Year Issue_ has been resolved.
---
This PR disables the production CCW RIF loader job in the BFD ETL pipeline.
* Does this PR modify or invalidate any of our security …
=> BFD-2218: Disable Production RIF Loader

ops/deploy-ccs.groovy, ops/packer/build_bfd-all.json
[BFD-2334](https://jira.cms.gov/browse/BFD-2334)
This is a temporary stop-gap effort to alleviate the immediate concerns posed by BFD-2334 by disabling the bfd-server-load AMI builds in the current build-deliver-deploy Jenkins pipeline. A subsequent change set and PR will correct the underlying issue.
---
This PR disables (removes) the logic for building new bfd-server-load AMIs. This
* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), …
=> BFD-2334: Disable bfd-server-load AMI builds

ops/terraform/services/migrator/README.md, ops/terraform/services/migrator/data-sources.tf, ops/terraform/services/migrator/deploy.groovy, ops/terraform/services/migrator/main.tf, ops/terraform/services/migrator/variables.tf, ops/terraform/services/pipeline/cloudwatch.tf, ops/terraform/services/pipeline/data-sources.tf, ops/terraform/services/pipeline/main.tf
[BFD-2276](https://jira.cms.gov/browse/BFD-2276)
Support BFD-2198 et al through further updates to the ephemeral environment creation process.
---
This is a collection of changes that make supporting the ephemeral 2276 environment (used in testing changes for BFD-2198 and BFD-2277) possible without considerable amounts of manual intervention. …
=> BFD-2276: Support to year-end CCW change testing

ops/ansible/roles/bfd-pipeline/defaults/main.yml, ops/ansible/roles/bfd-pipeline/templates/bfd-pipeline-service.sh.j2, ops/terraform/services/base/values/ephemeral.yaml, ops/terraform/services/base/values/prod-sbx.yaml, ops/terraform/services/base/values/prod.yaml, ops/terraform/services/base/values/test.yaml
[BFD-2265](https://jira.cms.gov/browse/BFD-2265)
Handle operations/deployment considerations for updated pipeline filtering configuration.
---
This is a modest adjustment to the pipeline filtering from the ansible and terraform perspectives updating the ansible variable and environment variable to match the new expectations of the bfd-pipeline ETL application. …
=> Update pipeline filtering configuration for 2023

ops/terraform/env/prod-sbx/stateless/main.tf, ops/terraform/env/prod/stateless/main.tf, ops/terraform/env/test/stateless/main.tf, ops/terraform/modules/resources/bfd_cw_dashboards/main.tf, ops/terraform/modules/resources/bfd_cw_dashboards/templates/bfd-dashboard-slos.tftpl, ops/terraform/modules/resources/bfd_server_slo_alarms/data-sources.tf, ops/terraform/modules/resources/bfd_server_slo_alarms/main.tf, ops/terraform/modules/resources/cw_alarms_slack_notifier/lambda-src/cw_alarms_slack_notifier.py
[BFD-2323](https://jira.cms.gov/browse/BFD-2323)
As a BFD Engineer, I would like the Latency SLO Dashboards and Slack alerts to conform to our naming
standards and also be more immediately actionable.
---
This PR:
- Adds links to each BFD Server CloudWatch Dashboard for each SLO Alarm such that when Alarms are
posted to Slack the on-call engineer can immediately view the Dashboard from said alert
- Adds the ASG Instance Count and CPU Utilization visuals to the SLO CloudWatch Dashboards to make
it easier to cross-check scaling events and server load against SLOs
- Updates the naming scheme of the BFD Server dashboards to follow `bfd-<env>-<svc>`
- Fixes some outdated SLO threshold visuals in some Patient graphs in the SLO Dashboards
- The …
=> BFD-2323: Improve Latency SLO Slack Alerts and improve existing CloudWatch Dashboards

.github/workflows/ci-java.yml, ops/terraform/env/mgmt/github-actions-iam.tf
[BFD-2347](https://jira.cms.gov/browse/BFD-2347)
Implement and Utilize an AWS OIDC Provider with Github Actions
---
This change set includes:
* a definition for an AWS OIDC provider for use with Github Actions
* an AWS OIDC provider-assumable AWS IAM Role with policies appropriate for the existing integration tests
* updates to the GHA workflow to make use of the newly defined OIDC provider-based authentication model
* removal of the soon to be outdated AWS IAM resources used by Github Actions
The change set here generally follows github's [deployment security hardening with OIDC in AWS guide](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services) using terraform …
=> BFD-2347: Implement, Utilize GHA-AWS OIDC Provider

ops/terraform/modules/resources/bfd_server_slo_alarms/main.tf
[BFD-2332](https://jira.cms.gov/browse/BFD-2332)
As a BFD/on-call Engineer, I would like the alerts received from percentile-based SLO alarms to be
accurate such that the alerts are actionable and indicate some sort of anomalous behavior.
---
This PR updates all of the percentile-based CloudWatch SLO Alarms in the `bfd_server_slo_alarms`
Terraform module to specify that they should not evaluate if there is a low number of samples. This
should help to alleviate false positive alarming that we have seen from time-to-time with these
alarms as they would often alarm with too few samples. …
=> BFD-2332: Update existing percentile CloudWatch SLO Alarms to not evaluate with a small sample size

.github/CODEOWNERS
[BFD-2352](https://jira.cms.gov/browse/BFD-2352)
Add Daryll Pierre as a PACA CODEOWNER.
---
This adds @daryll to the CODEOWNERS file for the relevant PACA code paths.
* Does this PR store or transmit …
=> BFD-2352: Add Daryll Pierre as a PACA CODEOWNER

apps/bfd-data-npi/pom.xml, apps/pom.xml
[BFD-2314](https://jira.cms.gov/browse/BFD-2314)
As a BFD Engineer I would like to have an automated checkstyle process in place for the BFD javadocs so that the code is documented, automatically checked for static javadoc issues, and reviewers can focus on elements of code that need human focus.
AC:
Checkstyle is enabled for the bfd-data-npi module
All checkstyle errors in the bfd-data-npi module are corrected
---
Add checkstyle to npi project
* If the answer to any of the questions below is **Yes**, then **you must** supply a …
=> BFD-2314: Add checkstyle to npi project

apps/bfd-data-fda/pom.xml, apps/pom.xml
[BFD-2313](https://jira.cms.gov/browse/BFD-2313)
As a BFD Engineer I would like to have an automated checkstyle process in place for the BFD javadocs so that the code is documented, automatically checked for static javadoc issues, and reviewers can focus on elements of code that need human focus.
AC:
Checkstyle is enabled for the bfd-data-fda module
All checkstyle errors in the bfd-data-fda module are corrected
---
Added java docs and checkstyle to fda project
* If the answer to any of the questions below is **Yes**, then **you …
=> BFD-2313: Added checkstyle to fda project

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/LoadedFileFilter.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/LoadedFilterManager.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/OffsetLinkBuilder.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/PatientLinkBuilder.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/QueryUtils.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4CoverageResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4ExplanationOfBenefitResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4PatientResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/pac/AbstractR4ResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/CoverageResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/ExplanationOfBenefitResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProvider.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/commons/OffsetLinkBuilderTest.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/R4CoverageResourceProviderIT.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/R4CoverageResourceProviderTest.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/R4ExplanationOfBenefitResourceProviderIT.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/R4ExplanationOfBenefitResourceProviderTest.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/R4PatientResourceProviderIT.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/R4PatientResourceProviderTest.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/CoverageResourceProviderTest.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/ExplanationOfBenefitResourceProviderIT.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/ExplanationOfBenefitResourceProviderTest.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/PatientLinkBuilderTest.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProviderIT.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProviderTest.java, apps/bfd-server/bfd-server-war/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
[BFD-2299](https://jira.cms.gov/browse/BFD-2299)
As a BFD User, I would like the application to give back more useful http status codes and errors in the event that I have given an invalid input to one of the BFD endpoints.
---
Changes a number of spots where we would previously throw an `IllegalArgumentException` that would return a 500 into `InvalidRequestException` instead, which will throw a 400 error. Also corrects a number of error messages to be more user friendly and adds a bunch of test coverage for these scenarios.
- Replace `IllegalArgumentException` with `InvalidRequestException` in scenarios where the user input has caused the issue and can be corrected
- Improved some messages to be more helpful with what the issue is and/or …
=> BFD-2299: Replace 500 errors with 400 errors where appropriate and update error messaging

ops/terraform/services/base/values/prod.yaml
[BFD-2219](https://jira.cms.gov/browse/BFD-2219)
Return to normal operation of the bfd-pipeline's CCW rif loader after the testing, adoption, and enablement of the v10 rif manifest schema as part of #1521.
---
Enable CCW rif load jobs in production.
* Does this PR …
=> BFD-2219: Re-enable Regular CCW Data Loads

ops/jenkins/bfd-run-synthea-generation/Jenkinsfile
[BFD-2410](https://jira.cms.gov/browse/BFD-2410)
The Jenkins pipeline for running Synthea generation, `bfd-run-synthea-generation`, is failing to
upload the post-generation `end_state.properties` file to the correct place in the
`bfd-mgmt-synthea` S3 bucket. This is due to an error in the path specified for the
`end_state.properties` file as the path to the file is specified to be in the `output/` directory,
which does not exist, instead of the `out/` directory.
---
This PR fixes a mistake in the path specified to the final `end_state.properties` during the `Update
Old end_state.properties` stage that was causing the stage to fail as the file could not be found
and therefore could not be uploaded to S3. Additionally, an oversight with AWS …
=> BFD-2410: Jenkins pipeline for Synthea generation fails to properly update end_state.properties in S3

.github/workflows/ci-runbook.yml, ops/terraform/services/common/README.md, ops/terraform/services/common/data-sources.tf, ops/terraform/services/common/outputs.tf, ops/terraform/services/common/scripts/rds-cluster-config.sh, runbooks/README.md, runbooks/how-to-clone-rds-cluster-with-terraform.md
[BFD-2090](https://jira.cms.gov/browse/BFD-2090)
Adds runbook for cloning/restoring RDS clusters with terraform.
---
This PR introduces a runbook as well as some _minor_ functional improvements to the `common` terraservice to facilitate using this runbook locally. The runbook covers cloning RDS clusters from snapshots using the `base` and `common` terraservices for a faithful reproduction of a targeted or seed environment's data store.
Further, this change set makes a minor adjustment to the `CI - Runbook` GitHub Actions workflow to use a [filter pattern](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet) that runs on changes targeting files immediately under the `runbooks/` …
=> BFD-2090: Add Runbook for RDS Cluster Cloning

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/QueryLoggingListener.java, ops/terraform/modules/resources/bfd_server_log_alarms/main.tf, ops/terraform/modules/resources/bfd_server_metrics/main.tf
[BFD-1872](https://jira.cms.gov/browse/BFD-1872)
Identify and address unknown SQL Queries in bfd-server.
---
This change set identifies one remaining query that was previously _unknown_ to the `QueryLoggingListener` in bfd-server. This also captures instances of unknown queries from the application logs as a metric in CloudWatch.
Specifically, the unknown query addressed here is an _administrative_ query required by hibernate that probes for the associated database's support for sequences, i.e. `select * from information_schema.sequences`.
In the future, when bfd-server encounters an unknown query, engineers should be notified of a missing pattern from the QueryLoggingListener.
This was identified with a query similar to the following in …
=> BFD-1872: Address unknown SQL Queries

apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/CcwRifLoadPreValidateSynthea.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoaderIT.java
[BFD-2158](https://jira.cms.gov/browse/BFD-2158)
Fixes some bugs preventing loading of synthetic test data due to errors in the pipeline pre-validation check queries.
---
- Fixed one of the pre-validation queries which did not have a count() like the rest (this was causing the validation part to fail since it was assuming they were all count queries)
- Fixed the validation to accept both count and non-count queries (just to clean it up a little)
- Fixed a query which was checking that both pde AND clm_grp_id were invalid in order to trip a validation failure; the tests were written assuming it was an OR, and my understanding matches that it should fail if either are invalid, so I adjusted the query to use OR
- Fixed a piece of the test which …
=> BFD-2158: Fixes for synthetic data pre-validation checks in pipeline

runbooks/how-to-run-synthea-automation.md
[BFD-2357](https://jira.cms.gov/browse/BFD-2357)
Updates the synthea runbook documentation to reflect the current state of the synthea automation.
---
- Adds the correct link to the synthea generation automation job
- Adds more accurate automation job parameters and descriptions
- Add explanation for the end state properties file
- Add manual steps needed for data loading using generated data
- Add manual steps needed for loading future data
- Updated troubleshooting to refer to Synthetic/Failed location as a holding ground for failed loads …
=> BFD-2357: Currency adjustments to the Synthea automation runbook

ops/terraform/services/pipeline/README.md, ops/terraform/services/pipeline/main.tf, ops/terraform/services/pipeline/modules/bfd_pipeline_slis/README.md, ops/terraform/services/pipeline/modules/bfd_pipeline_slis/data-sources.tf, ops/terraform/services/pipeline/modules/bfd_pipeline_slis/main.tf, ops/terraform/services/pipeline/modules/bfd_pipeline_slis/variables.tf
[BFD-2405](https://jira.cms.gov/browse/BFD-2405)
Addenda to support Pipeline SLIs in Ephemeral Environments.
---
Building off the success of @malessi's work in BFD-2405, I've made some modest adjustments to support ephemeral environments. …
=> BFD-2405: Pipeline SLI Ephemeral Support

ops/Dockerfile, ops/ansible/playbooks-ccs/ansible.cfg, ops/ansible/playbooks-ccs/build_bfd-platinum.yml, ops/ansible/playbooks-ccs/roles/platinum/tasks/install-dependencies.yml, ops/ansible/playbooks-ccs/roles/platinum/tasks/install-python3.yml, ops/ansible/playbooks-ccs/roles/platinum/tasks/main.yml, ops/ansible/roles/bfd-db-migrator/tasks/migrator.yml, ops/ansible/roles/bfd-db-migrator/test/ansible.cfg, ops/ansible/roles/bfd-db-migrator/test/test_basic.yml, ops/ansible/roles/bfd-pipeline/tasks/etl.yml, ops/ansible/roles/bfd-pipeline/test/ansible.cfg, ops/ansible/roles/bfd-server-load/tasks/server-load.yml, ops/ansible/roles/bfd-server-load/test/ansible.cfg, ops/ansible/roles/bfd-server-load/test/test_basic.yml, ops/ansible/roles/bfd-server/tasks/install.yml, ops/ansible/roles/bfd-server/test/ansible.cfg, ops/packer/build_bfd-all.json, ops/packer/build_bfd-db-migrator.json, ops/packer/build_bfd-pipeline.json, ops/packer/build_bfd-platinum.json, ops/packer/build_bfd-server-load.json, ops/packer/build_bfd-server.json
[BFD-1890](https://jira.cms.gov/browse/BFD-1890)
Use python3.9 as default python interpreter in ansible.
---
First, this PR explicitly encodes python3 as the interpreter by default where possible. Unfortunately, the built-in yum module in ansible only supports python2, so we're overriding for python2 support as necessary.
Further, we've determined that the amazonlinux2 included python3.7 (as well as the python3.8 available through epel and amazon-linux-extras) is insufficient for the recent adjustments to the python-based locust test suites. To more fully accommodate those changes, we're going out of our way to build python 3.9.16 from source for inclusion in both the platinum AMI and the ansible base container images.
Finally, we're …
=> BFD-1890: Use python3 interpreter for ansible

apps/pom.xml
[BFD-2454](https://jira.cms.gov/browse/BFD-2454)
As an Engineer, I want to ensure the New Relic Java Agent agent is up-to-date with the latest security patches and bug fixes to prevent potential security vulnerabilities and ensure my application is able to report metrics as expected.
---
- Bumps New Relic Java Agent from 8.0.0 -> 8.0.1
- Removes trailing whitespace in apps/pom.xml as formatted by my IDE …
=> BFD-2454: Bump New Relic agent to 8.0.1

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/TransformerUtilsV2.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/HospiceClaimTransformerV2Test.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/TransformerUtilsV2Test.java
[BFD-2455](https://jira.cms.gov/browse/BFD-2455)
User Story:
These functions do not currently have any unit tests for the contained resource for organization.
CARIN Confluence Page - https://confluence.cms.gov/display/BFD/CARIN+Conformance+-+Eob
---
Adds more hardening to our system by adding unit tests for the contained organization. …
=> BFD-2455: Unit tests for the contained resource for organization

ops/terraform/services/base/values/prod-sbx.yaml, ops/terraform/services/base/values/prod.yaml
[BFD-2195](https://jira.cms.gov/browse/BFD-2195)
---
This enables the option to implement IAM DB auth in the upper environments, it does not actually implement it. That will be done in follow-up work.
The changes will be applied during the next database-maintenance.
* …
=> BFD-2195: Enable IAM DB auth in upper environments

ops/terraform/env/mgmt/jenkins-iam.tf
[BFD-2469](https://jira.cms.gov/browse/BFD-2469)
The Jenkins IAM role does not specify any permissions for Athena which has caused issues with deployment as the work done in BFD-2301 requires that the role that is applying the new athena_views Terraform module has the appropriate permissions to execute and monitor Athena queries.
---
This PR updates the Jenkins IAM role policy to include permissions to _all_ `Athena` resources. This resolves the deployment issues stemming from Jenkins not having the appropriate permission to deploy the new Athena Views module. 
Note that the overly-permissive nature of the Jenkins IAM role policy will be tightened up in BFD-2468. These changes are strictly to immediately resolve the issue and nothing more. …
=> BFD-2469: Include athena permissions in Jenkins role

ops/ccs-ops-misc/synthetic-data/scripts/synthea-automation/split-future-claims.py
[BFD-2158](https://jira.cms.gov/browse/BFD-2158)
Fixes a tiny bug where the manifest split script was still using v9 instead of v10.
---
Fixes the split script to generate a manifest with v10 instead of v9.
* Does this PR modify or invalidate any of our security …
=> BFD-2158: Fix synthea split script to use v10 manifest

ops/terraform/modules/resources/bfd_cw_dashboards/templates/bfd-dashboard-slos.tftpl, ops/terraform/modules/resources/bfd_server_slo_alarms/main.tf
[BFD-2475](https://jira.cms.gov/browse/BFD-2475)
---
This PR updates the Warning and Alert thresholds for the 1 hour Error SLO from 50% and 90% to 1% and
10%, respectively. This ensures that anomalous errors are caught more immediately.
Once approved, the changes to the SLOs will be immediately applied to Terraform state and will
additionally be updated in the corresponding BFD SLOs Confluence page.
- If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact …
=> BFD-2475: Significantly reduce Alert and Warning thresholds for 1 hour 500 errors SLO

apps/bfd-model/bfd-model-rda/mappings/FissClaim.yaml, apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V105__rda_0_12_0_hotfix2.sql, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/server/RandomFissClaimGenerator.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/FissClaimTransformerTest.java
[PACA-984](https://jira.cms.gov/browse/PACA-984)
---
The fiss_claims.clm_typ_ind should be marked as nullable, as this is a `oneof` property in the proto files that won't always be set.
* Does this PR …
=> PACA-984: RDA 0.12 hotfix 2

ops/terraform/services/base/values/prod-sbx.yaml, ops/terraform/services/base/values/prod.yaml, ops/terraform/services/base/values/test.yaml
[PACA-987](https://jira.cms.gov/browse/PACA-987)
---
Enable the DLQ for the RDA pipeline in all environments
* If the …
=> PACA-987: Enable DLQ in all environments

rfcs/0015-centralized-configuration-management.md
[BFD-1639](https://jira.cms.gov/browse/BFD-1639)
Update the Centralized Configuration Management RFC's status to `Implemented`.
---
The single-line change in this PR represents the completion of the substantive work involved in adoption of a centralized configuration management strategy with AWS SSM Parameter Store.
Is the RFC properly updated and configuration management reflects SSM parameter changes? …
=> BFD-1639: Implement SSM Configuration Management

ops/terraform/services/server/server-regression/iam.tf
[BFD-2500](https://jira.cms.gov/browse/BFD-2500)
As a BFD engineer I want the "aws_iam_policy" "rds" resource value updated in iam.tf in ops/terraform/services/server/server-regression, so that code deployments are functional. 
---
Deployments are not functional. The aws_iam_policy rds resource value must be updated in the server-regression iam.tf file to fix this.
Is there anything else outstanding that might hinder the deployment from working again?
* If the answer to any of the questions below is **Yes**, then **you must** …
=> BFD-2500: Update AWS IAM RDS Policy Resource

apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/MessageError.java, apps/bfd-model/bfd-model-rda/src/main/java/gov/cms/bfd/model/rda/RdaClaimMessageMetaData.java, apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V108__change_claim_id_length_rda.sql
[PACA-1002](https://jira.cms.gov/browse/PACA-1002)
---
Fix the length of the claimID field in the meta data entity to allow proper insertion of data.
* Does this PR store or transmit data that was not …
=> PACA-1002: Fix claimId length in meta data entity

apps/bfd-model/bfd-model-dsl-codegen/bfd-model-dsl-codegen-plugin/pom.xml, apps/bfd-pipeline/bfd-pipeline-rda-bridge/pom.xml, apps/pom.xml
[PACA-1003](https://jira.cms.gov/browse/PACA-1003)
Snyk complained of security vulnerabilities in `snakeyaml` version 1.33.  That version was a transitive dependency from `jackson-dataformat-yaml` version 2.14.2.  
---
Sets an explicit version for `snakeyaml` that overrides the implicit one in `jackson-dataformat-yaml` so that version 2.0 is used instead of 1.33.  All tests pass with this change in place.
Also removes the `name` element from the rda-bridge pom file.  No other project uses an explicit name so maven  displayed output related to that project differently than all other projects which created unnecessary confusion.
Verified the version change:
```
$ mvn dependency:tree|grep snake
[INFO] |  +- org.yaml:snakeyaml:jar:2.0:compile …
```
=> PACA-1003: Override snakeyaml dependency to version 2.0.

ops/ccs-ops-misc/synthetic-data/scripts/synthea-automation/.dockerignore, ops/ccs-ops-misc/synthetic-data/scripts/synthea-automation/.gitignore, ops/ccs-ops-misc/synthetic-data/scripts/synthea-automation/Dockerfile, ops/ccs-ops-misc/synthetic-data/scripts/synthea-automation/build_docker.sh, ops/ccs-ops-misc/synthetic-data/scripts/synthea-automation/prepare-and-run-synthea.py, ops/ccs-ops-misc/synthetic-data/scripts/synthea-automation/run_synthea_locally.sh, ops/ccs-ops-misc/synthetic-data/scripts/synthea-automation/s3_utilities.py
…gle national script)
[BFD-2457](https://jira.cms.gov/browse/BFD-2457)
Removes the synthea national V2 script from the automation scripts and related docker files.
---
Removes the V2 synthea script references from the automation script(s), since only one script (the unversioned national script) will be used and updated from now on.
* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence …
=> BFD-2457: Remove V2 synthea script in automation

ops/terraform/modules/resources/bfd_server_metrics/main.tf
[BFD-2487](https://jira.cms.gov/browse/BFD-2487)
The claim filters do not accurately provide the number of requests for a given claim due to the endpoint descriptions. 
---
The Claim filter is including ClaimResponse due to Claims being filtered somewhat naively via Claim* and ClaimResponse*. For that reason the bfd server metrics main terraform file is updated with the proper fully qualified endpoint request specifications.
Are the number of requests for a given claim now accurate? …
=> BFD-2487: Update Claim Filter Endpoints

apps/bfd-db-migrator/src/main/java/gov/cms/bfd/migrator/app/MigratorApp.java, apps/bfd-db-migrator/src/test/java/gov/cms/bfd/migrator/app/MigratorAppIT.java, apps/bfd-db-migrator/src/test/java/gov/cms/bfd/migrator/app/RdaSchemaMigrationIT.java, apps/bfd-shared-test-utils/src/main/java/gov/cms/bfd/DatabaseTestSchemaManager.java, apps/bfd-shared-test-utils/src/main/java/gov/cms/bfd/DatabaseTestUtils.java, apps/bfd-shared-utils/src/main/java/gov/cms/bfd/sharedutils/database/DatabaseSchemaManager.java, apps/pom.xml, ops/Dockerfile
[BFD-2151](https://jira.cms.gov/browse/BFD-2151)
This supports the flyway 8-to-9 upgrade, including necessary changes to accommodate that new version.
---
This PR includes support for flyway 9. Here are some notable differences:
* As of _at least_ flyway 9.1.2 (see [here](https://github.com/flyway/flyway/issues/3497) and [here](https://github.com/flyway/flyway/commit/022a646b7959aa7a9a11760d8e93e5e238fbd6ec)) flyway defaults to enabling transactional locks
* `baselineOnMigrate` must be set to true to behave like flyway 8
* the clean method in flyway 9 is less effective (potentially behind some Flyway Teams features?) when attempting to return the containerized postgresql container to a known state; we've elected to provide further isolation …
=> BFD-2151: Upgrade flyway

ops/terraform/services/pipeline/README.md, ops/terraform/services/pipeline/main.tf, ops/terraform/services/pipeline/modules/bfd_pipeline_slo_alarms/.terraform-docs.yml, ops/terraform/services/pipeline/modules/bfd_pipeline_slo_alarms/README.md, ops/terraform/services/pipeline/modules/bfd_pipeline_slo_alarms/data-sources.tf, ops/terraform/services/pipeline/modules/bfd_pipeline_slo_alarms/get_est_or_edt.sh, ops/terraform/services/pipeline/modules/bfd_pipeline_slo_alarms/main.tf, ops/terraform/services/pipeline/modules/bfd_pipeline_slo_alarms/variables.tf, ops/terraform/services/pipeline/variables.tf
[BFD-2496](https://jira.cms.gov/browse/BFD-2496)
As a BFD Engineer, I want to know when the BFD is out of SLO for the pipeline, so that I know when there is an issue that requires prompt action by the BFD team.
---
This PR adds a new module to the `pipeline` Terraservice, `bfd_pipeline_slo_alarms`, that creates CloudWatch Alarms for each of our BFD Pipeline SLOs:
- Alarms covering our `Time to ingest a weekly batch load once available in S3` SLO; one alarm for the `Warning` threshold of 36 hours and another for the `Alert` threshold of 24 hours
- An alarm covering our `Weekend data load availability` SLO that will alarm if an ongoing data load exceeds Monday 9 AM EST/EDT
- This alarm will automatically handle `EST` vs `EDT` depending on if …
=> BFD-2496: Implement Pipeline SLO Alerts

apps/bfd-data-fda/Jenkinsfile, apps/bfd-data-npi/Jenkinsfile
[BFD-2551](https://jira.cms.gov/browse/BFD-2551)
Background:
We have some failures on the data oriented jobs likely due to outdated CBC images.
AC:
Data oriented Jenkins CI jobs build successfully in JDK 17
---
Updates the container image in the JenkinsFile for BFD-data libraries to java 17.  Tested on Jenkins using the replay mode with the new image and it builds successfully.
* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security …
=> BFD-2551: fix jenkins container image for bfd-data libraries

apps/bfd-server/README.md, apps/bfd-server/bfd-server-war/pom.xml, apps/bfd-server/bfd-server-war/src/main/config/server-start.sh, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/ServerInitializer.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/ServerExecutor.java, apps/pom.xml, contributing/docker/Dockerfile, ops/ansible/roles/bfd-server/defaults/main.yml, ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2, ops/ansible/roles/bfd-server/test/test_basic.yml, ops/terraform/services/base/values/prod-sbx.yaml, ops/terraform/services/base/values/prod.yaml, ops/terraform/services/base/values/test.yaml
[BFD-2546](https://jira.cms.gov/browse/BFD-2546)
Now that V2 is readily available, we no longer need include feature flags to check if it's enabled.
---
Since V2 is readily available publicly, the feature flags that toggle v2 on or off are no longer needed. This PR removes the logic and variables so that V2 functions just as V1 does when the BFD server is initialized.
Does this properly remove the feature flags at both the application and ansible/terraservice level?
* If the answer to any of the questions below is **Yes**, then …
=> BFD-2546: Remove V2 Feature Flag

ops/terraform/modules/resources/asg/main.tf, ops/terraform/services/migrator/main.tf, ops/terraform/services/pipeline/main.tf, ops/terraform/services/server/modules/bfd_server_asg/main.tf, ops/terraform/services/server/server-load/main.tf
[BFD-2193](https://jira.cms.gov/browse/BFD-2193)
Remediate Security Hub Findings _AWS Foundational Security Best Practices v1.0.0 EC2.8: EC2 instances should use Instance Metadata Service Version 2 (IMDSv2)_
---
This change requires that EC2 instances created by BFD infrastructure as code use the Instance Metadata Service v2 (IMDSv2) endpoints, which require session tokens.
Instance metadata access with this change:
**DO THIS**
```sh
TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` \
&& curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/
```
**DO NOT DO THIS**
```sh
curl http://169.254.169.254/latest/meta-data/
```
Fortunately, BFD infrastructure …
=> BFD-2193: Require IMDSv2 in EC2 Instances

apps/bfd-data-fda/Jenkinsfile, apps/bfd-data-fda/pom.xml, apps/bfd-data-npi/Jenkinsfile, apps/bfd-data-npi/pom.xml
[BFD-2581](https://jira.cms.gov/browse/BFD-2581)
User Story:
As a security engineer I want the maven javadoc-plugin to be removed from bfd artifacts so that we can avoid CVE-2018-1000632.
AC:
* Remove references to org.apache.maven.plugins:maven-javadoc-plugin@3.5.0 in bfd-data-fda and bfd-data-npi
* Existing data-oriented Jenkins jobs support overrides for forcing rebuilds
* The data-oriented artifacts are rebuilt and stored in the appropriate artifact repository
---
Remove references to org.apache.maven.plugins:maven-javadoc-plugin@3.5.0 in bfd-data-fda and bfd-data-npi.
Submitters …
=> BFD-2581: Remediate CVE-2018-1000632 in bfd-data-fda and bfd-data-npi

apps/pom.xml
[BFD-2566](https://jira.cms.gov/browse/BFD-2566)
User Story:
As a BFD contributor, I want the Java linting step to be moved from the pre-commit to the pre-push hook so that I can avoid the penalty of running the linter on every commit.
AC:
The Java linter executes automatically via pre-push hook
The other functionality of the existing pre-commit hook remains in tact
---
Removes the linter from pre-commit to pre push
Test Cases Verified
No remote exists, no files committed, just pushing branch	- Skip Formatter
No Remote Exists, no apps files commited	- Skip Formatter
No Remote Exists, apps files commited -	Run formatter
Remote Exists,  no apps files commited	- Skip Formatter
Remote Exists, apps files commited	- Run formatter
If you're …
=> BFD-2566: Fix pre-push git hook

Jenkinsfile, ops/jenkins/bfd-deploy-apps/Jenkinsfile, ops/terraform/services/base/values/test.yaml
[BFD-2567](https://jira.cms.gov/browse/BFD-2567)
User Story:
As a BFD release engineer, I want to common to be a part of the typical deployment pipeline so that I can deploy changes to the path-to-production envs without making special accommodations to common resources.
Background:
Common was introduced last summer but we neglected to add it to the deployment pipeline due to low change frequency
Without consistent deployments for common to the path-to-prod envs its highly likely that drift will/has develop(ed)
AC:
Existing deployment pipeline includes a stage for deploying the common Terraservice
---
Existing deployment pipeline includes a stage for deploying the common Terraservice
If you're reviewing this PR, please check for these things …
=> BFD-2567: Add common terraservice to deployment

ops/terraform/services/base/values/ephemeral.yaml, ops/terraform/services/base/values/prod-sbx.yaml, ops/terraform/services/base/values/prod.yaml, ops/terraform/services/base/values/test.yaml
[BFD-2556](https://jira.cms.gov/browse/BFD-2556)
User Story
As an operations engineer, I want the CCW RIF Loader to run with idempotence by default so that I can avoid reconfiguration when the RIF loader is interrupted.
Background
The BFD ETL Pipeline Job is currently configured to run without idempotence mode. While this provides a modest performance improvement over the additional checks that are party to idempotence, these performance gains pale in comparison to the more recent performance improvements introduced as part of [BFD-2508](https://jira.cms.gov/browse/BFD-2508) and [BFD-2509](https://jira.cms.gov/browse/BFD-2509).
In the event of intended or unintended interruptions to the pipeline due to availability, data discrepancies, or …
=> BFD-2556: Default CCW pipeline to idempotency mode

apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/HHAClaimTransformerV2Test.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/HospiceClaimTransformerV2Test.java
[BFD-2635](https://jira.cms.gov/browse/BFD-2635)
As part of some other work, it was noticed a couple tests in HHAClaimTransformerV2Test did not have @Test annotations and therefore were not being run. Upon adding the annotation, one of the tests failed. The test was:
HHAClaimTransformerV2Test#shouldNotSetBillablePeriodWithNullClaimQueryCode
Since this test presumably tests desired functionality, its failure indicates there may be a bug in the code that needs fixing. This should be investigated and fixed so this test can pass successfully.
The root cause of missing this was https://github.com/CMSgov/beneficiary-fhir-data/pull/1454 which added the test without annotations, and was not caught in code review, leading to the missed functionality …
=> BFD-2635: Fix claim query code test in HHATransformerV2Test

.github/workflows/ci-java.yml
[BFD-2649](https://jira.cms.gov/browse/BFD-2649)
Avoid AWS OIDC authentication issues in GHA with `configure-aws-credentials` upgrades.
---
These changes upgrade the configure-aws-credentials action to v2. There doesn't seem to be any substantive changes to dependencies thereof and the warnings received under `configure-aws-credentials@v1-node16` still seem to be present in `configure-aws-credentials@v2`, however... this seems to work. That makes it a little harder to argue against when the proposed fix also involves upgrading from an unsupported piece of software to a supported one. …
=> BFD-2649: Upgrade to GHA configure-aws-credentials@v2

ops/terraform/env/mgmt/jenkins-iam.tf
[BFD-2655](https://jira.cms.gov/browse/BFD-2655)
Fix permissions issues on Jenkins by adding application-autoscaling to CBC role.
---
[BFD-2570](https://jira.cms.gov/browse/BFD-2570) _or_ #1757 introduced new resource under `application-autoscaling` via terraform, however the Jenkins role lacks the permission to access these resources. This introduces additional permissions to accommodate these resources. …
=> BFD-2655: Add application-autoscaling to CBC role

apps/bfd-pipeline/bfd-pipeline-rda-grpc-apps/README.md, apps/bfd-pipeline/bfd-pipeline-rda-grpc-apps/src/main/java/gov/cms/bfd/pipeline/rda/grpc/apps/DirectRdaLoadApp.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/README.md
This would be to create a High-level Overview document on the Mock RDA API Server so the BFD can understand how it operates and interacts with PACA.
---
Updates README files with documentation on the mock RDA API server.
Fixes missing default value for RDA API version string in `DirectRdaLoadApp`. …
=> PACA-1056: mock rda api server doc updates

ops/terraform/services/pipeline/main.tf, ops/terraform/services/pipeline/s3.tf
[BFD-2671](https://jira.cms.gov/browse/BFD-2671)
Temporarily disable pipeline scaling to ensure that the trunk or master branch continues to exist in a deployable state.
---
This change set disables scaling for the bfd-pipeline and ensures that the new ASG is configured for a capacity of exactly one instance.
* Does …
=> BFD-2671: Temporarily disable pipeline scaling

apps/bfd-pipeline/bfd-pipeline-rda-grpc-apps/src/main/java/gov/cms/bfd/pipeline/rda/grpc/apps/LoadRdaJsonApp.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/StandardGrpcRdaSource.java
[PACA-910](https://jira.cms.gov/browse/PACA-910)
As a PACA engineer I need to load claims with negative sequence numbers directly into the database for use by BCDA smoke tests.
---
Updates `LoadRdaJsonApp` to properly:
- Parse pepper using hex decode instead of just using byte string.
- Accept starting FISS and MCS claim sequence number as configuration parameter.
Updates `StandardRdaGrpcSource` to:
- Allow the use of negative starting sequence number.
* If the answer to any of the questions below is **Yes**, then **you must** …
=> PACA-910: Add support for negative sequence numbers

apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/extract/s3/task/DataSetMoveTask.java, apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/s3/SharedS3Utilities.java, ops/terraform/services/base/values/prod-sbx.yaml, ops/terraform/services/base/values/test.yaml
[BFD-2684](https://jira.cms.gov/browse/BFD-2684)
Attempts to fix a bug where AWS downloads get stuck sometimes.
---
Increases the async S3 client configuration for maximum file size before splitting the file into smaller parts to 200MB. This will also increase the chunk size of each download piece to 200MB, which should reduce the number of threads needed for a large download.
Also deletes a KMS key addition to the copy request that was causing issues in prod-sbx; basically if the key is found and added to the request the copy fails, because AWS was expecting some specific header that wasnt added correctly. The kms key addition was unneeded, because the copy request if absent the specific kms key will default to the bucket-level encryption, …
=> BFD-2684: Increase minimum AWS file download part size to 200MB

Jenkinsfile, ops/terraform/services/base/values/prod-sbx.yaml, ops/terraform/services/base/values/prod.yaml
[BFD-2673](https://jira.cms.gov/browse/BFD-2673)
Prepare environments for RDS cluster upgrade from the r5 instance class to more modern r6i instance class.
---
This PR points the path-to-production environments (`prod-sbx` and `prod`) to effective, ephemeral RDS Cluster Clones and temporarily disables deployments of the `common` terraservice until the deployment of BFD-2674.
Skipping the `common` terraservice is necessary to avoid any issues where we may need to deploy between now and whenever BFD-2674 becomes available without conflicts on engine version, instance count, or instance class.
* Verify all PR security questions and checklists have been completed and …
=> BFD-2673: Prepare for RDS Cluster Upgrades

ops/terraform/services/common/variables.tf
[BFD-2674](https://jira.cms.gov/browse/BFD-2674)
Support RDS cluster upgrade with overridable cluster identifier variable.
---
This is an addendum to #1794 where the input definitions were mistakenly excluded from the change set.
* Does this PR modify or invalidate any …
=> BFD-2674: Fix cluster identifier override

ops/terraform/services/base/ephemeral.tf, ops/terraform/services/base/nonsensitive.tf, ops/terraform/services/base/values/prod-sbx.yaml
[BFD-2711](https://jira.cms.gov/browse/BFD-2711)
Non-sensitive AWS SSM Parameters created and managed by the `base` Terraservice were recently updated to use the `insecure_value` property instead of the `value` property as Terraform assumes that `value` is always sensitive. Unfortunately, due to an [outstanding Terraform AWS provider issue](https://github.com/hashicorp/terraform-provider-aws/issues/31267), using `insecure_value` in this manner results in non-sensitive value changes failing to apply along with erroneous diffs upon `apply` of the `base` Terraservice.
Fortunately, reverting to using `value` instead of `insecure_value` resolves both these issues.
---
This PR reverts usages of `insecure_value` back to using `value` instead.
This …
=> BFD-2711: Fix non-sensitive AWS SSM Parameters in base Terraservice do not update after value change

ops/terraform/services/eft/main.tf
[BFD-2733](https://jira.cms.gov/browse/BFD-2733)
As a BFD Engineer, I want the EFT S3 Bucket to retain objects for only 72 hours so that I can reduce the chance of sensitive data proliferation
---
This PR implements a 72 hour retention period for all objects incoming to the `bfd-${env}-eft` bucket(s). Additionally, versioning has been explicitly disabled for these EFT bucket(s) and the KMS bucket key has been enabled by default to reduce KMS cost.
- If the answer to any of the questions below is **Yes**, then **you must** supply a …
=> BFD-2733: Apply 72 hour object lifecycle policy to EFT S3 Bucket

apps/bfd-server/bfd-server-launcher/src/test/java/gov/cms/bfd/server/launcher/AuthenticationIT.java
[BFD-2812](https://jira.cms.gov/browse/BFD-2812)
As a BFD engineer I want tests involving BFD server to properly shut down any BFD server they start.
Currently  the ITs in the bfd-server-launcher project  leave several bfd-server processes still running.  The processes are started by the AuthenticationIT.  Simply changing the plain try blocks in two of the tests into try-with-resources blocks will allow the tests to kill the running processes automatically.
---
Changes tests in `AuthenticationIT` to use try-with-resources for the bfd server. …
=> BFD-2812: Fixes tests not stopping bfd servers.

.github/workflows/ci-java.yml, .github/workflows/ci-runbook.yml, .github/workflows/ci-rust.yml, .github/workflows/ci-terraform.yml
[BFD-2817](https://jira.cms.gov/browse/BFD-2817)
Enable GHA merge queues.
---
With the inclusion of `merge_group` in our GHA workflows, this should enable us to declare merge queues and allow us to be more efficient when merging several changesets consecutively.
You can learn more about merge queues from the [initial announcement of GitHub's public beta](https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/).
**This is our first attempt in introducing merge queues.** It's likely that there are some additional changes necessary to take full advantage of this feature.
* Verify all PR security questions and checklists have been completed and …
=> BFD-2817: Enable GHA Merge Queues

.github/workflows/ci-java.yml
[BFD-2820](https://jira.cms.gov/browse/BFD-2820)
Re-enable threaded maven builds
---
This [parallelizes maven builds](https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3) through the re-introduction of `--threads 1C` which allows for 1 thread per CPU core.
The results generally yield an improvement over existing executions of mvn-verify in the ci-java GHA workflow, widely ranging from 15-40% faster. …
=> BFD-2820: Re-enable threaded maven builds

ops/terraform/services/server/modules/bfd_server_metrics/main.tf
[BFD-2821](https://jira.cms.gov/browse/BFD-2821)
Recent changes to the Regression Suite in BFD-2729 uncovered mistakes in all `Claim` and `ClaimResponse` `access.json` Metric Filter pattern definitions that result in no metrics being collected for `Claim` and `ClaimResponse` endpoints.
---
This PR fixes `Claim` and `ClaimResponse` Metric Filters by removing an invalid trailing `/` in the URI filter patterns that attempt to match for `Claim` and `ClaimResponse`.
This PR has been verified by:
- `target`ed `terraform apply`ing the `server` Terraservice in the `test` environment specifying `module.bfd_server_metrics` as the target, verifying that the changes apply as expected
- Running the updated PAC Regression Suite from BFD-2729 against …
=> BFD-2821: Fix PAC endpoint metric filters do not filter URI correctly

insights/terraform/projects/bb2/services/analytics/modules/lambda/update_athena_metric_tables/sql_templates/template_generate_metrics_for_report_date.sql
[BB2-2564](https://jira.cms.gov/browse/BB2-2564)
Summary from the JIRA ticket:
Looks like there might be a bug on the BB2-DASG-Metrics dashboard (Engagement-SBX tab) related to SDK Requests.  Node and Python are showing the same numbers each week.  Most likely, the requests are not the same.
This PR fixes a bug with the Node SDK requests count. It was actually counting the Python SDK requests.
Is a simple fix replacing "python" with "node" in the SQL that is counting the Node SDK requests.
This has been tested and the related lambda has been replaced. Going forward, this metric will be the correct value in our weekly DASG metric reports. We may re-run the reporting for replacing the incorrect history as another Jira story---if …
=> BB2-2564: Fix insights SDK metric bug

apps/bfd-server/dev/bfd-data-dictionary/data/V1/0054_clm_id.json, apps/bfd-server/dev/bfd-data-dictionary/data/V1/0318_pde_id.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0015_carr_clm_pmt_dnl_cd.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0032_clm_disp_cd.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0049_clm_from_dt.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0054_clm_id.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0056_clm_line_num.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0099_clm_thru_dt.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0125_hcpcs_1st_mdfr_cd.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0126_hcpcs_2nd_mdfr_cd.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0127_hcpcs_3rd_mdfr_cd.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0128_hcpcs_4th_mdfr_cd.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0129_hcpcs_cd.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0131_icd_dgns_cd1.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0257_line_1st_expns_dt.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0258_line_alowd_chrg_amt.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0260_line_bene_prmry_pyr_cd.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0263_line_cms_type_srvc_cd.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0269_line_icd_dgns_vrsn_cd.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0270_line_last_expns_dt.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0271_line_nch_pmt_amt.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0274_line_place_of_srvc_cd.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0276_line_prcsg_ind_cd.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0294_nch_clm_type_cd.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0307_nch_wkly_proc_dt.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0318_pde_id.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0358_prvdr_num.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0362_prvdr_state_cd.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0391_rev_cntr_prvdr_pmt_amt.json, apps/bfd-server/dev/bfd-data-dictionary/data/V2/0629_clm_uncompd_care_pmt_amt.json
[BFD-2727](https://jira.cms.gov/browse/BFD-2727)
As a BCDA FHIR evangelist, I need some minor content fixes made to the BFD Data Dictionary (DD) to help drive my demo/workshop at the upcoming connectathon
---
This change adjusts the BFD data dictionary by:
* introducing documentation for [Claim Uncompensated Care Payment Amount](https://bluebutton.cms.gov/resources/variables/clm_uncompd_care_pmt_amt/ )
* adding missing CCLF mappings where appropriate
* removing irrelevant/non-applicable mappings as necessary
* If the answer to any …
=> BFD-2727: Address Data Dictionary Content Issues

apps/bfd-model/bfd-model-rif/src/main/resources/db/scripts/BFD-2686-Hackathon-Postgres-Partitioning/bene_monthly_upsert_example.sql, apps/bfd-model/bfd-model-rif/src/main/resources/db/scripts/BFD-2686-Hackathon-Postgres-Partitioning/eob_carrier_claims_compare.sql, apps/bfd-model/bfd-model-rif/src/main/resources/db/scripts/BFD-2686-Hackathon-Postgres-Partitioning/partition_beneficiary_monthly.sql, apps/bfd-model/bfd-model-rif/src/main/resources/db/scripts/BFD-2686-Hackathon-Postgres-Partitioning/partition_carrier_claims.sql, apps/bfd-model/bfd-model-rif/src/main/resources/db/scripts/BFD-2686-Hackathon-Postgres-Partitioning/partition_partd_events.sql
[BFD-2826](https://jira.cms.gov/browse/BFD-2826)
Implement postgres database table partitioning to check its efficacy within the BFD database.
This PR represents a set of scripts that were used to partition some BFD database tables
This was a hackathon task to check how BFD could possibly leverage postgres table partitioning to check both its effectiveness and performance. As such, there are several SQL scripts that will be preserved as examples of how BFD tables could be partitioned.
As such it takes three BFD tables and does the following:
- create partitioned table(s) for CARRIER_CLAIMS, PARTD_EVENTS, and BENEFICIARY_MONTHLY
- migrates data from current table (i.e., current CARRIER_CLAIMS to a partitioned instance of CARRIER_CLAIMS table, …
=> BFD-2826: Hackathon-SQL-to-setup-postgre-db-partitioning

ops/terraform/services/base/values/ephemeral.yaml, ops/terraform/services/base/values/prod-sbx.yaml, ops/terraform/services/base/values/prod.yaml, ops/terraform/services/base/values/test.yaml, ops/terraform/services/pipeline/modules/bfd_pipeline_slis/data-sources.tf, ops/terraform/services/pipeline/modules/bfd_pipeline_slis/iam.tf, ops/terraform/services/pipeline/modules/bfd_pipeline_slis/lambda_src/common.py, ops/terraform/services/pipeline/modules/bfd_pipeline_slis/lambda_src/pipeline_metrics_repeater.py, ops/terraform/services/pipeline/modules/bfd_pipeline_slis/lambda_src/update_pipeline_slis.py, ops/terraform/services/pipeline/modules/bfd_pipeline_slis/main.tf, ops/terraform/services/pipeline/modules/bfd_pipeline_slo_alarms/main.tf
[BFD-2835](https://jira.cms.gov/browse/BFD-2835)
The CCW RIF Pipeline SLO CloudWatch Alarms that evaluate the state of the following SLOs:
- Time to ingest a weekly batch load once available in S3
- Weekend data load availability
are not working properly. While the Alarms themselves are implemented properly (i.e. the Metric Math), quirks of CloudWatch Alarms' "evaluation period" combined with the infrequent submission of the corresponding Pipeline Metrics used by these Alarms result in no data being available for the CloudWatch Alarms to evaluate upon when the SLOs they represent would be violated. Thus, these CloudWatch Alarms fail to send alerts to VictorOps/Slack when they should.
---
This PR:
- updates the `bfd-pipeline-slis` module in …
=> BFD-2835: CCW RIF Pipeline SLO Alarms are failing to evaluate when SLOs are violated

.github/workflows/ci-java.yml
[BFD-2823](https://jira.cms.gov/browse/BFD-2823)
The GHA workflows have been producing build artifacts that are basically the log output from surefire and failsafe reports. Developers have not used these artifacts nor are they inclined to do so (based on pool by M. Burling as to their use and efficacy).
This PR removes the 'Upload test artifacts' step from the ci-java.yml; the following build artifacts will no longer be persisted:
- **/target/surefire-reports/*
- **/target/failsafe-reports/*
- bfd-server/bfd-server-war/target/server-work/access.*
- bfd-server/bfd-server-war/target/server-work/server-console.log
* Modify ci-java.yml to remove the 'Upload test artifacts' step
* build artifacts will no longer be persisted
If you're reviewing …
=> BFD-2823: Remove Upload of Test Artifacts

ops/ansible/playbooks-ccs/build_bfd-server-load.yml, ops/ansible/playbooks-ccs/launch_bfd-server-load.yml
[BFD-2881](https://jira.cms.gov/browse/BFD-2881)
The platinum AMI when built installs Python 3.9.16. However, the Python version in the `server-load` AMI ends up as 3.7.16. This version mismatch or downgrade causes build failures when installing dependencies that require versions greater than 3.8.
---
This PR adds a _temporary_ fix for the Python version mismatching in the `server-load` AMI by re-symlinking the Python 3.9.16 binary during the launch and build `server-load` Ansible playbook variants.
This should be reverted once a more permanent solution is discovered.
Submitters should …
=> BFD-2881: Server Load AMI is Downgrading the Platinum AMI Python Version Causing Build Failures

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/InpatientClaimTransformerV2.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/InpatientClaimTransformerV2Test.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/InpatientClaimTransformerTest.java, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobByPatientIdAll.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobByPatientIdPaged.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobReadInpatient.json
[BFD-2880](https://jira.cms.gov/browse/BFD-2880)
Per a note from bfd-users, clm_uncompd_care_pmt_amt is not mapped in v2. Per Bill's updates to the DD files before he left, this field should be mapped in V2 but isnt.
---
- Adds mapping for clm_uncompd_care_pmt_amt as noted in https://github.com/CMSgov/beneficiary-fhir-data/blob/master/apps/bfd-server/dev/bfd-data-dictionary/data/V2/0629_clm_uncompd_care_pmt_amt.json for V2 Inpatient
- Adds tests both for v1 which had no test for this existing mapped value, and the new mapping in V2
- Updates the golden test files with the new V2 mapping
Note the end resulting extension does not _exactly_ match Bill's example in the json file; the path to the url/value is correct, but in his example he has an …
=> BFD-2880: Add V2 mapping for clm_uncompd_care_pmt_amt (INPATIENT)

ops/terraform/services/_modules/bfd-terraservice/.terraform-docs.yml, ops/terraform/services/_modules/bfd-terraservice/README.md, ops/terraform/services/_modules/bfd-terraservice/main.tf, ops/terraform/services/_modules/bfd-terraservice/outputs.tf, ops/terraform/services/_modules/bfd-terraservice/variables.tf, ops/terraform/services/base/main.tf, ops/terraform/services/common/main.tf, ops/terraform/services/eft/main.tf, ops/terraform/services/migrator/main.tf, ops/terraform/services/pipeline/main.tf, ops/terraform/services/server/main.tf, ops/terraform/services/server/server-load/main.tf, ops/terraform/services/server/server-regression/main.tf
[BFD-2648](https://jira.cms.gov/browse/BFD-2648)
As a BFD infrastructure engineer I want there to be a reusable module for the terraservices that handles basic variable definitions so that I can more easily work with the terraservices without having to repeat myself.
---
Introduces a terraservice child module for reusability and modifies exist `main.tf` files in the `ops/terraform` directory to reference this module. …
=> BFD-2648: Introduce terraservice child module

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/TransformerUtilsV2.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/ExplanationOfBenefitE2E.java
[BFD-2850](https://jira.cms.gov/browse/BFD-2850)
---
When using an EOB request with lastUpdated AND pagination (using _count) the _count parameter seems to be ignored.
- Updates TransformerUtilsV2.java` 
-  Updates `searchEobByPatientIdWithLastUpdatedAndPagination()` test in ExplanationOfBenefitE2E.java` 
* Does this …
=> BFD-2850: Bug fix to count being ignored when using lastUpdated ranges

ops/terraform/env/mgmt/iam.tf
[BFD-2884](https://jira.cms.gov/browse/BFD-2884)
---
Updates the ssm ro policy to allow listing (describing) SSM parameters in order to allow console usage for devs.
* Does this PR store or transmit data …
=> BFD-2884: Allow listing of SSM parameters 

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/TransformerUtilsV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/pac/AbstractR4ResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/TransformerUtils.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/CoverageE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/ExplanationOfBenefitE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/PatientE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/TransformerUtilsV2Test.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/pac/ClaimE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/pac/ClaimResponseE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/CoverageE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/ExplanationOfBenefitE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/PatientE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/TransformerUtilsTest.java
[BFD-2888](https://jira.cms.gov/browse/BFD-2888)
Fixes an issue where the new startIndex error is raised if a result has 0 results and pagination is requested.
---
- Adds a check in the bundle logic for all endpoints to only sublist the results if there are >0 results
- This also prevents doing the validations on startIndex/count if our result list is empty, eliminating a confusing error
- Adds tests for this behavior  …
=> BFD-2888: Add check for pagination only if resources > 0

apps/bfd-server/bfd-server-launcher/pom.xml
[BFD-2890](https://jira.cms.gov/browse/BFD-2890)
As a BFD engineer I want the dependencies within the maven pom files to properly reflect those needed to perform builds reliably.  There are some cases where maven will not realize that `bfd-server-launcher-sample` must be built before `bfd-server-launcher`.
---
Adds an explicit test dependency on `bfd-server-launcher-sample` to the `bfd-server-launcher` project so that running tests of just the `bfd-server-launcher` with a clean local repository do not fail due to the sample project's war file being unavailable.
Submitters should …
=> BFD-2890: Fix intermodule dependencies

ops/terraform/services/eft/README.md, ops/terraform/services/eft/data-sources.tf, ops/terraform/services/eft/main.tf
[BFD-2893](https://jira.cms.gov/browse/BFD-2893)
As a BFD Engineer, I want the eft Terraservice to be apply-able similar to other Terraservices and for the NLB it creates to map only the subnets that our SFTP server is available in so that there is no need for special apply handling for eft and EFT SFTP traffic is guaranteed to route to our SFTP server
---
This PR:
- Refactors the `eft` Terraservice such that it can be `apply`'d with a single `apply`, even in environments that have no prior state
- This was originally a constraint as some data resources were generated with `for_each` based upon output of other resources not known until `apply`-time. Terraform requires the iterable of a `for_each` to be known ahead-of-time, so this was …
=> BFD-2893: Improve EFT Terraservice apply and NLB creation

ops/terraform/services/server/modules/bfd_server_asg/main.tf
[BFD-2911](https://jira.cms.gov/browse/BFD-2911)
The BFD Server's scaling policies' alarms were designed such that the metric they evaluate upon may return no data for a certain period if no action should be taken. When this happens, it was intended that the "missing" data for the given period would be treating as _good_ and _non-breaching_, and the alarms are configured this way. However, [CloudWatch Alarms treat missing/empty data as special case](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/AlarmThatSendsEmail.html#alarms-and-missing-data): whenever the Alarm tries to evaluate its state, it pulls _extra_ data beyond the evaluation period and if there is missing data within the evaluation period the Alarm will use that …
=> BFD-2911: Server ASG scaling alarms ignore periods of missing data when evaluating state

ops/jenkins/bfd-jenkins-sonarqube/Jenkinsfile
[BFD-2740](https://jira.cms.gov/browse/BFD-2740)
---
As a BFD contributor, I want the ability to produce static analyses for bfd-parent on pull requests so that I can inspire confidence in reviewers of my proposed changes.
- Verified the correctness of the `JenkinsFile` as it successfully builds the different stages and also produces the analyses on BFD-parent. 
- Link: https://sonarqube.cloud.cms.gov/dashboard?id=bfd-parent&branch=ade%2FBFD-2740-InitialIntegrationBetweenJenkinsAndSonarQube
This PR Introduces a Jenkinsfile in `ops/jenkins` to build a multistage pipeline in Jenkins that produces static analyses for BFD-Parent on PullRequest.  …
=> BFD-2740: Initial Integration between Jenkins and SonarQube

apps/bfd-data-fda/pom.xml, apps/bfd-data-npi/pom.xml, apps/bfd-data-npi/src/main/java/gov/cms/bfd/data/npi/utility/DataUtilityCommons.java, apps/bfd-db-migrator/pom.xml, apps/bfd-ops/pom.xml, apps/bfd-ops/src/main/assembly/tar.xml, apps/bfd-pipeline/bfd-pipeline-app/pom.xml, apps/bfd-pipeline/bfd-pipeline-rda-bridge/pom.xml, apps/bfd-server/bfd-server-launcher/pom.xml, apps/bfd-server/bfd-server-war/pom.xml, apps/bfd-server/pom.xml, apps/pom.xml, apps/utils/scripts/build-bfd
[BFD-2891](https://jira.cms.gov/browse/BFD-2891)
As a BFD engineer I would like to have a centralized repository for official release images and build artifacts.
---
This PR enables the use of maven release plugin to build and push tagged release artifacts and update pom versions using a standard process.  There are also minor changes to the bfd-data project code to make its behavior consistent with comments (release builds were broken without these changes).
A new maven project, `bfd-ops` has been added to compile the ops directory into an assembly so that it can also be tagged and pushed to CodeArtifact for use in deployments.
More information about [how to use the release plugin](https://github.com/CMSgov/beneficiary-fhir-data/wiki/2891-Ma …
=> BFD-2891: Configure maven release and deploy plugins

apps/build.groovy, apps/pom.xml, ops/jenkins/bfd-jenkins-sonarqube/Jenkinsfile
[BFD-2876](https://jira.cms.gov/browse/BFD-2876)
---
As a BFD contributor I want the test coverage in SonarQube to be accurate so that I can write tests to improve coverage.
- Updates the `build.groovy` file
- Updates the `JenkinsFile` in `ops/jenkins/bfd-jenkins-sonarqube/Jenkinsfile`
- Updates `apps/pom.xml` to update sonar jacoco path.  …
=> BFD-2876:  Upload Test Results to SonarQube

ops/terraform/modules/resources/cw_alarms_slack_notifier/lambda-src/cw_alarms_slack_notifier.py
[BFD-2634](https://jira.cms.gov/browse/BFD-2634)
The Lambdas responsible for parsing SNS Notifications from CloudWatch SLO Alarms and posting messages to our Slack channels were built with the assumption that all Notifications received include a `MetricName` property indicating the name of the corresponding Metric that the Alarm is alarming upon. However, there are several _computed metric_ Alarms that use Metric Math instead of a static CloudWatch Metric to determine the value to alarm upon (i.e. `bfd-server-prod-slo-http500-percent-24hr-warning`); these CloudWatch Alarms will send Notifications that do _not_ include the `MetricName` property and so the Lambda will fail to post messages to Slack.
---
This PR updates the Slack alarms Lambda …
=> BFD-2634: Slack alarms Lambdas are failing to post notifications for computed Alarms

ops/terraform/services/server/modules/bfd_server_slo_alarms/data-sources.tf, ops/terraform/services/server/modules/bfd_server_slo_alarms/main.tf
[BFD-2937](https://jira.cms.gov/browse/BFD-2937)
The `/v*/fhir/Patient by_contract=false 15-minute Mean Latency` SLO (see the [BFD SLOs Confluence page](https://confluence.cms.gov/pages/viewpage.action?spaceKey=BFD&title=BFD+SLOs) for more details), when broken, usually results in no immediate action for the responding on-call engineer to take. Additionally, the SLO often resolves itself immediately after breaking, as these SLO violations _usually_ occur due to a low number of requests with one or two outliers disproportionately affecting the calculated mean.
So, the corresponding alert to VictorOps should be disabled while this SLO is re-evaluated. `Patient` has _several_ other SLOs that effectively cover its performance, so disabling this …
=> BFD-2937: Patient by_contract=false 15-minute mean latency SLO is not actionable when broken 

apps/pom.xml
[BFD-2958](https://jira.cms.gov/browse/BFD-2958)
As a BFD contributor, I want static analysis to stop reporting on java:S5786 so that I can better focus on what's important.
**Background**
- java:S5786 points out a JUnit5-specific feature that no longer requires visibility of test classes/methods to be explicitly marked as public
- This is currently flagged under more than 1900 issues as of this writing
- This has little impact to readability
- Addressing the >1900 lines is not worthwhile
- This constraint should be ignored
---
- Updates the `apps/pom.xml` to exclude the warnings related to `S5786` in `bfd-parent` 
- Performed verification of these changes on the sonarQube server. For example the latest code review revealed a substantial …
=> BFD-2958: Exclude Warnings for java:S5786

ops/terraform/services/server/modules/bfd_server_asg/main.tf
[BFD-2968](https://jira.cms.gov/browse/BFD-2968)
The BFD Server's AutoScaling Group's Scaling Policies apply a default [cooldown period](https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-scaling-simple-step.html#as-step-scaling-warmup) where instance metrics are not submitted for 300 seconds (due to an ASG-default [instance warmup period](https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-default-instance-warmup.html?icmpid=docs_ec2as_help_panel)). This is useful for cases where a scaled-out instance enters `InService` before it's truly warmed-up. However, this does not apply to BFD Server instances as the BFD Server ASG has a Launch Lifecycle Hook that prevents BFD Server instances from entering `InService` …
=> BFD-2968: BFD Server ASG Scaling Policies set default cooldown stopping warmed instances from submitting metrics immediately

apps/utils/locust_tests/common/stats/stats_compare.py
[BFD-2507](https://jira.cms.gov/browse/BFD-2507)
- Description
Our Locust tests do not treat Athena queries failing as actual failures, so when this case happens we see no failures in our deployment pipeline.
- Background
A relatively recent string of failures in the Regression Suite caused by upgrades to Athena would have been caught faster if the aggregated stats framework treated FAILED Athena queries as true failures instead of ignoring them outright (treating FAILED queries as an absence of possible stats to compare against). [BFD-2456](https://jira.cms.gov/browse/BFD-2456) resolved this particular issue, but future issues could occur that would result in ignored FAILED Athena queries.
---
- Updates the `stats_compare.py` to send the …
=> BFD-2507: Fix bug relating to Athena query failures being ignored

insights/terraform/projects/ab2d/tables.tf, insights/terraform/projects/bb2/base_config/main.tf, insights/terraform/projects/foodtruck/main.tf, ops/terraform/services/server/insights/api-requests/glue.tf
[BFD-2668](https://jira.cms.gov/browse/BFD-2668)
BCDA BFD-Insights developer perms
---
Bugfix that adds and sets the `owner` var across  BFD Insights projects as the `owner` var is now required in `insights/terraform/modules/table` module. …
=> BFD-2668: Add owner var to bfd insights

apps/bfd-db-migrator/src/main/java/gov/cms/bfd/migrator/app/MigratorApp.java, apps/bfd-db-migrator/src/test/java/gov/cms/bfd/migrator/app/MigratorAppIT.java, apps/bfd-db-migrator/src/test/java/gov/cms/bfd/migrator/app/RdaSchemaMigrationIT.java, apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/AppConfiguration.java, apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/PipelineApplication.java, apps/bfd-pipeline/bfd-pipeline-app/src/test/java/gov/cms/bfd/pipeline/app/AppConfigurationTest.java, apps/bfd-pipeline/bfd-pipeline-app/src/test/java/gov/cms/bfd/pipeline/app/PipelineApplicationIT.java, apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/RDABridge.java, apps/bfd-server/bfd-server-launcher/pom.xml, apps/bfd-server/bfd-server-launcher/src/main/java/gov/cms/bfd/server/launcher/DataServerLauncherApp.java, apps/bfd-server/bfd-server-launcher/src/test/java/gov/cms/bfd/server/launcher/AppConfigurationIT.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/ServerInitializer.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/SpringConfiguration.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/ServerExecutor.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/ServerInitializerTest.java, apps/bfd-shared-utils/pom.xml, apps/bfd-shared-utils/src/main/java/gov/cms/bfd/sharedutils/config/AwsParameterStoreClient.java, apps/bfd-shared-utils/src/main/java/gov/cms/bfd/sharedutils/config/ConfigLoader.java, apps/bfd-shared-utils/src/main/java/gov/cms/bfd/sharedutils/config/ConfigLoaderSource.java, apps/bfd-shared-utils/src/main/java/gov/cms/bfd/sharedutils/config/LayeredConfiguration.java, apps/bfd-shared-utils/src/main/java/gov/cms/bfd/sharedutils/config/LayeredConfigurationSettings.java, apps/bfd-shared-utils/src/test/java/gov/cms/bfd/sharedutils/config/AwsParameterStoreClientIT.java, apps/bfd-shared-utils/src/test/java/gov/cms/bfd/sharedutils/config/ConfigLoaderSourceTest.java, apps/bfd-shared-utils/src/test/java/gov/cms/bfd/sharedutils/config/ConfigLoaderTest.java, apps/bfd-shared-utils/src/test/java/gov/cms/bfd/sharedutils/config/LayeredConfigurationIT.java, apps/bfd-shared-utils/src/test/java/gov/cms/bfd/sharedutils/config/LayeredConfigurationTest.java, apps/utils/scripts/README.md, apps/utils/scripts/run-bfd-pipeline, apps/utils/scripts/run-bfd-server, apps/utils/scripts/run-db-migrator
[BFD-2913](https://jira.cms.gov/browse/BFD-2913)
As a BFD engineer, I want the ssm configuration layer to support multiple hierarchies so that I can rely on the applications to reliably fetch their own configuration.
---
The `LayeredConfiguration` class is now configurable using a JSON configration defined in a new environment variable named `CONFIG_SETTINGS_JSON`.  The configuration JSON defines these properties:
| Property         | Type | Description |
| -------------------- | ------------ | --- |
| `ssmHierarchies` | List of strings | SSM parameter store paths containing configuration parameters both at the root level and within sub-folders.  These are loaded recursively and any sub folder names are included in the final parameter name …
=> BFD-2913: layered config ssm enhancement

ops/terraform/services/server/modules/bfd_server_dashboards/templates/bfd-dashboard-slos.tftpl, ops/terraform/services/server/modules/bfd_server_slo_alarms/main.tf
[BFD-2949](https://jira.cms.gov/browse/BFD-2949)
As a BFD team member, I want the ensure Patient by_contract=false 15 minute mean latency SLO fall in line with our SLO/SLA agreements with our customers and ensure that these alerts are actionable.
---
This PR removes the `/v*/fhir/Patient by_contract=false 15-minute Mean Latency` SLO's corresponding CloudWatch Alarms and graph from the `bfd-${env}-server-slos` CloudWatch Dashboards.
This SLO often breaks during periods of expected traffic, and recently these breakages have resulted in no action for the on-call engineer to take. After discussion with the partner that was affected by recent violations of this SLO, they confirmed that they had received no downstream reports of poor performance …
=> BFD-2949: Audit Patient by_contract=false 15 minute mean latency SLO

ops/terraform/services/base/values/prod-sbx.yaml, ops/terraform/services/base/values/prod.yaml, ops/terraform/services/base/values/test.yaml
Updates the RDS daily snapshot retention to 3 days to align with BFD's Backup and Retention Policy in prod, prod-sbx, and test.
[BFD-2975](https://jira.cms.gov/browse/BFD-2975)
As a BFD operations engineer, I want AWS to contain only meaningful resources that BFD is expected to maintain so that I can confidently/competently manage them.
---
Updates the number of automated RDS daily snapshot retention to 3 from 8.
* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security …
=> BFD-2975: Update RDS daily snapshot retention

ops/terraform/services/base/values/prod.yaml
[BFD-2857](https://jira.cms.gov/browse/BFD-2857)
Bug fix to add server startup client certificate to server truststore.
Add bluebutton-backend-prod-data-server-client-test certificate to terraform.
Verify that there are now 7 certificates in terraform for prod server truststore.
* …
=> BFD-2857: Remediate production client cert defect

ops/terraform/services/base/values/prod-sbx.yaml
[BFD-3003](https://jira.cms.gov/browse/BFD-3003)
Re-introduce a missing test client certificate to the prod-sbx environment.
---
A duplicate entry for `bluebutton_root_ca` was introduced to the prod-sbx.yaml, effectively overwriting that value. Historically, the BB2 partner has been accessing the prod-sbx environment from their test environment to satisfy their internal testing needs. This PR simply separates the configuration entries based on `test` and `sbx` usage on the BB2 client side.
* If the answer to any of the questions …
=> BFD-3003: Re-add test certificate to prod-sbx

apps/utils/cipher/cipher.main.kts, ops/terraform/env/mgmt/base_config/data-sources.tf, ops/terraform/env/mgmt/base_config/main.tf, ops/terraform/env/mgmt/base_config/terraform.tf, ops/terraform/env/mgmt/iam.tf, ops/terraform/env/mgmt/main.tf, ops/terraform/modules/resources/cw_alarms_slack_notifier/data-sources.tf, ops/terraform/services/base/ephemeral.tf, ops/terraform/services/base/main.tf, ops/terraform/services/base/sensitive.tf, ops/terraform/services/base/terraform.tf, ops/terraform/services/base/values/prod-sbx.yaml, ops/terraform/services/base/values/prod.yaml, ops/terraform/services/base/values/test.yaml, ops/terraform/services/server/insights/api-requests/lambda.tf, ops/terraform/services/server/main.tf, ops/terraform/services/server/modules/bfd_server_iam/data-sources.tf, ops/terraform/services/server/modules/bfd_server_iam/main.tf, ops/terraform/services/server/modules/bfd_server_iam/variables.tf, ops/terraform/services/server/server-load/data-sources.tf, ops/terraform/services/server/server-load/iam.tf, ops/terraform/services/server/server-load/main.tf, ops/terraform/services/server/server-regression/data-sources.tf, ops/terraform/services/server/server-regression/iam.tf, ops/terraform/services/server/server-regression/main.tf
[BFD-2997](https://jira.cms.gov/browse/BFD-2997)
As a BFD Engineer, I want a multi region key (MRK) to be used when encrypting sensitive values so that I can continue to access these values in the event of a disaster.
---
This PR:
- Adds a new `mgmt`-level "config" Multi-Region Key (MRK) with a corresponding replica key in `us-west-2` called `bfd-mgmt-config-cmk` to `mgmt`'s `base_config` module
- Updates all `mgmt` `base_config` sensitive SSM parameters to use the aforementioned MRK for encryption instead of `bfd-mgmt-cmk`
- Updates all IAM policies that had permissions to `bfd-mgmt-cmk` to either:
- Have _just_ permissions to `bfd-mgmt-config-cmk`, if it was obvious that the only usage of the `bfd-mgmt-cmk` was to decrypt sensitive SSM …
=> BFD-2997: Introduce Environment Multi Region Keys

apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoaderIT.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/BeneficiaryTransformerV2Test.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/CarrierClaimTransformerV2Test.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/CoverageTransformerV2Test.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/DMEClaimTransformerV2Test.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/HHAClaimTransformerV2Test.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/HospiceClaimTransformerV2Test.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/InpatientClaimTransformerV2Test.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/OutpatientClaimTransformerV2Test.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/PartDEventTransformerV2Test.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/SNFClaimTransformerV2Test.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/OutpatientClaimTransformerTest.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/utils/EndpointJsonResponseComparatorIT.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/utils/EndpointJsonResponseComparatorV2IT.java
[BFD-2956](https://jira.cms.gov/browse/BFD-2956)
User Story:
As a BFD developer I would like the disabled tests in the BFD repository to explain themselves so I can understand the reason by which they were disabled when auditing the codebase.
---
- Removed `buildSyntheticLoadedFiles` in `RifLoaderIT.java`. 
- Added comment to disabled annotation `loadSynthenticData` method in `RifLoaderIT.java`
- Added comment to disabled annt for `shouldOutputJSON()` method in `BeneficiaryTransformerV2RTest.java`
- Added comment to disabled annt for `shouldOutputMbiHistory()` method in `BeneficiaryTransformerV2RTest.java`.
- Added comment to disabled annt for `transformSampleARecord()` method in `BeneficiaryTransformerV2RTest.java`
- Removed disabled …
=> BFD-2956 Updates for Disabled Annotations With String Attachments 

ops/terraform/env/mgmt/iam.tf, ops/terraform/env/mgmt/jenkins-iam.tf, ops/terraform/env/mgmt/main.tf, ops/terraform/modules/resources/cw_alarms_slack_notifier/main.tf, ops/terraform/services/server/insights/api-requests/lambda.tf, ops/terraform/services/server/modules/bfd_server_iam/main.tf, ops/terraform/services/server/server-load/iam.tf, ops/terraform/services/server/server-load/main.tf, ops/terraform/services/server/server-regression/iam.tf, ops/terraform/services/server/server-regression/main.tf
[BFD-3020](https://jira.cms.gov/browse/BFD-3020)
As part of BFD-2997, new per-environment Multi-Region Keys (MRKs) have been added to our infrastructure to encrypt sensitive SSM values. Several entities (IAM Roles, IAM Policies, etc.) require permissions to either use or describe these new MRKs, and some of these entities do not have _all_ of these necessary permissions granted to them. This is causing deployment failures and could potentially cause deployment or runtime failures in a disaster recovery scenario
---
This PR:
- Updates all IAM Policies granting permissions to do various actions with the new config MRKs to grant those permissions for the MRKs' primary and all replica keys
- Updates the Jenkins IAM Policy to grant permissions …
=> BFD-3020: Some entities lack required permissions to config KMS MRKs causing deployment failures

ops/terraform/env/mgmt/iam.tf, ops/terraform/env/mgmt/jenkins-iam.tf, ops/terraform/services/migrator/data-sources.tf, ops/terraform/services/migrator/iam.tf, ops/terraform/services/migrator/main.tf, ops/terraform/services/pipeline/data-sources.tf, ops/terraform/services/pipeline/iam.tf, ops/terraform/services/pipeline/main.tf, ops/terraform/services/server/modules/bfd_server_iam/main.tf
[BFD-3020](https://jira.cms.gov/browse/BFD-3020)
As part of BFD-2997, new per-environment Multi-Region Keys (MRKs) have been added to our infrastructure to encrypt sensitive SSM values. Several entities (IAM Roles, IAM Policies, etc.) require permissions to either use or describe these new MRKs, and some of these entities do not have _all_ of these necessary permissions granted to them. This is causing deployment failures and could potentially cause deployment or runtime failures in a disaster recovery scenario
---
This PR fixes additional Terraservices/modules that were not included in the first PR for BFD-3020. More specifically, this fixes an issue causing the RDA Pipeline instances to not start properly.
If you're reviewing this PR, …
=> BFD-3020: Fix additional IAM Policies not having permissions for new MRKs

ops/terraform/services/pipeline/iam.tf
[BFD-2590](https://jira.cms.gov/browse/BFD-250-)
BUGFIX
---
Removes prod specific local vars that referenced ssm params as they cause terraform to fail in other environments.
* Does this PR store or …
=> BFD-2590: Bugfix to not reference env specific params

ops/terraform/env/mgmt/main.tf
[BFD-2992](https://jira.cms.gov/browse/BFD-2992)
BUGFIX
---
I forgot to remove a reference to retention policies in the main mgmt module after I moved to mgmt/backups module instead. This causes terraform errors as the params they reference are not defined in terraform (they are used by the pruning script only).
(_these will need to be defined in the backups module once we move away from eyamls_)
* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment …
=> BFD-2992: Bugfix to remove unused references to params in mgmt

ops/terraform/env/mgmt/backups/ami-pruner.tf, ops/terraform/env/mgmt/backups/lambda-src/ami_pruner/README.md, ops/terraform/env/mgmt/backups/lambda-src/ami_pruner/ami_pruner.py, ops/terraform/env/mgmt/main.tf
[BFD-2992](https://jira.cms.gov/browse/BFD-2992)
BUGFIX
---
Changes lambda env var `AWS_REGION` to `AWS_PRUNE_REGION` as the former is a reserved word. Updates doc and script accordingly.
Plan was applied successfully.  …
=> BFD-2992: Bugfix to not use reserved word in aws lambda env

.github/scripts/pre-commit.sh, .gitignore
[BFD-3026](https://jira.cms.gov/browse/BFD-3026)
BFD-2915 introduced changes to the pre-commit hook script intended to ensure the script could be ran from anywhere and work as expected. However, these changes are not working as expected and are breaking commits to the repository. Additionally, they are unnecessary as the pre-commit script's working directory is always ran relative to the Git working directory.
Also, generated release files in the top-level `dist` directory are not being ignored. These files are not source files and are versioned, and can be regenerated from a particular tag. Therefore, they should be ignored.
---
This PR:
- Fixes the pre-commit script to not break committing by reverting some workdir logic
- Adds top-level …
=> BFD-3026: Pre-commit script causes commit failures and top-level generated dist files are not ignored

ops/terraform/env/mgmt/base_config/data-sources.tf, ops/terraform/env/mgmt/base_config/scripts/read-and-decrypt-yaml.sh, ops/terraform/env/mgmt/base_config/scripts/tf-decrypt-shim.sh, ops/terraform/services/base/main.tf, ops/terraform/services/base/nonsensitive.tf, ops/terraform/services/base/scripts/read-and-decrypt-yaml.sh, ops/terraform/services/base/scripts/tf-decrypt-shim.sh, ops/terraform/services/base/sensitive.tf
[BFD-3034](https://jira.cms.gov/browse/BFD-3034)
The YAML decryption scripts were updated in BFD-2915 to understand hierarchical YAML configuration encrypted with `cipher`. Some values in our configuration use _templating_, where a token (like `${env}`) is used as a placeholder for values known when the configuration is applied. This is used heavily by ephemeral environment configuration within `ephemeral.yaml`, specifically to include the name of the ephemeral environment within some values.
Unfortunately, the new configuration scheme does not properly support this templating scheme, and so those values with placeholder tokens will not have these tokens replaced. Thus, templated configuration values are incorrect when applied to our …
=> BFD-3034: YAML decryption scripts do not template ephemeral values properly

ops/terraform/env/mgmt/base_config/scripts/read-and-decrypt-yaml.sh, ops/terraform/env/mgmt/base_config/scripts/tf-decrypt-shim.sh, ops/terraform/services/base/scripts/read-and-decrypt-yaml.sh, ops/terraform/services/base/scripts/tf-decrypt-shim.sh
[BFD-3036](https://jira.cms.gov/browse/BFD-3036)
The `read-and-decrypt-yaml.sh` scripts use `jq` for manipulating JSON. In particular, the `read-and-decrypt-yaml.sh` script _pipes_ the final result to `jq` to ensure the result is properly formatted and syntax highlighted when running the script in the terminal.
Piping to `jq` so that it reads from `stdin` is well-supported by the latest versions of `jq`, but the version that the `bfd-cbc-build` container includes, `1.5`, seems to have issues when piped to. `jq` `1.5` seemingly fails to read from `stdin` when the `read-and-decrypt-yaml.sh` is invoked via Terraform, and so `base` deployment is failing.
The offending pipe to `jq` is entirely unnecessary and is only included for convenience, so …
=> BFD-3036: Avoid jq Compatibility Issues in Build Container

ops/terraform/env/mgmt/base_config/scripts/tf-decrypt-shim.sh, ops/terraform/services/base/ephemeral.tf, ops/terraform/services/base/scripts/tf-decrypt-shim.sh
[BFD-3038](https://jira.cms.gov/browse/BFD-3038)
Certain IAM policies refer to the "config key alias", rather than the default, per-environment KMS key, for granting permissions to resources that need to decrypt sensitive SSM configuration values. This "config key alias" parameter exists in our established environment configuration, but does not get copied to ephemeral environments.
This is breaking deployments of ephemeral environments.
---
This PR adds the `kms_config_key_alias` parameter to the list of SSM parameters copied into an ephemeral environment from a seed environment. Additionally, the decrypt shims scripts have been improved such that query variables (that will be templated into configuration) can include spaces.
If you're …
=> BFD-3038: Ephemeral environment configuration does not copy config key alias from seed environment

ops/terraform/services/server/modules/bfd_server_dashboards/data-sources.tf, ops/terraform/services/server/modules/bfd_server_dashboards/main.tf, ops/terraform/services/server/modules/bfd_server_dashboards/templates/bfd-dashboard.tftpl
[BFD-2959](https://jira.cms.gov/browse/BFD-2959)
As a BFD/on-call Engineer, I want the BFD Server CloudWatch Dashboards to show as much relevant information as possible so that I can easily understand the current state of the BFD Server.
---
This PR makes several improvements to the `bfd-${env}-server` dashboards:
- A visualization for RDS CPU load has been added
- The existing ASG Instance Count visualization has been improved to show `NetworkIn` along with thresholds indicating the number of desired instances for a given `NetworkIn` range
- Live data has been enabled for all line graphs allowing the graphs to update in realtime
- A line graph has been added showing `500` and non-`2xx` responses per-partner
- A line graph has been added …
=> BFD-2959: Improve BFD Server CloudWatch Dashboards

apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/utils/EndpointJsonResponseComparatorIT.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/utils/EndpointJsonResponseComparatorV2IT.java, apps/pom.xml
[BFD-2957](https://jira.cms.gov/browse/BFD-2957)
As a BFD engineer, I would like important tasks such as generating test json data to be a part of the regular application build so that there files are maintained through regular build processes.
---
- Updates `generateApprovedResponseFiles` in `EndpointJsonResponseComparatorIT.java`.
- Updates `generateApprovedResponseFiles` in `EndpointJsonResponseComparatorV2IT.java`.
- Sets the system property in the `pom.xml`
* If the answer to any of the questions below is **Yes**, then **you …
=> BFD-2957: Migrate Away From Test Workflow for Test Data Generation

apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/TransactionManager.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/BeneficiaryTransformerV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/CarrierClaimTransformerV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/CoverageTransformerV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/DMEClaimTransformerV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/HHAClaimTransformerV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/HospiceClaimTransformerV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/InpatientClaimTransformerV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/OutpatientClaimTransformerV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/PartDEventTransformerV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/SNFClaimTransformerV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/TransformerUtilsV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/BeneficiaryTransformer.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/CarrierClaimTransformer.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/CoverageTransformer.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/DMEClaimTransformer.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/HHAClaimTransformer.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/HospiceClaimTransformer.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/InpatientClaimTransformer.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/OutpatientClaimTransformer.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PartDEventTransformer.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/SNFClaimTransformer.java
[BFD-2945](https://jira.cms.gov/browse/BFD-2945)
As a BFD application engineer, I want BFD to reduce redundancy so that the code is easier to maintain.
---
This is a pre-cleanup in advance of some small commonization to be done in various transformer classes. This fixes some style issues, sonar code smells, and bugs found while reviewing targets for 2945.
- Fixes sonar code smell issue of re-creation of a Random each loop in TransactionManager
- FIxes a lack of brackets on a number of statements in the transformers
- Removes some unneeded null initializers
- Update stream().forEach() to just use .forEach()
- Some modernization of switch statements to use new style
- Adjusts some !isPresent() for Optionals to just use .isEmpty()
- Removes …
=> BFD-2945: Cleanup of various code smells and some bugs

ops/jenkins/bfd-jenkins-sonarqube/Jenkinsfile, ops/jenkins/global-pipeline-libraries/vars/awsSsm.groovy
[BFD-3042](https://jira.cms.gov/browse/BFD-3042)
---
Change updates the Jenkinsfile to use the Recently updated sonarQube AccessKey Token. 
- Updates the JenkinsFile `ops/jenkins/bfd-jenkins-sonarqube/Jenkinsfile` to use token that was recently updated. 
- Validated change works Reference: https://jenkins-east.cloud.cms.gov/bfd/job/bfd-jenkins-sonarqube/job/ade%252FBFD-3042-JenkinsGitIssue/9/
* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment …
=> BFD-3042: Fetch SonarQube Token via SSM in Jenkins

apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/test/java/gov/cms/bfd/pipeline/ccw/rif/load/RifLoaderIT.java
[BFD-3018](https://jira.cms.gov/browse/BFD-3018)
---
This change fixes issues reported in the `LoadSampleU` test in the `RidLoaderIT.java` class. 
- Fixes the issue in `LoadSampleU` test.
- Removes the disabled dependency. …
=> BFD-3018: Fixed Issue relating in LoadSampleU Test

ops/terraform/services/common/README.md, ops/terraform/services/common/main.tf, ops/terraform/services/common/variables.tf
This reverts commit 0a93294268e347abf7e52e0f5a026c2a494414f7.
[BFD-3044](https://jira.cms.gov/browse/BFD-3044)
---
Fixes a bug in common that was causing the cluster to get deleted due to ssm reference. …
=> BFD-3044: RDS Maintenance prep bugfix

ops/k8s/helm/migrator/templates/job.yaml, ops/k8s/helm/migrator/values.yaml, ops/k8s/helm/pipeline/templates/_helper.tpl, ops/k8s/helm/pipeline/templates/job.yaml, ops/k8s/helm/pipeline/values.yaml, ops/k8s/helm/server/templates/_helper.tpl, ops/k8s/helm/server/templates/deployment.yaml, ops/k8s/poc/README.md, ops/k8s/poc/pipeline-values-ccw.yaml, ops/k8s/poc/pipeline-values-rda.yaml, ops/k8s/poc/pipeline-values-rif.yaml, ops/k8s/poc/pipeline-values.yaml, ops/k8s/poc/run-migrator.sh, ops/k8s/poc/run-pipeline.sh, ops/k8s/poc/run-server.sh, ops/k8s/poc/server-values.yaml
[BFD-3060](https://jira.cms.gov/browse/BFD-3060)
Note: This PR also includes updates to implement BFD-3058 and BFD-3059.  Since all of the changes are so small it was decided to merge them into this single PR.
As a BFD operations engineer, I want to be sure that EKS can accommodate:
* the Pipeline RDA workloads
* the Pipeline CCW workloads, and
* the Server workloads
so that I can confidently deploy Server on EKS in the future.
---
Updates the EKS proof of concept to include scripts and resources to execute the ETL pipelines (RDA and CCW/RIF) and FHIR server in the EKS environment. …
=> BFD-3060: expand EKS POC to include pipeline and server

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/CommonTransformerUtils.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4ExplanationOfBenefitResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/ExplanationOfBenefitResourceProvider.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/commons/CommonTransformerUtilsTest.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/R4ExplanationOfBenefitResourceProviderTest.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/ExplanationOfBenefitResourceProviderTest.java
[BFD-2964](https://jira.cms.gov/browse/BFD-2964)
As a BFD infrastructure engineer, I want BFD infrastructure to streamline redundancy in both the R4ExplanationOfBenefitResourceProvider and ExplanationOfBenefitResourceProvider classes by using a unified method where necessary
---
- Creates a common location for EOB IdType validation logic
- Creates a common location for publishing the MDC operation name
- Moves the parseTypeParam logic into common
- Fixes a number of small errors and code smells along the way
- Adds tests for invalid claim type
- Splits test cases for parsing type params into separate tests
* Verify all PR security questions and checklists have been …
=> BFD-2964: Reduce duplication in EOB Providers

.github/workflows/ci-java.yml, apps/Dockerfile
[BFD-3090](https://jira.cms.gov/browse/BFD-3090)
Use the bfd-parent version when creating the bfd-apps container image for use with GHA
---
In brief, this removes the hard-coded 1.0.0-SNAPSHOT from GHA's bfd-apps container image definition for use in the limited testing of BFD's ansible roles:
- ensure ci-java is triggered appropriately, including when the ci-java definition changes as is the case here
- define the image with a build argument for the bfd-parent version
- ensure yq is available for querying the pom.xml
- fetch the version from the bfd-parent pom directly with yq
- provide the bfd-parent version as a build argument to the container image creation process …
=> BFD-3090: Use bfd-parent version in bfd-apps image

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4PatientResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProvider.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/PatientE2EBase.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/PatientE2E.java
[BFD-3064](https://jira.cms.gov/browse/BFD-3064)
BCDA is generating a lot of 404's with the following error messages
failure during REST processing: ca.uhn.fhir.rest.server.exceptions.ResourceNotFoundException: By hash query found more than one distinct BENE_ID: 2. This change adds a distinctBeneIdsList so we can debug the actual  Bene Ids that are creating the error. 
---
- Updates the `apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4PatientResourceProvider.java`.
- Updates `apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProvider.java`.
- Updates both the `testPatientByIdentifierWhenMbiHashWithBeneDupesExpect404()` and …
=> BFD-3064: Updated test and PatientProviderResource classes IRT 404 err.

apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/ServerTestUtils.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/pac/ClaimE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/pac/ClaimResponseE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/utils/AssertUtils.java
[BFD-3112](https://jira.cms.gov/browse/BFD-3112)
As a BFD engineer I want to receive meaningful context when a JSON comparison fails during a test.
---
Modifies `AssertUtils` to compare pretty printed JSON strings instead of comparing individual nodes.  This results in more meaningful output when a comparison fails.
Also removes the need to add extra quotes to the paths used to filter nodes.  That requirement made the literal strings for those paths unnecessarily complicated. …
=> BFD-3112: Improve JSON comparison by using strings.

.github/workflows/build-release.yml, Jenkinsfile, apps/build.groovy, apps/pom.xml, ops/ansible/roles/bfd-db-migrator/defaults/main.yml, ops/ansible/roles/bfd-db-migrator/templates/bfd-db-migrator-service.sh.j2, ops/ansible/roles/bfd-db-migrator/test/run-tests.sh, ops/ansible/roles/bfd-db-migrator/test/test.sh, ops/ansible/roles/bfd-pipeline/defaults/main.yml, ops/ansible/roles/bfd-pipeline/templates/bfd-pipeline-service.sh.j2, ops/ansible/roles/bfd-pipeline/test/run-tests.sh, ops/ansible/roles/bfd-pipeline/test/test.sh, ops/ansible/roles/bfd-server/defaults/main.yml, ops/ansible/roles/bfd-server/tasks/install.yml, ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2, ops/ansible/roles/bfd-server/test/run-tests.sh, ops/ansible/roles/bfd-server/test/test.sh, ops/deploy-ccs.groovy
[BFD-3109](https://jira.cms.gov/browse/BFD-3109)
Use artifacts stored in AWS Code Artifact by the maven release plugin when constructing AMIs.
---
This change introduces some new methods to support fetching existing artifacts from Code Artifact, while re-using much of the existing solution for the remaining functionality. This change will to the monolithic build/deliver/deploy job will limit the functionality for tag-based releases only and for those releases that produce artifacts for storage under the associated tag in Code Artifact.
This also includes updates to the release artifact naming in the build-release action where they are now sourced and alternatively named form Code Artifact. These will need to be re-named in a follow-up …
=> BFD-3109: Use stored artifacts in AMI Builds

.github/workflows/build-release.yml, .github/workflows/ci-java.yml, Jenkinsfile, apps/bfd-data-fda/pom.xml, apps/bfd-data-fda/src/main/java/gov/cms/bfd/data/fda/lookup/FdaDrugCodeDisplayLookup.java, apps/bfd-data-npi/pom.xml, apps/bfd-data-npi/src/main/java/gov/cms/bfd/data/npi/utility/App.java, apps/bfd-server/bfd-server-war/pom.xml, apps/bfd-server/pom.xml, apps/build.groovy, apps/pom.xml, ops/ansible/roles/bfd-db-migrator/defaults/main.yml, ops/ansible/roles/bfd-db-migrator/templates/bfd-db-migrator-service.sh.j2, ops/ansible/roles/bfd-db-migrator/test/run-tests.sh, ops/ansible/roles/bfd-db-migrator/test/test.sh, ops/ansible/roles/bfd-pipeline/defaults/main.yml, ops/ansible/roles/bfd-pipeline/templates/bfd-pipeline-service.sh.j2, ops/ansible/roles/bfd-pipeline/test/run-tests.sh, ops/ansible/roles/bfd-pipeline/test/test.sh, ops/ansible/roles/bfd-server/defaults/main.yml, ops/ansible/roles/bfd-server/tasks/install.yml, ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2, ops/ansible/roles/bfd-server/test/run-tests.sh, ops/ansible/roles/bfd-server/test/test.sh, ops/deploy-ccs.groovy, ops/terraform/env/mgmt/github-actions-iam.tf, ops/terraform/env/mgmt/iam.tf
[BFD-3078](https://jira.cms.gov/browse/BFD-3078)
Use `maven-release` plugin for generating deployable and reference release artificats.
---
* Use maven-release in generating, storing deployable and reference release artificats
* Update ansible workloads (including packer) to use dynamic version strings instead of 1.0.0-SNAPSHOT, lookup required files, scripts, etc where possible
* Update deployment workloads to use dynamic versions strings instead of 1.0.0-SNAPSHOT everywhere. …
=> BFD-3078: Release Automation Improvement

.github/workflows/build-release.yml
[BFD-3121](https://jira.cms.gov/browse/BFD-3121)
Ensure that the newly published Data Dictionary Artifacts are named consistently with the existing artifacts
---
This PR adds some logic to the `Build Release` Workflow to rename data dictionary assets in accordance with historical convention.
- If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **N/A**
- Does this PR add any new …
=> BFD-3121: Ensure Consistency in Data Dictionary Release Artifacts

ops/jenkins/global-pipeline-libraries/vars/awsEc2.groovy
[BFD-3133](https://jira.cms.gov/browse/BFD-3133)
Fix syntax error discovered in bad 2.86.1 release.
---
Removes errant `"` character from the Ec2 global pipeline library.
* Does this PR store or transmit …
=> BFD-3133: Fix syntax error in Pipeline Library

.github/workflows/build-release.yml, Jenkinsfile
[BFD-3077](https://jira.cms.gov/browse/BFD-3077)
The process for deploying to production environments has changed. In order to do this the Build Release action must be run from github and a version created that matches the pattern ###.###.###. In order to run the multipipeline job but not deploy to production the version must match the pattern ###.###.###-xxxxx. As part of this change the previously existing job parameter deploy_prod_from_non_master has been removed.
---
Add check to confirm release tag follows proper formats.
Workflow build-release.yml allows release version format to be ###.###.### or ###.###.###-xxxxxx. Jenkinsfile checks for - in release tag to allow production deploy or not.
If you're reviewing this PR, please check for …
=> BFD-3077: Tag Deployment format for production

.github/workflows/build-release.yml, apps/pom.xml
[BFD-3120](https://jira.cms.gov/browse/BFD-3120)
Enable Jib Image Generation on Release
---
This PR re-enables the `release` maven profile's provisions for jib, allowing us to build and deliver deployable container image release artifacts. While these containers are not yet used in production, this continues to pave the way for a near-term re-platforming effort. In all, what's found in this change set:
* enables build/delivery of the jib-based container images in the release profile
* defaults to `bash` for [GHA shell commands](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell), which includes `--noprofile --norc -eo pipefail` to provide _faster_ failure, e.g. on AWS permissions …
=> BFD-3120: Enable Jib Images on Release

.github/workflows/ci-java.yml, apps/bfd-server/bfd-server-war/pom.xml, apps/pom.xml
[BFD-3149](https://jira.cms.gov/browse/BFD-3149)
As a BFD contributor, I want to be able to build the application without generating the open api documents so that I can avoid the new requirement for docker socket availability.
---
Add apidocgen property to pom file in bfd-parent to control execution of the exec-maven-plugin. It defaults to skipping the generation of open api docs. It executes in the release profile and when a user specifies -Dapidocgen.skip=false on the command line.
* Verify if addressed all AC 
* If the answer …
=> BFD-3149: Add apidocgen property to control api doc generation

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/adapters/SupportingInfoComponent.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/adapters/r4/ExplanationOfBenefitAdapter.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/adapters/stu3/ExplanationOfBenefitAdapter.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/AbstractSamhsaMatcher.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4EobSamhsaMatcher.java
[BFD-3164](https://jira.cms.gov/browse/BFD-3164)
For V2 Inpatient and SNF in EOB, the DRG codes are not being properly filtered. This is because the SAMHSA matcher check only checks for the v1 path (diagnosis.packageCode.Coding.System) and not the V2 DRG path (supportingInfo.Code.Coding.Code). As a result, DRG codes for V2 are not properly SAMHSA filtered.
---
- Adds a new adapter to check for SAMHSA DRG codes in the SAMHSA filter for supportingInfo.
- Test for this will be in the PR for 3117 …
=> BFD-3164: Bugfix for SAMHSA filter not filtering illegal DRG codes for V2 (SNF/Inpatient)

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/OpenAPIContentProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4ExplanationOfBenefitResourceProvider.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/ServerTestUtils.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/ExplanationOfBenefitE2E.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/R4ExplanationOfBenefitResourceProviderTest.java
[BFD-3164](https://jira.cms.gov/browse/BFD-3164)
As a BFD user I would like the ability to filter the response of the ExplanationOfBenefit endpoint so that I only get back the elements in the response that I care about.
---
- Adds adjustments to R4ExplanationOfBenefitResourceProvider to allow _elements to be passed in
- Adds new optional parameter, _elements
- Adds annotation needed for HAPI-FHIR to automatically pass _elements requests to this param
- Adds ResourceDef to the provider for POSTs
- Adds exception if _elements tag is used with GET requests to search 
- Adds _elements openAPI descriptions
- Tiny adjustment to ServerTestUtils that was bothering me
- Add tests to check for POST working with EOB v2 search endpoint, GET throws …
=> BFD-3164: Adding ability to pass _elements to EOB V2

apps/utils/locust_tests/requirements.in, apps/utils/locust_tests/requirements.txt
[BFD-3178](https://jira.cms.gov/browse/BFD-3178)
Background
Dependabot & Snyk is trying to bump jinja2 from 3.1.2 to 3.1.3 but needs to be added to the requirements.in file.
AC
* Revert change and update using the runbook https://github.com/CMSgov/beneficiary-fhir-data/wiki/How-to-Perform-Manual-Updates-to-Locust-Test-Dependencies
---
Bumps jinja2 from 3.1.2 -> 3.1.3 for locust_tests
* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), …
=> BFD-3178: Bump jinja2 from 3.1.2 to 3.1.3 for locust_tests

apps/bfd-shared-test-utils/src/main/java/gov/cms/bfd/DatabaseTestSchemaManager.java
[BFD-3068](https://jira.cms.gov/browse/BFD-3068)
---
OpenAPIDocs leverages bfd-server to generate Open API docs; the server, as part of its init, runs schema migrations; if the migrations fail, OpenAPIDocs hangs. This change resolves that issue.  This was tested by going into `bfd-server/bfd-server-war` directory and running the command. `mvn -Dapidocgen.skip=false clean verify
`. 
- Updates `DatabaseTestSchemaManager.java` …
=> BFD-3068: OpenAPIDocs bug fix

apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/extract/s3/DataSetManifest.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/extract/s3/task/ManifestEntryDownloadTask.java, apps/bfd-pipeline/bfd-pipeline-rda-bridge/src/main/java/gov/cms/bfd/pipeline/bridge/util/WrappedMessage.java, apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/PipelineApplicationState.java
[BFD-3183](https://jira.cms.gov/browse/BFD-3183)
As a BFD developer, I would like to consistently use lombok annotations in order to avoid writing redundant getter and setter methods for data classes. 
---
* Adds Lombok `@Getter`, `@Setter`, `@NoArgsConstructor`, and `@AllArgsConstructor` annotations where appropriate.
* Updates four classes in the `bfd-pipeline-ccw-rif`, ``bfd-pipeline-rda-bridge` and `bfd-pipeline-shared-utils` modules.
* When replacing actual getters/setters with the annotations the links to those methods in comments become broken so I had to remove the `{link}` …
=> BFD-3183: Add lombok annotations where possible to bfd-pipeline modules

ops/terraform/env/mgmt/kms-data-keys.tf
[BFD-3175](https://jira.cms.gov/browse/BFD-3175)
---
On 1/10/24's deployment of BFD 2.93.0, we came across issues with EC2 instances failing to startup. In Cloudwatch we found that the bfd-mgmt-ec2-failing-instances alarm was failing to send to the SNS topic due to the inability to decrypt the KMS key. See attachment screenshot. The policy attached to this KMS key has been altered via ClickOps to allow the decryption of the current kms key. This now allows the Cloudwatch Alarm to send notifications to the SNS topic.
- Encode the KMS key (bfd-mgmt-cmk) and policy attached in Terraform by updating `ops/terraform/env/mgmt/kms-data-keys.tf` by adding a new 
resource `"aws_kms_key""bfd_mgmt_cmk"`
- Verified imported resources by running …
=> BFD-3175: Encode bfd-mgmt-cmk in Terraform

ops/jenkins/bfd-run-sonarqube/Jenkinsfile
[BFD-3230](https://jira.cms.gov/browse/BFD-3230)
As a BFD contributor, I want BFD's static analysis to run with regularity so that I can better track BFD's progress toward quality standards.
---
The SonarQube multibranch/multistage job defined. As a result, this does readily accept scheduled triggers from the UI. This requires that a trigger is added to the Jenkins file identifying the specific branch at issue.
Added to the Jenkinsfile:
triggers {
cron(env.BRANCH_NAME == 'master' ? '30 11 * * *' : '')
}
The job  should run automatically at the time set in the cron entry.
Submitters …
=> BFD-3230: Trigger Master Branch SonarQube Job Daily

ops/ansible/playbooks-ccs/build_bfd-platinum.yml, ops/ansible/playbooks-ccs/roles/base_patch/tasks/main.yml, ops/ansible/playbooks-ccs/roles/platinum/tasks/install-security-updates.yml, ops/ansible/playbooks-ccs/roles/platinum/tasks/main.yml
[BFD-3234](https://jira.cms.gov/browse/BFD-3234)
Exclude kernel updates when patching app amis
---
This is a fix to hopefully prevent intermittent deployment failures. A top suspect of such failures is that kernel updates when applying the base_patch task in app ami's, is causing boot failures (due to kernel panics).
Going forward, kernel updates will be installed when building new platinum ami's. While this is automated, platinum builds can be triggered manually if an urgent kernel update is available.
* If the answer to any of …
=> BFD-3234: Exclude kernel updates when patching app amis

ops/terraform/env/mgmt/kms-data-keys.tf
[BFD-3231](https://jira.cms.gov/browse/BFD-3231)
---
While attempting to manage KMS CMK Data key for mgmt as part of [BFD-3175](https://jira.cms.gov/browse/BFD-3175), the kms:RencryptFrom was inadvertently excluded, causing failures when service roles attempted to access the mgmt kms key in path-to-production environments.
Updates the `aws_iam_policy_document` for data_keys
* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security …
=> BFD-3231: Correct Permissions on KMS Data Keys

Jenkinsfile, apps/utils/locust_tests/common/stats/stats_config.py, ops/jenkins/bfd-deploy-apps/Jenkinsfile, ops/terraform/services/server/deploy.groovy
[BFD-3016](https://jira.cms.gov/browse/BFD-3016)
Recent changes to the deployment process in [BFD-1789](https://jira.cms.gov/browse/BFD-1789) changed our deployments to leverage Git tags instead of deploying directly from master. Inadvertently, this is causing the Regression Suite to tag captured performance metrics with the name of the Git tag (typically something like 2_##_0), rather than with master. Since the process that starts the Regression Suite was not updated to account for this change in tagging scheme, during tag-based deployments the Regression Suite will query for previous runs tagged with the version of the ongoing deployment, and this query will inevitably return nothing. Thus, as of …
=> BFD-3016: Add a release flag conditional to regression suite execution

apps/bfd-server/bfd-server-launcher/src/test/java/gov/cms/bfd/server/launcher/ServerProcess.java
[BFD-3240](https://jira.cms.gov/browse/BFD-3240)
Address Insufficient Timeout in DataServerLauncherAppIT
---
This changeset increases the timeout for the Jetty and Application from 10s to 60s.
When awaiting both as part of `DataServerLauncherAppIT`, Jetty and/or the application fail to become available in the allotted 10s under certain circumstances. …
=> BFD-3240: Increase DataServerLauncherAppIT Timeout

Jenkinsfile
[BFD-3242](https://jira.cms.gov/browse/BFD-3242)
The Jenkins `stage` that deploys the `eft` Terraservice in `prod` is written incorrectly, such that:
- Deployments that are aborted at the `Manual Approval` `stage` will still attempt to deploy the `prod` `eft` Terraservice
- Deployments that are started while the `prod` Lockable Resources are locked (either manually or by another running Jenkins Pipeline) will still attempt to deploy `eft` to `prod` (provided that the `test` Lockable Resource is not _also_ locked)
This could cause unintended changes to the `prod` `eft` resources for Deployments that should not be affecting any `prod` resources.
---
This PR fixes the `prod` `eft` deployment `stage` such that it respects `prod` locks, Pipeline …
=> BFD-3242: prod EFT Terraservice deploy stage is not respecting prod locks or prod deployment skipping

ops/terraform/services/pipeline/modules/bfd_pipeline_slis/lambda_src/tests/test_update_pipeline_slis.py, ops/terraform/services/pipeline/modules/bfd_pipeline_slis/lambda_src/update_pipeline_slis.py
[BFD-3263](https://jira.cms.gov/browse/BFD-3263)
The Pipeline SLIs Lambda is triggered by S3 Event Notifications from files being uploaded to either `Incoming` or `Done` in the Pipeline S3 Bucket. The Lambda inspects each Event, looking at the _type_ of Event that it is, specifically looking for any `ObjectCreated` Events. However, due to a small mistake in the implementation of this inspection logic, only Events matching `ObjectCreated` _exactly_ are considered valid. `ObjectCreated` is akin to a _class_ of Event -- _actual_ Events are typically `ObjectCreated:Put` or `ObjectCreated:CompleteMultipartUpload`. So, these valid Events are being discarded erroneously and no Metrics are being generated.
---
This PR fixes a small mistake in the …
=> BFD-3263: Pipeline SLIs Lambda is rejecting valid S3 events resulting in no Pipeline Metrics

ops/terraform/services/pipeline/modules/bfd_pipeline_slis/main.tf
[BFD-3264](https://jira.cms.gov/browse/BFD-3264)
As a BFD Security Engineer, I want my DynamoDB Tables to have point-in-time-recovery enabled so that my tables can recover from any unintentional changes and so that they are compliant with all security requirements and scans
---
This PR enables PITR on all DynamoDB Tables used by the Pipeline SLIs Lambda.
- If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar …
=> BFD-3264: Enable point-in-time-recovery on Pipeline SLIs DynamoDB Tables

ops/jenkins/bfd-run-sonarqube/Jenkinsfile
[BFD-3268](https://jira.cms.gov/browse/BFD-3268)
---
As a BFD-contributor we want to update the SonarQube cron job to run on a nightly cadence from Monday to Friday. 
-  Updates the `beneficiary-fhir-data/ops/jenkins/bfd-run-sonarqube/jenkinsfile` to have the cron job run on a nighty cadence. 
* Does this PR add any …
=> BFD-3268: Updated Jenkins job bfd-run-sonarqube Cron Job

apps/bfd-data-fda/src/main/java/gov/cms/bfd/data/fda/utility/DataUtilityCommons.java
[BFD-3253](https://jira.cms.gov/browse/BFD-3253)
As a BFD Engineer, I want to ensure our static code analysis tool findings are cleaned and reported as fixed and safe.
---
-  Updates the `unzip` and `extractfile` methods in `apps/bfd-data-fda/src/main/java/gov/cms/bfd/data/fda/utility/DataUtilityCommons.java` to address ZipSlip vulnerability
Notes
https://sonarqube.cloud.cms.gov/project/issues?resolved=false&types=VULNERABILITY&id=bfd-parent&open=AYyCrOVxkKh3tcDiTpSW
- `bfd-data-fda/src/main/java/gov/cms/bfd/data/fda/utility/DataUtilityCommons.java L141 L158`
- `bfd-data-npi/src/main/java/gov/cms/bfd/data/npi/utility/DataUtilityCommons.java L101 L118`
* Verify all PR …
=> BFD-3253: Resolve zipSlip vulnerability re to SQ:s6096

apps/bfd-data-npi/src/main/java/gov/cms/bfd/data/npi/utility/DataUtilityCommons.java
[BFD-3281](https://jira.cms.gov/browse/BFD-3281)
---
As a BFD Engineer, I want to ensure our static code analysis tool findings are cleaned and reported as fixed and safe.
Notes
https://sonarqube.cloud.cms.gov/project/issues?resolved=false&types=VULNERABILITY&id=bfd-parent&open=AYyCrOUYkKh3tcDiTpR2
`bfd-data-npi/src/main/java/gov/cms/bfd/data/npi/utility/DataUtilityCommons.java L101 L118`
-  Updates the `unzip` and `extractfile` methods in `apps/bfd-data-fda/src/main/java/gov/cms/bfd/data/fda/utility/DataUtilityCommons.java` to address ZipSlip vulnerability
- `bfd-data-npi/src/main/java/gov/cms/bfd/data/npi/utility/DataUtilityCommons.java L101 L118`
* Verify all PR …
=> BFD-3281: Resolve bfd-data-npi zipSlip vulnerability (javasecurity:S6096)

apps/bfd-data-fda/src/main/java/gov/cms/bfd/data/fda/utility/DataUtilityCommons.java
[BFD-3279](https://jira.cms.gov/browse/BFD-3279)
As a BFD Engineer, I want to ensure our static code analysis tool findings are cleaned and reported as fixed and safe. 
Notes
https://sonarqube.cloud.cms.gov/project/issues?files=bfd-data-npi%2Fsrc%2Fmain%2Fjava%2Fgov%2Fcms%2Fbfd%2Fdata%2Fnpi%2Futility%2FDataUtilityCommons.java&resolved=false&severities=BLOCKER&types=BUG&id=bfd-parent&open=AYyCrOUYkKh3tcDiTpRt
`bfd-data-fda/src/main/java/gov/cms/bfd/data/fda/utility/DataUtilityCommons.java L178`
---
- Stream<Path> obtained from Files.walk(tempDir) is declared within the try-with-resources statement in the `recursivelyDelete` path method.  …
=> BFD-3279: Update recursivelyDelete to fix S2095 bug

apps/bfd-data-fda/src/main/java/gov/cms/bfd/data/fda/utility/DataUtilityCommons.java, apps/bfd-data-npi/src/main/java/gov/cms/bfd/data/npi/utility/DataUtilityCommons.java, apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/PipelineApplication.java, apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/extract/s3/S3FileManager.java
[BFD-3291](https://jira.cms.gov/browse/BFD-3291)
---
As a BFD contributor, I want BFD's static analysis in SonarQube to present only the most meaningful findings so that I can avoid wasting my time looking at less meaningful ones. Goal is to remediate the rules violation pertaining to Java:S5443
- Updated `DataUtilityCommons.java` in the `fda/utlility` dir.
-  Updated `DataUtilityCommons.java` in the `npi/utlility` dir.
- Updated `/src/main/java/gov/cms/bfd/pipeline/app/PipelineApplication.java`
- Updated `apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/extract/s3/S3FileManager.java`
* Verify all PR security questions and checklists …
=> BFD-3291: Remediate Java:S5443 violation

apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/extract/s3/S3FileManager.java
[BFD-3290](https://jira.cms.gov/browse/BFD-3290)
---
As a BFD contributor, I want BFD's static analysis in SonarQube to present only the most meaningful findings so that I can avoid wasting my time looking at less meaningful ones.
- Update `apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/java/gov/cms/bfd/pipeline/ccw/rif/extract/s3/S3FileManager.java`  …
=> BFD:3290: Address java:S4790 rule violation in bfd-pipeline-ccw

ops/ansible/roles/bfd-pipeline/templates/bfd-pipeline-service.sh.j2, ops/terraform/services/base/scripts/read-and-decrypt-yaml.sh, ops/terraform/services/base/values/prod-sbx.yaml, ops/terraform/services/base/values/prod.yaml, ops/terraform/services/base/values/test.yaml
[BFD-3297](https://jira.cms.gov/browse/BFD-3297)
Enable the RDA Cleanup Job for PAC data over 60-days of age.
---
Provide the configuration values for the RDA pipeline job's cleanup job. This will be disabled in both environment `test` and `prod-sbx` but fully enabled in `prod`.
* Does this PR add any new software …
=> BFD-3297: Enable RDA Cleanup Job

apps/bfd-shared-utils/pom.xml, apps/bfd-shared-utils/src/main/java/gov/cms/bfd/sharedutils/sqs/SqsDao.java
[BFD-3300](https://jira.cms.gov/browse/BFD-3300)
Address LocalStack SQS Readiness Issues
---
This implements a reasonable await for LocalStack container readiness which is especially helpful for container hosts that are **not** using Docker Desktop.
* Does this PR …
=> BFD-3300: Address LocalStack SQS Readiness Issues

apps/bfd-shared-utils/src/main/java/gov/cms/bfd/sharedutils/sqs/SqsDao.java, apps/bfd-shared-utils/src/test/java/gov/cms/bfd/sharedutils/config/AwsParameterStoreClientIT.java
[BFD-3305](https://jira.cms.gov/browse/BFD-3305)
Address LocalStack SMS Readiness Issues
---
Continuing on from #2219, this also implements a reasonable await for LocalStack container readiness. These changes largely target tests that involving the AWS SDK SsmClient, but I've also introduced a minor fix to my recent readiness additions to our SqsDao. …
=> BFD-3305: Address SSM LocalStack Readiness Issues

.github/workflows/ci-java.yml, apps/bfd-ops/pom.xml, apps/pom.xml
[BFD-3306](https://jira.cms.gov/browse/BFD-3306)
Selectively build bfd-ops
---
This implements an option to ignore the bfd-parent/bfd-ops from the default builds, `-DbfdOps.skip`. bfd-ops is really a release artifact, it's not in-use just yet, and it can take quite a while to build if you have a lot of untracked files in the ops hierarchy. For those working on ansible with virtual environments, building bfd-ops often takes more than 10m to complete. However, we default to building these artifacts as part of the typical CI and BFD release processes.
Submitters should complete the …
=> BFD-3306: Selectively build bfd-ops

ops/jenkins/global-pipeline-libraries/vars/terraform.groovy, ops/terraform/services/_modules/bfd-terraservice/main.tf, ops/terraform/services/_modules/bfd-terraservice/scripts/get_github_token.sh
[BFD-3312](https://jira.cms.gov/browse/BFD-3312)
The eft Terraservice uses the bfd-terraservice module's latest_bfd_release output in order to retrieve the correct version of the BFD EFT SFTP Outbound Lambda's Docker Image during deployment. The bfd-terraservice queries the GitHub API for the latest BFD release's metadata and extracts the release's version number to set the latest_bfd_release output value. This query is currently being executed without any authentication.
The unauthenticated query to the GitHub API has historically resulted in no issues with our deployments, but it seems that we have finally begun exceeding the extremely low rate limits for unauthenticated GitHub API requests.
The query in bfd-terraservice should be updated …
=> BFD-3312: GitHub API rate limiting is causing deployment failures

ops/terraform/services/base/values/test.yaml, ops/terraform/services/common/app-autoscaling.tf, ops/terraform/services/common/aurora-cluster.tf
[BFD-3316](https://jira.cms.gov/browse/BFD-3316)
Leverage IO Optimized RDS Clusters
---
In addition to transitioning to IO Optimized Aurora Clusters, this change set also scales the `test` cluster in **and** down:
- scaling-down to a modest db.r6i.2xlarge cluster, _c.f._ db.r6i.12xlarge
- scaling-in to a single instance overnight, and scaling out to support a single read replica between 0700 and 1900 ET bringing the cluster size to 2 for those 12 hours
These changes have been applied to each path-to-production environment, including `test`, `prod-sbx`, and `prod`.
Submitters should …
=> BFD-3316: Leverage IO Optimized RDS Clusters

ops/terraform/services/common/aurora-cluster.tf
[BFD-3319](https://jira.cms.gov/browse/BFD-3319)
Disable Monthly CPM
---
Disables Monthly snapshot retention as they are not required.
* Does this PR store or transmit data that was not stored or …
=> BFD-3319: Disable Monthly CPM

.github/CODEOWNERS
[BFD-3321](https://jira.cms.gov/browse/BFD-3321)
As a Tech Lead, I need to be a CODEOWNER, So that I can maintain the codebase.
---
Adds Don's GitHub user to CODEOWNERS.
* Does this PR store or transmit …
=> BFD-3321: Add Don to CODEOWNERS

.github/CODEOWNERS
[BFD-3321](https://jira.cms.gov/browse/BFD-3321)
As a IC, I need to be a CODEOWNER so that I can maintain the codebase.
---
Adds Melissa's GitHub user to CODEOWNERS.
* Does this PR store or transmit data …
=> BFD-3321: Add Melissa to CODEOWNERS

insights/terraform/projects/bb2/services/analytics/backend.tf, insights/terraform/projects/bb2/services/analytics/modules/lambda/update_athena_metric_tables/README.md, insights/terraform/projects/bb2/services/analytics/modules/lambda/update_athena_metric_tables/alter_table_schema_for_new_metrics_added.py, insights/terraform/projects/bb2/services/analytics/modules/lambda/update_athena_metric_tables/sql_templates/template_generate_per_app_metrics_for_report_date.sql, insights/terraform/projects/bb2/services/quicksight/backend.tf, insights/terraform/projects/bb2/services/quicksight/modules/quicksight-analysis-dasg-metrics/main.tf, insights/terraform/projects/bb2/services/quicksight/modules/quicksight-analysis-prod-applications/main.tf, insights/terraform/projects/bb2/services/quicksight/modules/quicksight-dataset-global-state-per-app/main.tf
[BB2-2905](https://jira.cms.gov/browse/BB2-2905)
Access Grant information needs to be added to Quicksight dashboards.  Specifically, the following metrics:
- Which production apps have the feature flag on --> app_access_grant_enabled
- Which app category they belong to (1-time, 13-month, research) --> app_access_grant_category
These fields need to be added to the BB2-PROD-APPLICATIONS dashboard.  
---
NOTES:
Sensitive values are stored in a shared terraform.tfvars file currently, but we are planning to refactor this to use AWS SSM as a future improvement task [BB2-2498](https://jira.cms.gov/browse/BB2-2498).
This ticket is tested alongside BB2-2963 since we apply the terraform changes to the test and prod workspaces that have been modified …
=> BB2-2905: Adds Access Grant feature flag and app category metrics to Quicksight

ops/terraform/services/base/values/prod-sbx.yaml, ops/terraform/services/base/values/prod.yaml, ops/terraform/services/base/values/test.yaml, ops/terraform/services/migrator/main.tf, ops/terraform/services/pipeline/data-sources.tf, ops/terraform/services/pipeline/iam.tf, ops/terraform/services/pipeline/main.tf, ops/terraform/services/server/main.tf, ops/terraform/services/server/modules/bfd_server_asg/main.tf, ops/terraform/services/server/modules/bfd_server_asg/variables.tf
[BFD-3324](https://jira.cms.gov/browse/BFD-3324)
Introduce modest cost savings with GP3 EBS Volumes
---
Swapping gp2 for gp3 EBS volumes includes potential cost savings up to 20%. Realistically, with the _more_ similar performance characteristics, this is _probably_ closer to something between 10 and 15 percent savings over the gp2 volumes:
Some highlights:
* I'm reducing the footprint of production BFD FHIR Server instances from 250GB to 170GB to maximize cost/performance ratios while still continuing to provide a sizable disk for buffered log data.
* I'm dramatically scaling-down the RDA pipeline instance volumes from 1000GB to the 170GB volumes–the 1000GB size was a holdover from the CCW/RIF pipeline workloads that **do** deal with …
=> BFD-3324: Leverage gp3 EBS Volumes

ops/terraform/services/base/values/prod.yaml
[BFD-3329](https://jira.cms.gov/browse/BFD-3329)
[BFD-3328](https://jira.cms.gov/browse/BFD-3328)
Disable RDA cleanup job on prod during 3328 maintenance
---
Disables RDA cleanup job in prod.
* Does this …
=> BFD-3329: Disable RDA cleanup job on prod during db maintenance

ops/terraform/services/eft/lambda_src/sftp_outbound_transfer/sftp_outbound_transfer.py, ops/terraform/services/eft/main.tf
[BFD-3362](https://jira.cms.gov/browse/BFD-3362)
Address SFTP Outbound Timeouts
---
This PR adjusts the strategy that was _loosely_ streaming the content of the S3 objects directly into an SFTP-accessible file, and instead relies on a file-like `BytesIO` object to serve as the local target and subsequent source when initially downloading from S3 and uploading to the intermediate SFTP file destination.
With these modest adjustments, we're seeing >30x performance increase over the former strategy. 289MB files that timed out in the allotted 900s before reaching roughly 90% completion are now successfully transferring in under 30s.
A version of this is currently running in both `test` and `prod` environments.
This also halves the Lambda timeout. …
=> BFD-3362: Address SFTP Outbound Timeouts

apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/AbstractCleanupJob.java, ops/terraform/services/base/values/prod.yaml
[BFD-3330](https://jira.cms.gov/browse/BFD-3330)
---
~~Optimized RDA cleanup script to hopefully run a little faster,~~ and turned it back on. 
Turns out, while the optimal way of writing the SQL would be a join on the delete, Hibernate does not accept it as valid. Additionally, ordering by last_updated does not seem to significantly affect the performance of the script, so removing it to cut out some additional processing time. 
* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the …
=> BFD-3330: Optimize RDA cleanup script

ops/terraform/services/base/values/prod.yaml
[BFD-3371](https://jira.cms.gov/browse/BFD-3371)
Disable RDA cleanup job due to foreign key constraint errors that occur when cleaning up the FISS tables.
---
Disables the RDA cleanup job
* Does this PR …
=> BFD-3371: disable rda cleanup job

.github/workflows/build-docker-images.yml, .github/workflows/build-release.yml
[BFD-3130](https://jira.cms.gov/browse/BFD-3130)
Make defaults for the build-release Workflow sensible **and** extend development support of the workflow itself.
---
* convert the workflow dispatch inputs for `build-release` and `build-docker-images` from required to overrides
* allow for forced github release object creation
* support overrides in version setting/validation step
* propagate version strings throughout the workflow
Generally, this should allow operators to cut the GA'd release from the trunk in as little as two clicks in the GitHub Actions UI. It also empowers engineers to continue running the workflow encoded in the trunk against arbitrary branches as well as allow for off-release GitHub release object creation at will. …
=> BFD-3130: Make defaults sensible in build release

ops/ansible/playbooks-ccs/roles/platinum/tasks/install-dependencies.yml
[BFD-3382](https://jira.cms.gov/browse/BFD-3382)
Lock grub2 dependency versions, if temporarily.
---
This introduces the yum versionlock plugin and logic to pin to a version not known to be impacted by any vulnerabilities that also avoids dependency conflicts that are currently exhibited in the platinum image builds based on the gold AMIs. …
=> BFD-3382: Address grub2 dependency issues

ops/terraform/env/mgmt/synthea.tf
BFD-3387
Remove Synthea Developers from MGMT.
---
Remove Synthea Developers Iam resources. …
=> BFD-3387: Remove Synthea Developer Resources

ops/terraform/services/base/values/prod-sbx.yaml, ops/terraform/services/base/values/prod.yaml, ops/terraform/services/base/values/test.yaml, ops/terraform/services/pipeline/user-data.sh.tftpl
[BFD-3390](https://jira.cms.gov/browse/BFD-3390)
Correct pipeline configuration hierarchy
---
This addresses the immediate issue surrounding the pipeline configuration hierarchy. The re-defined pipeline hierarchies appear to be sound, but the intermediate presentation to the ansible role exhibited two problems:
1. Only the `shared` hierarchy was being queried, leading to the pipeline workloads defaulting to safe, but undesirable configuration
2. Some hierarchies are now of variable length, which needs to target the `last` element of the hierarchy (the leaf) rather than a mere purported ultimate element.
These changes have already been applied out-of-band. The RDA pipeline appears to be working as expected.
If you're reviewing this PR, please …
=> BFD-3390: Correct pipeline configuration hierarchy

ops/jenkins/global-pipeline-libraries/vars/terraform.groovy
[BFD-3270](https://jira.cms.gov/browse/BFD-3270)
Rotation of GitHub PAT for temporary allow jenkins to deploy.
* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
* Do you think this PR requires …
=> BFD-3270: Rotation of GitHub PATs for Contract Transition

ops/terraform/services/pipeline/README.md, ops/terraform/services/pipeline/cloudwatch.tf, ops/terraform/services/pipeline/main.tf
[BFD-3414](https://jira.cms.gov/browse/BFD-3414)
Splunk-on-call has been paging the on-call engineer for pipeline errors that are not critical. After discussion, it has been determined that there are no pipeline errors that warrant paging the on-call engineer; therefore, errors in the ETL pipeline should be completely removed from Splunk-on-call.
---
Changes the monitoring for pipeline errors from alerts to notices. **Note: I left the SLI/SLO alarms alone as those would indicate an SLO violation which is a bit more important.**
* …
=> BFD-3414: Demote pipeline alarms from alerts to notices

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/SpringConfiguration.java
[BFD-3424](https://jira.cms.gov/browse/BFD-3424)
BFD is experiencing disk exhaustion due to a warning logs from a deprecated Javax namespace originating in the Spring config.
---
In the Spring config, I updated javax.persistence.query.timeout to jakarta.persistence.query.timeout.
* Does this PR add any new software …
=> BFD-3424: Updates Javax namespace to Jakarta in Spring Config

apps/bfd-data-fda/src/main/java/gov/cms/bfd/data/fda/utility/DataUtilityCommons.java
[BFD-3446](https://jira.cms.gov/browse/BFD-3446)
---
Added ndctext.zip to resources folder of bfd-data-fda, instead of downloading it from FDA.gov. This is a temporary work around until there is a stable alternative that avoids both storying binary data in the repository **and** fragile external dependencies that can fail us at build time. See BFD-2902 for more details.
* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, …
=> BFD-3446: NDC Download fix

ops/terraform/services/common/aurora-cluster.tf
[BFD-3450](https://jira.cms.gov/browse/BFD-3450)
Restore homogeneous RDS parameter groups.
---
This PR allows the RDS Cluster members to defer to their parent cluster definitions to resolve the appropriate parameter groups.
* Does this PR modify or invalidate any of …
=> BFD-3450: Fix heterogeneous RDS Parameter Groups

apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/AbstractCleanupJob.java
[BFD-3456](https://jira.cms.gov/browse/BFD-3456)
Recent changes to the RDA cleanup job are malfunctioning. The cleanup script should be reverted to a pre 2024-05-15 state.
---
Reverts the RDA Cleanup Script to v2.128.0 …
=> BFD-3456: Revert changes to RDA Cleanup Job

insights/terraform/projects/bb2/services/quicksight/modules/quicksight-analysis-dasg-metrics/main.tf
[BFD-3468](https://jira.cms.gov/browse/BFD-3468)
The DASG metrics dashboard needs a few minor fixes - updating one of the labels and fixing one of the calculations.
---
Updates the DASG metrics dashboard to have the correct label and calculation
* Does this PR modify …
=> BFD-3468: Fix bb2 dashboard label and calculation

ops/terraform/services/pipeline/README.md, ops/terraform/services/pipeline/data-sources.tf, ops/terraform/services/pipeline/main.tf, ops/terraform/services/server/data-sources.tf, ops/terraform/services/server/main.tf
[BFD-3470](https://jira.cms.gov/browse/BFD-3470)
Address issue where select ephemeral environment services were erroneously configured to communicate with their seed environment data stores.
---
This re-implements a features that allows for manual, operator-overrides of the environmental data store for pipeline and server workloads during exceptional periods of database maintenance. Unfortunately, an error was not detected until @dondevun's work on BFD-3460 where the seed environment is selected by default when the ephemeral services connect to the database. While this didn't directly impact the seed _or_ path-to-production environments, we did observe a confusing situation when both ephemeral and seed environment resources were attempting …
=> BFD-3470: Restore ephemeral environment isolation

.github/CODEOWNERS
[BFD-3482](https://jira.cms.gov/browse/BFD-3482)
Add Austin Schey to CODEOWNERS.
---
- Updates CODEOWNERS to Add Austin Schey …
=> BFD-3482: Adds Austin Schey to codeowners

ops/terraform/services/base/values/prod.yaml
[BFD-3497](https://jira.cms.gov/browse/BFD-3497)
Production RDS cluster capacity is decremented from 4 to 3 nodes
---
- Decremented RDA instance count in prod from 4 to 3
* Does this PR store or transmit …
=> BFD-3497: Decrements rds instance count in prod

ops/terraform/services/server/insights/api-requests/lambda_src/bfd-cw-to-flattened-json.py
[BFD-3490](https://jira.cms.gov/browse/BFD-3490)
The Insights Ingestion Lambda will sometimes fail to process batches of log records from the BFD Server's access.json log stream due to a small number of records from these batches failing to be processed. These batches, which could contain 1000s of log messages, are subsequently skipped and instead saved to S3.
In this case, the log messages are unable to be decoded as valid JSON, and the existing transformation Lambda does not handle such decoding errors gracefully. As a result, the transformation Lambda immediately exits when any such invalid message is encountered and the upstream Firehose Stream will mark the entire batch of records as `ProcessingFailed`.
---
This PR:
- adds type hinting …
=> BFD-3490: Fix Insights Ingestion Lambda to gracefully handle malformed JSON log messages

ops/terraform/services/base/values/test.yaml
[BFD-3479](https://jira.cms.gov/browse/BFD-3479)
---
Enables C4DIC in the test environment so BB2 can run some tests.
* If …
=> BFD-3479: Enable C4DIC in the test environment

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4EobSamhsaMatcher.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/Stu3EobSamhsaMatcher.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/R4EobSamhsaMatcherTest.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/Stu3EobSamhsaMatcherTest.java
BFD-3533
Adds data absent code system to known code systems within SAMHSA matcher
I added unit tests, ran the suite of integration tests, and we ran curl commands against the db to see EOB data now being returned.
=> BFD-3533: adds data absent code sytem to SAMHSA matcher

ops/terraform/env/mgmt/alarms.tf
BFD-3521 Create generalized global CloudWatch alert on lambda failures
BFD-3521
Creates a global CloudWatch Alarm that is defined to send alerts to the BFD-Warnings/Alerts slack channel  that notify us of any reported Lambda failures
The Alert(s) are implemented in Terraform
The first alert from the Alarm(s) create a slack notification, but subsequent alerts do not cause any further action (the Incidents are not self-resolving)
This is simply to reduce VictorOps Incident spam, and the On-Call should be resolving these Incidents manually anyways
tl;dr: do not add an ok_action to the CW Alarm
Please follow standard Git commit message guidelines:
* First line should be a capitalized, short (50 chars or less) summary.
* The rest of the message should be in standard Markdown …
=> BFD-3521 Create generalized global CloudWatch alert on lambda failures Update alarms.tf

ops/terraform/services/pipeline/modules/bfd_pipeline_slis/lambda_src/tests/test_update_pipeline_slis.py, ops/terraform/services/pipeline/modules/bfd_pipeline_slis/lambda_src/update_pipeline_slis.py
BFD-3552
This PR changes the logic for extracting the S3 event type from the invocation event to capture any raised `ValueError`s instead of letting them propagate to the Lambda Runtime, which would result in a false error. Additionally, unit tests have been added to cover the case where an unsupported event is extracted and when a valid event is extracted.
- Running the unit tests, _verifying that_ they all pass
=> BFD-3552: update-pipeline-slis Lambda is reporting failures for unsupported S3 events

ops/terraform/services/server/modules/bfd_server_asg/main.tf
BFD-3574
This PR fixes a mistake in defining the ASG autoscaling Alarms where the `CPUUtilization`'s Metric Namespace was mistakenly set to `AWS/AutoScaling` instead of `AWS/EC2`. With this change, the BFD Server can now properly scale-in and out in corresponding to the current workload.
Also, this fixes the scale-out Alarms using values intended for the scale-in Alarm unintentionally. Fortunately, the values between both were the same, so this is not a functional change.
- …
=> BFD-3574: BFD Server ASG autoscaling policies are not working due to wrong CPU metric

apps/utils/locust_tests/common/stats/aggregated_stats.py
BFD-3607
This PR adds a [pepper](https://en.wikipedia.org/wiki/Pepper_%28cryptography%29) to the `__generate_hash_str` function in `apps/utils/locust_tests/common/stats/aggregated_stats.py`. The value of the pepper itself has no intrinsic meaning, it is just used as a means for us to manually force the `hash` to be regenerated in cases like BFD-3563 where the values used to generate the `hash` haven't changed but external factors that impact performance of the Regression Suite has.
- Any other changes that could possibly affect …
=> BFD-3607: Update Regression Suite baseline hash generation to support manual regeneration of hash

ops/terraform/services/pipeline/main.tf
BFD-3523
Adds lifecycle meta-argument to ignore changes to desired_capacity
=> BFD-3523: Implement terraform lifecycle block to ignore ASG instance counts

apps/pom.xml
BFD-3609
This PR updates the AWSSDK BOM to 2.25.70 across the BFD parent POM which should update it across the shared utils. This should patch some Moderate vulns in Netty.
That this does not break any of your local builds and that it builds properly.... This is a minor version change.
CI/CD + …
=> BFD-3609: Update AWSSDK 2.25.70

ops/terraform/services/pipeline/modules/bfd_pipeline_slo_alarms/main.tf
BFD-3630
This PR updates the Alarm Actions for the BFD Pipeline SLO Alarms in `prod` to send `OK` -> `ALARM` alerts to Splunk On Call for `alert`-level Alarms and #bfd-warnings for `warning`-level Alarms.
- Running `terraform plan` in `prod` for the `pipeline` Terraservice, _verifying that_:
- The plan did …
=> BFD-3630: prod BFD Pipeline SLO Alarms are not sending alerts to Splunk On Call

apps/bfd-model/bfd-model-rif/mappings/HHAClaim.yaml, apps/bfd-model/bfd-model-rif/src/main/resources/db/migration/V20240911132746263__drop_clm_ps_ind_cd_not_null.sql
Modifies the 
BFD-3633
This PR changes the data model and database schema to allow the field `clm_pps_ind_cd` in the `hha_claims` table to be null; this will facilitate loading of Rif files where this field may be null.
Tested and verified in an ephemeral environment.
=> BFD-3633: Modify hha_claims field clm_pps_ind_cd to allow nulls

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/pac/R4ClaimSamhsaMatcher.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/pac/ClaimResponseE2E.java
BFD-3642
- Updates the PAC SAMHSA matcher to allow the Blue Button HCPCS system
- Fixes one of the claim response tests to assert the correct number of resources are being returned
Ran unit and integration tests, verified against test database.
=> BFD-3642: Update the PAC SAMHSA matcher to allow the Blue Button HCPCS system

ops/terraform/services/base/values/prod.yaml
BFD-3649
This PR updates the RDA ingestion interval from 2 minutes to 10 minutes to avoid overwhelming the RDA database. This had already occurred out-of-band, and this PR updates the YAML configuration to reflect the new value.
- `terraform plan`ning `base` in `prod`, _verifying that_ the changes match …
=> BFD-3649: prod RDA Pipeline ingestion interval should be increased to 10 minutes

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/pac/FissClaimTransformerV2.java, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v1/metadata.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/claimFissRead.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/claimFissReadWithTaxNumbers.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/claimSearch.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/claimSearchWithTaxNumbers.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/metadata.json
BFD-3650
Changes the FISS HCPCS URL to match what MCS uses and prevent the SAMHSA filter from not recognizing FISS data as SAMHSA.
Ran unit and integration tests.
=> BFD-3650: Change HCPCS system URL for FISS claims to fix oversharing in the SAMHSA filter

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/adapters/r4/ClaimAdapter.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4EobSamhsaMatcher.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/pac/R4ClaimSamhsaMatcher.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/Stu3EobSamhsaMatcher.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/SamhsaMatcherR4FromClaimTransformerV2Test.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/pac/R4ClaimSamhsaMatcherTransformerTest.java
BFD-3651
* Add check for supportingInfo in PAC SamhsaFilter.
* fix HCPCS check EOB Samhsa filter to properly use sets (V1 & V2).
* Add tests for supportingInfo in PAC and V2 EOB SAMHSA filter, and revenue lines in FISS
Added unit test to verify functionality of new SAMHSA filter addition, which have been validated as working.
=> BFD-3651: Fix for SAMHSA filter and SAMHSA filter tests.

ops/terraform/services/base/values/prod.yaml
BFD-3677
This PR re-enables the PAC endpoints in `prod` by reverting the changes made to the relevant SSM parameters.
- `terraform plan`ning `base` in `prod`, _verifying that_ the plan shows that the relevant SSM parameters are updated as expected
=> BFD-3677: Re-Enable Claim and ClaimResponse PAC Endpoints in Production

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/TransformerConstants.java
BFD-3675
- change the value for 'highlight color' on the C4DIC-ColorPalette-extension field to #335097
- Contact numbers should display like below
1-800-MEDICARE
(1-800-633-4227)
TTY: 1-877-486-2048
=> BFD-3675 Contact numbers, hex value change for C4DIC

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/RequestResponsePopulateMdcFilter.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/RequestResponsePopulateMdcFilterTest.java
BFD-3716
The current MBI filter in the MDC logger has a few limitations:
- Only looks for strings that start with `us-mbi|` which is not always the case
- Doesn't handle url-encoded values
- Only looks at the querystring
- Only looks at the Patient endpoint
This PR makes the following changes:
- Looks at the complete request parts for any MBIs (querystring, headers, and URL)
- Doesn't rely on there being a `us-mbi|` prefix - this _could_ produce false positives in theory, but I can't think of any conditions that would cause this. Even if it does, it's better than a false negative.
- Removes any filtering on a specific endpoint
- Adds test cases for the filter logic
- Are there any other spots that …
=> BFD-3716: Filter any MBI being logged to MDC

apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/OpenApiDocs.java
BFD-3101
Updates the OpenAPI spec to deprecated get _search endpoints.
Generated the doc locally, verified correctness.
=> BFD-3101: Add deprecated flag to _search endpoints for GET method in OpenAPI spec

.github/CODEOWNERS
BFD-3734
This PR removes user `meliGuzman` from our `CODEOWNERS` as they are no longer a contributor.
- Viewing the updated `CODEOWNERS` in GitHub, _verifying that_ there are no more errors
=> BFD-3734: Remove invalid users from CODEOWNERS

ops/terraform/env/mgmt/alarms.tf, ops/terraform/env/mgmt/backups/ami-pruner.tf, ops/terraform/env/mgmt/data-sources.tf, ops/terraform/env/mgmt/github-actions-iam.tf, ops/terraform/env/mgmt/main.tf, ops/terraform/env/mgmt/r53.tf
BFD-3724
**I will apply this out-of-band ahead of merging to `master`**
This PR fixes a few issues:
- GHA IAM Role now has permissions to do some necessary QuickSight and SSM IAM Actions
- `mgmt` Terraform has been updated to support sensitive/nonsensitive SSM configuration and to refer to updated nonsensitive configuration after BFD-3696
Have you fully verified and tested these changes? Is the acceptance criteria met? Please provide reproducible testing instructions, code …
=> BFD-3724: MGMT CI issues blocking MGMT environment apply

ops/terraform/services/common/aurora-cluster.tf
BFD-3735
This PR adds a (likely) temporary `ignore_changes` `lifecycle` block to the RDS Cluster `resource` so that the currently-paused Postgres upgrade does not interfere with intermediary deployment(s).
- `terraform plan`ning `common` in `test`, _verifying that_ there are no changes reported (without …
=> BFD-3735: Temporarily ignore version changes to RDS clusters

apps/bfd-shared-test-utils/src/main/java/gov/cms/bfd/DatabaseTestUtils.java, apps/pom.xml, apps/utils/scripts/create-bfd-db, ops/terraform/services/common/aurora-cluster.tf
BFD-3731
This PR updates the Postgres version for the BFD RDS Cluster, the BFD Server IT container, and the local BFD Server DB container to Postgres 16.4. Additionally, the temporary `ignore_changes` was removed from the RDS Cluster resource.
_All SDLC environments have had their RDS clusters upgraded to 16.4 already out-of-band._
Have you fully verified and tested these changes? Is the acceptance criteria met? Please provide reproducible testing instructions, code snippets, or …
=> BFD-3731: Upgrade RDS Clusters to Latest Minor Supported Aurora Version

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/CarrierClaimTransformerV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/DMEClaimTransformerV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/TransformerUtilsV2.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/CarrierClaimTransformerV2Test.java, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v1/metadata.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobByPatientIdAll.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobByPatientIdPaged.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobReadCarrier.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobReadCarrierWithMultipleLines.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobReadCarrierWithTaxNumbers.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobReadDme.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobReadDmeWithTaxNumbers.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/metadata.json, apps/bfd-server/bfd-server-war/src/test/resources/fakeOrgData.tsv
BFD-3753
Adds prvdr_spclty CareTeam qualification back into the EOB, alongside provider_taxonomy.
=> BFD-3753: Add prvdr_spclty back into CareTeam qualification

ops/ansible/roles/bfd-server/templates/bfd-server.j2
BFD-3756
- Removes config for `access.log` since that file no longer exists
- Adds `missingok` to prevent errors on missing files
- Changes the backup file format to include the timestamp. This prevents rotation from being skipped if the file already exists.
Copied changes into an existing ephemeral …
=> BFD-3756: Fix logrotate configuration

ops/terraform/services/eft/main.tf
BFD-3758
Changes the transfer family security policy to TransferSecurityPolicy-FIPS-2024-01
That this is properly changed in all locations within the code base for the EFT AWS Transfer Family
- This will be validated by a request to the EFT team.
=> BFD-3758: Update AWS Transfer Server Security Policy

ops/terraform/services/base/values/prod-sbx.yaml
BFD-3759
Updates the prod-sbx database config to match prod for MD's load testing
=> BFD-3759: Update prod-sbx database config to match prod

ops/terraform/services/base/values/prod-sbx.yaml, ops/terraform/services/base/values/prod.yaml, ops/terraform/services/base/values/test.yaml
BFD-3763
This fixes the formatting of the SAMHSA allowed partners SSM Parameters in each environment so that they can be properly parsed by the BFD Server JSON parser. This fixes the ongoing deployment issues.
- `terraform apply`'d `base` to `test` targeting the fixed Parameter, _verifying that_ the …
=> BFD-3763: Allowed SAMHSA certificates SSM parameter is formatted incorrectly causing Server init failures

apps/bfd-pipeline/bfd-pipeline-rda-bridge/README.md
BFD-3612
Updating the readme for the bridge script
=> BFD-3612: Update rda bridge documentation

apps/utils/scripts/run-bfd-server
BFD-3791
Fixes setting name for `samhsa_allowed_certificate_aliases_json` in the `run-bfd-server` script
=> BFD-3791: fix setting name for samhsa_allowed_certificate_aliases_json

apps/bfd-pipeline/bfd-pipeline-rda-grpc/pom.xml, apps/build.groovy, ops/jenkins/bfd-run-sonarqube/Jenkinsfile
BFD-3795
- Adds additional resources to the container host for testcontainers.org to work correctly.
- Increases heapsize for the maven build process
- Removes a duplicate entry from the rda-grpc pom for jakarta persistence
- Clarifies the _nightly_ sonarqube jenkins pipeline execution
Read through the solution and my own review comments to ensure that everything here makes sense.
Have you fully verified and tested these changes? Is the acceptance criteria met? Please provide reproducible testing instructions, code snippets, or screenshots as …
=> BFD-3795: Add resources to sonarqube pipeline job

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/V1Server.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/V2Server.java
BFD-3823
This PR fixes HAPI FHIR's defective handling of `POST` requests with parameters in both the body and in the query.
* Running a local BFD Server and sending a POST request with both body and query parameters, _verifying that_ the parameters were properly extracted and the correct …
=> BFD-3823: HAPI FHIR does not properly extract parameters from POST requests with query parameters

ops/terraform/env/mgmt/github-actions-iam.tf
BFD-3819
This PR fixes the GHA IAM Role such that it has the appropriate permissions to manage IAM Polices and KMS Key Policies.
* Running the `CI - Update OPS Infrastructure` Workflow with relevant pending changes to `mgmt`, _verifying that_ the [Workflow …
=> BFD-3819: GitHub Actions IAM Role lacks permissions to manage IAM policies and KMS key policies

ops/terraform/services/common/aurora-cluster.tf
BFD-3825
This PR fixes inconsistent Performance Insights and Enhanced Monitoring configuration between the RDS Cluster and RDS Writer Instance such that Terraform can `apply` `comon`.
- `terraform apply`ing `common` in `test`, _verifying that_ that it applies successfully
=> BFD-3825: Terraform for RDS Writer Instances must have RDS Observability configuration settings matching Cluster

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/OffsetLinkBuilder.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/PatientLinkBuilder.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/StringUtils.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4CoverageResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4ExplanationOfBenefitResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/R4PatientResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/CoverageResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/ExplanationOfBenefitResourceProvider.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProvider.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/CoverageE2EBase.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/ExplanationOfBenefitE2EBase.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/PatientE2EBase.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/R4ExplanationOfBenefitResourceProviderTest.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/R4PatientResourceProviderTest.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/ExplanationOfBenefitResourceProviderTest.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/PatientResourceProviderTest.java
BFD-3829
Adds input validation logic to automatically return a 400 error response when we receive an invalid number from some user input.
Unit/integration tests + some manual testing locally
=> BBFD-3829: Gracefully handle improperly formatted numeric request parameters

ops/terraform/services/pipeline/modules/bfd_pipeline_dashboard/templates/pipeline_dashboard.json.tftpl
BFD-3847
This fixes some invalid unit conversions in the new CCW Pipeline CloudWatch Dashboard, and also updates some visuals to convert their units to more useful units. Specifically:
- Per-dataset visuals are now in `hours`
- Per-RIF visuals are now in `minutes`
- ~~Adds any new software dependencies~~
- ~~Modifies any security controls~~
- ~~Adds new transmission or storage of data~~
- ~~Any other changes that could possibly affect security?~~
- `terraform …
=> BFD-3847: Fix Invalid Values in new Pipeline CloudWatch Dashboards

apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/AppConfiguration.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc-apps/src/main/java/gov/cms/bfd/pipeline/rda/grpc/apps/DirectRdaLoadApp.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc-apps/src/main/java/gov/cms/bfd/pipeline/rda/grpc/apps/LoadRdaJsonApp.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/RdaLoadOptions.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/RdaSourceConfig.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/main/java/gov/cms/bfd/pipeline/rda/grpc/source/StandardGrpcRdaSource.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/RdaLoadJobIT.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/RdaSourceConfigIT.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/StandardGrpcRdaSourceIT.java, apps/bfd-pipeline/bfd-pipeline-rda-grpc/src/test/java/gov/cms/bfd/pipeline/rda/grpc/source/StandardGrpcRdaSourceTest.java, ops/terraform/services/base/values/ephemeral.yaml, ops/terraform/services/base/values/prod-sbx.yaml, ops/terraform/services/base/values/prod.yaml, ops/terraform/services/base/values/test.yaml
BFD-3874
Adds configuration for the sequence number range update interval and updates the default to be 300 seconds (5 minutes). There's an issue with RDA that's making these calls run slowly that will hopefully be fixed, but this change is required to fix the processing speed in the meantime. …
=> BFD-3874: Increase RDA sequence number range update interval

ops/terraform/services/server/modules/bfd_server_asg/main.tf, ops/terraform/services/server/modules/bfd_server_asg/scripts/asg-data.sh
BFD-3893
This PR fixes an issue where the minimum size of a BFD Server AutoScaling Group was based upon the _desired capacity_ of the existing blue ASG rather than the _minimum size_ of blue or the configured default. This was leading to scenarios where the BFD Server was permanently scaled-out above 3 Instances, the default, and was unable to scale-in back to 3 during periods of low activity.
**Have you fully verified and tested these changes? Is the acceptance …
=> BFD-3893: Deploying Server during periods of scale-out causes permanent scale-out

apps/utils/locust_tests/lambda/server-regression/app.py
BFD-3894
This PR fixes the Regression Suite Lambda failing to do any comparisons against the baseline by explicitly specifying the path to the "stats compare meta file" when invoking `locust` in the Lambda handler.
- Building a new Regression Suite Lambda Docker Image, pushing it to …
=> BFD-3894: Regression Suite Lambda is unable to compare current run to baseline

Jenkinsfile
BFD-3892
This PR fixes the `terraform apply` order of `server` and `server-regression` and updates the JDP to run the Regression Suite prior to the second `terraform apply` of `server` so that incoming _green_ is verified before being swapped to blue.
* Using Jenkin's "Replay" feature …
=> BFD-3892: Jenkins Deployment Pipeline fully deploys BFD Server before Green can be verified

ops/terraform/env/mgmt/github-actions-iam.tf
BFD-3906
This PR adds some missing permissions from QuickSight and CloudWatch Logs that are necessary for the GHA IAM Role to make changes to the `mgmt` environment from BFD-3886.
* `terraform apply`ing to `mgmt` while assuming the GHA IAM Role, _verifying that_ all changes from …
=> BFD-3906: Extend MGMT Permissions to Avoid Automated Application Failure

ops/terraform/services/server/modules/bfd_server_asg/README.md, ops/terraform/services/server/modules/bfd_server_asg/main.tf
BFD-3908
This PR fixes issues caused by a Terraform AWS Provider bug when attempting to dynamically modify the `load_balancers` attribute of the `aws_autoscaling_group` resource by delegating Load Balancer attachment to a new `null_resource`. This allows us to keep the intended Blue/Green behavior with our legacy CLBs in our established environments without concern for further `apply` issues.
Additionally:
- `terraform apply` log noise from the various `null_resource`s has been reduced using the `quiet` attribute
- The Target Group (and Load Balancer) `null_resource` has been updated to first attach the desired TG and _then_ remove extra TGs. This ensures an ASG is always attached to a TG
Please …
=> BFD-3908: server Terraservice fails to apply due to Terraform AWS Provider bug

apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/SamhsaUtil.java, apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/samhsa/backfill/AbstractSamhsaBackfill.java, apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/samhsa/backfill/SamhsaBackfillService.java, apps/bfd-pipeline/bfd-pipeline-shared-utils/src/test/java/gov/cms/bfd/pipeline/sharedutils/SamhsaUtilTest.java, apps/bfd-pipeline/bfd-pipeline-shared-utils/src/test/java/gov/cms/bfd/pipeline/sharedutils/samhsa/backfill/AbstractSamhsaBackfillTest.java
BFD-3927
Adds test coverage for samhsa2.0 feature branch.
=> BFD-3927: Update test coverage for feature/samhsa2.0

ops/terraform/env/mgmt/jenkins-iam.tf, ops/terraform/services/server/certstores.tf
BFD-3952
This PR fixes an issue where the Jenkins IAM Role lacks enough permissions to `kms:DescribeKey` the default SSE S3 key, which Terraform looks up when the `kms_key_id` attribute is unspecified in `aws_s3_object` resources.
* Running through the deployment of 2.183.0 with the …
=> BFD-3952: Fix certstore S3 objects Jenkins deploy 

ops/terraform/env/mgmt/iam.tf
BFD-3969
Restores the cloudbees jenkins assumable role to use the root path to avoid external coordination for this now temporary resource.
Jenkins workflows that assume this role are working as expected with this change as applied.
=> BFD-3969: Use default, root path in Jenkins role

ops/terraform/services/pipeline/iam.tf
BFD-3987
- Removes IAM Path from CCW role to be added back at a later date through joint collaboration with the CCW team
- Validate this PR meets team standards
- Ensure no other changes were made through typo, or other possible human error
- Ran terraform plan against active environment workspaces …
=> BFD-3987: Fix: CCW RIF Role Permissions / External Partner Errors

.github/workflows/build-release.yml, apps/pom.xml
BFD-4005
This PR improves/fixes the `Build Release` Workflow and Maven Release process to ensure that the Maven projects are compiled only once, during `release:perform`, and that Jib-based container Images are built once and pushed once. Previously, `release:prepare` (done prior to `release:perform`) was compiling projects and building/pushing Images which was causing the Workflow to fail as the second Jib build was trying to push already-existing Images to our immutable repositories. It was also inefficient.
This PR (combined with BFD-3958) reduces our Maven release build times from approximately 20 minutes to _5 minutes_.
* ~~Adds any new …
=> BFD-4005: Build Release runs Jib Image Build Twice

ops/terraform/services/base/values/ephemeral.yaml, ops/terraform/services/base/values/prod-sbx.yaml, ops/terraform/services/base/values/test.yaml
BFD-4007
Disables the feature flag for `sex_extension/enabled` everywhere (it's already disabled in prod).
Changes applied to prod-sbx OOB.
=> BFD-4007: Disable sex extension feature flag

ops/terraform/services/pipeline/iam.tf
BFD-4006
This PR grants the `kms:GenerateDataKey` Action for the CCW Bucket Key to the `bfd-prod-ccw-rif` IAM Role. See the associated Jira ticket for more context.
**This change has already been made out-of-band in the interest of ensuring we receive this week's RIFs in a timely manner. This PR simply encodes the change in our IaC.**
**Have you fully verified and tested these changes? Is the acceptance criteria met? Please provide reproducible testing instructions, code …
=> BFD-4006: Update CCW RIF Role with additional KMS privilege

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/CommonTransformerUtils.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/TransformerUtilsV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/TransformerUtils.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/FDADrugCodeDisplayLookupIT.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/TransformerTestUtils.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/utils/RDATestUtils.java, apps/bfd-server/bfd-server-war/src/test/resources/fakeDrugOrg.json
… normalize drug code before lookup.
BFD-4019
This PR fixes two issues:
1. Drug code display values will be removed if the drug code cannot be looked up, instead of showing the placeholder.
2. Drug codes are normalized from the format `000000000` to `00000-0000` before the lookup.
Verified against …
=> BFD-4019: Bug in NDC lookup

.github/workflows/build_container_images_matrix.json, apps/utils/locust_tests/run-locust.Dockerfile
BFD-4009
This adjusts the ccw-pipeline context and dockerfile path to allow for the container-based lambda construction to proceed **and** addresses an innocuous (but unsightly) warning from the locust suite container builds. (Thanks, @malessi!)
Are we keeping things simple?
Successfully provisioned …
=> BFD-4009: Fix pipeline context, dockerfile path

ops/services/02-config/main.tf, ops/services/03-cluster/main.tf, ops/services/04-locust/main.tf, ops/services/04-migrator/main.tf, ops/services/05-ccw-pipeline/main.tf, ops/services/05-server/main.tf, ops/services/06-server-metrics/main.tf, ops/services/07-server-alarms/main.tf
BFD-4041
This PR updates the relative module roots for all Greenfield services to conform to their true paths (including the "hierarchy prefix").
* Any other changes that could possibly affect security?
N/A
=> BFD-4041: Update relative_module_roots for all Greenfield services

.github/workflows/build-container-images.yml
BFD-4042
- Updates the existing github action for building release containers to mask AWS account ID
- Verify in branch workflow runs that the account id is masked by using the registeries input
- Ran workflow against branch bfd-4042 and validated that account id's were masked
=> BFD-4042: Mask AWS Account ID in Build Container Images Workflow

ops/services/05-ccw-pipeline/ccw-runner-iam.tf, ops/services/05-ccw-pipeline/ccw-runner.tf, ops/services/05-ccw-pipeline/lambda-src/ccw-runner/ccw_runner.py
BFD-4044
This PR fixes the usage of database-related SSM parameters in `ccw-runner`. Additionally, this PR:
- adds logic to tag the `ccw-pipline` Task started by the `ccw-runner` with the set of default tags defined in the `ccw-pipeline` Terraservice.
- makes the logging config for the `ccw-runner` Lambda explicit
**Have you fully verified and tested these changes? Is the acceptance criteria met? Please provide reproducible testing instructions, code snippets, or screenshots as …
=> BFD-4044: Fix usage of invalid SSM parameters in ccw-runner Lambda

ops/services/03-cluster/data-sources.tf, ops/services/03-cluster/main.tf, ops/terraform/env/mgmt/kms-data-keys.tf
BFD-3945
This PR "formalizes" the ECS Fargate Cluster Terraservice by introducing the following:
- A default CMK storage encryption scheme that uses our default, per-environment data CMKs
- The `FARGATE` (on-demand) capacity provider as a capacity provider to our Cluster(s). Services/Tasks will be able to specify which of the capacity providers to use; for example, Server will be able to use a mix of both on-demand and spot providers to reduce cost while ensuring there is always some form of compute available
We have decided to standardize on a single Cluster per-environment. This reduces the complexity of our infrastructure as we have no real need to have multiple Clusters in each environment. …
=> BFD-3945: Formalize ECS Cluster Definition

apps/bfd-pipeline/bfd-pipeline-app/src/main/java/gov/cms/bfd/pipeline/app/PipelineApplication.java, apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/SamhsaUtil.java, apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/samhsa/backfill/AbstractSamhsaBackfill.java, apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/samhsa/backfill/SamhsaBackfillJob.java, apps/bfd-pipeline/bfd-pipeline-shared-utils/src/main/java/gov/cms/bfd/pipeline/sharedutils/samhsa/backfill/SamhsaBackfillService.java, apps/bfd-pipeline/bfd-pipeline-shared-utils/src/test/java/gov/cms/bfd/pipeline/sharedutils/samhsa/backfill/AbstractSamhsaBackfillTest.java
BFD-4068
Refactors a bit for performance, and fixes a minor bug with the reading the claim date.
Tested locally and in an ephemeral environment.
=> BFD-4068: Refactor SAMHSA backfill for performance.

apps/pom.xml
BFD-3904
Upgrades HAPI FHIR from version 7.6.0 to version 8.0.0 (The latest version available in maven). This is an extremely simple upgrade, as all of the major upgrade headaches were handled in the earlier upgrade to HAPI FHIR 7.
All integration tests pass, and the server has been tested locally.
=> BFD-3904: Upgrade HAPI FHIR to 8.0.0

.github/CODEOWNERS
BFD-4093
- Updates team members in CODEOWNERS file to account for current team structure
=> BFD-4093: Update CODEOWNERS

ops/services/01-base/README.md, ops/services/01-base/config-keys.tf, ops/services/01-base/data-keys.tf, ops/services/01-base/main.tf, ops/services/01-base/terraform.tf
BFD-4094
This PR introduces a new Greenfield Terraservice, `base`, that defines the most essential, _base_ resources in each BFD environment. For now, that is our "data" CMKs (keys we use to encrypt most things) and our "config" MRKs (keys we use to encrypt configuration data, like SSM parameters and our `sops` YAML). These resources have been ported from their definitions in `mgmt` and `mgmt/base_config`, and are functionally identical to their counterparts therein.
* ~~Any other changes that could possibly affect …
=> BFD-4094: Greenfield base Terraservice

ops/services/02-config/values/prod-sbx.sops.yaml, ops/services/02-config/values/prod.sops.yaml, ops/services/02-config/values/test.sops.yaml, ops/terraform/services/base/values/ephemeral.yaml, ops/terraform/services/base/values/prod-sbx.yaml, ops/terraform/services/base/values/prod.yaml, ops/terraform/services/base/values/test.yaml
BFD-4096
- Disables the SAMHSA backfill job in all envs now that the job has finished
- Enables shadow mode
- Adds the missing shadow config value to the sops-based config
Config-only change
=> BFD-4096: Disable SAMHSA backfill job, enable shadow mode in prod

.github/CODEOWNERS
BFD-4098
Removes Don DeVun from CODEOWNERS.
N/A
=> BFD-4098: Remove Don DeVun from CODEOWNERS

ops/services/02-config/values/ephemeral.yaml, ops/services/03-cluster/main.tf, ops/services/04-locust/main.tf, ops/services/04-locust/run-locust.tf, ops/services/05-server/data-sources.tf, ops/services/05-server/load-balancing.tf, ops/services/05-server/main.tf, ops/services/05-server/service.tf, ops/services/07-ccw-pipeline-alarms/lambda_src/manifests-verifier/manifests_verifier.py, ops/services/07-ccw-pipeline-alarms/manifests-verifier.tf, ops/services/07-server-alarms/error-alerter.tf, ops/services/07-server-alarms/lambda_src/error_alerter/error_alerter.py
BFD-4100
This PR fixes ephemeral environments for the new Greenfield Terraservices.
- `terraform plan`ning **every** Greenfield Terraservice in `4083-test`, _verifying that_ the is created successfully and is correct as expected
=> BFD-4100: Fix Greenfield Terraservice support for ephemeral environments

apps/bfd-pipeline/bfd-pipeline-idr/bfd.sql, apps/bfd-pipeline/bfd-pipeline-idr/extractor.py, apps/bfd-pipeline/bfd-pipeline-idr/loader.py, apps/bfd-pipeline/bfd-pipeline-idr/mock-idr.sql, apps/bfd-pipeline/bfd-pipeline-idr/model.py, apps/bfd-pipeline/bfd-pipeline-idr/pipeline.py, apps/bfd-pipeline/bfd-pipeline-idr/test_pipeline.py
BFD-4080
- Adds additional IDR data to the BFD database, as required for the Coverage resource
- Removed the `last_id` column from the progress tracking table. This column was meant to allow for fine-grained progress tracking in the event that the pipeline is killed during a data load, but this model doesn't scale well with tables that have composite primary keys. Instead, we'll just track progress based on `idr_trans_efctv_dt`. This means that we'll have to re-load a bit more data when recovering from a cancelled load, but it does reduce risk of missing data and likely improves overall load times due to less usage of `ORDER BY`.
* Adds any new …
=> BFD-4080: Add Coverage information to IDR pipeline

.github/workflows/build_container_images_matrix.json
BFD-4116
Fixes `ccw-runner` failing to building in `Build Release`.
- Checking that the path is now correct
=> BFD-4116: ccw-runner is failing to build in CI due to incorrect Dockerfile path

ops/services/06-ccw-pipeline-alarms/alarms-messages.tf, ops/services/06-ccw-pipeline-alarms/alarms-slos.tf, ops/services/06-rda-pipeline-alarms/alarms-messages.tf, ops/services/06-rda-pipeline-alarms/alarms-slos.tf, ops/services/06-server-alarms/alarms-elb.tf, ops/services/06-server-alarms/alarms-logs.tf, ops/services/06-server-alarms/alarms-slos.tf
BFD-4118
This PR ensures that Greenfield Alarms alert to the correct destination in the Legacy account.
- `tofu apply`ing this in `test` in Legacy, _verifying that_ the destinations were correct
=> BFD-4118: Greenfield observability Terraform does not have correct alarm config in Legacy

ops/services/04-ccw-pipeline/iam.tf, ops/services/04-ccw-pipeline/main.tf
BFD-4121
This PR ensures the Greenfield/Fargate CCW Pipeline uses the existing CCW Buckets in Legacy so that we can `apply` over the existing CCW Pipeline.
- `tofu apply`ing this in `test`, _verifying that_ everything works
=> BFD-4121: Greenfield CCW Pipeline does not use correct ETL Bucket in Legacy

apps/bfd-server-ng/README.md, apps/utils/locust_tests/.gitignore, apps/utils/locust_tests/.vscode-sample/launch.json, apps/utils/locust_tests/README.md, apps/utils/locust_tests/common/bfd_user_base.py, apps/utils/locust_tests/common/custom_args.py, apps/utils/locust_tests/common/data.py, apps/utils/locust_tests/common/db.py, apps/utils/locust_tests/common/db_idr.py, apps/utils/locust_tests/common/stats/stats_writers.py, apps/utils/locust_tests/pyproject.toml, apps/utils/locust_tests/run_locally_distributed.py, apps/utils/locust_tests/uv.lock, apps/utils/locust_tests/v2/regression_suite_post.py, apps/utils/locust_tests/v3/regression_suite.py
BFD-4036
- Adds a new regression suite for the V3 endpoints (`v3/regression_suite.py`)
- Updates README with some additional setup info and removes some sections that I thought were a bit unnecessary
- Fixes some type errors and removes `type: ignore` where it's no longer necessary
- Updates dependencies
- The monkey patch fix for psycopg is no longer needed with psycopg3, so that has been removed
- Makes the database connection string optional - it will pull from the standard Postgres environment variables when omitted
- Improves error handling in a few places
- Adds a sample file for debugging in VS Code  …
=> BFD-4036: Regression tests for V3

ops/platform/000-bootstrap/kms-keys.tf, ops/platform/02-alerting/lambda_src/slack-alerter/slack_alerter.py, ops/platform/02-alerting/slack-alerter.tf, ops/platform/02-alerting/sns-topics.tf, ops/terraform/env/mgmt/alarms.tf, ops/terraform/env/mgmt/kms-data-keys.tf
BFD-4111
- Adds Guard Duty Eventbridge Alerting for Runtime Monitoring
- Enables Events.amazonaws.com to utilize platform level KMS keys
- Enables Events.amazonaws.com to publish to Slack alerting sns topics 
- Review Terraform changes and ensure all docs are up to date as needed
- Validated …
=> BFD-4111: Guard Duty Health Status Monitoring (Critical Alert)

ops/services/04-ccw-pipeline/lambda-src/ccw-runner/ccw_runner.py
BFD-4141
This PR fixes the Pydantic errors causing the `ccw-runner` to fail to start the CCW Pipeline Task.
- Locally building a new `ccw-runner` Image, pushing this Image to ECR, and manually `tofu apply`ing `ccw-pipeline` in `prod` specifying to use the fixed `ccw-runner` Image, _verifying that_ …
=> BFD-4141: ccw-runner Lambda is failing to run due to Pydantic errors

apps/bfd-model/bfd-model-idr/sample-data/generator/claims_generator.py
BFD-4151
Some minor issues popped up with referencing the new code systems for the remaining institutional types. This fixes them. 
No more errors!
=> Fix claims generator

ops/services/01-config/values/test.sopsw.yaml
BFD-4156
This allows the bb2-local-client certificate to connect to V3.
- BB2 sent requests using the certificate and _verified that_ the request received a valid response
=> BFD-4156: Allow bb2-local-client certificate for v3

ops/services/01-config/values/prod.sopsw.yaml, ops/services/01-config/values/sandbox.sopsw.yaml
BFD-4162
This PR updates our resource allocations for Aurora and Fargate to better match our Reserved Instances and Compute Savings Plan.
- `tofu plan`ning `database` and `server`, _verifying that_ the plans report the expected changes will be made
=> BFD-4162: Adjust Greenfield Aurora and Fargate resource allocations

apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/patient/PatientHandler.java, apps/bfd-server-ng/src/test/java/gov/cms/bfd/server/ng/__snapshots__/PatientSearchIT.snap
BFD-4164
Currently, .link and .identifier are not populating when using the search endpoint. They should be, this fixes that.
Updated snapshot test
=> BFD-4164: fix patient search endpoint

apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/claim/model/AdmissionPeriod.java, apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/claim/model/BillablePeriod.java, apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/claim/model/ClaimLineNdc.java, apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/claim/model/ClaimProcedure.java, apps/bfd-server-ng/src/test/java/gov/cms/bfd/server/ng/__snapshots__/EobReadIT.snap, apps/bfd-server-ng/src/test/java/gov/cms/bfd/server/ng/__snapshots__/EobSearchIT.snap
BFD-4160
There are several instances where we're showing full ISO-8601 strings where we only need YYYY-MM-DD precision. This fixes that, as well as an the enumeration of NDCs. 
Updated tests.
=> BFD-4160: Fix v3 DateTime formats + "Optional" appearing in NDC

apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/IdrConstants.java, apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/claim/ClaimRepository.java, apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/eob/EobHandler.java, apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/eob/EobResourceProvider.java, apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/input/FhirInputConverter.java, apps/bfd-server-ng/src/test/java/gov/cms/bfd/server/ng/EobSearchIT.java, apps/bfd-server-ng/src/test/java/gov/cms/bfd/server/ng/__snapshots__/EobSearchIT.snap
BFD-4152
Implements _tag search parameter for EOB.
=> BFD-4152: Implement _tag search parameter for EOB in v3

apps/bfd-server-ng/README.md, apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/Configuration.java, apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/V3Server.java, apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/beneficiary/BeneficiaryRepository.java, apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/beneficiary/model/Beneficiary.java, apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/beneficiary/model/BeneficiaryBase.java, apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/beneficiary/model/BeneficiaryCoverage.java, apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/beneficiary/model/BeneficiaryEntitlementId.java, apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/beneficiary/model/BeneficiarySimple.java, apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/beneficiary/model/BeneficiaryThirdPartyId.java, apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/claim/ClaimRepository.java, apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/claim/converter/ClaimLineRevenueCenterCodeConverter.java, apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/claim/model/BenefitBalance.java, apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/claim/model/BenefitBalanceClaimValue.java, apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/claim/model/Claim.java, apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/claim/model/ClaimLine.java, apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/claim/model/ClaimLineRevenueCenterCode.java, apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/coverage/CoverageHandler.java, apps/bfd-server-ng/src/main/resources/application-sqlprofile.properties
BFD-4183
- Changes JPA queries to ensure every relation is explicitly joined against and `FETCH JOIN` is used
- Every relation must be included in the join, otherwise JPA may generate a separate query for each resulting row when it attempts to load the relation
- `FETCH JOIN` is required to ensure all data is fetched in a single query
- Separates the beneficiary model to prevent over-fetching
- Created `BeneficiaryCoverage` which includes the other tables required for coverage. This way the Patient endpoint doesn't need to join against these tables.
- `BeneficiarySimple` is a minimal version used for EOB
- Unrelated fix - make revenue center code optional
Please indicate if this PR does any of the …
=> BFD-4183: Performance fixes for JPA queries

.github/CODEOWNERS
BB2-3987
Remove Logan and replace with other BB2 members 
That the CodeOwners validates
This CODEOWNERS file is valid.
=> BB2-3987: Update CODEOWNERS to Remove Logan

apps/bfd-server-ng/README.md, apps/bfd-server-ng/src/main/java/gov/cms/bfd/server/ng/claim/model/TypeOfBillCode.java, apps/bfd-server-ng/src/test/java/gov/cms/bfd/server/ng/__snapshots__/EobReadIT.snap, apps/bfd-server-ng/src/test/java/gov/cms/bfd/server/ng/__snapshots__/EobSearchIT.snap
BFD-4189
Updates the logic for `typeOfBillCode` to match the FML specs.
Tests
=> BFD-4189: typeOfBillCode fixes

apps/bfd-pipeline/bfd-pipeline-idr/mock-idr.sql
BFD-4159
Adds comments to indicate SAMHSA columns
N/A
=> BFD-4159: Note which IDR columns contain SAMHSA

ops/images/bfd-platform-mount-certstores/Dockerfile, ops/images/bfd-platform-server-fluent-bit/Dockerfile, ops/services/03-migrator/main.tf, ops/services/04-ccw-pipeline/main.tf, ops/services/04-npi-pipeline/main.tf, ops/services/04-rda-pipeline/main.tf, ops/services/04-server-ng/service.tf, ops/services/04-server/service.tf
BFD-4084
This PR makes all containers' root filesystems readonly, mounting only the `/tmp` directory as read-writeable to enable workloads that need to download temporary files (the Pipelines).
- Deployed these changes to `test`, _verifying that_ all ECS services work as expected (`server` passes …
=> BFD-4084: Ensure ECS Containers Have Read-only Access to Root Filesystem (ECS.5)

apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/TransformerConstants.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/PartDEventTransformerV2.java, apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/TransformerUtilsV2.java, apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/PartDEventTransformerV2Test.java, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobByPatientIdAll.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobByPatientIdPaged.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobReadByPatientWithSamhsa.json, apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v2/eobReadPde.json
BFD-4228
Added pair to CCWCodeSystem map providing a code system mapping for `org_npi_num`
- run the tests
- check the choice of `cwCodebookVariable.ORG_NPI_NUM`
=> BFD-4228: Change EBO.provider.identifier.system to us-npi

ops/terraform-modules/bfd/bfd-terraservice/main.tf
BFD-4233
This PR fixes an issue where `Deleted` Peering Connections were being returned by the `data.aws_vpc_peering_connections.main` data resource which would result in empty, invalid CIDR blocks being added to the ingress/egress rules of the `server` Security Groups causing `plan`s/`apply`s of `server` to fail.
**Have you fully verified and tested these changes? Is the acceptance criteria met? Please provide reproducible testing instructions, code snippets, …
=> BFD-4233: Deleted Peering Connections return empty CIDRs resulting in invalid Server Security Group configuration

.github/scripts/pre-commit.sh
BFD-4246
This PR fixes some usability issues with the sops pre-commit hooks in the Greenfield environment. Specifically, all checks have now been replaced with functional equivalents that do not require the operator to authenticate to AWS prior to commit.
- Making a change that "exposed" a sensitive …
=> BFD-4246: sops precommit script does not work properly in Greenfield

ops/services/02-eft/main.tf
BFD-4272
This PR changes the `eft` Terraservice to create resources using the new `data` Subnets instead of the `private` Subnets.
- `tofu apply`ing these changes to `eft` in Greenfield `test`, _verifying that_ all resources requiring a Subnet now use the `data` Subnets instead of the `private` ones
=> BFD-4272: Greenfield EFT uses new data Subnets

.github/workflows/ci-java.yml, apps/pom.xml
BFD-4294
- re-organizes the mvn options in ci-java
- allows builds/analysis on *all* pushes to master (e.g.e merges) when push is not part of the release process by ignoring `actions-user` commits and ignoring results of `workflow_files`
- avoids generating/uploading analyses on `merge_group` triggers
- increases fetch-depth for builds on which sonar analyses are based to address sonarqube complaints
- enables manual execution (`workflow_dispatch`) of ci-java on arbitrary branches, e.g. `gh workflow run ci-java.yml --ref burling/bfd-4294 -f branch=master` runs the logic for ci-java.yml as of _latest_ `origin/burling/bfd-4293` against `master` repository content
- prefer the git hash for project versions instead of the default project version context
- instituted _wait_ …
=> BFD-4294 Improve ci-java, sonarqube analyses
